### ISSUE TITLE
Add InventoryMove

### ISSUE THREAD

**Issue by Nekiplay** [MCCTeam/Minecraft-Console-Client#1032]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

**Feature description**
Moving items between inventory

**Comment by BruceChenQAQ** [comment]
Moving items between multiple containers is now supported (via backpack transit). I will close this issue.
