### ISSUE TITLE
Explosion Records

### ISSUE THREAD

**Issue by Nekiplay** [MCCTeam/Minecraft-Console-Client#1061]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

**Feature description**
I think it would be a good idea to implement this, but I do not see how to implement this in dataTypes

**Comment by ORelio** [comment]
Not sure if really useful to have the list of blocks affected by an explosion but adding this to the TODO list. 😉

**Comment by milutinke** [comment]
When I updated the packet I added it, but it's not used, if someone needs it, you can use it.
I don't see why would anyone use this tho.
