### ISSUE TITLE
Alerts into .txt separate from Chatlogs

### ISSUE THREAD

**Issue by orange0513** [MCCTeam/Minecraft-Console-Client#1179]
How do i send alerts into a .txt file separate from chat logs

**Comment by ORelio** [comment]
This is currently not possible. Converting your question into a request for improvement 😉

**Comment by orange0513** [comment]
ORelio is this possible with chatbot's?

**Comment by ORelio** [comment]
Of course you can write our own ChatBot for this. Or use ChatLog and filter yourself the log afterwards.

**Comment by milutinke** [comment]
Implemented  in #2203
