### ISSUE TITLE
Porting MCC to .NET Framework 5

### ISSUE THREAD

**Issue by downloadpizza** [MCCTeam/Minecraft-Console-Client#1313]
The project works well in Mono on Linux, but the `.Net Framework`  is slowly dying out. `.Net core` was also "killed" and moved to `.Net 5.0` (and higher).

`.Net 5.0` is apparently almost at the first release, so it may be good to consider porting the project to unified `.Net` once it is released.

I don't see this as an important Issue, but it would be quite nice. I'll start looking for namespaces that dont exist in `.Net 5.0` to see what needs to be replaced. I assume the GUI stuff will completely break, but no idea.

**Comment by downloadpizza** [comment]
Non Standard Namespaces: `System.Deployment`, `System.Core`, `System.Data.DataSetExtensions`, 

Ill see if they are available on NuGet for `.Net core` as that probably means that they will get ported to `5.0`

**Comment by ORelio** [comment]
Discussed about it in several issues before (e.g #1306 recently) but there is not proper issue for .NET 5 yet so I'll leave it open as it is a bit soon for porting yet.

**Comment by breadbyte** [comment]
Hi! 

I just started porting this project to .NET 5.0. 
There are still some issues, but I've done the initial work to get it up and running on a Linux machine.
You can see my work over at https://github.com/breadbyte/Minecraft-Console-Client under the `bread` branch.
I might make a pull request once I've tested it more thoroughly and I'm certain about the stability of the code, but for now I have only tested it with 1.17.

![image](https://user-images.githubusercontent.com/14045257/124256389-d06a4900-db5d-11eb-9e2a-e355d49e27cb.png)

**Comment by ORelio** [comment]
Looks very promising! The code contains may workaround for Mono that you will be able to remove once ported to .NET 5. This should also resolve weird issues such as the mysterious silent disconnection bug (https://github.com/ORelio/Minecraft-Console-Client/issues/1306#issuecomment-720159571)
