### ISSUE TITLE
Add setting to increase disconnect timeout

### ISSUE THREAD

**Issue by cubic86** [MCCTeam/Minecraft-Console-Client#1337]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

The vanilla Minecraft clients handles lag spikes with no issues. However, the console client disconnects on each lag spike. Is there a way to increase the tolerance for such issues?

**Comment by milutinke** [comment]
Added.
