### ISSUE TITLE
Is there any way I could make it so that the client types a command in chat repeatedly(forever)?

### ISSUE THREAD

**Issue by MessengerRNA** [MCCTeam/Minecraft-Console-Client#1595]
Hi, I'm just looking to make it so that the client types the /sellhand all command for an infinite amount of time. Can anyone help me?

**Comment by ReinforceZwei** [comment]
Create a new text file with the following content and save it with file name `myscript.txt`. Then use console command `/script myscript.txt` to run the script. See https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config for  how to write a script.
```txt
send /sellhand all
wait 5
script myscript.txt
```

**Comment by MessengerRNA** [comment]
You also helped me in #1564 and I'm having the same issue all of a sudden after the commands were working for a few days. Here's the console output that you asked for in #1564. It supposed to tp me to the skyblock part of the server and then it says how much mcmmo credits I have, when it doesn't that means I'm still in the server hub. 

![](https://i.gyazo.com/22358fd1eaa578c52d11af19e4a4899c.png)

**Comment by MessengerRNA** [comment]
![image](https://user-images.githubusercontent.com/83925300/118524935-ac1cef00-b70c-11eb-877a-fec8c744eb06.png)
For some reason after a couple of tries it eventually works. Thanks for all the help!

**Comment by MessengerRNA** [comment]
It stopped working again... any solution?

**Comment by MessengerRNA** [comment]
So I just figured out that the account gets sent to the skyblock server and then it returns to the hub after a second when it doesn't work.

**Comment by ReinforceZwei** [comment]
Try enabling `terrainandmovement` in your `MinecraftClient.ini` file. Inventory doesn't work well on some server with terrain and movement disabled.

**Comment by MessengerRNA** [comment]
Terrainandmovement is already enabled.

**Comment by MessengerRNA** [comment]
Hey if you ever have time the server IP is arkhamnetwork.org

**Comment by ORelio** [comment]
Maybe the script provided by @ReinforceZwei in #1622 could help handling the inventory?
