### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by LarsNijhuis** [MCCTeam/Minecraft-Console-Client#1603]
Is there any way to control with a GUI. e.g. /shop ect. With a command tell it which slot to press. Thanks in advance.

**Comment by ReinforceZwei** [comment]
Use `/inventory` command. 

Make sure to enable inventory handling before using the command.

**Comment by TeacVern** [comment]
> Is there any way to control with a GUI. e.g. /shop ect. With a command tell it which slot to press. Thanks in advance.

how are you using the GUI version 
because I couldn't do it :))  

TeacVern (TV)#2472

**Comment by TeacVern** [comment]
> Use `/inventory` command.
> 
> Make sure to enable inventory handling before using the command.

how are you using the GUI version
because I couldn't do it :))

TeacVern (TV)#2472

**Comment by ORelio** [comment]
@TeacVern This issue is about servers that shows you a GUI based on inventory windows ingame. MCC can interact with these using the `/inventory` internal command. This is not about the GUI for running MCC, which is indeed unmaintained due to a lack of time.
