### ISSUE TITLE
Ability to reload configuration without restarting MCC

### ISSUE THREAD

**Issue by xXjojaXx** [MCCTeam/Minecraft-Console-Client#1605]
Starting MCC over and over again for some small changes can be quite tedious and loading the configurations and autoresponds regularly wouldn't be very great performance wise. So the idea would be an /reload command or something similar to load changes without completly stopping the bot.

**Comment by ORelio** [comment]
This could be done, however some settings would take effect immediately, while some others would need to disconnect and reconnect to the server to take effect. Adding your suggestion to the TODO list.

**Comment by xXjojaXx** [comment]
Thanks. Might take some time. Lots of ideas waiting for contributers right now.

**Comment by ORelio** [comment]
Yes, the lack of contributor to work on everything is our biggest issue 😅

**Comment by Splarkszter** [comment]
@ORelio Any updates on this one?, a separate reload and disconnect commands would be a huge Quality of Life improvement.

Like when i tried to make a script to bots disconnect when someone was sleeping, the only command is exit but that closes the client so it's not practical.

**Comment by ORelio** [comment]
Unfortunately still no ETA. Regarding your specific use case, from your bot, you can register a custom command so that when typing the custom command the bot unloads itself.

**Comment by milutinke** [comment]
I'll take a look at this when I catch some time.

**Comment by milutinke** [comment]
Implemented in #2167, currently needs testing but will be merged when the testing is done.
