### ISSUE TITLE
Microsoft Account Conneciton.

### ISSUE THREAD

**Issue by Nyjahvimm** [MCCTeam/Minecraft-Console-Client#1613]
Is there anyway for me to connect using a Microsoft account?

**Comment by ReinforceZwei** [comment]
Yes. See [this option](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Resources/config/MinecraftClient.ini#L12).

**Comment by Nyjahvimm** [comment]
Is there a way i can do mojang AND microsoft?

**Comment by ReinforceZwei** [comment]
Do you mean auto-detecting account type?

**Comment by Nyjahvimm** [comment]
Whenever i change it to a microsoft login, and then try to login with a microsoft account, it doesnt work. Possibly i am doing something wrong ?

**Comment by ReinforceZwei** [comment]
Please provide screenshot.

**Comment by DashiteGames** [comment]
what do I use to sign in my Microsoft account on the client, do I use my email or username

**Comment by ReinforceZwei** [comment]
@DashiteGames Email.

**Comment by DashiteGames** [comment]
It just keeps telling me "Minecraft Login failed : Incorrect password, blacklisted IP or too many logins."
my email and password is correct, type is set to Microsoft, and method set to mcc

**Comment by ReinforceZwei** [comment]
@DashiteGames If you having trouble signing in using `mcc` method, try `browser` login method.

**Comment by DashiteGames** [comment]
when i use the method browser is something suppose to pop up

**Comment by DashiteGames** [comment]
is there a video I can watch how how to get a Microsoft account to work on this client

**Comment by ReinforceZwei** [comment]
@DashiteGames ,

> when i use the method browser is something suppose to pop up

There will be a link on the screen. Copy the link and open it in your browser. Sign-in with your Microsoft account. Once you reached a blank screen, copy the link from browser address bar and paste it back to MCC.

> is there a video I can watch how how to get a Microsoft account to work on this client

We do not have any Microsoft Minecraft account so we cannot make tutorial video showing the full login process.

**Comment by notynote** [comment]
Can confirm that I cannot login to a server with email and pass for microsoft account. I have tried several microsoft account and it does not work. However, browser method works fine for all accounts.

**Comment by YTPSDanDie** [comment]
hey, I am using an older version which is "ORelio Minecraft Console Client v1.12.2 DEV."
I use this as it is perfect and never needed to do anything until now.
I purchased Minecraft Java as a new account yesterday which has changed to a Microsoft login.
Is there any coding I can change to accept the Microsoft login?

Also Nyjahvimm have you tried logging into https://www.minecraft.net/en-us/login - If you can successfully login on there use the same details to log in on the client.

Thanks in advance for any help!!

**Comment by ReinforceZwei** [comment]
@YTPSDanDie You have to download the latest version in other to use Microsoft account for logging in.

**Comment by YTPSDanDie** [comment]
> @YTPSDanDie You have to download the latest version in other to use Microsoft account for logging in.

Thank you just downloaded works perfectly just got to get used to new version lol used old version for years :)
