### ISSUE TITLE
Auto-Clicker so i can stay afk in my stone generator

### ISSUE THREAD

**Issue by BecHGM** [MCCTeam/Minecraft-Console-Client#1621]
Hello, i just wanted to know how to set up an auto clicker on the plugin, i want to stay afk in my stone generator, i found out that there is a command /dig in the plugin but i will have to keep writing it which is annoying .. hope you help me guys :D

**Comment by ORelio** [comment]
Hi, as explained in #1604 there is no simple "left click"/"right click" action.
You may use the [CobblestoneMiner](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/CobblestoneMiner.cs) script for your stone generator.

**Comment by ORelio** [comment]
Oh, also, you can use [ScriptScheduler](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-script-scheduler) to periodically send `/dig` to the server.
