### ISSUE TITLE
Perform action when inventory opens

### ISSUE THREAD

**Issue by ProfLinebeck** [MCCTeam/Minecraft-Console-Client#1622]
Hey!
I am using MMC since today and it's really great!
So far everything works like a charm, but i wonder if i is possible to use AutoRespond for reacting to a MMC message?

Example:
MMC gives the messages: `[MCC] Inventory # 1 opened: Connect to a server`
Now i basically want to do this:
```
[Match]
match=[MCC] Inventory # 1 opened: Connect to a server
actionother=script Test1
```

Is that or something similar possible already?

Kind Regards,
ProfLinebeck

**Comment by toni1506mc** [comment]
How does the inventory open?
With a Command (/server) or a Item ?

**Comment by ProfLinebeck** [comment]
> 
> 
> How does the inventory open?
> With a Command (/server) or a Item ?

It opens via an Item(Compass) in the hotbar. I can join that server etc, however it would be really usefull if there is a way to respont to console messages.

**Comment by toni1506mc** [comment]
> > How does the inventory open?
> > With a Command (/server) or a Item ?
> 
> It opens via an Item(Compass) in the hotbar. I can join that server etc, however it would be really usefull if there is a way to respont to console messages.

I don't think you can respond directly to messages from the console. Do you want to automate joining to another server using the compass?

**Comment by ProfLinebeck** [comment]
> 
> 
> > > How does the inventory open?
> > > With a Command (/server) or a Item ?
> > 
> > 
> > It opens via an Item(Compass) in the hotbar. I can join that server etc, however it would be really usefull if there is a way to respont to console messages.
> 
> I don't think you can respond directly to messages from the console. Do you want to automate joining to another server using the compass?

Alright, thanks!
I can already do this tho, but i wanted to make it more specific. I am using `wait` but instead of that, i wanted to "wait" for the console message to continue the code.
```
changeslot 5
wait 10
useitem
wait 80
inventory 1 click 14
wait 80
inventory 2 click 14
wait 30
autodrop on
```

Now as you can see, it waits for 8 seconds. This is cause sometimes there are server lags which causes `inventory` to not work. So i wanted to wait for the inventory to open and then clicking on the item. Console message would be a great solution for this

**Comment by ReinforceZwei** [comment]
You may use `ChatBot` `OnInventoryOpen()` event to listen for inventory open event.
https://github.com/ORelio/Minecraft-Console-Client/blob/83e61f04b7df1d347559551898db7c7f75fb0cc9/MinecraftClient/ChatBot.cs#L322-L326

Example:
`mybot.cs`
```cs
//MCCScript 1.0
MCC.LoadBot(new MyBot());

//MCCScript Extensions

public class MyBot : ChatBot
{
    int steps = 0;

    public override void Initialize()
    {
        ChangeSlot(4); // slot 0 - 8
        UseItemInHand();
        LogToConsole("Waiting for inventory to open...");
        // Now wait for inventory open event
    }

    public override void OnInventoryOpen(int inventoryId)
    {
        switch (steps)
        {
            case 0: WindowAction(inventoryId, 14, WindowActionType.LeftClick); break; // First click
            case 1: 
                {
                    WindowAction(inventoryId, 14, WindowActionType.LeftClick); // Second click
                    PerformInternalCommand("autodrop on");
                    UnloadBot();
                    break;
                }
            default: break;
        }
        steps++;
    }
}
```

**Comment by ProfLinebeck** [comment]
Loo

> 
> 
> You may use `ChatBot` `OnInventoryOpen()` event to listen for inventory open event.
> 
> https://github.com/ORelio/Minecraft-Console-Client/blob/83e61f04b7df1d347559551898db7c7f75fb0cc9/MinecraftClient/ChatBot.cs#L322-L326
> 
> Example:
> `mybot.cs`
> 
> ```cs
> //MCCScript 1.0
> MCC.LoadBot(new MyBot());
> 
> //MCCScript Extensions
> 
> public class MyBot : ChatBot
> {
>     int steps = 0;
> 
>     public override void Initialize()
>     {
>         ChangeSlot(4); // slot 0 - 8
>         UseItemInHand();
>         LogToConsole("Waiting for inventory to open...");
>         // Now wait for inventory open event
>     }
> 
>     public override void OnInventoryOpen(int inventoryId)
>     {
>         switch (steps)
>         {
>             case 0: WindowAction(inventoryId, 14, WindowActionType.LeftClick); break; // First click
>             case 1: 
>                 {
>                     WindowAction(inventoryId, 14, WindowActionType.LeftClick); // Second click
>                     PerformInternalCommand("autodrop on");
>                     UnloadBot();
>                     break;
>                 }
>             default: break;
>         }
>         steps++;
>     }
> }
> ```

Looks really good! Thanks ♥
