### ISSUE TITLE
Auto Respond stops working after reconnect

### ISSUE THREAD

**Issue by HolunderP** [MCCTeam/Minecraft-Console-Client#1623]
I hope it's okay to post this as an issue, since i am not 100% sure if something is wrong on my side. However i couldn't find anything, so i assume its a bug(?).

Pretty simple:
Auto Respond works as it should be, but once an Auto-Relog happens, the Auto Respond stops to work. In my case, there is a servermessage with "Use /login password to login", which triggers the Auto Respond successfully, but it does not trigger if Auto-Relog happened.

Is there anything i need to configure for this to work, maybe i missed something? Or is that actually a bug?

**Comment by ORelio** [comment]
Hi, this is abnormal because the bot should suspend/resume, or reload. Please try enabling `debugmessages` in config to see better if the bot is loaded but not working for some reason, or not loaded at all. If it still does not work, we'll need to implement #1606 to help diagnosing.

**Comment by ProfLinebeck** [comment]
> 
> 
> Hi, this is abnormal because the bot should suspend/resume, or reload. Please try enabling `debugmessages` in config to see better if the bot is loaded but not working for some reason, or not loaded at all. If it still does not work, we'll need to implement #1606 to help diagnosing.

Enabling debugmessages show actually nothing helpful :/ The bot is still working, but just ignoring matches for some reason.
The following screenshot shows the point where it has started to reconnect. After the "/login password" server message, it should trigger auto respond, but it doesn't. However(just to make this clear) it **does work** if there wasn't a reconnect.
![grafik](https://user-images.githubusercontent.com/85316197/120864831-26fb5c00-c58d-11eb-9f52-a0221140e447.png)

**Comment by ProfLinebeck** [comment]
I just found out that it successfully responded after 4-5 reconnects. As for this server i am playing on, players are getting kicked if they don't login within a few mins. Afer a few kicks and reconnects, the bot finally started to auto respond again.
