### ISSUE TITLE
Need help setting up a script for auto logging in subservers.

### ISSUE THREAD

**Issue by xEuranium** [MCCTeam/Minecraft-Console-Client#1627]
So I want my accounts to connect to the main server. When you join, it sends the message 'SERVERNAME - LOBBY'. I want my accounts to then run the command /gserver ms-skyblock-1 (The subserver my accounts need to go to.). In the event however that the subserver is down, i want my account to try again in let's say 10 seconds. It should look like this:

Input: Lobby message
Response: Run /gserver command every 10 seconds
Input: Subserver message
Response: Stop the /gserver command loop.

Any help is much appreciated!

**Comment by ORelio** [comment]
Hi,
As per user manual in [config/README](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config), I'd suggest using ScriptScheduler to perform command on login, or AutoRespond to perform command when server shows a specific message.
