### ISSUE TITLE
1.17 Support

### ISSUE THREAD

**Issue by TNTUP** [MCCTeam/Minecraft-Console-Client#1629]
Minecraft 1.17 implementation status:

☑️ Basic Chat Support
🚫 Terrain Handling
🚫 Inventories
🚫 Entities

---
**Describe your problem**

1.17 support :D (no rush, take your time! Sadly I don't know how to code so I can't contribute :c 

**Suggest a possible solution**

Take your time, as soon you are ready to update, go for it :D

PS: Do you guys has a discord server like a support server? I'd wish to join to talk and may help :)

**Comment by ReinforceZwei** [comment]
1.17 support was done in #1630

Regarding your question about Discord server, we do not have Discord server and probably will not have one due to lack of maintainers for managing Discord server.

**Comment by TNTUP** [comment]
Thanks ReinforceZwei and okay about the discord part, understandable!

**Comment by ORelio** [comment]
Hi @TNTUP, thanks for your support!
@ReinforceZwei reopening the issue as I think only basic chat is done for now.

**Comment by Sandstorrm** [comment]
about how long will it take for terrain 1.17? I have to use a normal client as I cant turn off fly in consol as player keeps flying.

**Comment by ORelio** [comment]
some pull requests are in progress but we are lacking maintainers and contributors so NO ETA available.

**Comment by milutinke** [comment]
Since this has been added in #1943 we can close this issue as resolved.
