### ISSUE TITLE
Using Inventory Handling

### ISSUE THREAD

**Issue by bignuto** [MCCTeam/Minecraft-Console-Client#1631]
Hey! I'm trying to visit someone using a command in Hypixel (1.17), and it usually just instacloses. Inventory handling and entities are on.
![image](https://user-images.githubusercontent.com/85851209/121824557-01501000-cc7b-11eb-9cb9-e6cb6f2fcdc3.png)

And during the few occasions where it doesn't close, how would I make it click a certain slot?
(the black slot) 
![image](https://user-images.githubusercontent.com/85851209/121824602-59871200-cc7b-11eb-9203-74082a2a2ec5.png)

Thanks in advance :D

**Comment by ReinforceZwei** [comment]
Enable `terrain and movement` and try again.

**Comment by bignuto** [comment]
> Enable `terrain and movement` and try again.

Sorry, I forgot to mention that was also on.

**Comment by ORelio** [comment]
Unsure why the inventory instacloses, but you can interact this way when the inventory stays open:
```
/inventory container list
/inventory container click <slot>
```
First list the inventory, then take note of slot number, and click the slot number.

**Comment by bignuto** [comment]
> Unsure why the inventory instacloses, but you can interact this way when the inventory stays open:
> 
> ```
> /inventory container list
> /inventory container click <slot>
> ```
> 
> First list the inventory, then take note of slot number, and click the slot number.

Thanks!
