### ISSUE TITLE
When I Go To An Island On A Single Block Skyblock Server, It Drops Down. (1.16.5)

### ISSUE THREAD

**Issue by ghostbottr** [MCCTeam/Minecraft-Console-Client#1632]
When I Go To An Island On A Single Block Skyblock Server, It Drops Down.

**Comment by ghostbottr** [comment]
Falling off the Island

**Comment by ReinforceZwei** [comment]
Could you provide some screenshots showing the situation?

**Comment by ghostbottr** [comment]
screen review?

**Comment by ghostbottr** [comment]
https://www.mediafire.com/file/px6la5bucix5tmv/Video+21-06-14+09-50-02-1-1.m4v/file

Screen Review.


The player named GhosterTR27 enters with the console, it happens in the video when I take it to the man.

**Comment by ReinforceZwei** [comment]
That's weird. Perhaps the client started gravity calculation before the chunk data arrive.

I am not familiar with the terrain and movement handling, maybe @ORelio could take a look at this issue?

**Comment by ghostbottr** [comment]
On some islands it does not go down. But most of it goes down. I wonder if I mcc the vanilla part of the ini file or do something else, will it work? I don't think so.

**Comment by iwixw** [comment]
I have the same problem on version 1.16+. Are there a couple more blocks under the player? I just solved this problem by putting 5-7 blocks under the player

**Comment by ghostbottr** [comment]
Yes. there is a block

**Comment by iwixw** [comment]
> ДА. есть блок

one?

**Comment by ORelio** [comment]
Hi,
What kind of block is under the player's feets?
Block properties are defined inside [MaterialExtensions.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/MaterialExtensions.cs).
Unknown blocks are treated as non-solid so gravity handling may not work if the data is incorrect.

**Comment by iwixw** [comment]
> Привет,
> какой блок находится под ногами игрока?
> Свойства блоков определяются внутри [MaterialExtensions.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/MaterialExtensions.cs).
> Неизвестные блоки обрабатываются как нетвердые, поэтому гравитационная обработка может не сработать, если данные неверны.

![image](https://user-images.githubusercontent.com/84740733/122531090-37511380-d030-11eb-8457-a78f6ef7558b.png)
Are these blocks the player can stand on normally?

**Comment by ORelio** [comment]
>  Are these blocks the player can stand on normally?

Yes.

**Comment by xXjojaXx** [comment]
Can you add this problem to the waiting for contributer list? Would be very kind, because I am facing this issue again and at some point somebody has to pause the movement downwards until the terrain sended by the server  is completly loaded.
Thank you very much
