### ISSUE TITLE
Auto-sneak when available height is 1.5 block

### ISSUE THREAD

**Issue by iwixw** [MCCTeam/Minecraft-Console-Client#1641]
1. After some time, the command /sneak disconnected. Ie the player gets up from the shift.
_

2. You probably know that on version 1.13+, if you place a half block (height 2 blocks) above the player, then the player himself will stand on the shift. (nickname will be hidden). In MMC when the player re-logs (there is a half block above him, i.e. the nickname must be hidden), the player will see the nickname standing on the shift.

                                      Sorry for my english i use a translator

**Comment by ORelio** [comment]
I'm not sure whether it's intentional but maybe the server disables it after some time, and MCC does not detect that change to put sneak back on. Also, I did not understand well the part about half blocks 😕

**Comment by iwixw** [comment]
It is difficult for me to express my thought with the help of a translator

**Comment by ReinforceZwei** [comment]
> Also, I did not understand well the part about half blocks

I guess he is talking about sneaking under 1.5 block height. Vanilla client player will keep sneaking under 1.5 block height after reconnect.

![image](https://user-images.githubusercontent.com/39955851/122662545-5a153080-d1c6-11eb-83ad-a0721d92c866.png)

**Comment by ORelio** [comment]
I see. MCC does not handle half blocks currently, so it cannot do this properly for now.

**Comment by ORelio** [comment]
Converted into an enhancement request. #300 needs to be implemented first.

**Comment by milutinke** [comment]
https://github.com/MCCTeam/Minecraft-Console-Client/assets/441903/4eeb9cc2-3f0d-46a2-b822-58176f1c24f5

coming soon

**Comment by milutinke** [comment]
Added with slab handling
