### ISSUE TITLE
MCC gets stuck after awhile and wont reconnect

### ISSUE THREAD

**Issue by BlexMC** [MCCTeam/Minecraft-Console-Client#1656]
Hello,
at irregular intervals, the Client disconnects and won't be able to reconnect. The following message gets sent into the console: 
```
Version is supported.
Logging in...
Checking Session...
mcc.disconnect.login
Failed to check session.
Failed to login to this server.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
```

**Comment by ORelio** [comment]
Are you looking for [AutoRelog](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot)? It can automatically relog you when connection is lost. Regarding the log you posted, `Failed to check session` usually means that MCC failed to contact Mojang for validating the session on server join. This may happen if you are using many accounts at the same time with MCC.

**Comment by PrivateServersGANG** [comment]
i had this to it would work fine then freeze/lag beyond fixing change the version

**Comment by ORelio** [comment]
OK. If you can't use AutoRelog, try `exitonfailure=true` in config then use a script to relaunch MCC in a loop: https://github.com/ORelio/Minecraft-Console-Client/issues/252#issuecomment-283615317

**Comment by milutinke** [comment]
Closing due to being stale.
Try with the latest release as there were a lot of changes since the issue was opened.
If you experience the issue again, open a new issue here, due to this being really old.
