### ISSUE TITLE
Hide chat messages in GetText event in ChatBots

### ISSUE THREAD

**Issue by Nekiplay** [MCCTeam/Minecraft-Console-Client#1658]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

I would like to cancel the text output to the console via the GetText event

**Comment by ORelio** [comment]
Hi,
What would be the purpose of filtering chat messages in bots?
Since MCC already has a chatfilter setting in config?

**Comment by Nekiplay** [comment]
Пример у меня есть скрипт на казино игровой валюты и я бы хотел чтобы я мог в GetChat допустим у нового параметра bool canceled поставить true и это сообщение не выводилось в консоль
![image](https://user-images.githubusercontent.com/35975332/124115122-d8a38500-da86-11eb-949f-6fc5e37d1929.png)
![image](https://user-images.githubusercontent.com/35975332/124115139-de996600-da86-11eb-8eb2-95dd02933af4.png)

**Comment by ORelio** [comment]
Okay, maybe I did not ask correctly.
_Why would you want to hide some messages from the user?_
If the user wants not so see something, they have a setting in config for that.
The ChatBot API is made to explicitly show the user anything that is done automatically on their behalf.
Hiding chat message contradicts that, so I want to make sure you have a use case where it is really useful.

**Comment by Nekiplay** [comment]
I am making a script for a command on one server and the server command outputs not quite the correct data than my version and I do not want the user to see 2 messages of the same nature

**Comment by ORelio** [comment]
Got it. Thanks for elaborating.
