### ISSUE TITLE
How to change the version?

### ISSUE THREAD

**Issue by i004** [MCCTeam/Minecraft-Console-Client#1663]
Hello, I have a 1.16.5 server, and when I connect to the server it kicks me and says that the server is outdated.
How I can change version to 1.16.5?

![image](https://user-images.githubusercontent.com/43674123/124491175-a4e49a00-ddbb-11eb-916f-0b94a3204ea9.png)

**Comment by Ccode-lang** [comment]
You need to change the version in the .ini file

**Comment by Daenges** [comment]
Does this answer satisfy your question? If yes, please remember to close the issue if you do not have any further questions. ;D
