### ISSUE TITLE
AutoRelog Issue

### ISSUE THREAD

**Issue by hamzakhanaguirre** [MCCTeam/Minecraft-Console-Client#1666]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
A clear description of what you want to happen (I'd like the app to do [...])

I want to be able to auto relog into the minecraft server without it crashing.

---
## Describe your current situation
A clear description of what is happening (The app didn't do what I expected, instead [...]/I don't know how to make the app to do [...])

I don't know how to make it stop crashing after it relogs into the mc server for the second/third time.

---
## Solutions you've already considered

1. I've only looked at the auto relog feature and made sure it was enabled.
2.

---
## Screenshots to help explain your situation (If applicable)

![Screen Shot 2021-07-06 at 7 36 56 PM](https://user-images.githubusercontent.com/72109606/124691956-8cdf4a00-de91-11eb-874e-ad9b6e4165bd.png)

---
## Anythings that could help us answering your question
(your scripts, config, log output, information about your system...)
I'm on mac os.

**Comment by hamzakhanaguirre** [comment]
![Screen Shot 2021-07-06 at 7 48 56 PM](https://user-images.githubusercontent.com/72109606/124692868-383cce80-de93-11eb-95ae-86c33d70273b.png)
my bad*

**Comment by Daenges** [comment]
Have you entered the correct kickmessages in the mentioned "kickmessages.txt"?

**Comment by ReinforceZwei** [comment]
Please provide screenshots of client crashing.

**Comment by hamzakhanaguirre** [comment]
![Screen Shot 2021-07-07 at 6 38 38 AM](https://user-images.githubusercontent.com/72109606/124769306-36ecbf80-deee-11eb-9c71-79d824422ef8.png)

**Comment by hamzakhanaguirre** [comment]
Now its just showing up blank when i start it up.

**Comment by ORelio** [comment]
Hi, this looks like a big issue in the Mono framework. This will likely be fixed by not using Mono once #1313 is implemented.

**Comment by hamzakhanaguirre** [comment]
How can I find out when that’s implemented and what would I do? Sorry if this is basic I just don’t really know much about this yet.

**Comment by ORelio** [comment]
It is work-in-progress, no ETA yet. For now, you may attempt to update Mono.

**Comment by hamzakhanaguirre** [comment]
Do you know where I can update mono? And to update do I need to uninstall the current version?

**Comment by ORelio** [comment]
Depends on your operating system.
https://www.mono-project.com/download/stable/

**Comment by milutinke** [comment]
Since mono is not used anymore, we can close this one too.
