### ISSUE TITLE
AutoDrop not working properly

### ISSUE THREAD

**Issue by DennieDev** [MCCTeam/Minecraft-Console-Client#1675]
---
## Expected Behavior
If I drop an item into the inventory via the console client it should automatically drop it

---
## Actual Behavior
It drops it after teleporting or spawning but then it stops

---
## Steps to Reproduce the Problem
- Enable autodrop with the everything tag
- Spawn the account on your server
- Drop something onto the account

---
## Screenshot (If applicable)
![image](https://user-images.githubusercontent.com/5616861/125063112-60a11480-e0af-11eb-8f63-989dcd502325.png)

---
## Specifications

  - Console Client version:  Latest
  - Device: (Desktop, Laptop, VPS, Raspberry Pi, etc): VPS
  - Operating System: Ubuntu 18.04LTS
  - Minecraft version: 1.12.2

**Comment by ReinforceZwei** [comment]
Hi, I cannot reproduce the bug on my machine. What server core is your server using? (vanilla, paper, bukkit, spigot, ...)

**Comment by Gamefist** [comment]
Its skyblocky.com not sure what core they use. I have had this issue on 1.12.2 and 1.16.5 so far

**Comment by milutinke** [comment]
Could not reproduce the bug, tried multiple versions.
