### ISSUE TITLE
I don't understand alerts

### ISSUE THREAD

**Issue by xEuranium** [MCCTeam/Minecraft-Console-Client#1676]
I don't understand how the Alerts function works. I just want to be alerted with something like a beep when someone says my ign. can anyone explain to me how it works?

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-alerts-bot
> Write in [`alerts.txt`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/alerts.txt) the words you want the console to beep/alert you on.
> Write in [`alerts-exclude.txt`](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/alerts-exclude.txt) the words you want NOT to be alerted on.
> For example write `Yourname` in `alerts.txt` and `<Yourname>` in `alerts-exclude.txt` to avoid alerts when you are talking.
