### ISSUE TITLE
Failing to change minecraft version

### ISSUE THREAD

**Issue by ghost** [MCCTeam/Minecraft-Console-Client#1679]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [ ] I have redacted session tokens and passwords before attaching screenshots

---
## Expected Behavior
When entering a custom minecraft version (in this case 1.17) the console client should set it to 1.17 in order to allow me to play on realms with the console client. Realms are currently 1.17, and they refuse connection on 1.17.1 and higher clients.

---
## Actual Behavior
The version stays on auto, it goes and it checks the version, puts it as 1.17.1, and then fails to connect as expected.

---
## Steps to Reproduce the Problem

  1. Try to connect to a realm.
  2. It will fail. Set the version to 1.17, which is the current version realms run on.
  3. Observe as it fails to change to 1.17 and instead puts it on 1.17.1, fails to connect, and prints the expected error message: [multiplayer.disconnect.incompatible] 1.17

---
## Screenshot (If applicable)

---
## Anythings that could help diagnosing the bug
(config, log output)

---
## Specifications

  - Console Client version:  latest
  - Device: (Desktop, Laptop, VPS, Raspberry Pi, etc) windows desktop
  - Operating System: windows
  - Minecraft version: 1.17 and 1.17.1
  - Server address (If applicable):

**Comment by ReinforceZwei** [comment]
Please enable debug message and post the log output here.
