### ISSUE TITLE
Issue logging in

### ISSUE THREAD

**Issue by HarryGK** [MCCTeam/Minecraft-Console-Client#1682]
![image](https://user-images.githubusercontent.com/86246686/125333072-cdb6e300-e317-11eb-8e3c-82ce3d15765f.png)

My console client has stopped letting me in for some reason, i tried deleting and redownloading the file but that did not work (the minecraft.ini)

**Comment by HarryGK** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/86246686/125333072-cdb6e300-e317-11eb-8e3c-82ce3d15765f.png)
> 
> My console client has stopped letting me in for some reason, i tried deleting and redownloading the file but that did not work (the minecraft.ini)

it gets me to the servers hub but will not allow me to connect to the other subservers

**Comment by ORelio** [comment]
`You logged in from another location`: Are you sure there is no other MCC or Minecraft instance running with this account?

**Comment by HarryGK** [comment]
> 
> 
> `You logged in from another location`: Are you sure there is no other MCC or Minecraft instance running with this account?

oddly it fixed itself? idk what happened
