### ISSUE TITLE
Unexpected handling queue empty

### ISSUE THREAD

**Issue by pxlzgmng** [MCCTeam/Minecraft-Console-Client#1683]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [x] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

---
## Expected Behavior

---
## Actual Behavior

---
## Steps to Reproduce the Problem

  1. Login to play.caelimc.xyz server
  2. got error   
  

---
## Screenshot (If applicable)

![Untitled](https://user-images.githubusercontent.com/87378026/125467299-9ac104bf-834f-4a66-b539-9e1fb875a8f8.png)

---
## Anythings that could help diagnosing the bug
(config, log output)

# Minecraft Console Client v1.17.1
# Startup Config File

[Main]

# General settings
# Leave blank to prompt user on startup
# Use "-" as password for offline mode

login=
password=
serverip=
type=mojang                        # Account type. mojang or microsoft
method=mcc                         # Microsoft Account sign-in method. mcc OR browser

# Advanced settings

language=en_GB
consoletitle=%username%@%serverip% - Minecraft Console Client
internalcmdchar=slash              # Use 'none', 'slash' or 'backslash'
messagecooldown=1                  # Minimum delay in seconds between messages to avoid being kicked for spam.
botowners=Player1,Player2,Player3  # Name list or myfile.txt, one name per line. !Server admins can impersonate owners!
mcversion=auto                     # Use 'auto' or '1.X.X' values. Allows to skip server info retrieval.
mcforge=auto                       # Use 'auto', 'false' or 'true'. Force-enabling only works for MC 1.13+.
brandinfo=mcc                      # Use 'mcc', 'vanilla', or 'none'. This is how MCC identifies itself to the server.
chatbotlogfile= true                   # Leave empty for no logfile
privatemsgscmdname=tell            # Used by RemoteControl bot
showsystemmessages=true            # System messages for server ops
showxpbarmessages=true             # Messages displayed above xp bar
showchatlinks=true                 # Show links embedded in chat messages
showinventorylayout=true           # Show inventory layout as ASCII art in inventory command
terrainandmovements=false          # Uses more ram, cpu, bandwidth
inventoryhandling=false            # Toggle inventory handling (beta)
entityhandling=false               # Toggle entity handling (beta)
sessioncache=disk                  # How to retain session tokens. Use 'none', 'memory' or 'disk'
resolvesrvrecords=fast             # Use 'false', 'fast' (5s timeout), or 'true'. Required for joining some servers.
accountlist=accounts.txt           # See README > 'Servers and Accounts file' for more info about this file
serverlist=servers.txt             # See README > 'Servers and Accounts file' for more info about this file
playerheadicon=true                # Only works on Windows XP-8 or Windows 10 with old console
exitonfailure=false                # Disable pauses on error, for using MCC in non-interactive scripts
scriptcache=true                   # Cache compiled scripts for faster load on low-end devices
timestamps=false                   # Prepend timestamps to chat messages
autorespawn=false                  # Toggle auto respawn if client player was dead (make sure your spawn point is safe)
minecraftrealms=true               # Enable support for joining Minecraft Realms worlds

[Logging]
# Only affect the messages on console.
debugmessages=true                # Please enable this before submitting bug reports. Thanks!
chatmessages=true                  # Show server chat messages
warningmessages=true               # Show warning messages
errormessages=true                 # Show error messages
infomessages=true                  # Informative messages (i.e Most of the message from MCC)
#chatfilter=                       # Regex for filtering chat message
#debugfilter=                      # Regex for filtering debug message
filtermode=blacklist               # blacklist OR whitelist. Blacklist hide message match regex. Whitelist show message match regex
logtofile=true                    # Write log messages to file
logfile=console-log-%username%-%serverip%.txt    # Log file name
prependtimestamp=false             # Prepend timestamp to messages in log file

[AppVars]
# yourvar=yourvalue
# can be used in some other fields as %yourvar%
# %username% and %serverip% are reserved variables.

[Proxy]
enabled=false                      # Use 'false', 'true', or 'login' for login only
type=HTTP                          # Supported types: HTTP, SOCKS4, SOCKS4a, SOCKS5
server=0.0.0.0:0000                # Proxy server must allow HTTPS for login, and non-443 ports for playing
username=                          # Only required for password-protected proxies
password=                          # Only required for password-protected proxies

[ChatFormat]
# Do not forget to uncomment (remove '#') these settings if modifying them
builtins=true                      # MCC built-in support for common message formats
# public=^<([a-zA-Z0-9_]+)> (.+)$
# private=^([a-zA-Z0-9_]+) whispers to you: (.+)$
# tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$

[MCSettings]
enabled=true                       # If disabled, settings below are not sent to the server
locale=en_US                       # Use any language implemented in Minecraft
renderdistance=medium              # Use tiny, short, medium, far, or chunk amount [0 - 255]
difficulty=normal                  # MC 1.7- difficulty. peaceful, easy, normal, difficult
chatmode=enabled                   # Use 'enabled', 'commands', or 'disabled'. Allows to mute yourself...
chatcolors=true                    # Allows disabling chat colors server-side
main_hand=left                     # MC 1.9+ main hand. left or right
skin_cape=true
skin_hat=true
skin_jacket=false
skin_sleeve_left=false
skin_sleeve_right=false
skin_pants_left=false
skin_pants_right=false
# Bot Settings

[Alerts]
enabled=false
alertsfile=alerts.txt
excludesfile=alerts-exclude.txt
beeponalert=true

[AntiAFK]
enabled=false
delay=600 #10 = 1s
command=/ping

[AutoRelog]
enabled=false
delay=10                           # use 10 for 10 seconds, 10-60 for a random delay between 10 and 60 seconds
retries=3                          # retries when failing to relog to the server. use -1 for unlimited retries
kickmessagesfile=kickmessages.txt  # file with list of matches in kick messages that will trigger autorelog
ignorekickmessage=false            # when set to true, autorelog will reconnect regardless of kick messages

[ChatLog]
enabled=true
timestamps=true
filter=messages
logfile=chatlog-%username%-%serverip%.txt

[Hangman]
enabled=false
english=true
wordsfile=hangman-en.txt
fichiermots=hangman-fr.txt

[ScriptScheduler]
enabled=false
tasksfile=tasks.ini

[RemoteControl]
enabled=false
autotpaccept=true
tpaccepteveryone=false

[AutoRespond]
enabled=false
matchesfile=matches.ini

[AutoAttack]
# Entity Handling NEED to be enabled first
enabled=false
mode=single                        # single or multi. single target one mob per attack. multi target all mobs in range per attack
priority=distance                  # health or distance. Only needed when using single mode
cooldownseconds=auto                # How long to wait between each attack. Use auto to let MCC calculate it

[AutoFishing]
# Entity Handling NEED to be enabled first
enabled=false
antidespawn=false

[AutoEat]
# Inventory Handling NEED to be enabled first
enabled=false
threshold=6

[AutoCraft]
# Inventory Handling NEED to be enabled first
# Enable terrainandmovements if you need to use crafting table
enabled=false
configfile=autocraft\config.ini

[Mailer]
# Let the bot act like a mail plugin
enabled=false
database=MailerDatabase.ini
ignorelist=MailerIgnoreList.ini
publicinteractions=false
maxmailsperplayer=10
maxdatabasesize=10000
retentiondays=30

[AutoDrop]
# Inventory Handling NEED to be enabled first
enabled=false
mode=include                      # include, exclude or everything. Include: drop item IN the list. Exclude: drop item NOT IN the list
items=                            # separate each item with comma ','
# For the naming of the items, please see 
# https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Inventory/ItemType.cs 

[ReplayMod]
# Enable recording the game and replay it later using Replay Mod
# You MUST exit the program using /quit command or the replay will NOT be saved!
enabled=false
backupinterval=300                # How long should replay file be auto-saved, in seconds. Use -1 for disabled

---
## Specifications

  - Console Client version: 1.17.1
  - Device: (Desktop, Laptop, VPS, Raspberry Pi, etc)
  - Operating System: windows 10
  - Minecraft version:1.16.5
  - Server address (If applicable): play.caelimc.xyz

**Comment by milutinke** [comment]
Can't re-create, probably fixed in the releases we did so far, it is happens to you again, re-open the issue.
