### ISSUE TITLE
Chatbot script

### ISSUE THREAD

**Issue by Fr-gs** [MCCTeam/Minecraft-Console-Client#1684]
Is there a script that sends a message forever every x minutes

**Comment by ReinforceZwei** [comment]
myscript.txt
```
send Hello!
// Wait 300 seconds (5 minutes)
wait 300
script myscript.txt
```

**Comment by ORelio** [comment]
Or use [ScriptScheduler](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-script-scheduler--task-scheduler):
```ini
[Task]
triggerOnInterval=true
timeInterval=60
action=send Hello World
```
