### ISSUE TITLE
Getting error: InvalidOperationException: { expected when running modified version of AutoRelog

### ISSUE THREAD

**Issue by trobanko12** [MCCTeam/Minecraft-Console-Client#1690]
**Prerequisites**
 - [y ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [y ] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [ y] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
I want this script to perform the auto relog whenever the player disconnects, unlike the included one that only relogsif certain conditions are met, I'd also like it to type a command once it has reconnected to the server

---
## Describe your current situation
I am getting an error: InvalidOperationException: { expected but I think all the braces are correct

---
## Solutions you've already considered

I tried googling for the issue but I am not very experienced with C#

---
## Screenshots to help explain your situation (If applicable)

![image](https://user-images.githubusercontent.com/87530662/125949017-386b132a-b1b3-4340-9306-43c2fa675f09.png)

---
## Anythings that could help us answering your question
```cs
//MCCScript 1.0


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MinecraftClient.ChatBots
{

    public class AutoRelog : ChatBot
    {
		
        private static Random random = new Random();
        private string[] dictionary = new string[0];
        private int attempts;
        private int delayMin;
        private int delayMax;

        public AutoRelog(int DelayBeforeRelogMin, int DelayBeforeRelogMax, int retries)
        {
            attempts = retries;
            if (attempts == -1) { attempts = int.MaxValue; }
            McClient.ReconnectionAttemptsLeft = attempts;
            delayMin = DelayBeforeRelogMin;
            delayMax = DelayBeforeRelogMax;
            if (delayMin < 1)
                delayMin = 1;
            if (delayMax < delayMin)
                delayMax = delayMin;
            LogDebugToConsoleTranslated("bot.autoRelog.launch", attempts);
        }

        public override void Initialize()
        {
            McClient.ReconnectionAttemptsLeft = attempts;
        }

        public override bool OnDisconnect(DisconnectReason reason, string message)
        {

                message = GetVerbatim(message);
                string comp = message.ToLower();

                LogDebugToConsoleTranslated("bot.autoRelog.disconnect_msg", message);

                    LaunchDelayedReconnection(null);
					MCC.LogToConsole("Sleeping for 800ms...");
					Thread.Sleep(800);
					MCC.SendText("/join prison");
                    return true;
        }

        private void LaunchDelayedReconnection(string msg)
        {
            int delay = random.Next(delayMin, delayMax);
            LogDebugToConsoleTranslated(String.IsNullOrEmpty(msg) ? "bot.autoRelog.reconnect_always" : "bot.autoRelog.reconnect", msg);
            LogToConsoleTranslated("bot.autoRelog.wait", delay);
            System.Threading.Thread.Sleep(delay * 1000);
            ReconnectToTheServer();
        }

        public static bool OnDisconnectStatic(DisconnectReason reason, string message)
        {
            if (Settings.AutoRelog_Enabled)
            {
                AutoRelog bot = new AutoRelog(Settings.AutoRelog_Delay_Min, Settings.AutoRelog_Delay_Max, Settings.AutoRelog_Retries);
                bot.Initialize();
                return bot.OnDisconnect(reason, message);
            }
            return false;
        }
    }
}
```

**Comment by trobanko12** [comment]
Not sure why only half of the thing is considered code on github, but there is a curly brace missing at the bottom (its there, just bad formatting) and some stuff at the top

**Comment by ReinforceZwei** [comment]
_Edited your issue to format the code correctly._

There's an option `ignorekickmessage` to ignore disconnect reason and reconnect anyway. Have you tried that option?
https://github.com/ORelio/Minecraft-Console-Client/blob/982f358bf37b69ac1d99887887d71fe86226a2fb/MinecraftClient/Resources/config/MinecraftClient.ini#L106-L111

***

For sending command after reconnect, you may use [Task Scheduler](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-script-scheduler--task-scheduler). See [sample-tasks.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini) for example.

**Comment by trobanko12** [comment]
Get the exact same error, even with the pre-made AutoRelog file (without editing anything, just the one included with the install) that one does not work too :(

**Comment by trobanko12** [comment]
Still have not been able to fix it, does it normally work with a fresh install and just using the default file? because that is what I did and it doesn't work

**Comment by ReinforceZwei** [comment]
Since you mention `file`, I assume you have loaded `AutoRelog` using `/script` command. `AutoRelog` is a built-in bot and you just need to enable it in the configuration file.

To enable `AutoRelog`:
1. Open `MinecraftClient.ini` file with any text editor
2. Locate `[AutoRelog]`
3. Set `enable` to `true` (Line 107)
https://github.com/ORelio/Minecraft-Console-Client/blob/982f358bf37b69ac1d99887887d71fe86226a2fb/MinecraftClient/Resources/config/MinecraftClient.ini#L106-L111
4. Save the file
5. Start Console Client

**Comment by trobanko12** [comment]
I have done that, how can I check if auto-relog is working correctly?

**Comment by ReinforceZwei** [comment]
You may either kick your client player from server or just wait for disconnection.

**Comment by trobanko12** [comment]
I have just asked for an admin to kick me out and the client did not attempt to reconnect, it just sat there idling

**Comment by ReinforceZwei** [comment]
Did you set `ignorekickmessage=true` in your configuration file?

**Comment by trobanko12** [comment]
Yes I did, `[AutoRelog]
enabled=true
delay=10                           # use 10 for 10 seconds, 10-60 for a random delay between 10 and 60 seconds
retries=1000                          # retries when failing to relog to the server. use -1 for unlimited retries
kickmessagesfile=kickmessages.txt  # file with list of matches in kick messages that will trigger autorelog
ignorekickmessage=true            # when set to true, autorelog will reconnect regardless of kick messages
`

**Comment by ReinforceZwei** [comment]
> it just sat there idling

Could you provide screenshot?

**Comment by trobanko12** [comment]
![image](https://user-images.githubusercontent.com/87530662/126040175-7a68dd24-434c-4e3a-81fb-f09c40afe4e9.png)

**Comment by trobanko12** [comment]
Even tried building a whole fresh new instance of the client with nothing edited but the AutoRelog feature enabled, still does notr work 
![image](https://user-images.githubusercontent.com/87530662/126040322-00173886-3cc2-4120-bb54-2b3203a27317.png)

**Comment by ReinforceZwei** [comment]
Did you save the configuration file after editing it?

**Comment by trobanko12** [comment]
Yep

**Comment by trobanko12** [comment]
This is exactly what I did:

Built the program using MsBuild
Navigated to resources, config and edited the MinecraftClient.ini
Change auto relog to true, same with ignorekickmessage
Saved the file, launched the exe, logged into the server and got kicked by console. The client just chills about doing nothing

**Comment by ReinforceZwei** [comment]
> Navigated to resources

This step is incorrect. You should be modifying the `MinecraftClient.ini` generated by `MinecraftClient.exe`.

**Comment by trobanko12** [comment]
awesome, fixed, thank you for your support!
