### ISSUE TITLE
[Question] Is there any documentation for the client?

### ISSUE THREAD

**Issue by BloodyEll** [MCCTeam/Minecraft-Console-Client#1694]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

I'm interested in the client and would like to play around with it, Is there any documentation on the usage of the API?

### Device

Laptop

### Operating System

MacOS

**Comment by ReinforceZwei** [comment]
You may start by seeing the [How to use](https://github.com/ORelio/Minecraft-Console-Client#how-to-use) section.

**Comment by milutinke** [comment]
Since now we have a proper documentation [website](https://mccteam.github.io/docs/), this issue can be closed.
