### ISSUE TITLE
Help putting a script in the client. 

### ISSUE THREAD

**Issue by Jaydoss1** [MCCTeam/Minecraft-Console-Client#1695]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Im not sure how to check what version 

### Description of the Question

I do not know how to inject my files into the minecraft client, or even how to get it up

### Solutions you've already considered

nothing really

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/87676720/126236325-f40484f2-0d95-485a-aaee-8a31fb969e51.png)
This is the macro i want to add to minecraft client could you guys help me out

### Anythings that could help us answering the question

```txt
Contact my discord Jaydos#2959 if its easier
```

### Minecraft Version

1.12.2

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

Hypixel

**Comment by ReinforceZwei** [comment]
I am not sure what exactly you want to achieve. If you want to start a external program, you may write a  C# script and use [`System.Diagnostics.Process`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=net-5.0) to start your program.

**Comment by ORelio** [comment]
use `/script myscripfilet.txt` in the console after joining a server
