### ISSUE TITLE
Time Interval

### ISSUE THREAD

**Issue by TeknoManyi** [MCCTeam/Minecraft-Console-Client#1699]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

I want infinity loop for tasks.ini but i dont know command

### Solutions you've already considered

1. 
2. 

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

**Comment by Daenges** [comment]
Orelios last comment shows a way to make a self repeating task here: #1684
