### ISSUE TITLE
[Idea] I wanted to request as well as ask if it's possible to implement Labymod into the console client.

### ISSUE THREAD

**Issue by 1Dilva** [MCCTeam/Minecraft-Console-Client#1701]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

The client has Vanilla and forge additions I think it wouldn't be as hard to implement Labymod as well

### Suggest a possible solution

I want to run console client using Labymod as a version option It's helpful to grind hours and to show off your cosmetics while you are AFK

### Minecraft Version

1.8.9, 1.12.2 and 1.16.5 but I want it mainly for 1.8.9

### Device

VPS

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
Seems like Labymod is a client modification mod. Unfortunately it is not possible to add a such feature to MCC that is targeting vanilla client.
