### ISSUE TITLE
Replay mod feature

### ISSUE THREAD

**Issue by Heringen** [MCCTeam/Minecraft-Console-Client#1702]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

How do i enable/use replaymod using MCC?
in sample files it just says "Replay Mod is A Minecraft Mod to record, relive and share your experience. You can see more at https://www.replaymod.com/

MCC supports recording and saving your game to a file which can be used by Replay Mod. You can simply enable ReplayMod in the .ini setting to use this feature. The only limitation is the client player (you) will not be shown in the replay. Please note that when recording is in progress, you SHOULD exit MCC with the /quit command or use /replay stop command before closing MCC as your replay may become corrupt if you force-close MCC with CTRL+C or the [X] button."
however no explicite explanation how to use it.
I do have replay mod installed.

### Solutions you've already considered

1. Adding ReplayMod=enabled in .ini nd using /replay start

### Anythings that could help us answering the question

```txt
Nop
```

### Minecraft Version

1.8.9

### Device

Desktop

### Operating System

Windows

**Comment by ORelio** [comment]
Set `enabled=true` in the correct section of the config file.
https://github.com/ORelio/Minecraft-Console-Client/blob/f16e9e87dd82381514d5ea11300d88b4d47dfd25/MinecraftClient/Resources/config/MinecraftClient.ini#L179-L182

**Comment by Heringen** [comment]
Yeah that works, thanks mate! Just to ask, does it automatically start recording when you open bot or? If so can it be paused/resumed or just straight up stopped?

**Comment by ReinforceZwei** [comment]
It will automatically start recording when you start the client. It cannot be paused or resumed. Once you stopped recording you will have to restart the client to start another record.

**Comment by Heringen** [comment]
> It will automatically start recording when you start the client. It cannot be paused or resumed. Once you stopped recording you will have to restart the client to start another record.

Aight, thanks for yall's help!
