### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by thomaskeig** [MCCTeam/Minecraft-Console-Client#1704]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1.9.0

### Description of the Question

How can I run this on a linux vps?

### Minecraft Version

1.17.1

### Device

VPS

### Operating System

Linux

**Comment by ReinforceZwei** [comment]
See https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-use

> On Linux: sudo apt-get install mono-runtime libmono-reflection-cil Then, open a terminal in this folder and run "mono MinecraftClient.exe". If you cannot authenticate on Mono, you'll need to run "mozroots --import --ask-remove" once. If Mono crashes, retry with mono-complete instead of mono-runtime. Use at least Mono v4.0.
