### ISSUE TITLE
[Question] A list of sentences

### ISSUE THREAD

**Issue by Fr-gs** [MCCTeam/Minecraft-Console-Client#1707]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

Is it possible to read sentences from a file and randomly pick a sentence from that file and send that in the minecraft chat.
The reason I wanna do this is because I want to send a random quote every hour. If this isn't possible let me know if there are any other options without reading it from a file maybe? Thank you

### Solutions you've already considered

1. 
2.

**Comment by ORelio** [comment]
See [sample-script-with-random-command.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-random-command.cs) for an example of how to do this.

**Comment by ORelio** [comment]
All script files must start with `//MCCScript 1.0`

**Comment by Daenges** [comment]
Now also possible with the `/setrnd` command. #1846
