### ISSUE TITLE
User Not Premium error

### ISSUE THREAD

**Issue by xEuranium** [MCCTeam/Minecraft-Console-Client#1715]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

When I try to log in with my Microsoft account into MCC, i get the error given in the screenshot: 'User not premium.'
It works just fine with my mojang account, but not with my microsoft account.

### Solutions you've already considered

1. Logging in by prompting email and password (didn't work)
2. Logging in via minecraft (Works, but not useful)

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/81428572/128626005-8736297f-4665-49e3-ba93-14154e3fa101.png)

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

m.mcs.gg

**Comment by ReinforceZwei** [comment]
Take a look at #1474

**Comment by xEuranium** [comment]
> Take a look at #1474

I did. I have logged in on this microsoft account multiple times, but now it suddenly gives this error. I have the latest version, the login credentials are right, it is set to microsoft.

**Comment by ReinforceZwei** [comment]
Maybe you could try to use `browser` method to sign-in.
