### ISSUE TITLE
[Question] How to change DiscordWebhook.cs skinModes

### ISSUE THREAD

**Issue by AbdobiZark** [MCCTeam/Minecraft-Console-Client#1716]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

I know someone has submitted it but there is no solution on how
![image](https://user-images.githubusercontent.com/88251043/128634346-79bfcf8b-e162-4596-9b54-047447822262.png)

### Solutions you've already considered

1. 
2. 

### Anythings that could help us answering the question

```txt
public WebhoookSettings()
    {
        // Set preconfigured skinModes
        skinModes.Add("flatFace", "https://crafatar.com/avatars/{0}");
        skinModes.Add("cubeHead", "https://crafatar.com/renders/head/{0}");
        skinModes.Add("fullSkin", "https://crafatar.com/renders/body/{0}");
```

### Minecraft Version

Auto

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

Crack Server

**Comment by AbdobiZark** [comment]
@Daenges can you help me with this?

**Comment by Daenges** [comment]
There are a few commands. The head is changed with
`/dw avatar size/scale/skintype [value]`

- size and scale change the resolution [numbers as values] (If the image does not fit for you, play around with it a bit.)
- skintype changes the skin appearance [options are 'flatFace', 'cubeHead', 'fullSkin'] try each of them and decide which fits best.

`/dw avatar overlay/fallbackskin`
- overlay toggles the skin overlay
- fallbackskin toggles the fallbackskin between Alex/Steve

**Comment by AbdobiZark** [comment]
@Daenges sad to say but it only work on the " Players " 
![image](https://user-images.githubusercontent.com/88251043/128634940-9c0853fb-b563-49e2-b0f7-3673c65cfe20.png)
not the [ Server ]

**Comment by Daenges** [comment]
Uhm.. the server is a standard image. It is hardcoded, since I did not had any idea of which icon a server should use. Look [here](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/DiscordWebhook.cs#L464). If the script detects a server message, it just sets the skin of a predefined UUID, which is a player with this console head. If you want to, you could change `sAPI.GetSkinURLCrafatar("f78a4d8dd51b4b3998a3230f2de0c670")` to any link to an image in string format you want.

**Comment by AbdobiZark** [comment]
@Daenges  thanks it work 
also i changed 2 of them, is it necessary?
![image](https://user-images.githubusercontent.com/88251043/128635498-44d47b92-067f-40b1-b6fd-268b58575c6f.png)

**Comment by Daenges** [comment]
The bottom one is for log purposes. The top one is for when everything works fine. Just change the top UUID and you should be fine.

**Comment by AbdobiZark** [comment]
aight thanks you are the best!
