### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Mcstudio-technik** [MCCTeam/Minecraft-Console-Client#1718]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

Hi, could you please explain to me how to run minecraft console client in docker on docker?

### Solutions you've already considered

1. 
2. 

### Minecraft Version

1.8.8

### Server Address (If applicable)

nssv.pl

**Comment by ORelio** [comment]
See https://github.com/ORelio/Minecraft-Console-Client/tree/master/Docker and  #1504
Feel free to ask @Tandashi for more details, if needed.

**Comment by Tandashi** [comment]
So you want to run the docker image in another docker instance. Is that correct? If so, are you using the [dind](https://hub.docker.com/_/docker) Image from Docker?

Is there a special reason why you have to run it inside another docker instance? Docker-in-Docker is usually only needed for development purposes.

**Comment by Mcstudio-technik** [comment]
I want to run in a different instance because I need to install on each vpn because the server can have 2 players with the same ip

**Comment by Tandashi** [comment]
Could you please explain your setup a bit more? I just don't understand how it currently looks like. Also, you need a [dind](https://hub.docker.com/_/docker) Image to run Docker in Docker. Else it will not work. Meaning, your VPN must be inside the dind Image.

**Comment by milutinke** [comment]
Since this now is covered in the [documentation](https://mccteam.github.io/docs/guide/installation.html#using-docker), we can close the issue.
