### ISSUE TITLE
[Question] How do I make my bot walk 2 blocks when joining a server?

### ISSUE THREAD

**Issue by PythonJoshua** [MCCTeam/Minecraft-Console-Client#1719]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest Version

### Description of the Question

It's not really a problem, I just do not know where to start when doing this.

### Solutions you've already considered

1. Asking Friends who have used this.
2. Trying to find code on youtube.

### Minecraft Version

1.12.2

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

0b0t.org

note: im not using .cs im using .ini

**Comment by ORelio** [comment]
1. Create a txt script with a couple of "move" commands
2. Schedule script with ScriptScheduler.
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-script-scheduler--task-scheduler

**Comment by OptimusPrm9** [comment]
if the server has via plugin set the minecraft version to 1.12.2 in config it worked for me.

**Comment by ORelio** [comment]
> hi, i tried using /move instead and it says '[MCC] Please enable Terrain and Movements in the config file first.' yet it is enabled.

Terrain and movement is likely not handled for the server version you are joining. MCC should tell you so upon login.
