### ISSUE TITLE
How do i send message in console on [MCC]LoginFailed:

### ISSUE THREAD

**Issue by jmdevcz** [MCCTeam/Minecraft-Console-Client#1721]
I cant find it anywhere in the code, i might not have checked properly.

**Comment by ReinforceZwei** [comment]
I don't understand your question. Please explain more with some screenshots.

**Comment by jmdevcz** [comment]
Well i want the code do stuff when this occurs: 
![image](https://user-images.githubusercontent.com/69910781/129008069-d9079a15-efa9-4976-9b1e-d70f03f2ce29.png)
 
![image](https://user-images.githubusercontent.com/69910781/129008174-44410e98-0f38-463c-b6fb-8f6b2c0bfb3a.png)

**Comment by ReinforceZwei** [comment]
Are you looking for [`AutoRelog`](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot)?

**Comment by jmdevcz** [comment]
where do i find the autorelog section that executes every relog

**Comment by jmdevcz** [comment]
im stupid :/

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client/blob/f16e9e87dd82381514d5ea11300d88b4d47dfd25/MinecraftClient/Resources/config/MinecraftClient.ini#L111
