### ISSUE TITLE
How to make the bot do multiple commands after joining the server at certain intervals?

### ISSUE THREAD

**Issue by NotHashkey** [MCCTeam/Minecraft-Console-Client#1722]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

How to make the bot do multiple commands after joining the server at certain intervals?

### Solutions you've already considered

1. going thru minecraftclient.ini file
2. 

### Minecraft Version

1.12.2

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

play.wildprison.net

**Comment by ReinforceZwei** [comment]
Take a look at [User Manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config) to learn writing a script.

**Comment by NotHashkey** [comment]
ok

**Comment by NotHashkey** [comment]
what version is terrain and movement available on?

**Comment by ReinforceZwei** [comment]
1.16.5 and below.

**Comment by NotHashkey** [comment]
I cant seem to find the "accounts.txt" file.....

**Comment by ORelio** [comment]
create it. here is an example:
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-accounts.txt
