### ISSUE TITLE
[ISSUE]  DiscordWebhook.cs

### ISSUE THREAD

**Issue by AbdobiZark** [MCCTeam/Minecraft-Console-Client#1724]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

Why my DiscordWebhook.cs sending yellow text i think an error and sometimes it send same message 4time to 10times. I tried to run it overnight and my MCCC freeze ( 9pm and freeze around 12am)

I need help how to fix or make it more light lightweight and stable so i could run it 24/7

btw my DiscordWebhook.cs is on default means i only configure the weebhook link thingy

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/88251043/128902032-326a890b-52cf-48f5-9d3b-b302be1b5bd2.png)
![image](https://user-images.githubusercontent.com/88251043/128902077-0c073ddf-24db-4e2e-b8c2-ab258a6c9ba5.png)

### Minecraft Version

Auto

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

Crack Server

**Comment by ORelio** [comment]
When the client reconnects to the server, it will keep the boat loaded so to avoid loading it multiple times you can load it from the scriptscheduler event "triggerOnFirstLogin".

**Comment by AbdobiZark** [comment]
@ORelio Like This?


[Task]
triggerOnFirstLogin=true
timeInterval=600
script=DiscordWebhook.cs

**Comment by ORelio** [comment]
```ini
[Task]
triggerOnFirstLogin=true
script=DiscordWebhook.cs
```
Else it would also load the bot again every 10 minutes

**Comment by AbdobiZark** [comment]
@ORelio 
Yeah the script works but the issue wasnt fix yet. Message keep repeating/duplication by it self that may cause of overheating/lag and ended up to freeze ( stuck at lobby and my console wasn't responding at all )

**Comment by AbdobiZark** [comment]
@Daenges do you have a solution for this ?

**Comment by AbdobiZark** [comment]
I made auto restart DiscordWebhook hope it work

➥tasks.ini
# 3600 = 1h cd
[Task]
triggerOnInterval=true
timeInterval=3600
action=DWHautorestart.txt

➥DWHautorestart.txt
/dw quit
wait 15
/script DiscordWebhook

does it work? I haven't tried yet

**Comment by AbdobiZark** [comment]
![image](https://user-images.githubusercontent.com/88251043/128967630-8f284d0a-960d-46fa-bf1b-b1a1c704d4fe.png)

**Comment by Daenges** [comment]
If you have restarted the client and made sure that all the multiple bots are unloaded, could you provide a full log in debug mode, maybe with a small screenshot of the text message, so that i can recreate this bug?

**Comment by AbdobiZark** [comment]
![image](https://user-images.githubusercontent.com/88251043/129175071-e79bac7f-a305-4ffa-b122-098a2e0a2a46.png)

**Comment by Daenges** [comment]
@AbdobiZark I am sorry, but I am unable to recreate your issue with the provided information. To determine the exact issue, you need to send the **entire** debug message log from start up until some messages that are forewarded. At best in text form. Just copy the full console content into a [pastebin](https://pastebin.com/) file or this issue. **Remember to remove ALL tokens before doing so**

**Comment by milutinke** [comment]
Did some testing and could not re-create, also i've updated to bot to use ProxyWebRequest.
I'll close the issue as it is a stale one, if this still happens, re-open it.
