### ISSUE TITLE
Specific Player TP Requests [Question]

### ISSUE THREAD

**Issue by EpicDude1238** [MCCTeam/Minecraft-Console-Client#1731]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1.4.6

### Description of the Question

Is there a way to set the remotecontrol auto accept tp requests to only accept from a certain player specified?
Tried a few things now but had no luck.
Any help would be great thanks

### Solutions you've already considered

1. 
2. 

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
See [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-remote-control).

**Comment by EpicDude1238** [comment]
I've done that, but is it capable of accepting the tp requests from people with /nick? ive added 4 different variants of my name /nick to myfile.txt for botowners but it still does not accept
![image](https://user-images.githubusercontent.com/43878094/130228980-f9ade850-800f-405e-9821-5c8dcf4b630d.png)
![image](https://user-images.githubusercontent.com/43878094/130229141-f597c368-f1ae-4549-b679-a48f84450e4d.png)
![image](https://user-images.githubusercontent.com/43878094/130229205-b15fa11e-6bde-417d-81bb-ebdb4b042e58.png)

**Comment by ReinforceZwei** [comment]
To set `botowners`, do `botowners=DefeatedZore,Zorov`. You may add more player name and separating them by comma `,`.

**Comment by ORelio** [comment]
See also [detecting chat messages](https://github.com/ORelio/Minecraft-Console-Client/blob/f16e9e87dd82381514d5ea11300d88b4d47dfd25/MinecraftClient/Resources/config/MinecraftClient.ini#L111).
Maybe the nicknamed players are not recognized by MCC because the chat format is different.
