### ISSUE TITLE
[Idea/Question] Is it possible to use the minecraft console client with a microsoft account?

### ISSUE THREAD

**Issue by brunobpinto** [MCCTeam/Minecraft-Console-Client#1733]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

So I've searched here in the issues and tried to use the Microsoft account with the Minecraft Console Client but it doesn't seem to work. It only works if I'm using a Mojang account. 

The problem is the account I play is a newly purchased account so the only option to log in is through Microsoft. Besides that Mojang is also starting to migrate a few accounts to Microsoft accounts, so it's gonna be a feature that will be needed no matter what in the future. I don't know if there is any way to log in with Microsoft account in this latest version or should be a feature to be added.

### Suggest a possible solution

I don't really know how to code but I'm guessing when the console asks for my login and password it uses some sort of API or connection to connect to minecraft.net. 

My suggestion would just be login into the other option. Instead of Mojang accounts, connect to Microsoft accounts. And before the console asks for login and password it would ask for what type of account is the user using.

I hope anyone can add this since would be extremely helpful. 🙃

### Device

Laptop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
Take a look at #1474
