### ISSUE TITLE
Console Client not working with Microsoft Account gives Network Error

### ISSUE THREAD

**Issue by BiTime123** [MCCTeam/Minecraft-Console-Client#1737]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Description of the Question

When I use the Console Client on Mac, with a Mircosoft Account, it gives me `Got error code from server: 410`.

I first went to search for similar questions (i.e [this one](https://github.com/ORelio/Minecraft-Console-Client/issues/1474)) and I followed those steps. I downloaded the latest version, moved my `MinecraftClient.ini` however, when I open the latest version, it doesn't give me a new `MinecraftClient.ini`

### Solutions you've already considered

1. I tried to add `type=mircosoft` + `method=mcc` which gives me the `Got error code from server: 410`.

### Attach screenshot here (If applicable)

![Screen Shot 2021-08-24 at 2 49 22 PM](https://user-images.githubusercontent.com/89481597/130673613-bdb3edf6-697c-4922-b698-ed97a41f8f4f.png)

### Anythings that could help us answering the question

```txt
I don't know what to put here.

(also have Monoframeworked installed if that helps)
```

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

MacOS

**Comment by ORelio** [comment]
Make sure you have the [latest build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) and try setting `debugmessages=true` in config to see more details.

**Comment by BiTime123** [comment]
turned it on and same thing

![Screen Shot 2021-08-24 at 4 30 44 PM](https://user-images.githubusercontent.com/89481597/130685867-952c4167-91ea-46c5-8c8b-01c644f622f1.png)

**Comment by ORelio** [comment]
Does not seems turned on. Should print the whole HTTP request and response. Alternatively you can try `--debugmessages=true` as command line argument.

**Comment by BiTime123** [comment]
I got this error message
<img width="1116" alt="Screen Shot 2021-08-24 at 4 56 21 PM" src="https://user-images.githubusercontent.com/89481597/130688761-1fa2dac1-0471-46a6-ab73-505750c81f9e.png">

**Comment by ReinforceZwei** [comment]
The word `Microsoft` is mistyped in the config. Fix the typo and try again.

**Comment by BiTime123** [comment]
same thing? since i changed Microsoft in the `MinecraftClient.ini`

![Screen Shot 2021-08-24 at 9 16 50 PM](https://user-images.githubusercontent.com/89481597/130710528-f795018c-bc05-43af-842e-ec9393c7066c.png)

**Comment by ReinforceZwei** [comment]
You can see MCC was connecting to Mojang (Minecraft.net) for signing-in in the screenshot. Either you didn't type it correctly or you forgot to save the file. The correct setting should be `type=microsoft`

**Comment by BiTime123** [comment]
tried this
![Screen Shot 2021-08-24 at 10 03 40 PM](https://user-images.githubusercontent.com/89481597/130714239-6b1f92de-9ab7-4e8d-a87f-2287242685f3.png)

and still got 
![Screen Shot 2021-08-24 at 10 04 52 PM](https://user-images.githubusercontent.com/89481597/130714300-1dd378e5-4df8-46ed-8454-90345926c21c.png)

**Comment by ReinforceZwei** [comment]
Try to delete the config file and let MCC generate a new one.

**Comment by BiTime123** [comment]
When i delete the config file (have a backup in case), and run MCC, it doesn't seem to generate a new one.

**Comment by ReinforceZwei** [comment]
That means you are not editing the correct config file. MCC will print out the location of the config file while starting. Find out the correct file and edit that one.

**Comment by BiTime123** [comment]
Where do I find that, I'd suppose somewhere [here](https://github.com/ORelio/Minecraft-Console-Client/issues/1737#issuecomment-905094952)

also here is the console client folder too. 
![Screen Shot 2021-08-25 at 2 07 39 AM](https://user-images.githubusercontent.com/89481597/130735598-000c470e-3cf7-4c6c-ac08-63c42161fe43.png)

**Comment by ReinforceZwei** [comment]
No, it should be at the very top.

**Comment by BiTime123** [comment]
Like here?
<img width="402" alt="Screen Shot 2021-08-25 at 2 10 56 AM" src="https://user-images.githubusercontent.com/89481597/130736015-d6731fe5-4d85-41cf-99f9-70be850de872.png">

Or
<img width="1121" alt="Screen Shot 2021-08-25 at 2 11 04 AM" src="https://user-images.githubusercontent.com/89481597/130736023-ac179959-38ab-4e5f-8eb8-35ff773109ef.png">

**Comment by BiTime123** [comment]
I think I just found it.

![Screen Shot 2021-08-25 at 2 12 38 AM](https://user-images.githubusercontent.com/89481597/130736238-66277fe1-4d3c-4b8f-bf61-c043aa77873f.png)

**Comment by ReinforceZwei** [comment]
Yes. You can see `Loading settings from ...`. That's the file MCC is reading. You have to edit that file.

**Comment by BiTime123** [comment]
That's the same one from [here](https://github.com/ORelio/Minecraft-Console-Client/issues/1737#issuecomment-905110649) and [here](https://github.com/ORelio/Minecraft-Console-Client/issues/1737#issuecomment-905207122)

**Comment by ReinforceZwei** [comment]
As per the screenshot shown, you were connecting to **Minecraft.net** for signing-in. Please make sure you are using the latest version. If you are unsure, download a new copy of MCC and put it into a new folder.

**Comment by ORelio** [comment]
HTTP 410 means `Gone` so your client is most likely an old version for the old login servers that no longer exist.

**Comment by itzgabbe** [comment]
when I had used my microsoft account so after a few days the account was blocked so I had to log in to the browser to remove the block since then I have not dared to use console client @ORelio
