### ISSUE TITLE
[BUG] Microsoft sign it errors

### ISSUE THREAD

**Issue by LostAndDead** [MCCTeam/Minecraft-Console-Client#1738]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

N/A

### Console Client Version

Latest

### Expected Behavior

Using Microsoft login type with MCC i should be able to put in my username and password and play.

### Actual Behavior

Login fails with a 200 code and the body:
`<html><head><noscript>JavaScript required to sign in<meta http-equiv="Refresh" content="0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid={some uaid, idk if its private or not}"/></noscrip...`

### Steps to Reproduce the bug

1. Ubuntu 18.04.5 LTS (Important as it works on windows) (Ran with mono)
2. Setup Microsoft account type
3. MCC Login style
4. Login (Or dont)

### Anythings that could help diagnosing the bug

```txt
All config files are default apart from changing login types
```

### Device

VPS

### Operating System

Linux

**Comment by ORelio** [comment]
Try `method=browser`:
https://github.com/ORelio/Minecraft-Console-Client/blob/f16e9e87dd82381514d5ea11300d88b4d47dfd25/MinecraftClient/Resources/config/MinecraftClient.ini#L13
This will allow you to authenticate using your web browser and the usual login form for microsoft accounts. When done and you get an empty page, copy the URL (address of the page) back into MCC.

**Comment by LostAndDead** [comment]
Yea that works bit its finicky and odd with re-logging, it works for now but would still be nice if it was fixed.

**Comment by minecraftchest1** [comment]
There isn't much that the developers can do due to the way that Microsoft account login works. It is possible to improve the user experience a bit, but it would still require a web browser.

**Comment by ReinforceZwei** [comment]
Maybe your account has MFA enabled. MCC cannot handle such case. Please use `browser` for signing-in.

**Comment by LostAndDead** [comment]
It doesn't have MFA, and yes browser does work but once again that's not the problem or really relevant at all, the login method works fine in Windows with the MCC method without anything other than putting in the username and password, the issue arises when its on an Ubuntu system over CLI. So what I'm trying to say is that the request sent to login on Ubuntu as shown in my error messages is that JavaScript isn't enabled, whereas it is enabled in Windows. Nothing to do with the browser login or 2fa, its just the OS and request.

**Comment by ReinforceZwei** [comment]
Are you using VPS? If so, maybe the IP address of your VPS was blacklisted by Microsoft.

**Comment by LostAndDead** [comment]
Pretty sure it isnt as there would be a different error message and verbose content if it was.

**Comment by minecraftchest1** [comment]
Can you share a screenshot of the error you get when signing in with the browser (please share the whole window).

**Comment by LostAndDead** [comment]
> Can you share a screenshot of the error you get when signing in with the browser (please share the whole window).

Have you read any of my messages? This has NOTHING to do with the browser method. That works fine but its not relevant at all to this conversation, the problem is with the request sent when using the MCC method on Ubuntu not enabling JavaScript.

**Comment by Bobu5** [comment]
im sorry if this is kinda Out of topic but LostandDead is there any chance that u got the same error message? (note:i put email on `login=` and password on `password=` for the sake of privacy) , got XLB error in my case
![Screenshot_20210927-002746_VNC Viewer](https://user-images.githubusercontent.com/87025837/134817850-1c7a899a-ef9c-41a4-9ff1-663fd0470a73.jpg)
i guess what ReinforceZwei said was correct, connecting through my ISP without any vpn would gave me the earlier issue since theres a routing problem with my ISP (indihome atm), but for some reason microsoft just doenst block a vpn like cloudflare's warp, its been working fine for me to log me into mc and then i can just disconnect from it later, just a little suggestion that u might try until the issue finallygot fixed g

**Comment by LostAndDead** [comment]
This is not the same error as me. This is all mine says
![image](https://user-images.githubusercontent.com/39418539/134821973-03bc2595-4680-4bb2-af60-69be7ff5dd25.png)
Enabling verbose mode gives me the error i shared above about JavaScript not being enabled

**Comment by minecraftchest1** [comment]
> > Can you share a screenshot of the error you get when signing in with the browser (please share the whole window).
> 
> Have you read any of my messages? This has NOTHING to do with the browser method. That works fine but its not relevant at all to this conversation, the problem is with the request sent when using the MCC method on Ubuntu not enabling JavaScript.

Never assume you know what is not helpful. If you have a problem, we need to know as much as we can.

**Comment by LostAndDead** [comment]
But sharing a screen shot of the browser method wont show anything it all works as expected? Why would i show something completely unrelated to the problem that works? Its the MCC method that is broken, not the browser method. How many times do i have to say this. I have given all the info about it, its just a JavaScript error with the MCC sign in on Ubuntu/Linux

**Comment by minecraftchest1** [comment]
Let me clarify. On windows you can sign in using the browser. In ubuntu, when you sign in with the browser, you get an error. Is this correct, or did i misunderstand something?

**Comment by minecraftchest1** [comment]
I reread the thread. Please tell us. How do you sign in using the cli on ubuntu? Please post the error you get.

**Comment by LostAndDead** [comment]
The error i get is in my initial post... Its a JavaScript not enabled error

**Comment by ReinforceZwei** [comment]
> The error i get is in my initial post... Its a JavaScript not enabled error

The message you saw is not an error message, but a truncated HTML body returned from Microsoft. HTTP code 200 mean sign-in was not successful and requires an additional action. 

To ensure your VPS IP address is not blacklisted by Microsoft, you may sign-in with browser on your VPS, or setup a temporary HTTP proxy and connect through it with your machine.
