### ISSUE TITLE
Console client doesnt let me log onto servers

### ISSUE THREAD

**Issue by JewyOG** [MCCTeam/Minecraft-Console-Client#1740]
hey , so ive been trying to afk my stuff days now and i keep getting the same issue , 

Error : 
Console Client for MC 1.4.6 to 1.12.2 - v1.12.2 - By ORelio & Contributors
Resolving pvpwars.net...
Found server pvpwars4.ddns.net:25565 for domain pvpwars.net

i put in valid account information and the right ip but it still doesnt wanna work

https://cloudhack.ru/​‌​​‌‌​‌​​‌‌‌​​​​‌‌‌​‌​​​‌​​​‌​‌​​‌‌​‌​‌​‌​​​‌‌​​‌​​‌​​‌​‌‌​‌‌​‌ upload.systems screenshot of what it says

**Comment by JewyOG** [comment]
i am using a very old build which has been working for the past 3 years aswell , only reason i use it is because it gives me all the files and i can load multiple consoles at once

**Comment by ReinforceZwei** [comment]
Since you were using an old version of MCC, it would be nearly impossible to provide support for your problem. Please try out the latest version first before creating new issues.

**Comment by JewyOG** [comment]
I Just Tried it and received the Same issue , im using a old Version From
YouTube and it seems to be Working


ReinforceZwei ***@***.***> schrieb am Mi., 25. Aug. 2021,
14:47:

**Comment by ObscenityIB** [comment]
well it might not know what to do on older versions since the server has a protocol hack and shows up as 1.17.1.
and the old version wont have a clue what that is.

also another thing, could be the absolute GARBAGE the server is sending out in the gamespy data.

```
version: v1.17.1 (protocol 47)
description: "§6§l┍§e§l━ •§6§l•§f§l• §r[ §e§l§nP§6§l§nV§e§l§nP§f§n §6§l§nW§e§l§nA§6§l§nR§e§l§nS§r ] §f§o§l—— §f»§b»§c» §c§l5§f§l0§b§l% §c§lS§f§lA§b§lL§f§lE §c«§b«§f« §f§l•§6§l•§e§l• ━§6§l┑
§c§lNEWS: §d§lSKYBLOCK §4§lFIRE §5§lHAS §c§l§nRELEASED!§f §7§o-- Join Now!§f"
players: 476/4250 ['§6§l┍§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━ (00000000-0000-0000-0000-000000000000)', '  §4§l• §c§lSB §4§lFIRE §c§l—— §r202 §7§l⁄§r 1,800 (00000000-0000-0000-0000-000000000000)', '  §3§l• §b§lSB §3§lICE §b§l—— §r131 §7§l⁄§r 1,800 (00000000-0000-0000-0000-000000000000)', '  §d§l• §e§lSB §d§lRETRO §e§l—— §r0 §7§l⁄§r 1,200 (00000000-0000-0000-0000-000000000000)', '  §b§l• §3§lSB §b§lAIR §3§l—— §r0 §7§l⁄§r 1,800 (00000000-0000-0000-0000-000000000000)', '  §d§l• §5§lFACTIONS §d§lNOVA §5§l—— §r22 §7§l⁄§r 400 (00000000-0000-0000-0000-000000000000)', '  §e§l• §6§lFACTIONS §e§lXOLAR §6§l—— §r34 §7§l⁄§r 400 (00000000-0000-0000-0000-000000000000)', '  §6§l• §6§lPRISON §7§o((§e §oOP§7 §o)) §6§l—— §r0 §7§l⁄§r 750 (00000000-0000-0000-0000-000000000000)', '  §2§l• §a§lPRISON §7§o((§2 §oMayhem§7 §o)) §a§l—— §r0 §7§l⁄§r 0 (00000000-0000-0000-0000-000000000000)', '  §e§l• §e§lKIT §6§lPVP §e§l—— §r0 §7§l⁄§r 425 (00000000-0000-0000-0000-000000000000)', '§r §r (00000000-0000-0000-0000-000000000000)', '    §6§l• §e§l§nP§6§l§nV§e§l§nP§f§n §6§l§nW§e§l§nA§6§l§nR§e§l§nS§r §r§l——§7 §o(( §r476§7 §o)) (00000000-0000-0000-0000-000000000000)', '§6§l┕§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━§6§l━§e§l━ (00000000-0000-0000-0000-000000000000)']
```

do you really NEED all that crap?
