### ISSUE TITLE
[BUG] Getting kicked every time I reconnect

### ISSUE THREAD

**Issue by ninto1** [MCCTeam/Minecraft-Console-Client#1747]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.12.2

### Console Client Version

Latest

### Expected Behavior

reconnect and work fine

### Actual Behavior

Reconnect, invalid session data, getting new data from microsoft, joining and then getting disconnected again instantly
It stays normal for a while, when I restart the client

### Steps to Reproduce the bug

1. join a server
2. wait for it to happen (kinda random)
3. see that is doesnt work as it should

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

timanarchy.org

**Comment by milutinke** [comment]
Closing due to lack of information and to being stale.
Use the latest release, as there were a lot of changes since the issue was opened.
If you still have an issue, open a new one.
