### ISSUE TITLE
[BUG] Session Cache does nothing for MSA accounts

### ISSUE THREAD

**Issue by TNTUP** [MCCTeam/Minecraft-Console-Client#1756]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17.1

### Console Client Version

Latest

### Expected Behavior

Session Cache should reuse the auth token instead of re-contacting Microsoft for getting a new auth token

### Actual Behavior

Everytime I quit or typing the command /reco, it always says "Cached session is invalid or expired"

### Steps to Reproduce the bug

1. Set-up your MinecraftClient.ini to microsoft, enable session caching in disk mode.
2. Load up to 3-5 accounts (MSA or Mojang)
3. Quit one of your alts and relog, should say it is invalid

### Anythings that could help diagnosing the bug

```txt
Too much debug log spam and it'll take too long to clear up session tokens or anything :/

I run all MCC instances within the same MinecraftClient.ini file and the SessionCache.ini, I suspect when I load another one the file loaded from previous MCC instances still have the older version of the file which isn't up to date, causing invalid sessions. I'm using "disk" option for caching.

I don't want to make every ini's for each MSA/Microsoft accounts as I own a lot so its not an option for me. I'd suggest creating a folder "sessionCache" containing all accounts ini's session cache tokens so it won't overlap others

My english sucks so bad if there'S any misunderstanding I can re-explain it
```

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
Which sign-in method (`mcc` or `browser`) you were using? For `browser`, if you didn't input your email address before MCC ask you to open the sign-in link, session cache will not work.

**Comment by TNTUP** [comment]
I'm using the `mcc` method
