### ISSUE TITLE
Feature: block reporting

### ISSUE THREAD

**Issue by j-romchain** [MCCTeam/Minecraft-Console-Client#1762]
Could you add a command to tell the block at a given coordinate or blocks around a given coordinate?

**Comment by ORelio** [comment]
Good idea. Labelling your issue as a feature request 👍

**Comment by xXjojaXx** [comment]
I think you can do it with your own chatbot by registering an own internal command and using the following methods to get the Block: GetWorld.GetBlock(new Location(x, y, z));

**Comment by milutinke** [comment]
Adding on my todo list.

**Comment by j-romchain** [comment]
Thank you!
