### ISSUE TITLE
Confusion about autorespond 

### ISSUE THREAD

**Issue by BigBrainDisease** [MCCTeam/Minecraft-Console-Client#1763]
I'm trying to make a specialized bot for my friends and I on hypixel that effectively accepts any party requests; but the way that hypixel sends certain messages is weird, and has ranks attached to usernames and I'm not sure how to get autorespond to respond correctly. sorry if this is annoying, but I wasn't sure where else to go for help.

example of a hypixel message
`-----------------------------
[MVP+] BigBrainDisease has invited you to join their party!
You have 60 seconds to accept. Click here to join!
-----------------------------`
i want the bot to detect specifically the `bigbraindisease` part of the text and add it to the end of `/party accept` I also would like for it to be able to detect usernames other than specifically `bigbraindisease` as that is only my username. I have tried using
`$u has invited you` (edit: i also would like to ignore the mvp bit of it as that is just a rank) as a match, but that doesn't work either. if it was only for a select few friends, then I would just add their usernames as specified triggers, but I want this to be available to everyone who knows about it without having to add their usernames every time. sorry if i'm being stupid and missed something critical, but i tried my best to figure it out on my own

**Comment by toni1506mc** [comment]
Do you know how to use Regex?

Here is a Example for a Regex
`^----------------------------- (?:\[MVP\+\]) ([a-zA-Z0-9_]+) has invited you to join their party! You have (?:[0-9]+) seconds to accept\. Click here to join! -----------------------------$`

**Comment by milutinke** [comment]
Read the [documentation on the Auto Respond](https://mccteam.github.io/guide/chat-bots.html#auto-respond) and use the latest release of the client.
To learn regex, take a look at the following tutorials from this section: https://mccteam.github.io/guide/configuration.html#chat-format-section
