### ISSUE TITLE
[BUG] silent disconnect

### ISSUE THREAD

**Issue by jcodyparker** [MCCTeam/Minecraft-Console-Client#1765]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.4

### Console Client Version

1.17.1

### Expected Behavior

Alts stay logged in

### Actual Behavior

When trying to use console client on my laptop, some accounts log in for a few seconds or up to a minute. Then they disconnect with nothing shown on screen or saved in the logs.

If I use it on my PC, they all work with 0 issues. This only happens with some of my accounts (real Minecraft accounts I own, not NFA alts). Some of my accounts stay logged in perfectly fine for days / weeks and never disconnect.

A few months ago I had no issues with this. Updated to the latest build and it still didn't fix the problem.

### Steps to Reproduce the bug

1. Log in with only a select few accounts

Thats it. Nothing different set up than the other accounts, and they work perfectly fine on my PC, but not my laptop.

I did not have this issue a few months ago.

### Anythings that could help diagnosing the bug

```txt
Nothing shows in the log file, it just stops outputting anything.
```

### Device

Laptop

### Operating System

Windows

**Comment by ORelio** [comment]
This bug occurs most on Linux and we never found the root cause of this.
This is hard to diagnose because it's random and provides o hint.
Related: #802 #830 #1303 #1656

**Comment by jcodyparker** [comment]
This is on windows 10 not Linux

**Comment by jcodyparker** [comment]
So now most of them are working on another PC my friend is letting me borrow. One or two of the accounts randomly DC and in the log file it says :

Disconnected by Server :
ReadTimeoutException : null


And it wont relog until I go back the computer and click it, or try to login with another console client instance on my main PC.

**Comment by ORelio** [comment]
I understand that your issue is on Windows but ultimately I think it's the same bug 😕

Regarding disconnection with ` ReadTimeoutException : null`, you can enable AutoRelog to automatically reconnect when this happens. See [Using the AutoRelog bot](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.md#using-the-autorelog-bot).

**Comment by jcodyparker** [comment]
I did that, seems to work but it has to auto relog every minute basically. And now 2 completely other accounts wont login at all 

Login failed :
Failed to check session

What does this mean?

**Comment by jcodyparker** [comment]
I just dont understand why this works perfectly fine on my main gaming PC connected to ethernet. But not my laptop or other gaming PC connected to wifi.

**Comment by ORelio** [comment]
Try `debugmessages=true` in config, you should get the exact details of the session check request as well as the server response.

**Comment by hwgilbert16** [comment]
This same issue is occurring with me. Running Ubuntu 20.04 LTS in a VM on my ProxMox server. I connect for a 10-15 seconds to my 1.17.1 server, and then I get randomly disconnected. No error messages with debug enabled or dick messages.

Never had this issue with 1.16.5.

**Comment by jcodyparker** [comment]
Like I said in the post, debug messages is enabled and it still shows nothing. Silent disconnects until I close and reopen MCC. This only happens on certain accounts, ONLY on wifi. Works fine on ethernet. We have good wifi here so that shouldn't br an issue and it worked fine a few months ago on wifi. Ended up getting an ethernet switch so I can have another port in my room to use for the second PC and now I don't disconnect. Just wish it would work on wifi.

**Comment by milutinke** [comment]
As the client has changed a lot since the issue was opened, I will close this issue as stale.
Try the latest version of the client, it should not have this issue, if you have any issues on the latest version, use Auto Relog chat bot.
