### ISSUE TITLE
Automatically typing MCC commands

### ISSUE THREAD

**Issue by Heringen** [MCCTeam/Minecraft-Console-Client#1768]
Precisely, is it possible for Anti-Afk or smth else to type /move north on it's own every x amount of time?

**Comment by kelvin-lee233** [comment]
[User mannual: How to write a script ](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-write-a-script-file)

**Comment by Heringen** [comment]
> [User mannual: How to write a script ](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#how-to-write-a-script-file)

Not rly into mcc coding so correct me if im wrong.
I make the script by just making .txt file with /move north as only text?

**Comment by Heringen** [comment]
How do i automate it tho?

**Comment by kelvin-lee233** [comment]
you can run the script by  command /script <filename>. [example script file](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)

**Comment by Heringen** [comment]
Aight i figured i was using [ScriptScheduler] wrongly, i figured it now but have a question.
"Simply enable the ScriptScheduler bot and specify a tasks file in your INI file"
What would be INI file for tasks? How do i setup that?

**Comment by ORelio** [comment]
In config you set which file contains your tasks:

https://github.com/ORelio/Minecraft-Console-Client/blob/981dd51a9b5821eea6d2564050b82daee6ae859e/MinecraftClient/Resources/config/MinecraftClient.ini#L154-L158

Then you put your tasks in the file you set in config, e.g. [tasks.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini).

**Comment by Heringen** [comment]
> In config you set which file contains your tasks:
> 
> https://github.com/ORelio/Minecraft-Console-Client/blob/981dd51a9b5821eea6d2564050b82daee6ae859e/MinecraftClient/Resources/config/MinecraftClient.ini#L154-L158
> 
> Then you put your tasks in the file you set in config, e.g. [tasks.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini).

This cleared all up, working nicely now. Thanks for help!
