### ISSUE TITLE
[BUG] Client hangs after 1-2 seconds on Linux

### ISSUE THREAD

**Issue by marvic2409** [MCCTeam/Minecraft-Console-Client#1776]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.15.2

### Console Client Version

1.17.1

### Expected Behavior

For the client to receive messages and keep the connection alive. 

### Actual Behavior

After logging in, the client receives the join message, and the Essentials Welcome message. After this, the client is unable to receive messages, send them, or interact in any way. The client hangs, and the connection is lost but the client doesn't show this. The client freezes up.

### Steps to Reproduce the bug

Run the client on linux

### Anythings that could help diagnosing the bug

```txt
https://pastebin.com/jpmFeNtX
Log files
```

### Device

Desktop

### Operating System

Linux

**Comment by rozatoo** [comment]
I seem to be having this issue too.

![image](https://user-images.githubusercontent.com/69800109/137303392-337bd6d0-14f7-4f17-8cb8-855d21bd4465.png)
and after 2 attempts:
![image](https://user-images.githubusercontent.com/69800109/137303883-1673957b-91d1-43e8-861b-7ae6f5129b09.png)

Extra info:
I have been using MCC on this server for 2 weeks, its been working fine until this issue suddenly started happening.
I have tried moving in game, and then logging on again to see if it makes a difference
I have tried joining a different server and could not recreate the issue

**Comment by Bobu5** [comment]
strange, i myself use mcc on my linux laptop, no issue about not getting any message or getting kicked after a few second of joining the server, heres the screenshot of mcc running: 
(mcc client 1)
![image](https://user-images.githubusercontent.com/87025837/141686976-9707327e-2f07-4341-91f4-23ab794bcd22.png)

(mcc client 2)
![image](https://user-images.githubusercontent.com/87025837/141687029-3aa729dd-4c1c-4c1c-9d57-d96251b71802.png)

running 1.16.5 on client 1, and 1.17.1 on client 2, both didnt have the issue that u have mentioned, perhaps its a issue on the server side? 

running it inside Ubuntu server 20.04 LTS, heres some neofetch of my laptop
![image](https://user-images.githubusercontent.com/87025837/141687114-2fab5278-0f65-4696-9e09-1b6b61bea370.png)

**Comment by Bobu5** [comment]
> Yeah it seems that the issue only happens when I afk at a XP farm. Anywhere else the connection issue never happens. If I then stay offline for a couple hours and join again it works again. Quite a strange issue.

can confirm, mcc also crash after a few hr for me, i think for my case the source of the crash in my case are from the scriptscheduler, imma put the mono log here when i came back home later

**Comment by rozatoo** [comment]
Do the crashes always happen for you or does it only happen sometimes? @Bobu5

**Comment by Bobu5** [comment]
sorry im late 

> Do the crashes always happen for you or does it only happen sometimes? @Bobu5

yes, it always happen after a few hour, im pretty sure its either because one of my script looping to much or maybe its just because it no likey my old laptop

**Comment by Bobu5** [comment]
> > Yeah it seems that the issue only happens when I afk at a XP farm. Anywhere else the connection issue never happens. If I then stay offline for a couple hours and join again it works again. Quite a strange issue.
> 
> can confirm, mcc also crash after a few hr for me, i think for my case the source of the crash in my case are from the scriptscheduler, imma put the mono log here when i came back home later

oh, yeah mono log, heres my latest crash log, not sure which one tho
https://www.toptal.com/developers/hastebin/awezajeqig.json

**Comment by udu3324** [comment]
This is happening to me too. I am using build #1855 on Mint Linux with mono. It joins the server and just spits out one line from the chat. About 10 seconds later, it loses connections and auto rejoins the server. This then repeats over and over again. Client is running 1.18.1

**Comment by udu3324** [comment]
> This is happening to me too. I am using build #1855 on Mint Linux with mono. It joins the server and just spits out one line from the chat. About 10 seconds later, it loses connections and auto rejoins the server. This then repeats over and over again. Client is running mc v1.18.1

I did some troubleshooting and ran this in terminal `mono MinecraftClient.exe`
Somehow, it fixed it lol

**Comment by rozatoo** [comment]
> > This is happening to me too. I am using build #1855 on Mint Linux with mono. It joins the server and just spits out one line from the chat. About 10 seconds later, it loses connections and auto rejoins the server. This then repeats over and over again. Client is running mc v1.18.1
> 
> I did some troubleshooting and ran this in terminal `mono MinecraftClient.exe` Somehow, it fixed it lol

How were you starting the program before using `mono MinecraftClient.exe`?

**Comment by udu3324** [comment]
> > > This is happening to me too. I am using build #1855 on Mint Linux with mono. It joins the server and just spits out one line from the chat. About 10 seconds later, it loses connections and auto rejoins the server. This then repeats over and over again. Client is running mc v1.18.1
> > 
> > 
> > I did some troubleshooting and ran this in terminal `mono MinecraftClient.exe` Somehow, it fixed it lol
> 
> How were you starting the program before using `mono MinecraftClient.exe`?

I was just double clicking it in the file explorer

**Comment by rozatoo** [comment]
![image](https://user-images.githubusercontent.com/69800109/163101539-34846169-e2e2-4941-8e8f-bdbd85629263.png)
I have figured out why this issue happens for me.  
Basically MCC starts using shit tons of CPU power after several days of continuous uptime or when you AFK at a high entity count area after a couple hours.
This then causes my AWS burst capacity to be destroyed causing AWS to limit my cpu capacity to the point that MCC doesn't work anymore.
In this image you can see another two examples of this happening:
![image](https://user-images.githubusercontent.com/69800109/163102122-ced12adb-f312-4015-8745-bc1af91c4d55.png)

**Comment by milutinke** [comment]
Try using the latest build, since Mono is no longer used and needed, also there have been a lot of performance optimizations and bug fixes, this should not happen on newer builds.
I'll be closing the issue, if you experience some problems, make a new one.
