### ISSUE TITLE
Implement Spectator mode teleport

### ISSUE THREAD

**Issue by xXjojaXx** [MCCTeam/Minecraft-Console-Client#1814]
Is there the possibility of using spectator teleport in mcc. According to the minecraft protocol on wiki there is an extra package for that, which I think MCCs Chatbot Class isn't able to use right now, but pls correct me if I'm wrong. So my question is: Is there any work around for using this package? And pls dont tell me I could do it via InventorHandling in the spectator menu, that will be to slow and inconsistent for my usecase.
Thank you very much
xXjojaXx

**Comment by xXjojaXx** [comment]
Closing as kind of a duplicate, because Pull Request already exists.

**Comment by ORelio** [comment]
Implemented in #1825. Thanks for your contribution!
