### ISSUE TITLE
Feature organization

### ISSUE THREAD

**Issue by xXjojaXx** [MCCTeam/Minecraft-Console-Client#1816]
Right now there are 49 features waiting for contributers to be implemented, so I want to know, if theres an organization system behind about which requests are the most importantto do next and about who is working on which part. I think there isn't, but it would be really nice, because it would make contributing a lot easier.

**Comment by ORelio** [comment]
Not really, unfortunately. Would be nice to determine the popularity of each feature request based on amount of replies and reactions to each one then sort them but I'm not sure GitHub offers an easy way to do this 🤔

**Comment by xXjojaXx** [comment]
Oh ok, I always thought their has to be. Tjen never mind, I think its just like it is.
