### ISSUE TITLE
Hypixel 

### ISSUE THREAD

**Issue by Exilliux** [MCCTeam/Minecraft-Console-Client#1817]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Is there a way to connect to Hypixel?

### Suggest a possible solution

I just want to talk to some friends without having to load up minecraft!

### Minecraft Version

1.8.9-latest

### Device

Laptop

### Operating System

Windows

**Comment by ORelio** [comment]
I did not test that server in particular. What's preventing you to connect to this server?

**Comment by iplayon60hz** [comment]
Yes it is possible. When the console client is open, type in your login and mc.hypixel.net
If you logged in successfully, great, if not a couple of solutions are below that worked for me:
- Try to change your mcversion to 1.12.2
- If that doesn't work also try to change brandinfo to forge.
Once you are on hypixel you can use commands like usual, for example /party [ign] then /chat p to talk in party chat
Or, you can /message [ign] to send a message. Most commands still work
If you are going to use this often i'd reccomend putting your login and the hypixel ip in the general settings, as it just makes it quicker. Hope this helped :)

**Comment by Bobu5** [comment]
just some kind of reminder, be careful with the anticheat, I'm kinda scared that they will ban your account as soon as u joined through mcc, just like the accident where ppl gotbanned after joining with bedrock proxied through geyser since they have different movement handling , which we also seem to face with in mcc
