### ISSUE TITLE
i want to login with only username-token-uuid details. can you help me please?

### ISSUE THREAD

**Issue by wovl** [MCCTeam/Minecraft-Console-Client#1819]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

i want to login with only username-token-uuid details. can you help me please?
i dont want to use e mail and password to login account. i want to login with token-uuid (i mean session loginning) please help me.

### Minecraft Version

1.12.2

### Device

Desktop

### Operating System

Windows

**Comment by ORelio** [comment]
> i want to login with only username-token-uuid details. can you help me please?

In which legitimate use case would you have username, token and uuid but not the email and password?

**Comment by wovl** [comment]
> > i want to login with only username-token-uuid details. can you help me please?
> 
> In which legitimate use case would you have username, token and uuid but not the email and password?

I dont know details, i have got account supplier, he gives me tokens for adbotting. But its really annoying to do with liteloader. I was already using  mcc for adbots but i dont have mail and password rn. Can you please help me about session loginning?

**Comment by ORelio** [comment]
Sorry but MCC is not intended for spamming, hacking, infringing server rules or doing anything illegal, so I cannot help you for setting up ad bots, especially if you run them with accounts you don't own.

**Comment by wovl** [comment]
Is it possible to do? I mean can someone else do it for me? Im ready for pay for this job
