### ISSUE TITLE
Can't log in after migrating account

### ISSUE THREAD

**Issue by jcodyparker** [MCCTeam/Minecraft-Console-Client#1822]
I migrated my account to Microsoft, changed my config file from mojang to microsoft, and now it wont let me log in and gives me this error. It lets me login fine with Lunar or default launcher with the same email and password. So it is not incorrect, and I'm not blacklisted.

![image](https://user-images.githubusercontent.com/90956620/141705707-8e3e3915-aeb4-4baf-8af5-bdd32704d506.png)

**Comment by ReinforceZwei** [comment]
Try to use browser for signing in. Set `method=browser` in the config.

**Comment by jcodyparker** [comment]
I tried that now, when I paste the link into the browser it just shows a blank white page and never loads. It worked for a second but now it's gone. Tried multiple times

**Comment by jcodyparker** [comment]
![image](https://user-images.githubusercontent.com/90956620/141708212-e2655705-0c75-4766-ac5e-becea3fc355c.png)

**Comment by ReinforceZwei** [comment]
You have to copy the link from address bar to MCC when you reached the blank page.

**Comment by jcodyparker** [comment]
Did that, now I'm getting this. I think I used the wrong email in the browser when I clicked it the first time. How do I change it?

![image](https://user-images.githubusercontent.com/90956620/141708751-96cc215c-a1ce-43b1-9748-495d09c44a4b.png)

**Comment by ReinforceZwei** [comment]
Open an incognito window in browser.

**Comment by jcodyparker** [comment]
It worked thank you! Just had to go to the microsoft website and sign out of the wrong account then sign into the right one from there then try again in MCC. Do I have to do this every time I open MCC or just this once? I use a startup script on a separate computer normally so I can start it remotely.

**Comment by jcodyparker** [comment]
So now when I get disconnected and console client auto reconnects, it shows the browser login. So auto relog is useless now. Is there any other way to get this to work without using "browser" as an option? 

Beginning to think I shouldn't have merged yet, this is really annoying.

**Comment by jcodyparker** [comment]
Bump. Need a way to auto-relog when disconnected

**Comment by ReinforceZwei** [comment]
Please be patient. Improved Microsoft sign-in is working in #1827.
