### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by IsaacJuracich** [MCCTeam/Minecraft-Console-Client#1824]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8

### Console Client Version

Latest

### Expected Behavior

For example if the replaybot isn't running, can you run the replaybot with the chat.botload and have it work normally?

### Actual Behavior

s

### Steps to Reproduce the bug

1. 
2. 
3. 
No bug

**Comment by milutinke** [comment]
Since the `/reload` command is now implemented and will be merged, you will be able to do this.
