### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by Samubrine** [MCCTeam/Minecraft-Console-Client#1829]
### Discussed in https://github.com/MCCTeam/Minecraft-Console-Client/discussions/1828

<div type='discussions-op-text'>

<sup>Originally posted by **Samubrine** November 21, 2021</sup>
I used console client back in 2020 and just came back recently with a new PC, and I decided to open it and I realized that it takes roughly ~20 minutes for it to actually join the server.  I have no idea what's causing consoleclient to be very slow and I have not found any solution for this problem yet. Please help</div>

**Comment by ReinforceZwei** [comment]
Please continue discuss at #1828.
