### ISSUE TITLE
Any way to make a random delay on the script scheduler?

### ISSUE THREAD

**Issue by throwaway4206** [MCCTeam/Minecraft-Console-Client#1830]
I searched the readme and tried some stuff myself, but I can't find anyway to make a random delay using the script scheduler. Is this not a feature?

**Comment by ORelio** [comment]
Indeed that's not possible at the moment, but it's a good idea. Could be implemented like AutoRelog with delay expressed as a `min-max` interval. Converting your issue to a enhancement request 👍

**Comment by milutinke** [comment]
I'll be looking into adding this in the following days.
