### ISSUE TITLE
[BUG] No CI check on commit

### ISSUE THREAD

**Issue by ReinforceZwei** [MCCTeam/Minecraft-Console-Client#1834]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

N/A

### Console Client Version

N/A

### Expected Behavior

Each commit should have the green tick if build job was success.
![image](https://user-images.githubusercontent.com/39955851/142992062-e85feff4-a8d3-4b39-a7ce-817a9799a900.png)

### Actual Behavior

After #1809, the build job still being triggered but there is no green tick.
![image](https://user-images.githubusercontent.com/39955851/142991941-7f714129-639a-4e18-a9f4-cf89f554befe.png)

### Steps to Reproduce the bug

N/A

**Comment by ORelio** [comment]
Could not find any setting in both AppVeyor and GitHub that could explain this. The Webhook works because AppVeyor does the build, but for some reason the build status does not go back to GitHub 🤔

**Comment by ORelio** [comment]
OK, maybe I have found. I authorized AppVeyor to access my account (Authorized OAuth App), and it might be using that to access the repository and set the status. I've de-authorized and re-authorized AppVeyor and made sure it had access to the MCCTeam organization in the process. This should hopefully fix the status on commits 🙏

**Comment by ReinforceZwei** [comment]
Latest commit 6918a64 still have the status missing.
![image](https://user-images.githubusercontent.com/39955851/143172385-72d96493-7bbc-482a-aa02-68bddf0a8f1d.png)

**Comment by ORelio** [comment]
That commit was between my two messages so before re-authorizing. Let's see on the next commit if it's fixed or not!

**Comment by ReinforceZwei** [comment]
Unfortunately it is still not appearing.
![image](https://user-images.githubusercontent.com/39955851/144428150-5f7249f7-606d-4084-8c8a-cd48b34cbdfb.png)

**Comment by ORelio** [comment]
Well, I'm not sure what to do then 😕
Well, at least builds are still taking place, and build status is visible on README.
No CI checks were done apart from checking if the project builds.

**Comment by ReinforceZwei** [comment]
Okay, just let it go :P
