### ISSUE TITLE
[Idea] Any way to update the client for 1.18 our selves?

### ISSUE THREAD

**Issue by OmarRahmanK** [MCCTeam/Minecraft-Console-Client#1835]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Since 1.18 came out (literally today), the client has stopped working. Because of this, I was wondering if there was a way for us (users of your software) to update it ourselves and make it compatible with 1.18.

### Minecraft Version

1.18

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
You could update the client to 1.18 if you have the protocol document and know how to program in C#. Currently [wiki.vg protocol](https://wiki.vg/Protocol) document still on 1.17.1.

**Comment by Pokechu22** [comment]
The [pre-release protocol page](https://wiki.vg/Pre-release_protocol) covers 1.18-rc1 (and I don't think there have been further changes since the release candidates), though the pre-release page is generally less complete/tested.

**Comment by OmarRahmanK** [comment]
Okay, thanks, will do.

**Comment by ReinforceZwei** [comment]
Implemented in #1836
