### ISSUE TITLE
[BUG]  Process is terminated due to StackOverflowException.

### ISSUE THREAD

**Issue by gman12333** [MCCTeam/Minecraft-Console-Client#1839]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

auto

### Console Client Version

latest (downloaded at 11PM  December 5, 2021)

### Expected Behavior

i expect it to promt me to login to the microsoft account

### Actual Behavior

it opens for 1 sec and then it gives me the error "Process is terminated due to StackOverflowException." then it will close

### Steps to Reproduce the bug

1. Download latest version of console client
2. Open console client
3. Boom!!!!

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/48095274/144764396-7b73575e-c971-4960-9fe5-b85745f672f5.png)

### Anythings that could help diagnosing the bug

```txt
NONE
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

GlitchMC.ga

**Comment by milutinke** [comment]
Try running the latest build which uses .NET Core 6.
There were a lot of changes and bug fixes, this should not happen in newer builds.
If you have any issues with newer build, open a new issue.
