### ISSUE TITLE
Minecraft 1.18: Add support for inventories

### ISSUE THREAD

**Issue by kegri** [MCCTeam/Minecraft-Console-Client#1840]
Hello there, I'm trying to use Minecraft Console Client on Repl.it with my alt minecraft account. I want to make the bot eat food when it's hungry, I turned on the Inventory Handling and AutoEat with threshold 6, I restarted the client and console says "[ERROR] Inventories are currently not handled for that MC version.", using version 1.18.

**Comment by ReinforceZwei** [comment]
Inventory handling doesn't support Minecraft version 1.18.

**Comment by BruceChenQAQ** [comment]
Inventory processing is implemented in https://github.com/MCCTeam/Minecraft-Console-Client/pull/1943
