### ISSUE TITLE
QUESTION: Is the new vurnability of minecraft fixed for console client?

### ISSUE THREAD

**Issue by UniqueNIHAL** [MCCTeam/Minecraft-Console-Client#1844]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17.2

### Console Client Version

The latest one I just re-downloaded it to check

### Expected Behavior

I couldn't find a place to ask this question sorry had to choose bug report :p

### Actual Behavior

.

### Steps to Reproduce the bug

1. 
2. 
3. 

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/87065344/145507927-e95e79d0-0f23-4e9c-b61c-31b696b87b0d.png)

### Anythings that could help diagnosing the bug

```txt
Is this bug as above mentioned in screenshot fixed and is console client safe?
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

play.craftadia.com

**Comment by Pokechu22** [comment]
The issue is inapplicable to MCC, as MCC does not use log4j (or Java).

**Comment by UniqueNIHAL** [comment]
Ah kk thanks 😊
