### ISSUE TITLE
Bungeecord-Server Switch Detection

### ISSUE THREAD

**Issue by xXjojaXx** [MCCTeam/Minecraft-Console-Client#1847]
I know here may not be the best place to ask, but I didn't find a better one, so here is my question: Can i use MCC to detect, when my bot gots moved from one server on a bungeecord network to another? Or first of all: what packet does the server send to make the player go to there?
Thanks for your help
xXjojaXx

**Comment by ReinforceZwei** [comment]
> Or first of all: what packet does the server send to make the player go to there?

I guess is the [Respawn](https://wiki.vg/Protocol#Respawn) packet. 

> To change the player's dimension (overworld/nether/end), send them a respawn packet with the appropriate dimension, followed by prechunks/chunks for the new dimension, and finally a position and look packet.

**Comment by xXjojaXx** [comment]
Hmm, ok, it's gonna be quite hard to spot a difference between a normal respawn packet (after being death etc.) and one moving the bot to another server

**Comment by ReinforceZwei** [comment]
I think you have to handle the `Dimension` NBT field or `World Name` in the respawn packet which currently MCC just ignored them.

**Comment by xXjojaXx** [comment]
Ok, that does mean it (the additional attributes for OnRespawn) has to be implemented into MCC codewise by me or somebody else, right? Would you mark the question as 'waiting for contributor' while it's pending? Would really appreciate it.

**Comment by BruceChenQAQ** [comment]
Try using the latest release, MCC has added support for dimension data.
