### ISSUE TITLE
Ubuntu "Cannot open assembly 'MinecraftClient.exe': File does not contain a valid CIL image"

### ISSUE THREAD

**Issue by FinnPaes** [MCCTeam/Minecraft-Console-Client#1849]
Hey, I have an Ubuntu 18.04 server, trying to install Console Client on there. I downloaded the newest version from here: https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts  and ran the command **mono MinecraftClient.exe**

This gives me the following error: "Cannot open assembly 'MinecraftClient.exe': File does not contain a valid CIL image"
What should I do to fix this?

![image](https://user-images.githubusercontent.com/71390226/145993028-5b3757e7-910d-4be4-8628-cc5bf79729e9.png)

**Comment by ReinforceZwei** [comment]
What is your mono version? (run `mono --version` to show mono version)

**Comment by FinnPaes** [comment]
![image](https://user-images.githubusercontent.com/71390226/145994908-ba1588ba-48dd-4206-9965-b74874780685.png)

**Comment by ReinforceZwei** [comment]
Not sure what is the problem. Maybe your download is corrupted?

**Comment by FinnPaes** [comment]
I used wget -o MinecraftClient.exe ARTIFACTSLINK
That gave me the issue above ^^

Once downloading it to my main PC, then uploading it with FTP it worked... 
Thank you! Seems like wget breaks things?

**Comment by ReinforceZwei** [comment]
I think you don't need the `-o` there. Just `wget <The download link>` is enough.
