### ISSUE TITLE
SessionToken Error

### ISSUE THREAD

**Issue by xXjojaXx** [MCCTeam/Minecraft-Console-Client#1853]
Getting the following Error when starting (might have to do something with the new update) :
`Unhandled Exception:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at MinecraftClient.Protocol.Session.SessionToken.FromString (System.String tokenString)
  at MinecraftClient.Protocol.Session.SessionCache.LoadFromDisk ()
  at MinecraftClient.Protocol.Session.SessionCache.InitializeDiskCache ()
  at MinecraftClient.Program.Main (System.String[] args)`

Would be cool if you could have a look at it @ReinforceZwei and tell me what I can change about it. Thank you very much!
(PS: Forgot to mention im still using a normal mojang and not an microsoft account, which is likely to cause the problem. I know you don't really support it anymore, but I hope/think making it unable to use directly isn't intentionally ; )).

**Comment by xXjojaXx** [comment]
I assume the error gets thrown out because the token String has the exact length of 4 and you changed the method to use the fifth argument('session.RefreshToken = fields[4];') without changing the if statement from fields.Length < 4 to field.Length < 5 in the SessionToken.FromString(string tokenString). But that doesn't makes me realize what I should change either.

**Comment by ReinforceZwei** [comment]
Could you try deleting your old session cache file?

**Comment by ReinforceZwei** [comment]
A fix was done in https://github.com/MCCTeam/Minecraft-Console-Client/commit/04d83bf277f1500fbc2660c0df5991735beee726. Please try again.
