### ISSUE TITLE
[Bug/Crash] Mono crash when loading .ini (SIGSEGV while executing native code)

### ISSUE THREAD

**Issue by HaroldTaylor** [MCCTeam/Minecraft-Console-Client#1856]
### Prerequisites

- [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

Auto

### Console Client Version

Lastest (19/12/2021)

### Expected Behavior

It should load ini setting and connect to a server

### Actual Behavior

It crashes as soon as it tries to load in the ini setting

### Steps to Reproduce the bug

1. Download MinecraftClient.exe.
2. Install Mono and libmono.
3. Start MinecraftClient.exe.
4. Close and edit ini.
5. Start MinecraftClient.exe again.
6. Crash.

### Attach screenshot here (If applicable)

This is the crash report from Mono: [mono_crash.125dfbeaf.0.txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/7740207/mono_crash.125dfbeaf.0.txt)
Copy and paste of what it says after running, mono MinecraftClient.exe: [Termial_output.txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/7740208/Termial_output.txt)

### Anythings that could help diagnosing the bug

```txt
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-3.2 Mon Jul 12 07:04:24 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
```

### Device

Raspberry Pi

### Operating System

Linux

**Comment by milutinke** [comment]
Since Mono is no longer used, I'll be closing the issue.
Use the latest build which requires .NET Core 6.
If you have any issues with the latest build, open a new issue.
