### ISSUE TITLE
Relative coordinates in a text script

### ISSUE THREAD

**Issue by TyraVex** [MCCTeam/Minecraft-Console-Client#1857]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

2858e0c

### Describe your problem

Relative coordinates in a .txt script like ```useblock ~ ~-1 ~```

### Suggest a possible solution

Add the possibility to use relative coordinates in a text script

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

**Comment by xXjojaXx** [comment]
Can be implemented together with/from the same contribuor as #1815, because it's quite similar. Might have a look at it.

**Comment by TyraVex** [comment]
Thanks! 
I'm working with multiple accounts and right now i need one script for each one of them to specify coordinates for them to work with. This feature would be very cool :)

**Comment by ReinforceZwei** [comment]
Duplicate of #1815. Please continue discuss in there.

**Comment by TyraVex** [comment]
But the other issue is considered fixed using some C# workarounds
That's why I opened this issue...

**Comment by ORelio** [comment]
Although a workaround is presented, the other issue is still waiting to be implemented :)

**Comment by TyraVex** [comment]
🤞
