### ISSUE TITLE
[Idea] Execute a new line in text script only if the previous one was successfully executed

### ISSUE THREAD

**Issue by TyraVex** [MCCTeam/Minecraft-Console-Client#1858]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest from yesterday

### Describe your problem

On a server the logging time can range from a few seconds to around 30
I need a way to execute commands if only the player is successfully connected
And it's the same for every command that need a random time to be executed.
Without a C# script, how do you handle these random delays ? 

### Suggest a possible solution

[title]

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

**Comment by ORelio** [comment]
Although this is a good idea, internal commands do not have a status code so implementing this will require a lot of work. Also some commands like server join are asynchronous so no immediate status code will be available. The best way to deal with errors joining a server would be using a C# script.

**Comment by TyraVex** [comment]
When you are connecting to a server, you can't type in the console
This means adding a piece of code checking every second if text can be inputted into the console would be sufficient to know if the account is connected or not
I don't think it is more complicated than that

**Comment by Daenges** [comment]
Your suggestion is problematic since the script would try to send a message, but since there is no conditioning (or catching) in the MCC script language, it would just fail and end if the message can not be sent.

The MCC commands are rather for simple tasks, than for the more complex stuff. Due to the fact, that C# is an advanced programming language (in comparison to the MCC scripting) it would be easier to write a C# script with the chatbot API, than trying to do a workaround with the script commands.

**Comment by ORelio** [comment]
Please note that text script execution is paused while (re)connecting to the server so you can use `connect` followed by `send`.

**Comment by TyraVex** [comment]
Well I learnt the basics of c#...
Is there any value returning if the player is connected?

**Comment by Daenges** [comment]
@TyraVex Just use [this function](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L111). It is called when you are able to send messages.

**Comment by Daenges** [comment]
@TyraVex If you have any questions while implementing your idea we are happy to help out. ;D

**Comment by TyraVex** [comment]
> 

I love you thank you :)

**Comment by ORelio** [comment]
There's also an `OnDisconnect()` event to detect when not connected to the server anymore.
https://github.com/MCCTeam/Minecraft-Console-Client/blob/76a10c0cd87818fb7dd6362834c2e14f4f843cb9/MinecraftClient/ChatBot.cs#L149-L155

**Comment by TyraVex** [comment]
Good to know thanks :)

**Comment by TyraVex** [comment]
Hi,
I'm still a noob since I started learning c# a week ago so excuse me if some of these questions may look like silly

Is there a way to detect if a chest isn't opened after a few seconds after useblocking it?
I tried to play with OnInventoryOpen(ID); but this only allow me when the container is opened, and I can't use it in a if statement since it's a method...
Also, is it possible to do OnInventoryOpen("chest") instead of giving an ID?

Have a good day :)

**Comment by ORelio** [comment]
`OnInventoryOpen` is an event, you override the method in your ChatBot and MCC itself will call it when the event happens.
Example for chat messages: [sample-script-witch-chatbot.cs](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) in which MCC calls the methods when a message is received.
