### ISSUE TITLE
[BUG] chat.disabled.options

### ISSUE THREAD

**Issue by aion1998** [MCCTeam/Minecraft-Console-Client#1864]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.1

### Console Client Version

最新

### Expected Behavior

找到配置项

### Actual Behavior

![image](https://user-images.githubusercontent.com/19725014/147083757-61337b4d-7e9d-4fe1-83f1-a71f0048bad6.png)
如图，发生了这个提示，但是翻了十多遍配置文件完全找不到在哪里配置

### Steps to Reproduce the bug

1. debug打包
2. 找到打包的debug文件夹然后运行exe，退出，修改ini文件的服务器地址这些基础信息
3. 再次启动exe，随便打句话就会提示图片上所显示的

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/19725014/147083757-61337b4d-7e9d-4fe1-83f1-a71f0048bad6.png)

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

mc13.starmc.cn:33085

**Comment by ReinforceZwei** [comment]
Similar to #1813. Probably your character is dead and server is preventing you from chatting. See https://github.com/MCCTeam/Minecraft-Console-Client/issues/1813#issuecomment-961817359

**Comment by aion1998** [comment]
![image](https://user-images.githubusercontent.com/19725014/147094837-6ba7446c-9bce-460c-9d8c-f36b398febfd.png)

这是我从公司下班后，回到家里再次尝试，整个流程

**Comment by aion1998** [comment]
啊，搞会了，其实就只是死了，如果配置文件里配置了自动复活为true，就不会有这个问题
这个服务器比较坑爹，进去的出生点会卡死人，感谢大佬们的回复
