### ISSUE TITLE
[BUG] Raspberry pi4 Lose Connection (Timed out)

### ISSUE THREAD

**Issue by NoxRare** [MCCTeam/Minecraft-Console-Client#1867]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.1

### Console Client Version

Latest

### Expected Behavior

Login and stay connected to server.

### Actual Behavior

I lose connection everytime I try to connect to my personal server.. I can connect fine to hypixel and some other server but as soon as I connect to my own (PaperSpigot) server it does not seem to want to stay connected, it worked fine back in 1.18 but as soon as I updated either the MCC or the server it stopped working..

I've done some testing and putting the render distance on the server to 4 seems to make it work, problem with this is that I would be ruining the render distance for others on the server.

I hope you guys know what paperspigot is, otherwise I can explain I guess lol.

### Steps to Reproduce the bug

1. Have Raspberry pi 4B
2. Try to join a PaperSpigot Server..
 

### Device

Raspberry Pi

### Operating System

Linux

**Comment by milutinke** [comment]
A lot of things have changed since this issue was open, download the latest build for ARM processors and try it now, I think that this issue won't be a thing.
I'll be closing this issue, if you still have a problem, re-open it.
PS: Mono is no longer used, use .NET Core 6, here is a manual for installation: https://mccteam.github.io/
