### ISSUE TITLE
i have a error

### ISSUE THREAD

**Issue by shadowstar1109** [MCCTeam/Minecraft-Console-Client#1872]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

ultimate

### Expected Behavior

.

### Actual Behavior

I have a error in a command /move i change the versions : 1.16.5, 1.8 and more but the error is the same 
Failed to compute path to X:201 Y:10 Z:70 (for example) can i help me i try all 

### Steps to Reproduce the bug

1. 
2. 
3. 

### Device

Laptop

### Operating System

Windows

**Comment by Daenges** [comment]
Well there could be several reasons for this error to appear. 

1. The most likely one would be that you entered a position that is blocked by blocks or just generally unreachable. Remember the bot is currently unable to mine/set blocks. It only calculates a path, that is not blocked by anything and walks it off.

2. Your goal is too far away. The path finding algorithm has a timeout of 5 seconds, if nothing is found you get an error message. This includes coordinates that are too far away, for instance if your goal is out of render distance.

**Comment by shadowstar1109** [comment]
It is certainly unattainable, I think because I want him to throw himself into a void and I don't know why he doesn't want to

**Comment by Daenges** [comment]
Well.. The bot has a protection which prevents the execution of potentially lethal walking commands. You maybe need to find another way to kill it.

**Comment by shadowstar1109** [comment]
> Bueno ... El bot tiene una protección que evita la ejecución de comandos para caminar potencialmente letales. Quizás necesites encontrar otra forma de matarlo.

I do not want it to die is the entry a server. you can help?

**Comment by Daenges** [comment]
Your question is very difficult to understand. Do you want to know how you can join a server?

**Comment by shadowstar1109** [comment]
> Tu pregunta es muy difícil de entender. ¿Quieres saber cómo puedes unirte a un servidor?

srry i use translate when you enter the server you need to enter and put the password and then throw yourself into a void the server is mc.srolemine.com

**Comment by Daenges** [comment]
Ahh. I see. You need to fall down a hole to join the server. Indeed this looks like a problem, since the walking command tries to protect you, without any possibility to deactivate this protection.

**Comment by shadowstar1109** [comment]
> Ah. Veo. Necesitas caer por un agujero para unirte al servidor. De hecho, esto parece un problema, ya que el comando para caminar intenta protegerte, sin ninguna posibilidad de desactivar esta protección.

do you know any way?

**Comment by Daenges** [comment]
This needs to be fixed in the code. It is not a very complicated fix, just something like a `-f` to tell the bot that you know what you are doing, so it just executes this. Althought the easiest solution for it would be to just implement it for single block movements. So you can walk up to the corner automatically and then do a single block movement with `-f`.

**Comment by shadowstar1109** [comment]
> Esto debe arreglarse en el código. No es una solución muy complicada, solo algo como `-f`decirle al bot que sabes lo que estás haciendo, por lo que simplemente lo ejecuta. Aunque la solución más sencilla sería simplemente implementarlo para movimientos de un solo bloque. De modo que puede caminar hasta la esquina automáticamente y luego hacer un movimiento de un solo bloque con `-f`.

can you do?

**Comment by shadowstar1109** [comment]
done?
how update?

**Comment by Daenges** [comment]
Nope. I submitted a solution for this problem. Since I do not own this repository it must be approved by an owner.
If they think the new code is fine they will merge it. (Normally this should take about a day or two.)
When the new code is implemented, you need to download the client again.

**Comment by shadowstar1109** [comment]
> No. Envié una solución para este problema. Dado que no soy el propietario de este repositorio, debe ser aprobado por un propietario. Si creen que el nuevo código está bien, lo fusionarán. (Normalmente, esto debería tomar alrededor de uno o dos días). Cuando se implementa el nuevo código, debe descargar el cliente nuevamente.

Could I implement it in mine and would it work?

**Comment by Daenges** [comment]
You could. But therefore you would need to apply my changes to the client code and compile it yourself

**Comment by shadowstar1109** [comment]
> Tú podrías. Pero, por lo tanto, necesitaría aplicar mis cambios al código del cliente y compilarlo usted mismo. Creo que sería más fácil para ti esperar un poco.

compile it with msbuild?

**Comment by Daenges** [comment]
Yep. Just swap the content of the move command file with the new one and compile it.

**Comment by shadowstar1109** [comment]
> Sí. Simplemente intercambie el contenido del archivo de comando de movimiento con el nuevo y compílelo.

thnks bro <3 i close this

**Comment by shadowstar1109** [comment]
> Yep. Just swap the content of the move command file with the new one and compile it.

Bro the command /move east -f give me => you dont have permission to do this in red

**Comment by Daenges** [comment]
Must have to do something with the server. On my vanilla server it worked perfectly fine. Maybe try around a bit. This is defenetly not an error from the client.

**Comment by shadowstar1109** [comment]
resolve it bro the permission is if i havent unsafe zone

**Comment by Daenges** [comment]
Okay.

**Comment by shadowstar1109** [comment]
thnks you i love you <3
