### ISSUE TITLE
[Idea] Climb ladders

### ISSUE THREAD

**Issue by luizhrios** [MCCTeam/Minecraft-Console-Client#1873]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

MCC can't get path that need to climb ladders or even /move up in front of one, doesn't work.

### Suggest a possible solution

MCC to be able to calculate a path with ladders and be able to climb.

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Made this, currently trying to improve it, will open a PR soon.

**Comment by milutinke** [comment]
Implemented in #2286 will be merged soon.
