### ISSUE TITLE
[BUG] inventory container not working when multiple inventories where opened

### ISSUE THREAD

**Issue by FusselTV** [MCCTeam/Minecraft-Console-Client#1875]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

Server version : MC 1.7-1.16 (protocol v754)

### Console Client Version

Minecraft Console Client v1.18.1 - for MC 1.4.6 to 1.18.1 - Github.com/MCCTeam AppVeyor build 543, built on Fri 12/24/2021 from commit 2524802

### Expected Behavior

I want to write a script that is working like this:
![2021-12-28 02-36-42](https://user-images.githubusercontent.com/89834718/147518357-7e34eda0-9bfd-4543-a294-a0c1455a6d9d.gif)

My script looks like this:
![image](https://user-images.githubusercontent.com/89834718/147519353-6fbf4071-ca66-4efb-bc98-3f0e1df793fc.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/89834718/147518723-98a7c6ef-e5b0-4602-bb00-4e14e1bed95f.png)

As soon as the second inventory opens `inventory container` is no longer working. To get it working again I need to close the last inventory by hand with `inventory 1 close`
This solution is not working for me because I want to run scripts, that are muting different reasons and therefore multiple inventories with other IDs open (inventory IDs increase therefore `inventory 1 close` is no longer working because the last inventory ID is e.g. 6).

### Steps to Reproduce the bug

provided enough explanation above

### Device

Desktop

### Operating System

Linux

### Server Address (If applicable)

mc.pvpgym.net

**Comment by ORelio** [comment]
> As soon as the second inventory opens `inventory container` is no longer working.

If there are several inventories, your command is ambiguous because MCC does not know which container you are referring to. Therefore you'd need to close the first container before opening the second one, or use container IDs. If you need to perform advanced _and_ automated operations on containers, maybe you'll need to program a C# script.

**Comment by ORelio** [comment]
However, maybe we could adjust `container` to automatically select the container with highest ID.
Any though about it, @ReinforceZwei? 🤔

**Comment by ReinforceZwei** [comment]
That's what I was thinking when I saw this issue.

**Comment by ORelio** [comment]
Ok, adjusted `container` to select the container with highest ID, which hopefully should be the foreground one.
Please try out the latest development build and see if it works for you.

**Comment by xXjojaXx** [comment]
Nice adjustment, could be helpful in multiple cases 👍

**Comment by FusselTV** [comment]
Fixes my issue thanks a lot!
