### ISSUE TITLE
Script Scheduler action

### ISSUE THREAD

**Issue by shadowstar1109** [MCCTeam/Minecraft-Console-Client#1876]
Hello, how do I make Script Scheduler wait a few seconds and do an action?

**Comment by ORelio** [comment]
https://github.com/MCCTeam/Minecraft-Console-Client/blob/7b049576a3d7e9c38afc019671f5eb52053fc6b9/MinecraftClient/config/sample-tasks.ini#L39-L42

**Comment by shadowstar1109** [comment]
action=sleep 100 for example?

**Comment by shadowstar1109** [comment]
done work it thnks
