### ISSUE TITLE
[BUG] 'refresh_token' or 'assertion' is not valid

### ISSUE THREAD

**Issue by TNTUP** [MCCTeam/Minecraft-Console-Client#1877]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.1

### Console Client Version

1.18.1

### Expected Behavior

Check if session is valid then log on the server if valid; else reauth then save the new session token and log on the server

### Actual Behavior

Crashes the client with the error:

Cached session is invalid or expired.

Exception non gérée : System.Exception: AADSTS70000: The provided value for the input parameter 'refresh_token' or 'assertion' is not valid. The token was issued for a different client id
Trace ID: bc91620f-4314-4d54-aba7-6357f25c7b02
Correlation ID: 33c80e12-ae48-4200-b9f9-ea81fb9b4036
Timestamp: 2021-12-28 21:56:37Z
   à MinecraftClient.Protocol.Microsoft.RequestToken(String postData)
   à MinecraftClient.Protocol.Microsoft.RefreshAccessToken(String refreshToken)
   à MinecraftClient.Protocol.ProtocolHandler.MicrosoftLoginRefresh(String refreshToken, SessionToken& session)
   à MinecraftClient.Program.InitializeClient()
   à MinecraftClient.Program.Main(String[] args)

### Steps to Reproduce the bug

1. N/A
2. 
3. 

Seems to happen randomly/rarely, not related to minecraft launcher afterall (The PC which MCC clients are ran does not have a .minecraft in its %appdata% directory). I wish not to nuke/reset the SessionCache.ini as I don't want to lose already authenticated ones which is still valid. (Happens to my friend aswell so this couldn't be Minecraft Launcher's fault)

### Anythings that could help diagnosing the bug

```txt
MinecraftClient.ini: https://paste.gg/p/anonymous/e989da231e2046d3ae98121e9d25af77
Logs (startup/crash): https://paste.gg/p/anonymous/4187cedc67034e4dbba6b32ba4d9ec01

There's too many lines outputting from debugmessages=true, if needed I can try sorting this out (by forcing dumping lines in a file)
```

### Device

Desktop

### Operating System

Windows

**Comment by TNTUP** [comment]
Sensitive data if I include SessionCache.ini (from the alt I've been testing), cannot post here. But I can give the POST request (snipped the M3BAY token

ession data has been successfully loaded from disk.
Access token expiration time is 2021-12-28 16:43:44
Cached session is invalid or expired.
< POST /consumers/oauth2/v2.0/token HTTP/1.0
< Host: login.microsoftonline.com
< User-Agent: MCC/1.18.1
< Accept: */*
< Connection: close
< Content-Type: application/x-www-form-urlencoded
< Content-Length: 417
< 
< client_id=54473e32-df8f-42e9-a649-9419b0dab9d3&grant_type=refresh_token&redirect_uri=https%3A%2F%2Fmccteam.github.io%2Fredirect.html&refresh_token=M.R3_BAY.

**Comment by ReinforceZwei** [comment]
Have you switched login method between `mcc` and `browser`?

**Comment by TNTUP** [comment]
> Have you switched login method between `mcc` and `browser`?

No, untouched that setting for years. Seems to happen rarely/randomly. I don't know if its due to the token expiry and it couldn't check/renew it? After X minutes I was able to log in with the affected account

**Comment by ReinforceZwei** [comment]
Which login method you are using?

**Comment by TNTUP** [comment]
type=microsoft
method=mcc

(I have uploaded the contents of the MinecraftClient.ini in a paste linked above^^)

**Comment by TNTUP** [comment]
This is getting annoying, happens on every day (probably either at the same hour/min). I notice the auth token or session token or whatever it is called xD expires after 24 hours while using the latest version. Using my old backup (1.17.1 only) fixes it (I guess it changes something...)

**Comment by ReinforceZwei** [comment]
A temporary workaround have been made in #1925.

**Comment by TNTUP** [comment]
Updated client, now it throws HTTP 200 :(

**Comment by TNTUP** [comment]
Still persists :(
