### ISSUE TITLE
[Idea] Player face in Windows Terminal

### ISSUE THREAD

**Issue by TNTUP** [MCCTeam/Minecraft-Console-Client#1879]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1.18.1 #543

### Describe your problem

Using Windows Terminal, the icon (player face) doesn't show up (ran either from powershell.exe or cmd.exe) using MinecraftClient.exe or a shortcut.

### Suggest a possible solution

Implement a way to get player heads in the Windows Terminal

### Attach screenshot here (If applicable)

https://scr.rightawake.com/20211228175051.png
https://scr.rightawake.com/20211228175937.png

### Minecraft Version

1.18.1

### Device

Desktop

### Operating System

Windows

**Comment by ORelio** [comment]
The Terminal app must provide an API for allowing an app to change the tab icon.
I'm not sure if there is one on Windows Terminal.

**Comment by TNTUP** [comment]
I found this https://github.com/microsoft/terminal "Windows Console API server" idk if it can help, if not this issue can be closed if it does not offer API for it^^

**Comment by BruceChenQAQ** [comment]
Currently Windows Terminal does not seem to support this feature.
But a feature request already exists: [Suggestion: ability for terminals to set their tab icon](https://github.com/microsoft/terminal/issues/1868)

**Comment by milutinke** [comment]
Since the feature is not supported, and it is questionable if it will be ever supported by the Windows Terminal, I'll close the issue.
