### ISSUE TITLE
Xbox Game Pass Account Authentication

### ISSUE THREAD

**Issue by tsgfra33** [MCCTeam/Minecraft-Console-Client#1881]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Hi, using xbox game pass accounts gives me an error telling me that the user is not premium...

### Suggest a possible solution

It would be possible to add the authentication method for accounts of the xbox game pass? Thanks 

### Device

VPS

### Operating System

Linux

**Comment by ReinforceZwei** [comment]
Please make sure your account own Minecraft Java Edition. Bedrock Edition will not work with MCC.

**Comment by tsgfra33** [comment]
The xbox game pass, contains all minecraft versions java included. But the authentication method i think it's different beacause it makes me login only with minecraft launcher

**Comment by tsgfra33** [comment]
Hi, i'll explain more batter. Xbox game pass gives you the access to use all versions of minecraft java included, if i try to login in third party launchers for example tlauncher using microsoft authentication it tells me that I am not a premium user, but if I try from the official minecraft launcher (the latest) I can easily log in. I don't know if what I'm asking is possible, if you need more information I'm available. Thanks so much for your hard work.

**Comment by VeryEvilPanda** [comment]
I am also experiencing this problem. I have two accounts, one which I bought years ago and migrated to Microsoft, and one which I have access to with my Xbox Game Pass Ultimate. The alt account from game pass works with every other launcher for me (Minecraft, Lunar, MultiMC), but when I try to use it with MCC it tells me 'Minecraft Login failed :User not premium.' I believe this is an issue with MCC and not my account because it works with lots of other launchers. It would be great if this was fixed soon.

**Comment by javaarchive** [comment]
An easy way to implement this would be to allow the user to input their access token directly, which I've been told is not the proper way to do microsoft auth but still works.

**Comment by tsgfra33** [comment]
> An easy way to implement this would be to allow the user to input their access token directly, which I've been told is not the proper way to do microsoft auth but still works.

This might be a great solution, but are you sure it works with gamepass accounts?

**Comment by ReinforceZwei** [comment]
We don't own any Xbox game pass account for testing unfortunately. We may not be able to fix this issue.

**Comment by tsgfra33** [comment]
@ReinforceZwei i can give one account for testing if necessary, but where i can send it to you?😅
