### ISSUE TITLE
[BUG] Cant join a server

### ISSUE THREAD

**Issue by DerpDerpling** [MCCTeam/Minecraft-Console-Client#1883]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.1

### Console Client Version

AppVeyor build 545

### Expected Behavior

To join the server without any issues

### Actual Behavior

its giving me this error

`[ERROR] InvalidOperationException: Queue empty.
[ERROR] Failed to join this server.`

ill attach a [log here](https://i.derpy.xyz/qYHhz.txt)

### Steps to Reproduce the bug

1. open MCC
2. Try to connect to play.hobbitcraft.cc
3. observe

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/57187871/147787245-63992ca6-0b04-4cf5-be78-5f1a1042db2a.png)

### Anythings that could help diagnosing the bug

```txt
[My config file](https://i.derpy.xyz/MinecraftClient.ini)
[My Log File](https://i.derpy.xyz/qYHhz.txt)
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

play.hobbitcraft.cc

**Comment by BruceChenQAQ** [comment]
Should be fixed in the latest release. I can't test it since I'm not in the whitelist.
