### ISSUE TITLE
Mcc methods in dll (C# Question) 

### ISSUE THREAD

**Issue by xXjojaXx** [MCCTeam/Minecraft-Console-Client#1886]
Again, I know this is more a c# than a mcc question, but I think this is the best place to ask.
My Idea was that I need the same code in a lot of my MCC Scripts and Chatbots, which means it would be great to collect these "often used" methods at one general place. The only way I know to do this until know is using DLLs, but as far as I know I can't use Methods from MCC (ex. SendText()) or any other external source in my dll, because it doesn't know it's host/parent or however it's called.
So my question for you is:
Is there any way to use/include MCC functionality/methods into my dll or is there another way or workaround for a code collection I can easily use in my scripts, which can use MCC Methods.
Thank you very much.

**Comment by ReinforceZwei** [comment]
Assuming you are using Visual Studio. In your DLL project, you can add MCC as project reference in project explorer. Then you can start using MCC namespace in your DLL.

**Comment by xXjojaXx** [comment]
I can't imagine hpw this is ment to work. I use Mcc in a docker container so I don't really have access to the actual source. Will it work if I just add a reference to some Mcc project as long as the classes I want to use are the same or does it have ro be the actual instance of mcc I'm using to run my bot in the container?

**Comment by milutinke** [comment]
Closing due to being stale. If you need help, re-open.
