### ISSUE TITLE
[BUG] ScriptScheduler not functioning

### ISSUE THREAD

**Issue by DevDistorts** [MCCTeam/Minecraft-Console-Client#1887]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18

### Console Client Version

Latest

### Expected Behavior

Running /prison command onLogin by using Script Scheulder 

### Actual Behavior

When running the docker container, the Client is able to connect to server, but it doesn't seem execute the task, even though it shows the script loading in the DEBUG.

### Steps to Reproduce the bug

1.  git clone MCConsoleClient Github Repo
2.  Build Docker Image using Github Wiki pages
3.  Use default docker-compose file
4.  Append the following changes below to the tasks.ini, startup-script.txt & MinecraftClient.ini
5.  Start-up docker-compose stack & profit

### Anythings that could help diagnosing the bug

```txt
Log Output (w/Debug enabled): https://www.toptal.com/developers/hastebin/raw/wesodaleni
tasks.ini: https://www.toptal.com/developers/hastebin/raw/avagorucan
startup-script.txt: https://www.toptal.com/developers/hastebin/raw/owajinutol
MinecraftClient.ini: https://www.toptal.com/developers/hastebin/raw/jojacugara
```

### Device

VPS

### Operating System

Other

### Server Address (If applicable)

mc.vortexnetwork.net

**Comment by DevDistorts** [comment]
Hello,

Hope everyone had a great holiday, I am still running into this issue to where I am unable to get these Scheduled tasks to run.

Let me know what further information I could provide to better troubleshoot the issue!

Regards, 
Distorts

**Comment by ORelio** [comment]
Hi, unfortunately I took too much time to look at your issue and the files you uploaded are gone. Do not hesitate to set `debugmessages=true` in `MinecraftClient.ini` if not already done, because this might help you self diagnosing what is wrong with the bot. It should tell you that it's loading your task and show all the details of the task.

**Comment by milutinke** [comment]
Could not re-create, try the latest build.
Closing the issue due to being stale, if you still have a problem, re-open it, but please attach debug information.
