### ISSUE TITLE
Blacklisted IP or Too Many Logins

### ISSUE THREAD

**Issue by jcodyparker** [MCCTeam/Minecraft-Console-Client#1888]
So I randomly get "blacklisted IP, incorrect password, or too many logins" when trying to login to some accounts. But on the same PC, I can login perfectly fine with normal MC launcher. Then later in the day, it logs into console client perfectly fine. Why does this happen so often on MCC, but logs in fine on the normal MC launcher?

**Comment by ORelio** [comment]
Maybe there's an anti-bot mechanism that triggers more easily with MCC.
I'm not 100% sure because we don't know exactly what happens server-side 😕

**Comment by jcodyparker** [comment]
Ah ok. Is the "blacklisted IP" per account? Because I cna still login to console client on other accounts.

**Comment by ReinforceZwei** [comment]
We need the actual console output with debug messages enabled for diagnosing your problem.

**Comment by jcodyparker** [comment]
It's just mojang blacklisting my IP for no reason. I didnt login too many times, one time and boom blacklisted. I havent had issues with this for months. Every other one of my accounts (one being my brothers that he can login perfectly fine, from a PC on the same network) doesnt work at all now and says blacklisted or invalid credentials, even when logging into default MC launcher. But my main accounts works perfectly fine for some reason. I can login to my main on MCC, and on default launcher still.

**Comment by jcodyparker** [comment]
So I tried logging into different accounts on a VPS, I open them once and they work fine. If I close them, and then re-open a few minutes later it blacklists the IP for the account and I can't log in. Why is this happening on the VPS?
