### ISSUE TITLE
Use dll from path

### ISSUE THREAD

**Issue by xXjojaXx** [MCCTeam/Minecraft-Console-Client#1890]
I want to load an dll from another path with
//dll MyDll.dll
//using MyNamespace

but this doesn't work because mono only looks for DLLs next to the exe and at the system path for assemblies.

Can I make a work-around to still use that dll or can somebody include that into mcc?
Thanks

**Comment by ORelio** [comment]
By looking at [`CSharpRunner.cs`](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/CSharpRunner.cs), all `//dll` arguments are passed as is to the .NET compiler as `ReferencedAssemblies`. I'm not sure what prevents you from using relative or absolute paths for your DLLs.
