### ISSUE TITLE
[BUG] Join time out

### ISSUE THREAD

**Issue by 5UP3R-D1N** [MCCTeam/Minecraft-Console-Client#1891]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

Latest

### Expected Behavior

I'm trying to join my server to AFK my bot there.
I checked my router that it is running fine

### Actual Behavior

Its timed out and it just restart the client

### Steps to Reproduce the bug

I don't know how to.

### Anythings that could help diagnosing the bug

```txt
log : https://pastebin.com/eMSNT2am
Config : https://pastebin.com/M69NpYii
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

5UP3R_5MP.aternos.me:20293

**Comment by ORelio** [comment]
I'm not sure what is the root cause of this, but some Forge mods may prevent MCC for working properly. MCC does not "handle" Forge mods, it just tells the server that it has all the required mods. Sometimes, this does not work (and we can't implement all Forge mods out there) 😕

**Comment by 5UP3R-D1N** [comment]
> I'm not sure what is the root cause of this, but some Forge mods may prevent MCC for working properly. MCC does not "handle" Forge mods, it just tells the server that it has all the required mods. Sometimes, this does not work (and we can't implement all Forge mods out there) 😕

That server doesn't contain forge mod at all
