### ISSUE TITLE
[Idea] move with the water

### ISSUE THREAD

**Issue by shadowstar1109** [MCCTeam/Minecraft-Console-Client#1897]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

ultimate

### Describe your problem

Hello, the bot does not move with the water, how do I interact?

### Minecraft Version

1.16.5

### Device

Laptop

### Operating System

Windows

**Comment by ORelio** [comment]
This is not implemented. See #206 for the feature request.
