### ISSUE TITLE
[BUG] Server disconnects MCC because it timed out

### ISSUE THREAD

**Issue by Masken8** [MCCTeam/Minecraft-Console-Client#1898]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.1

### Console Client Version

Latest

### Expected Behavior

Server doesn't disconnect the client after ~30 seconds

### Actual Behavior

Server disconnects the client because it timed out.
```
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
<redacted> joined the game
[MCC] Connection has been lost.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
```
I asked a server admin to check the server logs and it just says Timed out.

### Steps to Reproduce the bug

1. `sudo pacman -Syu`
2. `sudo pacman -S wine wine-mono`
3. `wine MinecraftClient.exe`
4. Edit `MinecraftClient.ini` to login with `microsoft` using the `browser` option
5. `wine MinecraftClient.exe`
6. Login
7. Join a server

### Anythings that could help diagnosing the bug

```txt
This consistently happens on Linode with Arch Linux.
I have tried on both Nanode 1 GB and Linode 4 GB.

The Minecraft Server is a Paper server behind Waterfall and Geyser.
```

### Device

VPS

### Operating System

Linux

**Comment by ORelio** [comment]
Is there any difference if you use Mono instead of Wine?
Well, there are also issues with Mono (#1303) but that might help.

**Comment by Masken8** [comment]
Seems to work with Mono
