### ISSUE TITLE
[BUG] Afking in hypixel skyblock personal island kicks you to limbo

### ISSUE THREAD

**Issue by Soup333** [MCCTeam/Minecraft-Console-Client#1906]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [x] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

Latest

### Expected Behavior

Afk's normally and dosent get transferred to limbo 

### Actual Behavior

I joined personal island but after a few minutes it says "You were spawned in Limbo"
Somehow something is triggering doing that as joining with the official Minecraft client with the exact same steps doesn't do that.

### Steps to Reproduce the bug

1. Join mc.hypixel.net
2. Do /skyblock
3. Get kicked to limbo after a few minutes 

### Attach screenshot here (If applicable)

![PXL_20220114_052324145](https://user-images.githubusercontent.com/92235850/149456291-d5018cfc-4b05-4aaa-adb0-e4f3f0390146.jpg)

### Device

Raspberry Pi

### Operating System

Linux

### Server Address (If applicable)

mc.hypixel.net

**Comment by javaarchive** [comment]
This could be because of the brand string sent by MCC or detection of the client specifically, since I've also been kicked to limbo upon using a blacklisted mod.

**Comment by Soup333** [comment]
> This could be because of the brand string sent by MCC or detection of the client specifically, since I've also been kicked to limbo upon using a blacklisted mod.
> 
> https://github.com/MCCTeam/Minecraft-Console-Client/blob/4ba09754de04a2d87fe921be6e7dd4b445edf2ad/MinecraftClient/Settings.cs#L20

Well I already tried changing the brand name so I guess they are somehow detecting it

**Comment by milutinke** [comment]
It's most likely their anti cheat detecting a bot movement, we can't do much about it.

**Comment by milutinke** [comment]
Confirmed that Hypixel now bans MCC users. nothing that we can do about it.
