### ISSUE TITLE
[Idea] Forge 1.12 Support

### ISSUE THREAD

**Issue by gamenTV** [MCCTeam/Minecraft-Console-Client#1907]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

latest

### Describe your problem

Forge 1.12 Support would be nice

### Device

Other

### Operating System

Linux

**Comment by ORelio** [comment]
Forge _should_ be supported on 1.12. Could you describe the login process? 🤔

**Comment by Yertled** [comment]
It works flawlessly for me on forge 1.12, but I can't get it to work on Forge 1.16 modpacks.
