### ISSUE TITLE
[BUG] Randomly crashes, or crashes when opening

### ISSUE THREAD

**Issue by jcodyparker** [MCCTeam/Minecraft-Console-Client#1908]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.4

### Console Client Version

Latest

### Expected Behavior

Expect it to not crash

### Actual Behavior

MCC crashes when opening, or randomly crashes some days showing the error I posted as a screenshot. It wouldn't open at all today until I deleted the session cache, then it opened right up. Some days it works fine and other days it randomly crashes during the day at some point. I'm on the latest dev build. I tried turning on the log to file option, and it doesn't create a log when it crashes on first open.

### Steps to Reproduce the bug

1. Open MCC
2. Sometimes wait
3. Sometimes it just instantly crashes

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/90956620/149663153-ca53ba65-3da7-4b11-b666-717bc0429b75.png)

### Anythings that could help diagnosing the bug

```txt
No log being created when it crashes
```

### Device

VPS

### Operating System

Windows

**Comment by ORelio** [comment]
It's complicated to diagnose this if no error details can be gathered on your side 😕

**Comment by jcodyparker** [comment]
It won't login, then crashes now, no log is being created either

![image](https://user-images.githubusercontent.com/90956620/153531147-916577a6-cbde-4d5a-8d08-a4507366d40b.png)

**Comment by jcodyparker** [comment]
Works fine on my personal computer though. What is this error?

**Comment by BruceChenQAQ** [comment]
Fixed similar issues(https://github.com/MCCTeam/Minecraft-Console-Client/issues/1780) in https://github.com/MCCTeam/Minecraft-Console-Client/commit/eba309191cd145c95b94dd0fed284c1b788b2e2b and https://github.com/MCCTeam/Minecraft-Console-Client/commit/bb4c13168beaefb278d21140f3ae56ef788b8b00. Try the latest version.
