### ISSUE TITLE
[BUG] Unhandled Exception

### ISSUE THREAD

**Issue by loungeclown** [MCCTeam/Minecraft-Console-Client#1909]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.1

### Console Client Version

1.18.1

### Expected Behavior

I'd expect it to work properly and normally

### Actual Behavior

Its just not working

### Steps to Reproduce the bug

1. Open the client
2. Issue reproduced!

### Anythings that could help diagnosing the bug

```txt
`Minecraft Console Client v1.18.1 - for MC 1.4.6 to 1.18.1 - Github.com/MCCTeam
AppVeyor build 547, built on Sun 01/16/2022 from commit 223db4a

Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The file or directory is corrupted and unreadable. (Exception from HRESULT: 0x80070570)
   at MinecraftClient.WinAPI.WindowsVersion.get_WinMajorVersion()
   at MinecraftClient.Program.Main(String[] args)
`
```

### Device

Laptop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
I think this is due to file corruption on your system. Try to reinstall .NET Framework may fix the problem.
