### ISSUE TITLE
[Idea] launcher emulation

### ISSUE THREAD

**Issue by Werewolf6845** [MCCTeam/Minecraft-Console-Client#1913]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1,16,2

### Describe your problem

Hello. I have such a problem, the server on which I played made my own launcher and transferred most of the modes to it. Is it possible to emulate this launcher to enter the mode?

### Minecraft Version

1,16,2

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
You will have to find out what modification have been made in their own launcher, then implement the changes in MCC. As there's tons of modified launcher out there, it's not possible for us to accept and implement such request.

**Comment by ORelio** [comment]
While it's likely possible to emulate a launcher, by studying the launcher and emulating how it identifies itself to the server, as said by @ReinforceZwei each launcher is different so we cannot implement this ourselves. That would be an endless work :/
