### ISSUE TITLE
[Idea] When will the passage through half block?

### ISSUE THREAD

**Issue by iwixw** [MCCTeam/Minecraft-Console-Client#1917]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

517

### Describe your problem

When will the passage through half block?

### Minecraft Version

1.18.1

### Operating System

Windows

**Comment by ORelio** [comment]
Currently this feature is still waiting for interested contributors: #553
I'll close this one as duplicate.
