### ISSUE TITLE
VKontakte bot 

### ISSUE THREAD

**Issue by iwixw** [MCCTeam/Minecraft-Console-Client#1920]
I have a script that can send and receive text commands. But how to make it so that (Login, Password, Server IP) was input through VK?
( script: https://pastebin.com/2c7NBtG7 )

**Comment by ORelio** [comment]
You mean this?
https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/VkMessager.cs
There are some comments explaining what you need to make it work.
See also: #1685

**Comment by iwixw** [comment]
> You mean this? https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/VkMessager.cs There are some comments explaining what you need to make it work. See also: #1685 

No, unfortunately this is not what I need

**Comment by Daenges** [comment]
@iwixw You can create an [Accounts File](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-accounts.txt) ([Explaination](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config#servers-and-accounts-file)). Then you can process messages from VK [here](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-accounts.txt) and start the internal command: `connect <server> [account]`. ([cf](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config#internal-commands))
