### ISSUE TITLE
[BUG] curl bad/illegal format or missing URL

### ISSUE THREAD

**Issue by Art0sh** [MCCTeam/Minecraft-Console-Client#1924]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.1

### Console Client Version

Latest

### Expected Behavior

Using docker, I would expect it to "work", meaning, I expect mcc to run and let me log in, connect to servers and stuff.

### Actual Behavior

When using docker run, the newly generated container wont start and instead I get an error saying
`curl: (3) URL using bad/illegal format or missing URL
Cannot open assembly 'MinecraftClient.exe': No such file or directory.`

### Steps to Reproduce the bug

1. build the docker image using the readme
2. try to start a container using docker run -it --restart on-failure:5 -v <PATH_ON_YOUR_MACHINE_TO_MOUNT>:/opt/data minecraft-console-client:latest
3. get the error

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/35751343/152619171-c8468a19-0d9a-4689-9a09-ebd7a0d0ff9e.png)

### Device

VPS

### Operating System

Linux

**Comment by ORelio** [comment]
Thanks for reporting. Should be resolved in commit 698690293809dec8ce3ff0c96d8566d4fd8d160a.
Run `git pull` inside the folder to update the Docker script and launch `docker build` again.
