### ISSUE TITLE
[QUESTION] Detecting time of the day

### ISSUE THREAD

**Issue by milutinke** [MCCTeam/Minecraft-Console-Client#1928]
Hello,

I'm trying to make a function which could get the exact time of day in Minecraft time (0 - 24000, just like for /time command).
I've seen that there is a packet for that (`0x59`) and that it's already implemented as `OnTimeUpdate` function in `ChatBot` class.

My questions is:
How I could get Minecraft day time from that number I get in `OnTimeUpdate`? (I do not have idea for the formula).

I've looked through the game code, that number is incremented on each tick, but all references of it are used in formulas that are used for Sky gradient and fog colors, or the total age of the world in days (division by 24000L).
Thanks.

PS:
Could you add a Question template for Issues?

**Comment by ORelio** [comment]
Hi,

As per https://wiki.vg/Protocol#Time_Update you need to divide `TimeOfDay` by 24000.
> The time of day is based on the timestamp modulo 24000. 0 is sunrise, 6000 is noon, 12000 is sunset, and 18000 is midnight. 

Also, there is no Question template because there's the [Discussions](https://github.com/MCCTeam/Minecraft-Console-Client/discussions) section for this.

**Comment by milutinke** [comment]
Oh, I haven't seen the Discussions thing, it's a new thing on Github.
Thanks.

Here is the code for getting the time in 24h format if someone needs it in the future:
```
public class SimpleTimeChatBot : ChatBot {
        private long timeOfDay;

	public long TimeOfDay {
		get { return this.timeOfDay; }
	}

	public override void Initialize() {  }

	private string PadString(string text, int len, string padCharacter, int mode) {
		string s = text;

		while(s.Length < len) {
			if(mode == 0) s += padCharacter;
			else s = padCharacter + s;
		}

		return s;
	}

	public string GetFormatedTime() {
		long time = this.timeOfDay;

		if(time < 0)
			time = time * -1;

		time = time % 24000;

		int hours = 6 + (int) (time / 1000);

		if(hours >= 24)
			hours -= 24;
		
		double minutesDouble = (double) time % 1000;
		minutesDouble = (minutesDouble / 1000) * 60;

		int minutes = (int) Math.Round(minutesDouble);

		if(minutes == 60) {
			minutes = 0;
			hours++;
		}

		return PadString("" + hours, 2, "0", 1) + ":" + PadString("" + minutes, 2, "0", 1);
	}

	public override void OnTimeUpdate(long worldAge, long timeOfDay) {
		this.timeOfDay = timeOfDay;
	}
}
```
