### ISSUE TITLE
[Idea] 

### ISSUE THREAD

**Issue by aion1998** [MCCTeam/Minecraft-Console-Client#1930]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

最新

### Describe your problem

有没有什么办法能写个扩展的脚本，能够实现自动挖掘指定坐标区域内的所有方块
我有点想弄，但是没有任何思路

### Suggest a possible solution

和圈地插件一样，标记两个点，然后自动寻找安全的路径进行挖掘

### Minecraft Version

1.18.1

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
Use [MineCube.cs](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/MineCube.cs).

**Comment by Daenges** [comment]
Yep. MineCube.cs should do exactly what you want. Unfortunately this script is more of a beta version, since the movement and block detection sometimes fails. Which makes it a bit unreliable at times.

**Comment by aion1998** [comment]
> Yep. MineCube.cs should do exactly what you want. Unfortunately this script is more of a beta version, since the movement and block detection sometimes fails. Which makes it a bit unreliable at times.

Thank you very much

**Comment by aion1998** [comment]
> Use [MineCube.cs](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/MineCube.cs).

Thank you very much，俺懂了
