### ISSUE TITLE
[BUG] Not allowing me to type anything after logging into the server

### ISSUE THREAD

**Issue by itzmemonkeyboy19** [MCCTeam/Minecraft-Console-Client#1933]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17

### Console Client Version

Latest

### Expected Behavior

I expect that once the console client logs into the MC server that I am trying to get onto that I can type.

### Actual Behavior

As soon as I log on to the server that I type in, I get the auto-welcome chat messages in the .cmd. But as soon as I get those I can not type in anything.

### Steps to Reproduce the bug

1. I'm not sure
2. Try logging onto the same server?
3. No idea
4

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

play.vortexnetwork.net

**Comment by 5UP3R-D1N** [comment]
Maybe you died? Try /respawn or turn on AutoRespawn

**Comment by milutinke** [comment]
Try the latest build, if you have any issues typing, try using Windows Terminal or Alacritty.
If you still have issues, re-open the issue.
