### ISSUE TITLE
AutoAttack 

### ISSUE THREAD

**Issue by AbdobiZark** [MCCTeam/Minecraft-Console-Client#1935]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

Latest

### Expected Behavior

idk

### Actual Behavior

this warn msg keep spamming

[WARN] Update: Got error from MinecraftClient.ChatBots.AutoAttack: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at MinecraftClient.ChatBots.AutoAttack.Update()
   at MinecraftClient.McClient.OnUpdate()

### Steps to Reproduce the bug

1. 
2. 
3. 

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/88251043/153403799-95eb095b-fe1b-4db1-b8a3-4f67413c0ead.png)

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Fixed in #1943
Waiting for an approval.

**Comment by 5UP3R-D1N** [comment]
I got it too it spam my console like a thousand times

**Comment by AbdobiZark** [comment]
> 

didn't work for me.

**Comment by AbdobiZark** [comment]
> Fixed in #1943 Waiting for an approval.

didn't work for me
