### ISSUE TITLE
Full help for /inventory

### ISSUE THREAD

**Issue by 5UP3R-D1N** [MCCTeam/Minecraft-Console-Client#1942]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Fully doc for /inventory plz

### Suggest a possible solution

Its hard to use /inventory and I know only /inventory container click #
But what about the other command I don't know what it is

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

**Comment by 5UP3R-D1N** [comment]
> Type `/help inventory`.

;-; where's the list of action
There suppose to be more than just "click" right?

**Comment by milutinke** [comment]
> > Type `/help inventory`.
> 
> ;-; where's the list of action There suppose to be more than just "click" right?

Use `/inventory help`
And then use `/inventory help <action>` for the specific action.

**Comment by MousePak** [comment]
inventories always seem to increase in number too, in the following example clicking any item within a shop opens a new ID.
`/shop
\inventory 6 click 11
\inventory 7 click 19 m`

/shop created container ID 6 >> clicking item within shop opens ID 7
This behavior unfortunately blocks scripting unless other hidden options exist


Having further information in how to script inventory further would be beneficial too. This is an area I would like included in OP request.

```
[MCC] Inventory # 6 opened: Select a shop category...
[MCC] Use /inventory to interact with it.
```

Can we use chat matching for MCC messages?
Are ID's kept within a var or array we could use?
cscript could this be used to capture ID or MCC messages?

If we could have examples im sure we could create something special.

**Comment by MousePak** [comment]
@ReinforceZwei wow never tried this just thought the word "container" was for reference not use !
expect I could get much closer to what im after using multiple cycles knowing that

Having something interact with MCC messages would have been ideal but going off topic for this thread.
Thank you (fast reply too)

**Comment by milutinke** [comment]
Since I've made a detailed explanation with examples for Inventory handling in our documentation: https://mccteam.github.io/guide/usage.html#inventory
I'll be closing the issue.
If you need any more help, refer to the documentation, and if you really can't figure out, join our Discord and ask.
