### ISSUE TITLE
message after the call

### ISSUE THREAD

**Issue by kysteno4ek** [MCCTeam/Minecraft-Console-Client#1949]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

the newest

### Describe your problem

how do I make the script run automatically after a kick? or write 1 message after the kick

**Comment by Daenges** [comment]
There is no direct way I think... But you could use [Auto Relog](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Resources/config/MinecraftClient.ini#L130) and setup a task to execute on rejoin.

**Comment by MousePak** [comment]
first part.. 
auto relog could catch a message when kicked to reconnect (server rules could find yourself banned)

```
[AutoRelog]
enabled=true
delay=10
retries=3 #-1 = unlimited
kickmessagesfile=kickmessages.txt

```
second part..
tasks has the field triggerOnLogin that could run a script of your choosing

```
[Task]
triggerOnLogin=true
script=event_login.txt

```
