### ISSUE TITLE
AutoAttack: Allow adding mobs to the list of auto attacks e.g. cow, pig

### ISSUE THREAD

**Issue by iwixw** [MCCTeam/Minecraft-Console-Client#1954]
How to add mobs to the list of auto attacks: cow, pig

**Comment by ckxckv** [comment]
You have to edit the source code then make a build of the client yourself. I just edited EntityTypeExtensions.cs and added Pig/Cow to it to make the client think it is hostile and attack it.

**Comment by iwixw** [comment]
I changed EntityTypeExtensions.cs what to do next?

**Comment by ReinforceZwei** [comment]
Currently you cannot customize mobs list to be attacked. Adding it to todo list.

**Comment by milutinke** [comment]
Looking into implementing this in the following days.

**Comment by milutinke** [comment]
Implemented in #2214
