### ISSUE TITLE
[Enhance]  Update to 1.18.2

### ISSUE THREAD

**Issue by bun20381** [MCCTeam/Minecraft-Console-Client#1958]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2

### Console Client Version

20220206-9

### Expected Behavior

Login 1.18.2 as normal

### Actual Behavior

"Server is running Forge without mods.
Server version : Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x (protocol v758)
Cannot connect to the server : This version is not supported !
Server version :
"

Works if you manually type in 1.16.5 or something but 1.18.2 servers do not work

### Steps to Reproduce the bug

1.  Connect to server running 1.18.2
2.  Get error message about version not being supported.

 

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/86184646/156890332-1e1d57b9-6984-4362-aecb-b1c9f6c3c47e.png)

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
1.18.2 is not yet supported. Marked your issue as enhancement.

**Comment by Pokechu22** [comment]
Changes: https://pokechu22.github.io/Burger/diff_1.18.1_1.18.2.html - all that's changed is that status effect IDs are a VarInt instead of a Byte, affecting 2 packets.

**Comment by oguzhantanitmis** [comment]
I'm waiting too, I hope it comes now

**Comment by shuiqing2046** [comment]
I'm waiting too, I hope it comes now

**Comment by Traveler07** [comment]
I'm waiting too, I hope it comes now

**Comment by ReinforceZwei** [comment]
@ORelio Maybe we could merge #1961 first? I don't think it would cause merge conflict as 1.18.2 update doesn't really have change in protocol.

**Comment by ORelio** [comment]
Indeed, the other changes are taking too much time so I merged the pull request.
