### ISSUE TITLE
Chat reaction.

### ISSUE THREAD

**Issue by BridgingDragon** [MCCTeam/Minecraft-Console-Client#1960]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

So, in multiple servers I play there is a small game called a Chat Reaction, where it is like "Hover HERE and type the word first to win aa prize!" or something, and with console client it doesn't let you hover over it or say what it would say.

### Suggest a possible solution

So if it's possible I would suggest adding something that either tells you what it is, or just lets you hover over it.

### Minecraft Version

1.17.1

### Device

Desktop

### Operating System

Linux

**Comment by ReinforceZwei** [comment]
Any example screenshots?

**Comment by BridgingDragon** [comment]
> 

Sure, here is a example, and BTW I'm hovering over the "HERE"
![image](https://user-images.githubusercontent.com/70116463/156941326-91cb036c-b325-4a02-8747-5099dbe8d128.png)

**Comment by milutinke** [comment]
> > 
> 
> Sure, here is a example, and BTW I'm hovering over the "HERE" ![image](https://user-images.githubusercontent.com/70116463/156941326-91cb036c-b325-4a02-8747-5099dbe8d128.png)

The only way to handle that is to write a custom chat bot and use `GetText(string text, string json)` function and then parse the json and extract what you need.
