### ISSUE TITLE
How do I recognise coloured text using the autoresponder?

### ISSUE THREAD

**Issue by timotrocks** [MCCTeam/Minecraft-Console-Client#1966]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Hello! I am trying to make a simple welcomer bot for my housing in hypixel. Right now, it does not respond to coloured text. The join text is $u &ehas entered the world.
Also, there is no colon after the $u but the username is a different colour from "has entered the world"
$u is the username, &e is yellow and $u can be any colour, depending on the player's rank. I want the bot to autorespond a custom message e.g. Hello, $u! Welcome to the housing!

### Suggest a possible solution

 I could do one response for every rank (colour). Idk if this is a function that I'm too dumb to know about or it is not a function but how do I make the bot recognise coloured text?

### Attach screenshot here (If applicable)

N/A

### Minecraft Version

1.8

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
For now there is no possibility of this, because the AutoRespond chat bot strips out the colors from the text, however we could add a setting for telling the bot not to strip colors.

**Comment by milutinke** [comment]
Implemented.
