### ISSUE TITLE
Using Common Config.ini File, Common Accounts.txt and Common Servers.txt File

### ISSUE THREAD

**Issue by JacksonWillford** [MCCTeam/Minecraft-Console-Client#1969]
Good evening, I'm attempting to make .bat files that can open various accounts. I was hoping to be able to do something like this inside a batch file:

`MinecraftClient.exe myconfig.ini myAccountAlias myServerAlias`

Where myAccountAlias and myServerAlias come from the accounts.txt and servers.txt files. I read through the usages in the documentation and I couldn't find my desired usage. Can someone please tell me if this is possible?

**Comment by ORelio** [comment]
try `MinecraftClient.exe myconfig.ini --login=ALIAS --serverip=ALIAS`
This will override the corresponding sections from `myconfig.ini`
See [command-line usage](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config#command-line-usage).
