### ISSUE TITLE
How To Stop ActionBar Messages Logging In The Console

### ISSUE THREAD

**Issue by GamingFrazix** [MCCTeam/Minecraft-Console-Client#1972]
So Im On A Server Which Sends Constant ActionBar Messages Which Causes The Console To Clog Up Quickly And Reach The Logging Limit I Tried Looking Through The Settings File But Found Nothing Help Me!

**Comment by ORelio** [comment]
https://github.com/MCCTeam/Minecraft-Console-Client/issues/1547#issuecomment-822588538
