### ISSUE TITLE
I setup(ed) the mono devel thing on Android but there is a issue

### ISSUE THREAD

**Issue by Shaurya4356** [MCCTeam/Minecraft-Console-Client#1974]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

The mono is always creating/fetching config files from root directory even tho I change directory of mcc.exe . My issue is I want to use few terminal for autoattack and few for just afk so how to have different config for mcc.exe 

### Minecraft Version

1.16.5

### Device

Other

### Operating System

Linux

**Comment by Shaurya4356** [comment]
The possible solution is to make mono fetch config from the same folder as mcc,because having same directory for configs can allow me to have different. Config for each instance of mcc

**Comment by milutinke** [comment]
Mono is no longer used, use .NET and the latest release.
