### ISSUE TITLE
[BUG] Can't type anything

### ISSUE THREAD

**Issue by Heringen** [MCCTeam/Minecraft-Console-Client#1977]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [x] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

Latest

### Expected Behavior

Words

### Actual Behavior

It's simple, i can't type anything after logging, it just keeps disconnecting me every few secs and won't let me type https://prnt.sc/-XFOcy4mgAWQ

### Steps to Reproduce the bug

1. Open mcc
2. Connect to server
3. Type

### Attach screenshot here (If applicable)

![asd](https://user-images.githubusercontent.com/78539601/159162682-d20b4865-9cc1-4f14-87f0-5575a3e9386d.PNG)

### Device

Desktop

### Operating System

Windows

**Comment by alicenchains** [comment]
Im having the same issue. If I manually change the version to something else it'll say login failed and typing works again.  However if you use the v1.12.2 DEV it'll work. Only problem with that is I can't get 1.12.2 to work with Microsoft logins. Im trying to use the version 1.18.2 with debugmessages on to test color codes, and they show up so I know that isnt the issue. Tried changing to several different versions and they all give different errors on invalid log even though I know the server supports said versions.

**Comment by Ferrie0416** [comment]
I having the same issue with a server im trying to join. it joins the server but thats it, it doesnt do scripts or let me type anything.
when i join a different server everything works perfectly fine.

**Comment by milutinke** [comment]
Try the latest build which uses .NET Core 6.0 and report back.
