### ISSUE TITLE
The client isn’t working on Alpine Linux even with mono or wine

### ISSUE THREAD

**Issue by ryan1112009** [MCCTeam/Minecraft-Console-Client#1978]
I want to afk 24/24 on a server (a server that allows afk 24/24), but when i sleep my computer it just disconnect the wifi, I have tried many options but none of them work. So I decided to install a linux shell on my ipad, so the problem of afking 24/24 is solved (I won’t tell how to be connected to wifi as long as imy ipad is online , but if you want comment, because the tutorial of that is quite long to type). But I got another problem, my alpine linux won’t be able to execute the latest mcc client.exe file even with mono or wine. 
The output of mono when running it is:
mono_os_mutex_init_type: pthread_mutexattr_setprotocol failed with "Function not implemented" (38)
Aborted
The output of wine when running it is:
Illegal instruction
My mono version is 6.12.0.122
My wine version is 6.18
I have chmod +x the mcc client file too.
Any idea ?

**Comment by milutinke** [comment]
Since Mono is no longer used, install .NET 6 and try it now.
Here is the manual for installation: https://docs.microsoft.com/en-us/dotnet/core/install/linux-alpine
