### ISSUE TITLE
Proxy [BUG] 

### ISSUE THREAD

**Issue by Nimolas** [MCCTeam/Minecraft-Console-Client#1980]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

MC 1.4.6 to 1.18.1

### Console Client Version

v1.18.1

### Expected Behavior

The proxy to work!

### Actual Behavior

When I go to start it ¨mono MinecraftClient.exe¨ it waits like 5 seconds then it CTRL + C and doesn't do anything.

### Steps to Reproduce the bug

1. Turn on proxy
2. set address to one from this https://www.proxy-list.download/SOCKS4 (I was using 98.175.31.195:4145)
3. try to launch

### Attach screenshot here (If applicable)

:

### Anythings that could help diagnosing the bug

```txt
Nothing outputs
```

### Device

VPS

### Operating System

Linux

**Comment by milutinke** [comment]
I'm closing this issue in favor of #2152
