### ISSUE TITLE
[Suggestion] Xbox Gamepass Account Support

### ISSUE THREAD

**Issue by Thedudediing** [MCCTeam/Minecraft-Console-Client#1989]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Recently, I bought minecraft alt accounts and they turned out to be xbox gamepass accounts, When logging in using clients such as The main launcher, Lunar, Badlion, crystal etc, the accounts are recognised and a user is able to play using the account in any server including Hypixel with no issues. When a user tries to use the alt accounts using the console client the accounts are recognised as "Non premium" accounts. 

### Suggest a possible solution

Since Migration happened a majority of servers now use xbox gamepass accounts as "Alt accounts" to afk and perform some light work tasks Therefore, I believe supporting the accounts would be of a great help to the factions/skyblock community.

### Minecraft Version

1.8.9+

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Try logging using a browser method, in the `MinecraftClient.ini` set method to browser.
Start the MCC and you will get a link in the console, `CTRL + Click` on it, it will open in a web browser then you can log in, you will get a code after login, copy it and paste it in the console and press enter.
I'll close the issue, if you need help, re-open it.
