### ISSUE TITLE
[BUG] Problem with microsoft login

### ISSUE THREAD

**Issue by Heringen** [MCCTeam/Minecraft-Console-Client#1990]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [x] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

Latest

### Expected Behavior

Normal login

### Actual Behavior

If i open MCC and just type in email and password, i get the incorrect password/email/blacklisted ip message.
But if i from then do /connect [name from accounts.txt] [server ip], the same email/password do work.
WHY?

### Steps to Reproduce the bug

1. Enter cerdentails normally
2. Use /connect to connect to server with same cerdentails
3. 

### Device

Desktop

### Operating System

Windows

**Comment by Affenmilchmann** [comment]
Have you edited this setting?
`type=microsoft                        # Account type. mojang or microsoft. Also affects interactive login in console.`
Because its `type=mojang` by default

**Comment by milutinke** [comment]
Could not re-create. Use the latest build and check your settings.
Also, recommendation is to use the browser method of login.
Closing the issue due to being stale, re-open if you need any help.
