### ISSUE TITLE
[BUG] im having trouble logging in and stuff

### ISSUE THREAD

**Issue by sleepyexo** [MCCTeam/Minecraft-Console-Client#1998]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

latest

### Expected Behavior

im trying to sign in and stuff im brand new btw

### Actual Behavior

it says login right so i use my mc acc and it says "Microsoft authenticate failed: Invalid credentials. Check your credentials"
even tho i am using the right stuff any ideas on what to do? sorry im new and stuff

### Steps to Reproduce the bug

1. idk
2. idk
3. idk

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Could not re-create it, check if Caps Lock is not on.
Also, try logging using a browser method, in the `MinecraftClient.ini` set `method` to `browser`.
Start the MCC and you will get a link in the console, ctrl + click on it, it will open in a web browser then you can log in, you will get a code after login, copy it and paste it in the console and press enter.
I'll close the issue, if you need help, re-open it.
