### ISSUE TITLE
[BUG] Block placement seems not work on the spigot/paper/... server.

### ISSUE THREAD

**Issue by BlueDeer233** [MCCTeam/Minecraft-Console-Client#2006]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue

### Minecraft Version

1.16.5

### Console Client Version

Latest

### Expected Behavior

Place a block.

### Actual Behavior

Nothing happen.

### Steps to Reproduce the bug

1. Connect to a spigot or a fork version of spigot server.
2. send /autotree type Oak
3. send /autotree set x y z
4. send /autotree toggle

### Anythings that could help diagnosing the bug

```txt
I tested it on a vanilla server, it worked normally.
```

### Device

Desktop

### Operating System

Windows

**Comment by BlueDeer233** [comment]
The Player Block Placement Packet ID is 0x2E, but 0x2C in 
https://wiki.vg/index.php?title=Protocol#Player_Block_Placement

**Comment by ORelio** [comment]
I'm not sure what is the difference between both, putting that on the todo list (investigation needed).

**Comment by BlueDeer233** [comment]
And DigBlock can't work as well  :(

**Comment by milutinke** [comment]
Tested on the latest build on Spigot, Vanilla and Paper MC it works normally.
I'll close the issue, if there is still a problem, re-open it.
