### ISSUE TITLE
My internet is disappearing all over the house

### ISSUE THREAD

**Issue by FurnyGo** [MCCTeam/Minecraft-Console-Client#2009]
When I launch 10 accounts at the same time and try to run a script on all of them, my internet disappears all over the house and only restarting the router helps
Do you know how to fix it?

**Comment by ORelio** [comment]
Minecraft Console Client sends a constant stream of packets when terrain and movements are enabled, just like the official client does, so you may try disabling that feature in config. Apart from that, it's supposed to be lightweight network-wise so I've no further suggestions.

**Comment by Daenges** [comment]
Set [this](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Resources/config/MinecraftClient.ini#L35) to `false`.

**Comment by FurnyGo** [comment]
But why doesn't the internet turn back on after turning off all accounts?

**Comment by Daenges** [comment]
> But why doesn't the internet turn back on after turning off all accounts?

Your router may have a security switch against DOS attacks, which denies internet access if too many packets are sent. This could get triggered if you send too many data at the time.

**Comment by ORelio** [comment]
Or the router is crashed for some reason and needs a reboot.
