### ISSUE TITLE
[BUG] strange behavior: breaks scrolling, panels. 

### ISSUE THREAD

**Issue by Superslim-anoniem** [MCCTeam/Minecraft-Console-Client#2016]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2

### Console Client Version

Latest

### Expected Behavior

Program runs normally, doesnt affect unrelated things. 

### Actual Behavior

The program can randomly break scrolling/make panel/start menu equivalent stop working. 

### Steps to Reproduce the bug

As far as I can tell it's random, but the last failure occurred after it reconnected after a server restart. 

### Anythings that could help diagnosing the bug

```txt
config: https://pastebin.com/q7qwZbdr
Couldn't get a log with the failure. 
Server is fabric with only the simple vc mod. 
The desktop environment I'm using is KDE Plasma.
```

### Device

Laptop

### Operating System

Linux

**Comment by ORelio** [comment]
This is strange, I'm not sure how this can happen since MCC does not interact outside of console input/output, files and network, especially on Linux. On Windows it also sets the console icon and allow you to paste from clipboard, but not much more. It is likely that the issue you are facing occurs somewhere outside MCC itself (but maybe triggers for some reason when you launch MCC).

**Comment by Superslim-anoniem** [comment]
Could it be something to do with mono?

**Comment by ORelio** [comment]
Yes, maybe.

**Comment by milutinke** [comment]
Seems like a Mono issue, since we do not use Mono anymore, I'll close the issue.
Try the latest release with .NET.
