### ISSUE TITLE
Add a way of logging in with tokens

### ISSUE THREAD

**Issue by TwixGamer00** [MCCTeam/Minecraft-Console-Client#2026]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Add the function to login with tokens so you can use easymc for example

**Comment by milutinke** [comment]
This could be used maliciously, and would give the MCC bad reputation.
Won't add.
