### ISSUE TITLE
Custom items afk farming

### ISSUE THREAD

**Issue by itsMaxra** [MCCTeam/Minecraft-Console-Client#2027]
hello i want to farm vote party keys from a server but its custom with texture pack and i cant receive them with mcc so maybe ad something like loading the server custom texture pack or if is there a way to fix this

**Comment by ORelio** [comment]
I'm not sure we cal help with custom items 🤔

**Comment by milutinke** [comment]
The MCC auto fakes the texture pack, as for detecting custom items, you can look at their NBT data and compare their names or properties they have.
