### ISSUE TITLE
Need help with the digging script

### ISSUE THREAD

**Issue by kysteno4ek** [MCCTeam/Minecraft-Console-Client#2029]
I have a script for digging works well - only the problem is when it drips a little moves its head and on the server where I play there is an AFC system and this bypasses this AFC system = I violate. What to do about it?.
[a.zip](https://github.com/MCCTeam/Minecraft-Console-Client/files/8774699/a.zip)
.

**Comment by ORelio** [comment]
Try setting `moveheadwhilewalking` to `false` in config:
https://github.com/MCCTeam/Minecraft-Console-Client/blob/17dbe10ff3c3fc344e7f6bfa82607340eebeb005/MinecraftClient/Resources/config/MinecraftClient.ini#L48
