### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Ultimatecreeper4** [MCCTeam/Minecraft-Console-Client#2031]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

1.18.2

### Expected Behavior

No spammed message

### Actual Behavior

![image](https://user-images.githubusercontent.com/106564658/171070133-f9cbee60-bfe2-49f1-83a4-1935c44bd0af.png)
This is in the console client

### Steps to Reproduce the bug

It seems to be only on hypixel. It seems to be getting information from what is seen. The spammed message does not actually appear in chat in a regular client.

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/106564658/171070841-69ecf4e3-acb8-45d0-b02a-58e45484294b.png)
This is wat it looks like in a regular client

### Device

Laptop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
See #177
