### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ItzMiracleOwO** [MCCTeam/Minecraft-Console-Client#2032]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.1

### Console Client Version

commit 6986902

### Expected Behavior

it should connect to the server
it worked this morning.

### Actual Behavior

![image](https://user-images.githubusercontent.com/76854136/171164424-102d0b24-dabf-4716-8266-262a236b5f5b.png)

### Steps to Reproduce the bug

connect to a server

### Attach screenshot here (If applicable)

-

### Anythings that could help diagnosing the bug

```txt
-
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

play.applecraftmc.org

**Comment by milutinke** [comment]
Can you try the latest build and report back?
