### ISSUE TITLE
Inventory Command Request/Idea

### ISSUE THREAD

**Issue by TomCammil** [MCCTeam/Minecraft-Console-Client#2036]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Whenever managing inventory. To me it seems that the only option you have, is to first click something in your inventory, making it hover. Then you select a new slot in your inventory/chet/pv that you want to place the hovering item in.

My point is, it would be very handy to have a "ShiftClick" feature/option, where it just stores selected items in a quick manner. There might already be something like this, but so far i only found the feature "/inventory 1 _**Click**_ 20" working, where "click" is the only clicking option you have.

An example of how a shiftclick feature would be helpful:
Imagine you have a script that receives items in a way. The script detects when the items are picked up, and in your inventory/hotbar. When it detects the new items, it opens a pv, and with the suggested "ShiftClick" feature, you could easily stash it all quickly by telling the script which slots to shiftclick, as the items will always land in the same slot as long as previous items are disposed before new ones come.

Without a "ShiftClick" feature, what you will have to do is make a long script like this: (As example, slot 1-10 is your hotbar, slot 11-20 is your pv/chest)

/inventory 1 click 1
/inventory 1 click 11
/inventory 1 click 2
/inventory 1 click 12
/inventory 1 click 3
/inventory 1 click 13
.. and so on.

This script moves 3 items from hotbar to the 3 first slots in your pv/chest.
The issue with a script like this, is that the next time you receive new items, it will attempt to stash these items in the slots where there already are items. This will basically make the script not work... With a ShiftClick feature, it will stash the selected items in whatever empty slot it can find in the pv.

### Suggest a possible solution

Explained above

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

**Comment by BruceChenQAQ** [comment]
Implemented in #2172
