### ISSUE TITLE
Help пж 

### ISSUE THREAD

**Issue by DARKSRG** [MCCTeam/Minecraft-Console-Client#2037]
Help please, I start the client, it works fine, but then I get kicked from the server for no particular reason.
Screenshots are attached.
![image](https://user-images.githubusercontent.com/103605226/172053604-c855ce5f-f2fe-4e93-abc9-25943910f25f.png)

**Comment by deosync** [comment]
включи гравитацию или отключи может поможет

**Comment by milutinke** [comment]
Also, try running the latest version, there have been a lot of bug fixes in the meantime.

**Comment by milutinke** [comment]
Try the latest build, if you have any issues, open the issue.
