### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by OskarRB051007** [MCCTeam/Minecraft-Console-Client#2038]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

# Minecraft Console Client v1.17.1

### Describe your problem

When i try and join a Modded server it says that forge is supported (1.8.9) but when i try and join the server it kicks me for not having the mods installed. Am i running a bad version? Is there a way to install the mods onto the console client? (i know how to do it normally so i do have the mods). Basically what i am saying where should i put my 'mods' folder and 'flans' folder if i am trying to join a server with said mods?

### Suggest a possible solution

Me to be able to join any server with mods (even with flans mod)

### Attach screenshot here (If applicable)

AppVeyor build 586, built on Thu 05/05/2022 from commit b3cc235
[MCC] [Settings] Loading Settings from /home/container/MinecraftClient.ini
Resolving minecraft-breakdown.net...
Found server mc.minecraft-breakdown.net:25565 for domain minecraft-breakdown.net
Cached session is still valid for SolOlieDK.
Retrieving Server Info...
Server is running Forge with 12 mods.
Server version : 1.8.9 (protocol v47, with Forge)
[MCC] Version is supported.
Logging in...
[MCC] Checking Session...
[MCC] Server was successfully joined.
Type '/quit' to leave the server.
[MCC] Disconnected by Server :
[MCC] Unfortunately you don't have all required mods for this server.
To enjoy all our custom features please install our client mod:

www.minecraft-breakdown.net/join

It will take a few minutes only! See you in-game.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.

### Minecraft Version

1.8.9

### Device

Other

### Operating System

Linux

**Comment by milutinke** [comment]
Sadly we do not have a way of supporting Forge mods, neither a way of spoofing that we have some installed.
If you know any programming feel free to contribute.
