### ISSUE TITLE
[Idea] 

### ISSUE THREAD

**Issue by VovaPutinGta** [MCCTeam/Minecraft-Console-Client#2040]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

latest

### Describe your problem

Hi! 
I'll get right to the point, when I try to start automatic fishing, I get the message "[ERROR] Inventions are currently not handled for that MC version.
[ERROR] Entities are currently not handled for that MC version." on one of the forums, I read that inventory processing is not supported on 1.18, so when will this feature be supported?

### Minecraft Version

1.18.2

### Device

Desktop

### Operating System

Windows

**Comment by Daenges** [comment]
This project currently lacks contributors. As there is noone actively working on the 1.17+ support, it may take some time.

If your server supports older versions you can set the client version to 1.16.5, where everything is supported.

**Comment by ORelio** [comment]
See 1.17 support: #1629
