### ISSUE TITLE
[BUG]  Cant move

### ISSUE THREAD

**Issue by adabugra** [MCCTeam/Minecraft-Console-Client#2041]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17.2

### Console Client Version

Latest

### Expected Behavior

Move

### Actual Behavior

I cant move

### Steps to Reproduce the bug

I cant move the bot when i try to move it, it says  [MCC] Failed to compute a safe path to {0}. Try -f parameter to allow unsafe movements. but when i try with -f it says Cannot move in that direction. How can i fix this

### Attach screenshot here (If applicable)

![Ekran görüntüsü 2022-06-07 154747](https://user-images.githubusercontent.com/57899270/172382939-2c565c91-5014-403a-a621-36520252c52e.png)

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Fixed.
