### ISSUE TITLE
[Idea] inventory bypass

### ISSUE THREAD

**Issue by i7vlo** [MCCTeam/Minecraft-Console-Client#2050]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

how i can cancel inventory packet ?

**Comment by ORelio** [comment]
When an inventory opens, it's the server who decides this, and tells your game "ok here is an inventory that opened"
You can decline (close) that using `/inventory container close`
