### ISSUE TITLE
AutoClicker

### ISSUE THREAD

**Issue by gggvvbh** [MCCTeam/Minecraft-Console-Client#2052]
Hi, can i use auto clicker in your client? If yes, how?

**Comment by ORelio** [comment]
There is no simple "auto click" that we can do, see #1604 for more info.
However depending on what you want to click exactly, that may or may not be doable.

**Comment by JackC-23** [comment]
> There is no simple "[auto click](https://opautoclicker.in)" that we can do, see #1604 for more info. However depending on what you want to click exactly, that may or may not be doable.
okay. However, we can try to use auto click on continuous clickable tasks.
