### ISSUE TITLE
[Idea] I'd like to create a script that sneaks and right clicks to open an inventory, and depending on the inventory's name clicks on an item

### ISSUE THREAD

**Issue by iamkurcze** [MCCTeam/Minecraft-Console-Client#2055]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

I have never written anything in c#, but i do code in java so i think just a little suggestion will help me a lot. I'd like to make a script that first of all opens a gui (sneak & RMB), then it checks whats the inventorys name... and finally with an swich decides which item type should it click. For example: Sugar Cane -> click sugar cane, Spider Eye -> Click Spider eye.

### Suggest a possible solution

...

### Attach screenshot here (If applicable)

...

### Minecraft Version

1.16.5

### Device

Raspberry Pi

### Operating System

Linux

**Comment by milutinke** [comment]
Closing in favor of #2204
