### ISSUE TITLE
somone please help me 

### ISSUE THREAD

**Issue by budubean** [MCCTeam/Minecraft-Console-Client#2058]
my client won't let me play on a specific server I wanna play it says server is running forge without mods and server version: Velocity 1.7.2- 1.19 (protocol v759) and cannot connect to the server but it lets me login to another server anyone know how I can fix thank you

**Comment by ORelio** [comment]
You may attempt to manually set the desired version in config, some servers allow multiple versions:
https://github.com/MCCTeam/Minecraft-Console-Client/blob/17dbe10ff3c3fc344e7f6bfa82607340eebeb005/MinecraftClient/Resources/config/MinecraftClient.ini#L26

**Comment by budubean** [comment]
> You may attempt to manually set the desired version in config, some servers allow multiple versions:
> 
> https://github.com/MCCTeam/Minecraft-Console-Client/blob/17dbe10ff3c3fc344e7f6bfa82607340eebeb005/MinecraftClient/Resources/config/MinecraftClient.ini#L26

thank you
