### ISSUE TITLE
[I want to log in to the console client by receiving a code by email] 

### ISSUE THREAD

**Issue by titlo10** [MCCTeam/Minecraft-Console-Client#2062]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

To log in to the system, i need to write a username and password, but I want to ask if it is possible to log in by receiving a code by email and entering this code into the console client. I bought an account without a password from microsoft, I can log in only after receiving the code in the email

### Suggest a possible solution

Add this feature to the new version of the console client

### Minecraft Version

1.19.x

### Device

Desktop

### Operating System

Windows

**Comment by BruceChenQAQ** [comment]
Using the browser login method may solve your problem.

``method=browser       # Microsoft Account sign-in method. mcc OR browser``

**Comment by milutinke** [comment]
To my knowledge this can't be implemented, use the browser login method.
