### ISSUE TITLE
Failed to check session

### ISSUE THREAD

**Issue by jcodyparker** [MCCTeam/Minecraft-Console-Client#2064]
Is this a Mojang issue, or mcc issue? Can't log back in to any of my accounts even on latest dev build

![image](https://user-images.githubusercontent.com/90956620/178348182-214a089f-518e-42ba-9691-162cf7676def.png)

**Comment by breadbyte** [comment]
Failed to check session means that the server is unable to authenticate your session against mojang servers, or you are trying to connect to an online server in offline mode.

Delete your `SessionCache.ini` and retry logging in. If you are migrated, please change your login method in the `MinecraftClient.ini` to `microsoft`, and try again.

**Comment by jcodyparker** [comment]
I tried deleting SessionCache.ini already, none of my accounts work including my main migrated account. Nothing was ever changed in my config also. I have one account still running, but once it closes I won't be able to open it again. I've been trying to login all day and it hasn't worked in about 8 hours or longer.

**Comment by jcodyparker** [comment]
Actually now it's working fine on my VPS with my main account, but on my main PC at home I cannot connect with mcc still. Normal minecraft launcher works fine still. The same account that works fine on my VPS doesn't work on my home PC

**Comment by jcodyparker** [comment]
It only doesn't work on unmigrated accounts. Did we completely lose support for unmigrated now? They all stopped working the same day

**Comment by jcodyparker** [comment]
> 

Oh hi! never thought I'd see a friend on here xD

All of my migrated accounts work fine but none of the unmigrated. They were just working the other day then randomly all wouldn't open the next day

**Comment by jcodyparker** [comment]
> > It only doesn't work on unmigrated accounts. Did we completely lose support for unmigrated now? They all stopped working the same day
> 
> Hi @jcodyparker hehe I'm having trouble too so came here to look and saw your name and had to say hiiii! <3

Oh hi! Never thought I'd see a friend on here xD

All of my migrated accounts work still but none of the unmigrated ones. They worked fine the other day, the next day none of them work.

**Comment by breadbyte** [comment]
If you can give us debug logs of the entire login process (with session tokens and other sensitive info trimmed), it would be helpful!

I am unable to test if unmigrated accounts are broken completely as I only have one minecraft account and I have migrated it.

**Comment by jcodyparker** [comment]
Debug log only shows this

### Log started at 2022-07-25 22:22:27 ###
Version is supported.
Logging in...
[DEBUG] Crypto keys & hash generated.
Checking Session...
Login failed :
Failed to check session.

**Comment by BruceChenQAQ** [comment]
Try to ping ``sessionserver.mojang.com``, will there be high latency?
