### ISSUE TITLE
[BUG]checking sesssion login failed failed to check session autoreloading

### ISSUE THREAD

**Issue by Zoid4000** [MCCTeam/Minecraft-Console-Client#2065]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

newest

### Expected Behavior

checking sesssion login failed failed to check session autoreloading

### Actual Behavior

checking sesssion login failed failed to check session autoreloading

### Steps to Reproduce the bug

1. no thing it just does this
2. 
3. 

### Attach screenshot here (If applicable)

![asdasdas](https://user-images.githubusercontent.com/41523702/179157570-2d3dd6c4-6ef1-4fdd-8145-0d302a0298e0.PNG)

### Anythings that could help diagnosing the bug

```txt
i have no clue what the problem is
```

### Device

Laptop

### Operating System

Windows

**Comment by breadbyte** [comment]
Go to your `MinecraftClient.ini` and try changing your `mcversion` to `auto`.

**Comment by Zoid4000** [comment]
tried that still does noithing

**Comment by TeeDDeeT** [comment]
i have the same issue, and don't know how to fix it

**Comment by LuckiestOne23** [comment]
I can confirm that this happens on unmigrated accounts. My migrated one seems to work.

**Comment by milutinke** [comment]
Migrate your account.
The non-migrated accounts will be disabled by Mojang.
