### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Splarkszter** [MCCTeam/Minecraft-Console-Client#2066]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.0

### Console Client Version

1.19-pre-release

### Expected Behavior

Be able to comprehend and set configs

### Actual Behavior

Or i don't understand because lack of info in the """documentation""" called [user-manual ](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config) or i'm doing something wrong.

by 'fill in the `accountlist` field in INI file' i guess it is on the `MinecraftClient.ini` right?

i have this on the `MinecraftClient.ini`

```
[accountlist]
Bot0,BOT_Splark_0,-
Bot1,BOT_Splark_1,-

botowners=Splarkszter

[serverlist]
s1,*serverip*

ignorekickmessage=true

[ScriptScheduler]
enabled=true
tasksfile=test.ini
```

and i don't know how to use `debugmessages=true` because there is nothing

if i type the command `reconnect` it does reconnect but `ignorekickmessage=true` does not makes it reconnect on disconect. (image2)

i have that and only the script scheduler part seems to want to do something

### Steps to Reproduce the bug

n/a

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/90066319/179284792-4d9daccf-8e68-40b4-82f1-7680bd1b90fb.png)
 
![image](https://user-images.githubusercontent.com/90066319/179296614-55245054-b737-4045-8ccb-105f0d5f4db9.png)

### Anythings that could help diagnosing the bug

```txt
n/a
```

### Device

Desktop

### Operating System

Windows

**Comment by breadbyte** [comment]
Is this your entire `MinecraftClient.ini` file? If so, save everything that you have currently and let the application generate a new one with all the complete options available (delete your current one and just run the application).

`ignorekickmessage=true` is an option that is tied to the `[AutoRelog]` settings section. Regenerating the file should allow you to see the option to enable AutoRelog in the configuration file.

**Comment by Splarkszter** [comment]
Oh, strange. I don't know why it did not generate before.

It works fine now. thanks!!!

**Comment by Splarkszter** [comment]
One more thing. is there a way to skip the initial login to have loaded the accounts instead of having dummy data?

**Comment by breadbyte** [comment]
You can pass in a username and password as a command line argument when you start the application.

A complete list of arguments can be found [here.](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config#command-line-usage)

You can then call `MinecraftClient.exe` from a batch file or a powershell script using command line arguments to bypass the initial login process.

**Comment by Splarkszter** [comment]
thanks again! made it work. nice!
