### ISSUE TITLE
[BUG] /sneak vs antiafk 

### ISSUE THREAD

**Issue by truong0235** [MCCTeam/Minecraft-Console-Client#2077]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

latest

### Expected Behavior

when antiafk sending /sneak command, the player will sneak

### Actual Behavior

the player does nothing

### Steps to Reproduce the bug

1. set /sneak command in antiafk 
2. join a server
3. see result (using another account to see)

### Anythings that could help diagnosing the bug

```txt
[AntiAFK]
# Send a command on a regular basis to avoid automatic AFK disconnection
# /!\ Make sure your server rules do not forbid anti-AFK mechanisms!
enabled=true
delay=600 #10 = 1s
command=/sneak
```

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
You should use just `sneak` without `/`
