### ISSUE TITLE
[BUG] I can not connect to 1.19 Server

### ISSUE THREAD

**Issue by Ege9** [MCCTeam/Minecraft-Console-Client#2079]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19

### Console Client Version

Latest

### Expected Behavior

I was expecting for the Console Client to connect to the 1.19 server.

### Actual Behavior

Client 1.19 is not connecting to the server.
It says:
Server version : Purpur 1.19 (protocol v759)
Cannot connect to the server : This version is not supported !
Why can't it connect to 1.19 server? Is there a way to make it work?

### Steps to Reproduce the bug

1. 
2. 
3. 

### Attach screenshot here (If applicable)

![a](https://user-images.githubusercontent.com/110056150/181078413-409da198-a39a-43ed-bcf9-21d6da415d12.PNG)

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

play.craftkolik.com

**Comment by milutinke** [comment]
There is no need to make an issue for a version that is not even in the repository and that is currently being worked upon.
In my repository it says that it is experimental and might not function as intended.
A lot of things still need to be changed for it to be stable and working.
Report any bugs you find in #2053
