### ISSUE TITLE
regex help

### ISSUE THREAD

**Issue by WolfgamingWG** [MCCTeam/Minecraft-Console-Client#2081]
So im trying to make the console client detect my private messages, made the regex for it, tested it with regex101 and put myself as owner in config but it still doesn't work?

What im trying to detect: [MEMBER name -> me] message
The regex i made: `^\[[a-zA-Z0-9_]+ ([a-zA-Z0-9_]+) -> me\] (.+)$`
Regex link: https://regex101.com/r/XvzqbD/1
Response: not even sending an error msg or saying anything in the console itself.

Anyone who can help me with this?

**Comment by milutinke** [comment]
Try using the latest release as the settings format has been changed.
Reopen the issue if you still have it.
