### ISSUE TITLE
[BUG] this version is not supported

### ISSUE THREAD

**Issue by Saidas25** [MCCTeam/Minecraft-Console-Client#2085]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [x] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19

### Console Client Version

Latest

### Expected Behavior

i tried to connect to a minecraft server (version 1.19) but it did not let me it said Cannot connect to the server : This version is not supported ! i typed 1.19 in Server version but it still did not let me join

### Actual Behavior

it should let me join but it does not

### Steps to Reproduce the bug

1. idk
2. idk
3. idk

### Attach screenshot here (If applicable)

![Screenshot (666)](https://user-images.githubusercontent.com/91024239/181934270-2d647b5a-2721-4f93-b3a4-a921870c29b0.png)

### Anythings that could help diagnosing the bug

```txt
i don't know
```

### Device

Laptop

### Operating System

Windows

**Comment by breadbyte** [comment]
1.19 is not officially supported yet.

You can get a development build that supports 1.19 [here.](https://github.com/MCCTeam/Minecraft-Console-Client/issues/2053#issuecomment-1196534899)

**Comment by Saidas25** [comment]
i joined the server i wanted but after i did /register it kicked me and said [MCC] Disconnected by Server :
[MCC] Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(32) + length(8) exceeds writerIndex(32): PooledUnsafeDirectByteBuf(ridx: 32, widx: 32, cap: 32)
Not connected to any server. Use '/help' for help.

**Comment by Saidas25** [comment]
how do i fix that?

**Comment by Saidas25** [comment]
it kicks me after i say anything

**Comment by Saidas25** [comment]
still waiting for an answer...

**Comment by breadbyte** [comment]
We don't know how to fix this error right now as this is new to us.

The error message implies that it is an error with the server itself.

For us to be able to fix the error, we need to investigate the issue.
