### ISSUE TITLE
Help with an error while running custom script

### ISSUE THREAD

**Issue by JayDeeper** [MCCTeam/Minecraft-Console-Client#2086]
Hey basically a mate and me wrote a script in python for a server and it was working all fine no errors of bugs and we stopped playing for a while but i started playing again and everytime i try and run the script i get this error

Unhandled Exception: System.InvalidOperationException: Cannot see if a key has been pressed when either application does not have a console or when console input has been redirected from a file. Try Console.In.Peek.

   at System.Console.get_KeyAvailable()

   at MinecraftClient.Program.HandleFailure(String errorMessage, Boolean versionError, Nullable`1 disconnectReason)

   at MinecraftClient.Program.InitializeClient()

   at MinecraftClient.Program.Main(String[] args)

when i launch mcc normally it works if someone wants to help out i can send them the code also i should point out the script works on my friends pc but not mine

**Comment by breadbyte** [comment]
Are you running the latest exe release or did you build from source?

**Comment by JayDeeper** [comment]
> Are you running the latest exe release or did you build from source?

latest exe

**Comment by JayDeeper** [comment]
> Are you running the latest exe release or did you build from source?

hey just wondering if your still up for helping me

**Comment by breadbyte** [comment]
Sure! I was just out of town for a bit so I was unavailable for a while.

I'll get to your request in a bit.
Can I get a copy of your script?

**Comment by JayDeeper** [comment]
> Sure! I was just out of town for a bit so I was unavailable for a while.
> 
> I'll get to your request in a bit. Can I get a copy of your script?
nw i really apreciate your help is there a way i can dm you on here or should i just upload it to pasetbin?

**Comment by JayDeeper** [comment]
> Sure! I was just out of town for a bit so I was unavailable for a while.
> 
> I'll get to your request in a bit. Can I get a copy of your script?

nw i really apreciate it here is a pastebin link https://pastebin.com/m83B2dnN all it is is basically a chat reader so i get alerts for certain things should be easy enough to understand it

**Comment by breadbyte** [comment]
I can't seem to replicate this issue, are you using any specific console other than the windows command prompt?
What are the steps you usually do when you run this code?

**Comment by JayDeeper** [comment]
> I can't seem to replicate this issue, are you using any specific console other than the windows command prompt? What are the steps you usually do when you run this code?

No i normally run it through command prompt or idle if im testing something new, my mate of mine cant replicate it either we were thinking its something to do with a .net framework but ive reinstalled most. This is what my friend said "The error is caused by the Popen Because we're redirecting the stdin to PIPE But there shouldn't be an error in the first place"

**Comment by breadbyte** [comment]
You can try a different terminal like [Windows Terminal](https://aka.ms/terminal) or [Alacritty](https://github.com/alacritty/alacritty) and see if it makes a difference.

**Comment by ObscenityIB** [comment]
Found this issue while having the same problem.

Looks like it is caused by MCC trying to force a read from a console, when a console doesn't exist (eg. running in a script).

https://github.com/MCCTeam/Minecraft-Console-Client/blob/ca966a464c2262a7b51f6395fe901b12b832e7ee/MinecraftClient/Program.cs#L772-L773

Recompiling with these lines commented out has fixed the issue for me.

**Comment by breadbyte** [comment]
> Found this issue while having the same problem.
> 
> Looks like it is caused by MCC trying to force a read from a console, when a console doesn't exist (eg. running in a script).
> 
> https://github.com/MCCTeam/Minecraft-Console-Client/blob/ca966a464c2262a7b51f6395fe901b12b832e7ee/MinecraftClient/Program.cs#L772-L773
> 
> Recompiling with these lines commented out has fixed the issue for me.

That's odd, `HandleFailure` shouldn't get triggered when running on a script.
Good catch, thanks.
