### ISSUE TITLE
[Idea] 

### ISSUE THREAD

**Issue by ling-luan** [MCCTeam/Minecraft-Console-Client#2089]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

1.18.2 Is it supported Forge?

Server is running Forge without mods.
Server version : 1.18.2 (protocol v758)
[MCC] Version is supported.
Logging in...
[MCC] Login failed :
[MCC] This server has mods that require Forge to be installed on the client. Contact your server admin for more details.

### Minecraft Version

1.18.2

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Unfortunately we do not have a mechanism in place to spoof mods for the time being.

**Comment by milutinke** [comment]
Try setting your branding to `forge` in `MinecraftClient.ini`
The MCC should spoof installed mods by default.
