### ISSUE TITLE
[BUG] Disconnects with the reason - disconnect.timeout

### ISSUE THREAD

**Issue by titlo10** [MCCTeam/Minecraft-Console-Client#2098]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.x

### Console Client Version

Latest

### Expected Behavior

Connection without any problems.

### Actual Behavior

After connecting to the server, after a few minutes it disconnects from the server with the reason **disconnect.timeout**

### Steps to Reproduce the bug

1. I turned on **debugmessages**=true, but it doesn't show anything
2. I wrote to the technical administrator of the server where I play
3. 

### Anythings that could help diagnosing the bug

```txt
I turned on debugmessages=true, but it doesn't show anything. I also contacted the technical administrator of the server where I'm playing, he told me that the client incorrectly receives or incorrectly processes keepalive
```

### Device

Desktop

### Operating System

Windows

**Comment by titlo10** [comment]
I contacted the technical administrator of the server where I'm playing, he told me that the client incorrectly receives or incorrectly processes keepalive

**Comment by BruceChenQAQ** [comment]
Can you provide the server address? 
After we switched to .NET5, a performance issue https://github.com/MCCTeam/Minecraft-Console-Client/issues/2082 was created, which should be fixed in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2124.

You can try logging into the server using the old version:
https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220506-20

**Comment by BruceChenQAQ** [comment]
There may be the same problem as #2144.
You can try using this build to test if the problem still exists: https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/bugfix_pre_build

**Comment by milutinke** [comment]
Try the latest build and report back
