### ISSUE TITLE
[BUG]  "Login Failed" on VPS, works fine on Main PC

### ISSUE THREAD

**Issue by jcodyparker** [MCCTeam/Minecraft-Console-Client#2099]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

1.17.1

### Expected Behavior

Login

### Actual Behavior

Doesn't login without using Session Cache from my Main PC

### Steps to Reproduce the bug

1. Log in
2. 
3. 

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/90956620/184245681-06222e25-0c2d-4d2a-905f-45752accb348.png)

### Anythings that could help diagnosing the bug

```txt
Two of my accounts, it doesn't let me login on my VPS without taking the Session Cache from my main PC and copying it over to the VPS. If I delete the Session Cache on the VPS, it won't log in and gives the error in the screenshot.

The other two accounts work perfectly fine and never have this issue.

How do I fix this? It's very annoying because if for some reason it crashes or auto reconnects, I have to start mcc on main PC and copy the Session Cache all over again. I don't understand why 2 of them don't work, but my other 2 accounts work perfectly fine.
```

### Device

VPS

### Operating System

Windows

**Comment by jcodyparker** [comment]
Bump

**Comment by milutinke** [comment]
Are you trying to connect ti a 1.16.5 server from a 1.17.1?
Also, enable `debugmessages` in `MinecraftClient.ini` and provide the full log. (PS: Redact an auth token if there is one displayed).

**Comment by DefeatedZoro** [comment]
sometimes for security, microsoft may send you an email to confirm its you, if they do, click the link to verify ip and try again

**Comment by jcodyparker** [comment]
> 

It was this, thank you!

**Comment by jcodyparker** [comment]
> sometimes for security, microsoft may send you an email to confirm its you, if they do, click the link to verify ip and try again

It was this, thank you!
