### ISSUE TITLE
[Idea] 

### ISSUE THREAD

**Issue by onure9e** [MCCTeam/Minecraft-Console-Client#2100]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest (20220506-20: CalculatePath: Fix offset calculation, improve approaching (#2013))

### Describe your problem

Hello i'm using latest version of minecraft console client and some servers has drop test(for antibot) but minecraft console client dosn't have gravity

sorry for typos

### Minecraft Version

1.8.8

### Device

VPS

### Operating System

Windows

**Comment by onure9e** [comment]
In short, it might be good to add gravity.

**Comment by breadbyte** [comment]
You can enable this by setting `terrainandmovements` to `true` in the `MinecraftClient.ini` config file.

It is only implemented for Minecraft 1.16 and lower, however.

**Comment by onure9e** [comment]
Thanks
