### ISSUE TITLE
[Idea] Can I Be Developer?

### ISSUE THREAD

**Issue by epsseniyer** [MCCTeam/Minecraft-Console-Client#2101]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

@latest

### Describe your problem

I'm An Senior on low end and C#

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Fork the project, make a change that you think it's an improvement, test it out and open a pull request.
As simple as that.

**Comment by ORelio** [comment]
After some successfully merged pull requests we can consider giving you write access but for now please send contributions through pull requests. Thanks for your interest in improving MCC 🙂
