### ISSUE TITLE
[Idea] Documentation replacement in the main repository

### ISSUE THREAD

**Issue by milutinke** [MCCTeam/Minecraft-Console-Client#2108]
Greetings,

Since we now have a documentation [website](https://mccteam.github.io/), which is hosted in a separate [repository](https://github.com/MCCTeam/MCCTeam.github.io), 
I think that we should remove the [config/README](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config#minecraft-console-client-user-manual) from the main repository in favor of the website.
Of course, this should be done when the documentation on the website is updated to include more examples and missing things (currently there are only few things missing, like the list of contributors, the license, hangman, examples for `accountlist` and `serverlist`).
This would prevent making mistakes (in a form of having 2 different versions of documentation that do not match) and duplication.

**Comment by ORelio** [comment]
I agree with this. Let me know when everything is moved.
Regarding contributor list, maybe we can just use https://github.com/MCCTeam/Minecraft-Console-Client/graphs/contributors now.

**Comment by milutinke** [comment]
> I agree with this. Let me know when everything is moved. Regarding contributor list, maybe we can just use https://github.com/MCCTeam/Minecraft-Console-Client/graphs/contributors now.

Already using that in the Contributing section, so yeah, it's better than manually typing them out.
Also, I think that the main README should include the new short description from the documentation website and a logo, aka. putting the emphasis on Java Edition, since we're not supporting Bedrock.
Maybe have a logo in the middle, and links bellow it.

Example:
---

<div align="center">

<img src="https://i.pics.rs/LLDhE.png" alt="Logo"/>

# Minecraft Console Client (MCC)

[Documentation]() | [Installation]() | [Configuration]() | [Usage]()
 
<br />
</div>

## **About**

**Minecraft Console Client (MCC)** is a lightweight cross-platform open-source Minecraft TUI client for **Java** edition that allows you to connect to any Minecraft Java server, send commands and receive text messages in a fast and easy way without having to open the main Minecraft game.

**Comment by ORelio** [comment]
Looks good to me! Feel free to proceed with a commit or pull request 🙂

**Comment by milutinke** [comment]
Ported everything to the website, I think I've not missed anything.
I'll open a PR soon with the updated README.md
