### ISSUE TITLE
[BUG] setrnd and %variable% not working on autorespond

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2115]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

latest

### Expected Behavior

[Match]
match=Ben, 
actionother=setrnd variable Yes No Ohohohoho Ahahahh
actionother=send %variable%
ownersonly=false
cooldown=0
========================
result

<Ben228>: No
<Ben228>: Yes
<Ben228>: Ohohohoho
<Ben228>: Ahahahh

### Actual Behavior

[Match]
match=Ben, 
actionother=setrnd variable Yes No Ohohohoho Ahahahh
actionother=send %variable%
ownersonly=false
cooldown=0
========================
result

<Ben228>: %variable%
<Ben228>: %variable%
<Ben228>: %variable%
<Ben228>: %variable%

### Steps to Reproduce the bug

1. on autorespond
2. edit matches.ini for some %variable%
3. ready your autorespond writes to the chat instead of a random phrase or text %variable%

### Device

Laptop

### Operating System

Windows

**Comment by ORelio** [comment]
You cannot put the same field several times.
What happens here is that `actionother` is loaded twice and the second one will override the first.
So your `setrnd` command will never run.
Use `action=script yourscript.txt` and put the commands there.

**Comment by deosync** [comment]
thx
