### ISSUE TITLE
[BUG] Text Colours Are Gone :(

### ISSUE THREAD

**Issue by agitationswapping** [MCCTeam/Minecraft-Console-Client#2122]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19

### Console Client Version

Latest

### Expected Behavior

Previously, I had beautiful coloured output in past versions.

### Actual Behavior

However, at the moment, the output I get from the console doesn't seem to have any colour and instead has the raw formatting.

It makes it a lot harder to read the output.

### Steps to Reproduce the bug

1. Download MinecraftClient.exe from here: https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220821-34
2. Configure MinecraftClient.ini to connect to a server with coloured text.
3. Launch MinecraftClient.exe

### Attach screenshot here (If applicable)

![TroublshootNoColours](https://user-images.githubusercontent.com/111817552/186038251-00308fbd-244e-42e4-b4d7-be13f707c79b.png)

### Device

Desktop

### Operating System

Windows

**Comment by kvr25565** [comment]
Windows 7's cmd doesn't support colors. Install cmder

**Comment by agitationswapping** [comment]
Why did it work before on Windows 7?

**Comment by agitationswapping** [comment]
Sounds like you're saying the console is now "broken" by default on Windows 7. The user can't avoid having "colour gibberish" unless they (1) find this thread or somehow know the technical implications of the colour scheme change, (2) have administrative access and permission to install to the current PC they're using, and (3) feel comfortable installing a custom command line software most people have never used.

The console supported windows native before so all the code should still exist for this. How hard is it to have a setting and support both vt100 and windows native? Or is that a lot of added overhead/complexity?

Ideally, you could default to windows native for Windows 7 and let power users pick a different colour scheme if they know what they're doing.

**Comment by breadbyte** [comment]
We can certainly add checks for Windows 7 and 8 and change the mode accordingly.

**Comment by BruceChenQAQ** [comment]
![image](https://user-images.githubusercontent.com/26017411/207525061-fff5c76c-f841-418a-b005-504fb1f08296.png)

Support for older color schemes has been added in the latest release.

For obsolete terminals, you may need to change these settings:
```toml
[Main.Advanced]
EnableEmoji = false

[Console.General]
ConsoleColorMode = "legacy_4bit"

[Console.CommandSuggestion]
Use_Basic_Arrow = true
```
