### ISSUE TITLE
[Idea] Add follow player function

### ISSUE THREAD

**Issue by kvr25565** [MCCTeam/Minecraft-Console-Client#2125]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1.19 latest

### Describe your problem

Following player/entity 

### Suggest a possible solution

Add /follow or /move follow command

### Minecraft Version

1.16.5

### Device

Desktop

### Operating System

Windows

**Comment by deosync** [comment]
ye I need this

**Comment by milutinke** [comment]
It's a cool idea.
I'll be looking into this after #2120, #2123, #2324 are merged.

**Comment by milutinke** [comment]
Implemented in #2174
