### ISSUE TITLE
I can not open the Console Client.

### ISSUE THREAD

**Issue by Ege9** [MCCTeam/Minecraft-Console-Client#2127]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

Latest

### Expected Behavior

I expected to be able to open the Console Client

### Actual Behavior

When i download the latest Console Client version and click MinecraftClient.exe, it wont open. A command prompt appears for a milisecond, and then nothing happens.

### Steps to Reproduce the bug

What

### Device

Laptop

### Operating System

Windows

**Comment by breadbyte** [comment]
Please install [.NET 6](https://dotnet.microsoft.com/en-us/download).

**Comment by SarpYilmax** [comment]
Same Ege9
