### ISSUE TITLE
[BUG] MCC Doesn't work with Mono but works fine with Dotnet

### ISSUE THREAD

**Issue by kvr25565** [MCCTeam/Minecraft-Console-Client#2128]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

Latest

### Expected Behavior

MCC works with mono finely

### Actual Behavior

Cannot open assembly 'MinecraftClient': File does not contain a valid CIL image.

### Steps to Reproduce the bug

1. Download MCC
2. Download Mono
3. mono MinecraftClient

### Anythings that could help diagnosing the bug

```txt
When i open MCC with dotnet it works fine but when i open MCC with mono it says "Cannot open assembly 'MinecraftClient': File does not contain a valid CIL image." I use arch linux x64. I also tested it on Pi and it gave the same error message
```

### Device

VPS

### Operating System

Linux

**Comment by breadbyte** [comment]
Mono is no longer required, please install [.NET 6](https://dotnet.microsoft.com/en-us/download) instead.

**Comment by kvr25565** [comment]
> Mono is no longer required, please install [.NET 6](https://dotnet.microsoft.com/en-us/download) instead.

But what if i can't install .NET

**Comment by milutinke** [comment]
> > Mono is no longer required, please install [.NET 6](https://dotnet.microsoft.com/en-us/download) instead.
> 
> But what if i can't install .NET

Then MCC won't work or you need to use an older version that runs on NET 4.8, but you then can't play on 1.19
Alternative would be using Docker

**Comment by ORelio** [comment]
You can install .NET 6 to a wider range of systems, not just Windows but now also macOS and Linux:
https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by kvr25565** [comment]
> You can install .NET 6 to a wider range of systems, not just Windows but now also macOS and Linux: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

I can't install it on termux

**Comment by ORelio** [comment]
Since you're mentioning Termux, see also #2145

**Comment by milutinke** [comment]
> > You can install .NET 6 to a wider range of systems, not just Windows but now also macOS and Linux: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
> 
> I can't install it on termux

I've figured out a way to do it, see #2145 or [the documentation page](https://mccteam.github.io/docs/guide/installation.html#running-on-android).
I'll be closing this Issue in favor of that one, since the MCC does not work in Mono anymore.
