### ISSUE TITLE
[Question] mine help

### ISSUE THREAD

**Issue by Muharrem652** [MCCTeam/Minecraft-Console-Client#2131]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

v1.19

### Describe your problem

I couldn't run MineCube.cs and Cobblestone Miner.cs, can you tell me how to get them working? Show the screen better by sharing.
discord: !değişik#3416

### Minecraft Version

1.12.2

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Please use English.

**Comment by Muharrem652** [comment]
> Please use English.

fix

**Comment by milutinke** [comment]
First you need to enable `terrainhandling`, then you can use the following command for Minecube:
`/mine x y z` or `/mine x1 y1 z1 x2 y2 z2` for mining an area.
Example: `/mine 145 72 207`

For Cobblestone Miner, in the `CobblestoneMiner.cs` you find the following code:
```csharp
// === CONFIG - REPLACE COBBLESTONE LOCATION x y z VALUES HERE ===
// You need to stand in front of the cobblestone block to mine
// Also make sure the Cobblestone will regenerate e.g. using water and lava
Location cobblestone = new Location(x, y, z);
// === END OF CONFIG ===
```

In `new Location(x, y, z);`, replace `x`, `y`, `z` with coordinates of the block which you want to mine.
Example:
```csharp
// === CONFIG - REPLACE COBBLESTONE LOCATION x y z VALUES HERE ===
// You need to stand in front of the cobblestone block to mine
// Also make sure the Cobblestone will regenerate e.g. using water and lava
Location cobblestone = new Location(2546, 65, 1305);
// === END OF CONFIG ===
```

**Comment by Muharrem652** [comment]
> 

Can I add diamond gold and similar mines and coordinates in CobblestoneMiner.cs

**Comment by milutinke** [comment]
> > 
> 
> Can I add diamond gold and similar mines and coordinates in CobblestoneMiner.cs

Yes you can, but for that it's better using [OreMiner](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/config/ChatBots/OreMiner.cs)

If you want to do it `CobblestoneMiner`, in the `Update` function, you can add the following:
```csharp
case Material.DiamondOre:
    DigBlock(cobblestone);
    break;
```

Here is the full list of available materials: [https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Material.cs](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Material.cs)

**Comment by Muharrem652** [comment]
> 

thx
