### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by miyatatakeshi** [MCCTeam/Minecraft-Console-Client#2132]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

Latest 1.19

### Expected Behavior

Low cpu usage (like %1 or 2).

### Actual Behavior

Very high cpu usage.

### Steps to Reproduce the bug

1. Nothing anything special.
2. Just running the client.
3. Voila!

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/75170571/187095965-db1af175-7516-4e42-8ff1-d847fc2a7564.png)

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Do you have terrain and movements enabled?
Also, this could be #2082.

**Comment by miyatatakeshi** [comment]
It is disabled. I was using it  just fine like a month ago and client wasn't using more than 2%. I just reinstalled it with newer version and this happened.

**Comment by milutinke** [comment]
> It is disabled. I was using it just fine like a month ago and client wasn't using more than 2%. I just reinstalled it with newer version and this happened.

Most likely it's the above mentioned bug, I think that BruceChan has fixed it in one of his newer pull requests, he also did some major optimizations, so when that gets merged you will have better performance.
Also, try updating your .NET to a newer version, could be a specific bug on that version.
For me the CPU usage is normal for .NET 6.0.302

**Comment by BruceChenQAQ** [comment]
Should be fixed in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2124

**Comment by BruceChenQAQ** [comment]
After updating to .NET5 it is no longer possible to use CryptoStream directly from the standard library (#2082 ), the current version uses the BouncyCastle library.

In #2124 , I rewrote that part of the code, that will speed up the encryption and decryption process on supported devices using SSE2 and AES-NI instruction set, which should achieve a performance not worse than the old version.

**Comment by miyatatakeshi** [comment]
Installed May 5th version for testing and this is the result. Working fine.
![image](https://user-images.githubusercontent.com/75170571/187235237-c7d3cdf6-4602-455b-b979-10aedc970556.png)
Lastly I'm using .NET 6.0.7

**Comment by milutinke** [comment]
> Installed May 5th version for testing and this is the result. Working fine. ![image](https://user-images.githubusercontent.com/75170571/187235237-c7d3cdf6-4602-455b-b979-10aedc970556.png) Lastly I'm using .NET 6.0.7

That is the version which is running on .NET 4.8, so it's the issue 2082, since it has appeared after the update to .NET 5.
Pull requests will probably be merged soon, for now you could use the older version, but 1.19 is not supported in it.
