### ISSUE TITLE
[BUG] Can't run client on ubuntu 22.04

### ISSUE THREAD

**Issue by Vazgen005** [MCCTeam/Minecraft-Console-Client#2133]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19

### Console Client Version

Latest

### Expected Behavior

Minecraft Console Client v1.19 - for MC 1.4.6 to 1.19 - Github.com/MCCTeam

### Actual Behavior

zsh: exec format error: ./MinecraftClient
./MinecraftClient: ./MinecraftClient: cannot execute binary file

### Steps to Reproduce the bug

1.  Run client on linux (Ubuntu 22.04)

### Attach screenshot here (If applicable)

video: https://youtu.be/3lfd2kVoUJ0

### Anythings that could help diagnosing the bug

```txt
i tried to build client myself but it didn't help
```

### Device

VPS

### Operating System

Linux

**Comment by milutinke** [comment]
Do you run on an ARM processor by any chance?

**Comment by Vazgen005** [comment]
It helped! Thanks! And yes, I ran it on an ARM processor.

**Comment by breadbyte** [comment]
We should also include precompiled ARM builds, considering that there is a significant amount of people here running under ARM.
