### ISSUE TITLE
[BUG] Can't use more than 5 console clients at once.

### ISSUE THREAD

**Issue by Lord420123** [MCCTeam/Minecraft-Console-Client#2146]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2

### Console Client Version

1.19

### Expected Behavior

I'm expecting to be able to open all the 11 console clients that I want to open and expect to see them running smoothly.

### Actual Behavior

I open all 11 clients and only 5 of them successfully connect, the rest just sit blank and will eventually just time out just to reconnect and have the same thing happen all over.

(When I put on debug messages, nothing came from it.)

### Steps to Reproduce the bug

1. Open more than 5 console clients at the same time.

### Anythings that could help diagnosing the bug

```txt
Opening more than 5 instances of console clients(for me), makes the rest not work.
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

boxpvpv.minehut.gg

**Comment by breadbyte** [comment]
Can you please try [this pre-release version of](https://github.com/BruceChenQAQ/Minecraft-Console-Client-1.19dev/releases/tag/bugfix_pre_build) #2124 and see if it is fixed?

**Comment by Lord420123** [comment]
I tried it, and it was all the same.

**Comment by ORelio** [comment]
Could be some anti-ddos protection server-side also.

**Comment by Lord420123** [comment]
Is there a fix to it, or is it something with the server?

**Comment by Lord420123** [comment]
So it is server-side I guess.

Quick question, can you open X amount of console clients by just clicking on a single 'MinecraftClient.exe'?

**Comment by BruceChenQAQ** [comment]
Yes, you can specify the ".ini" configuration file to be loaded via arguments, or change the configuration file before opening the next one.

**Comment by BruceChenQAQ** [comment]
You can write a script to start multiple clients with different configurations, specifying the location of the ".ini" configuration file to be loaded via arguments.

**Comment by milutinke** [comment]
Try using a proxy, that will solve your issue.
There are cheap proxies, even free ones you can use.
Here you can find more on proxies in MCC: https://mccteam.github.io/docs/guide/configuration.html#proxy

**Comment by Lord420123** [comment]
I tried using a few, but I don't think I 100% know what I'm doing.

What it looks like in the config:
https://prnt.sc/5fbvDnmlAtwD

What it looks like launching the client(with debug msg on):
https://prnt.sc/tuBhzQmhhFtx

**Comment by Lord420123** [comment]
I've tried many different things, but I just cannot figure out how to set it up correctly, it always ends in a "Socket Exception. System.Net.Socket.Exception tried to connect to an unreachable host".

**Comment by BruceChenQAQ** [comment]
Throwing this exception indicates a problem connecting to the server through a proxy, which could be that the proxy is not available or the server has blocked the IP segment.

I set up a SOCKS4 proxy locally, and I was able to connect to the server through this proxy using MCC, you can check if the proxy is available first.

**Comment by Lord420123** [comment]
Thanks a lot for telling me. What I don't understand is how you set up a proxy locally. Do you have to go into the settings of your internet connection, or how is it? I'm a little confused about that.

**Comment by BruceChenQAQ** [comment]
You need to set up a proxy on a VPS or buy one to bypass the server's restrictions on simultaneous connections. Creating a proxy locally does not change the IP you connect to the server.

**Comment by milutinke** [comment]
```
enabled=login
type=SOCKS4
server=213.7.196.26:4153
username=
password=     
```

This one works for me.
Check out the link I've sent, it says which protocol you need to write in `type=` and the ip and port in `server=`.

**Comment by Lord420123** [comment]
I bought a month of privateinternetaccess and enabled the vpn, and added it to the proxy. I still get the same error, but now it comes up much faster than it did previously. I just don't know how to do this, honestly.

**Comment by Lord420123** [comment]
With all of the above in mind, I'm a big noobie when it comes to techie things, so I would really appreciate it if someone had some kind of follow-along tutorial to set up a proxy and whatnot. I've been doing some digging myself for a few hours and I just can't seem to get things going. Thanks a lot for helping in the first place.

**Comment by milutinke** [comment]
> It didn't work for me, but where did you find it?

https://freeproxyupdate.com/

> With all of the above in mind, I'm a big noobie when it comes to techie things, so I would really appreciate it if someone had some kind of follow-along tutorial to set up a proxy and whatnot. I've been doing some digging myself for a few hours and I just can't seem to get things going. Thanks a lot for helping in the first place.

https://www.youtube.com/watch?v=5cPIukqXe5w
https://www.youtube.com/watch?v=c7YF23yvot8
https://mccteam.github.io/docs/guide/configuration.html#proxy

**Comment by Lord420123** [comment]
> > It didn't work for me, but where did you find it?
> 
> https://freeproxyupdate.com/
> 
> > With all of the above in mind, I'm a big noobie when it comes to techie things, so I would really appreciate it if someone had some kind of follow-along tutorial to set up a proxy and whatnot. I've been doing some digging myself for a few hours and I just can't seem to get things going. Thanks a lot for helping in the first place.
> 
> https://www.youtube.com/watch?v=5cPIukqXe5w https://www.youtube.com/watch?v=c7YF23yvot8 https://mccteam.github.io/docs/guide/configuration.html#proxy

Highly informative with a lot of useful information, thanks for showing me.

However, I've no idea at all how you set up a proxy in itself. Do you use a program from the web? Or do you configure some things in your settings, the videos where they allegedly explain those kinds of things, fry my brain and I don't get a single piece of information from it. If you or someone else have something on that, it'd be fantastic. Thanks for the help.

**Comment by milutinke** [comment]
> > > It didn't work for me, but where did you find it?
> > 
> > 
> > https://freeproxyupdate.com/
> > > With all of the above in mind, I'm a big noobie when it comes to techie things, so I would really appreciate it if someone had some kind of follow-along tutorial to set up a proxy and whatnot. I've been doing some digging myself for a few hours and I just can't seem to get things going. Thanks a lot for helping in the first place.
> > 
> > 
> > https://www.youtube.com/watch?v=5cPIukqXe5w https://www.youtube.com/watch?v=c7YF23yvot8 https://mccteam.github.io/docs/guide/configuration.html#proxy
> 
> Highly informative with a lot of useful information, thanks for showing me.
> 
> However, I've no idea at all how you set up a proxy in itself. Do you use a program from the web? Or do you configure some things in your settings, the videos where they allegedly explain those kinds of things, fry my brain and I don't get a single piece of information from it. If you or someone else have something on that, it'd be fantastic. Thanks for the help.

You don't need to make your own proxy, just use free ones.
The info you need is an ip address, a port, the type of proxy and username and password if you need to login to it.
Then you fill that info in `MinecraftClient.ini` in the `[Proxy]` section.

**Comment by Lord420123** [comment]
Ok, so I never did anything wrong, all the proxies i tried basically just didn't work -.-

well, that's progress I guess lol. Thanks.

**Comment by Lord420123** [comment]
https://prnt.sc/p1UXHJaiVJ1S

But seriously, what is it cause of this error? Can it just be labelled as "This proxy doesn't work"?

**Comment by Lord420123** [comment]
One error message that I have now realized never changes, no matter the proxy I try, is "Unhandled exception. System.Net.Socket.SocketException (10065) A socket-exception was attempted on an unreachable host".

**Comment by Lord420123** [comment]
Since I feel as though this post has come a bit further and is now in a different problem, I've decided to open #2152, so it can be kept a little bit more organized. Thanks for all your help with this one, it means a lot.
