### ISSUE TITLE
[BUG] debugmessages=true | Causes [process exited with code 3762504530 (0xe0434352)]

### ISSUE THREAD

**Issue by subrand0m** [MCCTeam/Minecraft-Console-Client#2151]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17 and 1.19.2

### Console Client Version

1.19

### Expected Behavior

Expected Behavior is the app launches with Debug enabled so I can report another issue. 

### Actual Behavior

Application launches and crashes with debugmessages=true 

Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
[MCC] [Settings] Loading Settings from C:\*\MinecraftClient-windows\MinecraftClient.ini
Resolving mchub.com...
[MCC] [Translations] No translation file found for en. (Looked 'C:\*\MinecraftClient-windows\lang\mcc\en.ini'
[MCC] [Translations] No translation file found for system language (en). (Looked C:\*\MinecraftClient-windows\lang\mcc\en.ini'
Color test: Your terminal should display [0123456789ABCDEF]: [0123456789ABCDEF]

[SessionCache] Initializing FileSystemWatcher for file: C:\*\MinecraftClient-windows\SessionCache.ini 
Loading Minecraft profiles: launcher_profiles.json
Loading session cache from disk: SessionCache.ini
Loaded session: *Readdicted*
Session data has been successfully loaded from disk.
Access token expiration time is 9/5/2022 12:04:17 AM
Cached session is still valid for subrand0m.
Saving session cache to disk
[KeysCache] Initializing FileSystemWatcher for file: C:\*\MinecraftClient-windows\ProfileKeyCache.ini 
Loading profile key cache from disk: ProfileKeyCache.ini
Loaded profile key, it will be refresh at 9/6/2022 6:45:30 AM
Profile keys has been successfully loaded from disk.
Cached profile key is still valid for subrand0m.
Success. (session ID: *Readdicted*)
Unhandled exception. System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 31.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at ConsoleInteractive.InternalWriter.Write(String value)
   at ConsoleInteractive.InternalWriter.WriteLine(String value)
   at ConsoleInteractive.ConsoleWriter.WriteLine(String value)
   at MinecraftClient.ConsoleIO.WriteLine(String line)
   at MinecraftClient.Translations.WriteLine(String key, Object[] args)
   at MinecraftClient.Program.InitializeClient()
   at MinecraftClient.Program.Main(String[] args)

[process exited with code 3762504530 (0xe0434352)]

### Steps to Reproduce the bug

1. Change debugmessages=false to debugmessages=true 
2. Launch the client

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
We're aware of this issue, Breadbyte is working on solving it.

**Comment by milutinke** [comment]
Also, try running in Alacrity or Powershell to avoid this bug, but do not make the window small.

**Comment by subrand0m** [comment]
> Also, try running in Alacrity or Powershell to avoid this bug, also do not make the window small.

Worked in powershell, thanks! Now I can open the real bug I wanted to report on ^_^
