### ISSUE TITLE
[BUG] Proxy not working correctly.

### ISSUE THREAD

**Issue by Lord420123** [MCCTeam/Minecraft-Console-Client#2152]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2

### Console Client Version

1.19

### Expected Behavior

I type in said IP:port and type of proxy with 'enabled=login'(also tried 'true'), and it should connect to the server.

### Actual Behavior

It doesn't connect with the proxy, and the client closes leaving an error message(error message in the screenshot).

https://prnt.sc/3eKKxPf3b3Iz

The part that is in danish is "A socket operation was attempted on a host, that was unreachable".

### Steps to Reproduce the bug

1. Type in a proxy in MinecraftClient.ini.
2. Open your console client.
3. And this should happen(that's how it happens for me).

### Anythings that could help diagnosing the bug

```txt
I've tried numerous proxies, watched videos on how to set them up, and tried many different things, but it just does not work. I thought that maybe there was a reason(which of course there is), for this same error message to appear at each and every proxy that I try.
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

boxpvpv.minehut.gg

**Comment by Lord420123** [comment]
I've been searching for quite a while, but I haven't found a single clue that could diagnose the issue at hand, it's nowhere to be found. If anyone has some information regarding this specific thing right here, please let me know.

**Comment by Lord420123** [comment]
I installed the newest build (1.19.2) and tried again, but I still got the same error message:

https://prnt.sc/JxH6qZlPbAeg

**Comment by milutinke** [comment]
> I installed the newest build (1.19.2) and tried again, but I still got the same error message:
> 
> https://prnt.sc/JxH6qZlPbAeg

I have updated the Proxy library to the latest version, try building my fork form this branch: https://github.com/milutinke/Minecraft-Console-Client/tree/proxy

How to build: https://mccteam.github.io/docs/guide/installation.html#building-from-the-source-code

Just use this clone command instead the one in the documentation:
```bash
git clone https://github.com/milutinke/Minecraft-Console-Client/ --recursive -b proxy
```

**Comment by milutinke** [comment]
For me it works perfectly

![http://i.pics.rs/BBp9p.png](http://i.pics.rs/BBp9p.png)

**Comment by milutinke** [comment]
> 



> That's nice to see. Knowing how much time I've spent on _trying_ :P
> 
> But well currently I'm having a few problems myself, and since I have no knowledge whatsoever about these programs, idk what to do:
> 
> **When opening** _MinecraftClient.sln_ **with** _Visual Studio 2022_ https://prnt.sc/cHPiMdWhojGG
> 
> **The two lines of message that show what went wrong:** https://prnt.sc/fmNVPVzO9ejq
> 
> Edit: Just found out the folder it's talking about is literally empty: https://prnt.sc/aVMjkmY-YnbC

You have not cloned the repository correctly,
Use my command, it needs to clone recursively the ConsoleInteractive repository.

**Comment by Lord420123** [comment]
> > 
> 
> > That's nice to see. Knowing how much time I've spent on _trying_ :P
> > But well currently I'm having a few problems myself, and since I have no knowledge whatsoever about these programs, idk what to do:
> > **When opening** _MinecraftClient.sln_ **with** _Visual Studio 2022_ https://prnt.sc/cHPiMdWhojGG
> > **The two lines of message that show what went wrong:** https://prnt.sc/fmNVPVzO9ejq
> > Edit: Just found out the folder it's talking about is literally empty: https://prnt.sc/aVMjkmY-YnbC
> 
> You have not cloned the repository correctly, Use my command, it needs to clone recursively the ConsoleInteractive repository.

Thanks for pointing that out, I retried and it worked this time, I tried MinecraftClient.exe in the files and it worked, but where do I find the files where I can config the accounts and change proxy?

**Comment by Lord420123** [comment]
I configured my Client and changed the proxy to the one that worked fine in your screenshot, and this same error message showed up again:

https://prnt.sc/59bcvXwQmbxL

**Comment by milutinke** [comment]
> I configured my Client and changed the proxy to the one that worked fine in your screenshot, and this same error message showed up again:
> 
> https://prnt.sc/59bcvXwQmbxL

Which .NET version are you running?
Also, are you running a VPN, a Proxy or a custom DNS server (or using a custom DNS server and HOSTS file) on your PC/Network by any chance?

I think that something is interfering with the connection, some possibilities couldbe:
- internet provider blocked a lot of those proxies on their DNS servers
- you're using a DNS server that has those proxy IP addresses blocked
- if you're running a custom HOSTS file maybe it has those IP addresses blacklisted
- if you're using a VPN maybe their DNS server has them blocked.

**Comment by Lord420123** [comment]
I've downloaded .NET Core Runtime 3.1.28, put on a VPN, changed DNS settings, and flushed the cache. Despite it all though, it still gives me the same error message.

**Comment by milutinke** [comment]
> I've downloaded .NET Core Runtime 3.1.28, put on a VPN, changed DNS settings, and flushed the cache. Despite it all though, it still gives me the same error message.

You need .NET Core 6: https://docs.microsoft.com/en-us/dotnet/core/install/windows

**Comment by Lord420123** [comment]
> > I've downloaded .NET Core Runtime 3.1.28, put on a VPN, changed DNS settings, and flushed the cache. Despite it all though, it still gives me the same error message.
> 
> You need .NET Core 6: https://docs.microsoft.com/en-us/dotnet/core/install/windows

I just did that, and it still said the same thing.

I have a feeling that the issue lies internally on my pc / with my internet. But not sure.

**Comment by milutinke** [comment]
> > > I've downloaded .NET Core Runtime 3.1.28, put on a VPN, changed DNS settings, and flushed the cache. Despite it all though, it still gives me the same error message.
> > 
> > 
> > You need .NET Core 6: https://docs.microsoft.com/en-us/dotnet/core/install/windows
> 
> I just did that, and it still said the same thing.
> 
> I have a feeling that the issue lies internally on my pc / with my internet. But not sure.

I've tested the MCC on multiple devices and proxies, it works as expected.
i have no more ideas what could cause the issue.

**Comment by milutinke** [comment]
If you can't solve the issue, try getting a free Amazon VPS EC2, you can get one on 12 months on AWS, tho you need to add a phone number and a credit card.

**Comment by Lord420123** [comment]
> 

I've gotten a hold of the VPS thingy on amazon AWS, I'm in the middle of setting it up, but I'm a bit confused. Where exactly do I type this(in some kind of search-bar inside of Cygwin? I don't quite follow?):

https://prnt.sc/bLPbu4JxIzWe

**Comment by milutinke** [comment]
> > 
> 
> I've gotten a hold of the VPS thingy on amazon AWS, I'm in the middle of setting it up, but I'm a bit confused. Where exactly do I type this(in some kind of search-bar inside of Cygwin? I don't quite follow?):
> 
> https://prnt.sc/bLPbu4JxIzWe

You can use Git Bash terminal to do that
Download it here: https://git-scm.com/

**Comment by Lord420123** [comment]
> > > 
> > 
> > 
> > I've gotten a hold of the VPS thingy on amazon AWS, I'm in the middle of setting it up, but I'm a bit confused. Where exactly do I type this(in some kind of search-bar inside of Cygwin? I don't quite follow?):
> > https://prnt.sc/bLPbu4JxIzWe
> 
> You can use Git Bash terminal to do that Download it here: https://git-scm.com/ Here is how you can add a new use with a SSH key login: https://www.youtube.com/watch?v=vpk_1gldOAE (You could just use a password, but it's better using a SSH key because of security)

I was trying to do as was instructed in the video above, but then when I typed in this command: `scp ~/.ssh/id_rsa.pub Marco@DESKTOP-*****@xxx.xxx.x.xxx:/c/users/Marco/.ssh/uploaded_key.pub`

It gave me this error:
https://prnt.sc/jZJbfpCUTCDv

**Comment by milutinke** [comment]
> > > > 
> > > 
> > > 
> > > I've gotten a hold of the VPS thingy on amazon AWS, I'm in the middle of setting it up, but I'm a bit confused. Where exactly do I type this(in some kind of search-bar inside of Cygwin? I don't quite follow?):
> > > https://prnt.sc/bLPbu4JxIzWe
> > 
> > 
> > You can use Git Bash terminal to do that Download it here: https://git-scm.com/ Here is how you can add a new use with a SSH key login: https://www.youtube.com/watch?v=vpk_1gldOAE (You could just use a password, but it's better using a SSH key because of security)
> 
> I was trying to do as was instructed in the video above, but then when I typed in this command: `scp ~/.ssh/id_rsa.pub Marco@DESKTOP-*****@xxx.xxx.x.xxx:/c/users/Marco/.ssh/uploaded_key.pub`
> 
> It gave me this error: https://prnt.sc/jZJbfpCUTCDv

Since you're on Windows, you can't use `~/.ssh/id_rsa.pub`, you need to provide the full path to the `id_rsa.pub`
Also you need to authenticate with your root ssh key by adding `-i <path to the key>`

Usage:
`scp -i <path to the root key> <path to a local file> <remote user>@<ip/host>:<path on the remote server>`

Example:
`scp -i C:\Users\RandomUser\keys\my_root_key.pub C:\Users\RandomUser\Desktop\SomeFile.txt root@host:/home/someuser/`

**Comment by milutinke** [comment]
I'll include this in the `Installing the MCC on a VPS` section in the documentation when I finish it.

**Comment by Lord420123** [comment]
To be completely honest, nothing is working, and I do not understand what I am doing, but I am trying :)

This is what happened when I wrote down the above into the terminal(correct any mistakes I made), and then the following happened:

https://prnt.sc/0tIfSKBz_rii

**Comment by breadbyte** [comment]
> To be completely honest, nothing is working, and I do not understand what I am doing, but I am trying :)
> 
> This is what happened when I wrote down the above into the terminal(correct any mistakes I made), and then the following happened:
> 
> https://prnt.sc/0tIfSKBz_rii
> 
> When I used the private IP address instead, it simply said "Connection timed out". - when using the `ssh root@IP` command

You need to use `/` instead of `\` in your file paths.

**Comment by milutinke** [comment]
> To be completely honest, nothing is working, and I do not understand what I am doing, but I am trying :)
> 
> This is what happened when I wrote down the above into the terminal(correct any mistakes I made), and then the following happened:
> 
> https://prnt.sc/0tIfSKBz_rii
> 
> When I used the private IP address instead, it simply said "Connection timed out". - when using the `ssh root@IP` command

My bad, you need to provide a path to the private, not the public key.
The private key does not have an extension.



> > To be completely honest, nothing is working, and I do not understand what I am doing, but I am trying :)
> > This is what happened when I wrote down the above into the terminal(correct any mistakes I made), and then the following happened:
> > https://prnt.sc/0tIfSKBz_rii
> > When I used the private IP address instead, it simply said "Connection timed out". - when using the `ssh root@IP` command
> 
> You need to use `/` instead of `\` in your file paths.
> 
> Instead of `C:\Users\Username\.ssh\my_root_key.pub`, you use `C:/Users/Username/.ssh/my_root_key.pub`.

Windows uses `\` that is why I've used it in a example.

**Comment by milutinke** [comment]
This is the example with `ssh` command, it also uses `-i`
![image](https://user-images.githubusercontent.com/441903/189296995-0585ef99-62bd-45d3-96eb-a01b7a910c3c.png)

**Comment by milutinke** [comment]
![image](https://user-images.githubusercontent.com/441903/189298118-b82cf115-b9d2-41dd-8f69-c2842efb17bc.png)
Ignore the `-P` option, that is for a custom ssh port.

**Comment by Lord420123** [comment]
I don't understand what went wrong here:
https://prnt.sc/FHB021c0a1aR

Did I type the wrong command?
The file does exist, I don't know.

**Comment by milutinke** [comment]
> I don't understand what went wrong here: https://prnt.sc/FHB021c0a1aR
> 
> Did I type the wrong command? The file does exist, I don't know.

The `-i` path is to your private file (the one without extension, not `.pub`), the parameter afterwards is the file you want to transfer, look at my example

Here is the usage:

`scp -i <your private key file path> <file that you want to transfer path> <user>@<public ip adress of the server>:<remote directory where you want to transfer to>`

Example:
`scp -i C:/Users/SomeUser/Desktop/myprivatekey C:/Users/SomeUser/Desktop/SomeFileIwantTotransfer.txt root@173.89.24.52:/home/someuser/`

**Comment by Lord420123** [comment]
I typed in, the above, and then this happened:

https://prnt.sc/BFVOMsbN-a7h

I didn't mention "my_root_key", don't know why that's there.

**Comment by milutinke** [comment]
Start from the beginning.
Terminate the instance, delete all keys from amazon and your pc.
Make a new instance with Ubuntu 22.04, generate a new key pair, name it: `VpsRoot`
it will auto download `VpsRoot.pem`
Then copy your Public DNS IPv4.
Make a new folder, move the `VpsRoot.pem` to it.
Generate a new key pair for the user by opening Git Bash in the same folder by right clicking on the empty space on it and selecting Git Bash, and typing the command:
 ```bash
 ssh-keygen -t RSA -b 4096
 ```
 
Give it a name of `MCC_Key`, give it a password if you want, hit enter.
Then login to the VPS with your root key (`VpsRoot.pem`) with the command:
```bash
ssh -i VpsRoot.pem ubuntu@<your ip here>
```
(`ubuntu` is the default root name on AWS)
Example: `ssh -i AmazonVPS.pem ubuntu@ec2-3-71-108-69.eu-central-1.compute.amazonaws.com`

Once you login, you need to make a new user:
```bash
sudo useradd mcc -m
```

Give it a password:
```bash
sudo passwd mcc
```

Give it sudo group/premissions:
```bash
sudo usermod -aG mcc
```

Give it a bash shell:
```bash
sudo chsh mcc -s /bin/bash
```

Login to the user while logged in as root:
```bash
su mcc
```

Go to the `mcc` user home with:
```bash
cd ~
```

Make a new `.ssh` directory:
```bash
mkdir .ssh
```

Enter to it:
```bash
cd .ssh
```

Go to your local folder on your pc where the `MCC_Key.pub` is, open it up and copy all of the contents.

Go back to the terminal with ssh session

Make an empty file `authorized_keys`:
```bash
touch authorized_keys
```

Open it with nano:
```bash
nano authorized_keys
```

Paste the copied contents of `MCC_Key,pub` in the nano editor by pressing a right click.
Once it's pasted, click `CTRL + X`, type `Y` to confirm and hit Enter.

Now open the SSHD config with nano:
```bash
sudo nano /etc/ssh/sshd_config
```

Find the line with `#PubkeyAuthentication yes`, remove the `#` to un-comment the line.
Find the line with `#AuthorizedKeysFile      .ssh/authorized_keys .ssh/authorized_keys2`, again remove the `#` to un-commnent (should be right bellow the top one)
Save the file with `CTRL + X`, then type `Y` and hit Enter.

For additional security you could change the port if you want, and disable root login.

Restart the SSHD service:
```bash
sudo systemctl restart sshd
```

Check if it is running (active) with:
```bash
sudo systemctl status sshd
```

Press `q` to exit the log.
Check if it is `active/running`, if not, check the config file for mistakes.
Now you can login to the MCC user with SSH and the key you've generated:
```bash
ssh -i MCC_Key mcc@<ip here>
```

**Comment by milutinke** [comment]
I'll record tutorials for everything when I catch some free time.

**Comment by Lord420123** [comment]
Thanks a lot for helping me through all this, it really means a lot. Someone else might have the same issue down the road, and go through these posts xD, truly nice of you!

And speaking upon this topic, I went and searched up how to download Ubuntu, and got onto to several different thing, the thing that I'm a bit confused with is this(BalenaEtcher):
https://prnt.sc/Zyqk6QwNcpRp

Do I continue despite what's being said, or find another way?

**Comment by milutinke** [comment]
> Thanks a lot for helping me through all this, it really means a lot. Someone else might have the same issue down the road, and go through these posts xD, truly nice of you!
> 
> And speaking upon this topic, I went and searched up how to download Ubuntu, and got onto several different things, the thing that I'm a bit confused with is this(BalenaEtcher): https://prnt.sc/Zyqk6QwNcpRp
> 
> Do I continue despite what's being said, or find another way?

If you want to install Ubuntu on your local machine, you should first backup all important stuff.
Haven't used BelenaEtcher, I use Rufus.
Don't select a system drive, only select USBs.

**Comment by Lord420123** [comment]
I think I'm just going to wait because there seem to be way too many complications for me to just get ubuntu without a USB.

**Comment by milutinke** [comment]
Just follow the guide for AWS, you can run it 24/7 there

**Comment by Lord420123** [comment]
I tried doing the first step in Cygwin(for convenience on my part), but this happened:

https://prnt.sc/Sv1gNyWrUOrS

**Comment by milutinke** [comment]
You can just use git bash instead of powershell, then you do not need to set the permissions
The command is just `chmod` without `-`, so not `-chmod`
Example: `chmod 0644 MCC_Key.pem`

**Comment by Lord420123** [comment]
It apparently cannot access the file, or whatever it says:

https://prnt.sc/jrTqK73_c8my

**Comment by milutinke** [comment]
You need to open Git bash directly in the folder where the key is, just right click on an empty white space in the folder and write the command.
Also try with permissions `644`

**Comment by milutinke** [comment]
https://user-images.githubusercontent.com/441903/189483533-21c5e8c0-3b5a-42ac-846f-94447b8b5948.mp4

**Comment by Lord420123** [comment]
Finally understood that I have to open it up _inside_ the file, I followed the exact things you wrote above, and this happened:

https://prnt.sc/18iUF1ow4fyv

**Comment by milutinke** [comment]
> Finally understood that I have to open it up _inside_ the file, I followed the exact things you wrote above, and this happened:
> 
> https://prnt.sc/18iUF1ow4fyv

Go to `C:\Users\<your windows user here>\.ssh` and delete all files that have `known_hosts` in their name.
I've recorded the whole thing, tho without any sounds, I have some workers in the house, a lot of noise, I'll do a proper series for the documentation when I can.
I'm uploading it.

**Comment by Lord420123** [comment]
I did that and tried the same thing again, but it doesn't connect.

The thing comes up `Sure you want to continue trying to connect (yes/no[fingerprint]` i answer "yes", and it creates the `known hosts` thing, I just press Enter, and it says "Connection failed".

https://prnt.sc/h639xgEA-0sT

**Comment by milutinke** [comment]
> I did that and tried the same thing again, but it doesn't connect.
> 
> The thing comes up `Sure you want to continue trying to connect (yes/no[fingerprint]` i answer "yes", and it creates the `known hosts` thing, I just press Enter, and it says "Connection failed".
> 
> https://prnt.sc/h639xgEA-0sT

Have you pasted the right public key in the `authorized_keys`, check if it is correct.
Here is the full process from creating a VPS to the MCC installation and usage:
https://files.catbox.moe/12fzat.mp4

**Comment by Lord420123** [comment]
The only error that I just came across:

https://prnt.sc/0AjT9lfY9jhJ

**Comment by milutinke** [comment]
Have you unzipped it first?
Do a `ls -laH` for the listing of files.

**Comment by Lord420123** [comment]
I did the unzip command:
https://prnt.sc/v8BGa5ebXCtm

Then I did ls -laH:
https://prnt.sc/7N3x8k6FL6oN

**Comment by milutinke** [comment]
> I did the unzip command: https://prnt.sc/v8BGa5ebXCtm
> 
> Then I did ls -laH: https://prnt.sc/7N3x8k6FL6oN

You downloaded the wrong zip, you need the Linux zip (not linux-arm64 or windows or osx)

**Comment by Lord420123** [comment]
I got it right this time, but what do I do about the "MinecraftClient.exe"?:
https://prnt.sc/YK3HU4mpcQEP

**Comment by milutinke** [comment]
> I got it right this time, but what do I do about the "MinecraftClient.exe"?: https://prnt.sc/YK3HU4mpcQEP

Just delete it with `rm MinecraftClient.exe`.

Watch this to get familiarized with linux:
https://www.youtube.com/watch?v=SkB-eRCzWIU

**Comment by Lord420123** [comment]
It worked, but when I try to log in to an account this happens:

https://prnt.sc/qpDxW4qTszR6

**Comment by milutinke** [comment]
> It worked, but when I try to log in to an account this happens:
> 
> https://prnt.sc/qpDxW4qTszR6

Try the browser method of login.

**Comment by Lord420123** [comment]
I just realized that in the file path: `/home/mcc/MCC/MinecraftClient.ini`, there's no "home" or "MCC" folder or anything.

https://prnt.sc/ukNKNDumD8gq
does that have something to do with it?

**Comment by milutinke** [comment]
Have you made the `mcc` user and logged as `mcc`?
Type `pwd` in the directory where you have installed the MCC in and screenshot.

**Comment by Lord420123** [comment]
https://prnt.sc/AmMk_BN75VvE

**Comment by milutinke** [comment]
You have the right folder.
Just use the `method=browser` and copy the link when you get it, login and copy over the key you got and paste it in the MCC and press Enter.

**Comment by Lord420123** [comment]
> You have the right folder. Just use the `method=browser` and copy the link when you get it, login and copy over the key you got and paste it in the MCC and press Enter.

I understand, but how do I change the method of log in, when I don't know/can't access the file path the settings are being loaded from? "home/mcc/MCC/MinecraftClient.ini"

**Comment by milutinke** [comment]
> > You have the right folder. Just use the `method=browser` and copy the link when you get it, login and copy over the key you got and paste it in the MCC and press Enter.
> 
> I understand, but how do I change the method of log in, when I don't know/can't access the file path the settings are being loaded from? "home/mcc/MCC/MinecraftClient.ini"

It should be there.
Navigate to the MCC folder and do `ls -laH`, you should see it, if not, run the MCC and exit it with CTRL + C, it should auto generate the ini file.

**Comment by Lord420123** [comment]
I tried making the path manually, but it didn't do anything.

I checked inside the terminal with `ls -laH` and `pwd`

https://prnt.sc/ShcdRbYMMzoi

but the directory isn't there.

**Comment by milutinke** [comment]
You're missing a `/` at the start, in linux everything is in the `/` (root) directory.
The folder is clearly there since you are in it, and the file is there too xD

The full path
`/home/mcc/MCC/MinecraftClient.ini`

**Comment by milutinke** [comment]
Ignore the error, it's because there is not graphical environment or a web browser.
https://user-images.githubusercontent.com/441903/189497989-eb57b928-9127-4bda-bf44-3585a8f51909.mp4

**Comment by Lord420123** [comment]
Thanks, it works completely now, there's just one little thing I need to be fixed now(more of an in-game issue), is it possible for me to log in with this IP on an actual Minecraft client, so I can complete this:

https://prnt.sc/CrgeT2sYkV66

and fully join the server?

**Comment by milutinke** [comment]
What kind of captcha is that, is it displayed in a map, or in the chat or you need to open a link in a web browser and complete it there?

**Comment by milutinke** [comment]
If it is the one which needs to be opened in a web browser, you could install a graphical environment, a VNC server and then connect through VNC and start MCC and open up a web browser.

**Comment by Lord420123** [comment]
> What kind of captcha is that, is it displayed in a map, or in the chat or you need to open a link in a web browser and complete it there?

You join the server, and it is displayed on a banner in front of you, which spans out about 7 blocks long and 3-4 blocks tall.

**Comment by milutinke** [comment]
We don't have a mechanism for that.
You could install a GUI, install minecraft, make the window small since everything is rendered on a cpu, install optifine and then complete the captcha and then close the mc and run the MCC.

**Comment by Lord420123** [comment]
> > What kind of captcha is that, is it displayed in a map, or in the chat or you need to open a link in a web browser and complete it there?
> 
> You join the server, and it is displayed on a banner in front of you, which spans out about 7 blocks long and 3-4 blocks tall. We don't have a mechanism for that. You could install a GUI, install minecraft, make the window small since everything is rendered on a cpu, install optifine and then complete the captcha and then close the mc and run the MCC:

I appreciate the help, but I have no clue whatsoever on how to do that xD

**Comment by milutinke** [comment]
Sorry for editing your comment, my muscle memory today... xD
Watch this: https://www.youtube.com/watch?v=ODhGNe0s4lI

**Comment by milutinke** [comment]
Installing MC on Ubuntu: https://www.youtube.com/watch?v=BzDz1fiqCjc
Installing Optifine: https://www.youtube.com/watch?v=tDxMWEjni4w

**Comment by Lord420123** [comment]
https://prnt.sc/uX2FEGToAnaT

I can't install the extension for some reason?

**Comment by milutinke** [comment]
> https://prnt.sc/uX2FEGToAnaT
> 
> I can't install the extension for some reason?

That is a command that requires root privileges to be run.
You need to use a `sudo` prefix.

`sudo apt install taskel`

**Comment by Lord420123** [comment]
https://prnt.sc/GwWQsoa7KXIy

These options are completely different from the guy in the video's, and I have no clue which one to pick.

**Comment by milutinke** [comment]
> https://prnt.sc/GwWQsoa7KXIy
> 
> These options are completely different from the guy in the video's, and I have no clue which one to pick.

Go with Gnome, it's the default one on Ubuntu

**Comment by milutinke** [comment]
72 replies xD
Can't wait for Orelio to make a Discord.

**Comment by Lord420123** [comment]
> 72 replies xD Can't wait for Orelio to make a Discord server.

Lmao, here's to 73 xD.

I don't understand what's happening here:
https://prnt.sc/BICl3zU-QqRY

**Comment by milutinke** [comment]
it didn't start properly,
Watch this: https://www.youtube.com/watch?v=3K1hUwxxYek

**Comment by milutinke** [comment]
Also, can you screenshot the banner, I am interested in the pattern so I could maybe make a bot for it.

**Comment by Lord420123** [comment]
> Also, can you screenshot the banner? I am interested in the pattern so I could maybe make a bot for it.

I'm trying to find a picture of it, since I don't know if I can reproduce it, and this is the closest one I've come across:
https://prnt.sc/W6dUpO2Ykna9

the captcha was bugged and didn't load correctly. I'll se if i can reproduce it though.

**Comment by Lord420123** [comment]
> > Also, can you screenshot the banner? I am interested in the pattern so I could maybe make a bot for it.
> 
> I'm trying to find a picture of it, since I don't know if I can reproduce it, and this is the closest one I've come across: https://prnt.sc/W6dUpO2Ykna9
> 
> the captcha was bugged and didn't load correctly. I'll se if i can reproduce it though.

I put on a vpn, and that triggered it, so here is an image of the captcha in full-function:
https://prnt.sc/YoM7zoZvRuqm

**Comment by milutinke** [comment]
> > > Also, can you screenshot the banner? I am interested in the pattern so I could maybe make a bot for it.
> > 
> > 
> > I'm trying to find a picture of it, since I don't know if I can reproduce it, and this is the closest one I've come across: https://prnt.sc/W6dUpO2Ykna9
> > the captcha was bugged and didn't load correctly. I'll se if i can reproduce it though.
> 
> I put on a vpn, and that triggered it, so here is an image of the captcha in full-function: https://prnt.sc/YoM7zoZvRuqm

That looks like multiple maps on a wall.

**Comment by Lord420123** [comment]
Exactly, it's 10 different maps. But it would work if I installed a GUI, or what you said?

**Comment by milutinke** [comment]
> Exactly, it's 10 different maps. But it would work if I installed a GUI, or what you said?

You need a GUI in order to use ordinary mc to complete the captcha, then you can close it and start the mcc.

**Comment by Lord420123** [comment]
> > Exactly, it's 10 different maps. But it would work if I installed a GUI, or what you said?
> 
> You need a GUI in order to use ordinary mc to complete the captcha, then you can close it and start the mcc.

That sounds about as complicated as setting up the VPS without that tutorial, lol. Just cause i know nothing.

**Comment by milutinke** [comment]
Just follow the video tutorials, you can search up about setting up a VNC server.
Installing Minecraft is then easy.

**Comment by Lord420123** [comment]
I already did this(https://www.youtube.com/watch?v=3K1hUwxxYek), but I still don't understand why the first one isn't working:

https://prnt.sc/GVMS-FAO9_X3

**Comment by milutinke** [comment]
> I already did this(https://www.youtube.com/watch?v=3K1hUwxxYek), but I still don't understand why the first one isn't working:
> 
> https://prnt.sc/GVMS-FAO9_X3

Uninstall TigerVNC with `sudo apt remove <program name>` and try installing it manually: https://help.ubuntu.com/community/VNC/Servers#TigerVNC
If it does not work, try using `x11vnc`: https://www.youtube.com/watch?v=d6X4Z-DjO1E

**Comment by Lord420123** [comment]
I did what the x11vnc video said to do, and this happened:
https://prnt.sc/Sc3GRNui0UiK

**Comment by Lord420123** [comment]
What is wrong with this?
https://prnt.sc/nF27SuSFtuWd

**Comment by Lord420123** [comment]
How do I install/execute the optifine file?

https://prnt.sc/si5Sii58vfm8

**Comment by milutinke** [comment]
> I did what the x11vnc video said to do, and this happened: https://prnt.sc/Sc3GRNui0UiK
> 
> is it because I need to have minecraft installed inside the ssh?

I'll take a look on how to setup a proper gui, and I'll explain it to you.

> How do I install/execute the optifine file?
> 
> https://prnt.sc/si5Sii58vfm8

You need GUI for that.

**Comment by breadbyte** [comment]
Oops, didn't mean to do that, must have pressed a keyboard shortcut or something.

**Comment by milutinke** [comment]
Here is how to do a setup: https://www.youtube.com/watch?v=bVKNSf1p1d0

My configuration for reference:
```
[Interface]
Address = 10.0.0.1/24
SaveConfig = true
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE;
ListenPort = 51820
PrivateKey = server private key

[Peer]
PublicKey = client public key here
AllowedIPs = 10.0.0.2/32
```

My client settings for reference:
```
[Interface]
PrivateKey = your client private key here
Address = 10.0.0.2/24
DNS = 94.140.14.14, 94.140.15.15

[Peer]
PublicKey = your server public key here
AllowedIPs = 0.0.0.0/0
Endpoint = (server ip address):51820
PersistentKeepalive = 30
```

**Comment by milutinke** [comment]
@Lord420123 Join discord, so we don't spam here.
I'll close the issue.
