### ISSUE TITLE
[BUG] Move command using cardinal names not working propperly.

### ISSUE THREAD

**Issue by Splarkszter** [MCCTeam/Minecraft-Console-Client#2155]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.0

### Console Client Version

[20220904-38]

### Expected Behavior

Move north,south,west and east

### Actual Behavior

Moving east does 2 block,
Moving west does nothing,
Moving north moves north 1 east 1
Moving south moves south 1 east 1

### Steps to Reproduce the bug

1. See the attached video

### Anythings that could help diagnosing the bug

```txt
Moving to coordinates seems to be working well. But using cardinal names does not.

Video:
https://youtu.be/mYcA3RobMzI
```

**Comment by Splarkszter** [comment]
Also would be cool to specify how many blocks to move on the desired cardinal name.

**Comment by Splarkszter** [comment]
Also also. The releases tb should be cleaned. Leaving bugless or feature important/old releases only.

**Comment by milutinke** [comment]
Try with [20220905-42](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220905-42)

**Comment by Splarkszter** [comment]
Works. cool.
