### ISSUE TITLE
[BUG] /chunk status not correctly display

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2163]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

latest

### Expected Behavior

/chunk status

### Actual Behavior

/chunk status and correctly view 

### Steps to Reproduce the bug

1. run minecraftclient.exe on default windows console
2. write /chunk status
3. and you see this 
![image](https://user-images.githubusercontent.com/79597112/188729622-fcc61df7-0e36-40a1-bce2-0a1970521799.png)

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/79597112/188729622-fcc61df7-0e36-40a1-bce2-0a1970521799.png)

### Device

Laptop

### Operating System

Windows

**Comment by deosync** [comment]
sorry for my English but "Russian f*cking kid"

**Comment by BruceChenQAQ** [comment]
The bug about displaying ``§`` has been fixed in the latest build.

The CMD of windows10 does not support displaying emoji like "🔳🟩🟨", you can use [Windows Terminal](https://github.com/microsoft/terminal/releases).

**Comment by BruceChenQAQ** [comment]
Now supports not using emoji to indicate chunk loading status, change ``enableemoji=false`` in the settings.
