### ISSUE TITLE
[BUG] Remote control not working?

### ISSUE THREAD

**Issue by Splarkszter** [MCCTeam/Minecraft-Console-Client#2164]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.0

### Console Client Version

Lastest

### Expected Behavior

Run console commands using /tell to the bot

### Actual Behavior

nothing happens when sending the message but console displays it recieved the tell message

### Steps to Reproduce the bug

1. enable remotecontrol setting on the config
2. include yourself as botowner
3. use /tell to send a message to the bot

### Anythings that could help diagnosing the bug

```txt
i have the RemoteControl=true and BotOwners=Splarkszter

but nothing happens, versions before (even with bot being able to send messages on 1.19.0) it worked, but now it does not.
```

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Fixed in the latest release
![image](https://user-images.githubusercontent.com/441903/188845206-1c03af2d-7d6e-48ec-add6-b30547c5e2ea.png)

**Comment by RyterX** [comment]
hello! i have the same issue, nothing to do. my version is 1.19.4

**Comment by milutinke** [comment]
> hello! i have the same issue, nothing to do. my version is 1.19.4

Make sure you have set yourself as the bot owner and that you have the Remote Contr ol chat bot enabled.
If the server you play on uses a custom chat format for private messages, you will need to write the RegEx for that format in the Chat section in the configuration file.

**Comment by RyterX** [comment]
Hi, yes i enabled all things, my server Is Vanilla without plugin. But nothing to do. Wich Is the special character for command? . + / ??? I tried everything but nothing works

**Comment by milutinke** [comment]
> Hi, yes i enabled all things, my server Is Vanilla without plugin. But nothing to do. Wich Is the special character for command? . + / ??? I tried everything but nothing works

Tested it on my server, it works.
You need to send a command without a slash.
Here is an example: `/tell yourbotnamehere send this is a reply`
Or another one `/tell yourbotnickhere respawn`

**Comment by RyterX** [comment]
![image](https://user-images.githubusercontent.com/50300226/235359632-42f47023-46e9-478c-9366-45ac77b6993a.png)

nothing

> > Hi, yes i enabled all things, my server Is Vanilla without plugin. But nothing to do. Wich Is the special character for command? . + / ??? I tried everything but nothing works
> 
> Tested it on my server, it works. You need to send a command without a slash. Here is an example: `/tell yourbotnamehere send this is a reply`

**Comment by milutinke** [comment]
> ![image](https://user-images.githubusercontent.com/50300226/235359632-42f47023-46e9-478c-9366-45ac77b6993a.png)
> 
> nothing
> 
> > > Hi, yes i enabled all things, my server Is Vanilla without plugin. But nothing to do. Wich Is the special character for command? . + / ??? I tried everything but nothing works
> > 
> > 
> > Tested it on my server, it works. You need to send a command without a slash. Here is an example: `/tell yourbotnamehere send this is a reply`

Post your config (Make sure to remove the login details)

**Comment by RyterX** [comment]
[MinecraftClient - Copy.txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/11362483/MinecraftClient.-.Copy.txt)

**Comment by RyterX** [comment]
> Post your config (Make sure to remove the login details)

Done, any suggestion? 😭

**Comment by RyterX** [comment]
i tried also to re-download mcc to start a clean session with all set to default, i add myself to botowners, enabled remote control, and used "//tell bot send hello" and "/tell bot send hello" 
but nothing happens

**Comment by milutinke** [comment]
> 
> ![image](https://user-images.githubusercontent.com/50300226/235359632-42f47023-46e9-478c-9366-45ac77b6993a.png)
> 
> nothing
> 
> > > Hi, yes i enabled all things, my server Is Vanilla without plugin. But nothing to do. Wich Is the special character for command? . + / ??? I tried everything but nothing works
> > 
> > Tested it on my server, it works. You need to send a command without a slash. Here is an example: `/tell yourbotnamehere send this is a reply`
> 
> 

Haven't noticed, your message is not in English, enable custom chat format and update the regex for private message to match your language

**Comment by RyterX** [comment]
> 

Yes, I tried but doesn't work
