### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by alex2003527** [MCCTeam/Minecraft-Console-Client#2165]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.12.2

### Console Client Version

Latest

### Expected Behavior

I tried to connect to server through your client

### Actual Behavior

I use gre tunnel on my server, that's why any other connections are blocked with firewall and your client can't connect to the server. Could you please send me an IP from what your client is connecting to the server so I can add the rule into the firewall to allow connections? Thank you in advance 

### Steps to Reproduce the bug

1. to send me an IP from what your client is connecting to my server

**Comment by milutinke** [comment]
The client is connecting from your IP, unless you're using a proxy option in the client.

**Comment by BruceChenQAQ** [comment]
You can capture all packets sent by MCC.
However, as the domain name resolution associated with the authentication server may change, the IP connected to may also change.
