### ISSUE TITLE
[BUG] Unable to join servers that force resource packs 1.19.2

### ISSUE THREAD

**Issue by jacobpetre** [MCCTeam/Minecraft-Console-Client#2168]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

20220907-48

### Expected Behavior

To be able to join servers which force resource packs.

### Actual Behavior

Client crashes as soon as the packet to force a resource pack is received.

```
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type ResourcePackSend. (PacketID: 61, Protocol: 760, LoginPhase: False, InnerException: System.InvalidOperationException).
 ---> System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at MinecraftClient.Protocol.Handlers.DataTypes.SkipNextString(Queue`1 cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()
```

### Steps to Reproduce the bug

1. Open MCC
2. Login
3. Connect to a server which forces resource pack upon joining. 

### Device

VPS

### Operating System

Windows

### Server Address (If applicable)

play.mineraze.net

**Comment by BruceChenQAQ** [comment]
Use the latest release to check if there are still problems.
I always get message ``Please disconnect from your proxy or VPN before re-joining!`` so that I can't test.
