### ISSUE TITLE
[BUG] Bot uses magic to walk

### ISSUE THREAD

**Issue by Splarkszter** [MCCTeam/Minecraft-Console-Client#2170]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.0

### Console Client Version

Lastest

### Expected Behavior

Walk normally

### Actual Behavior

Bot is able to skip single block gaps and climb 2 blocks tall

### Steps to Reproduce the bug

1. Setup terrain and movements
2. Tell bot to go to coordinates
3. Bot walks

### Device

Desktop

### Operating System

Windows

**Comment by BruceChenQAQ** [comment]
Can you provide a screenshot of the terrain where this occurred?

**Comment by Splarkszter** [comment]
![image](https://user-images.githubusercontent.com/90066319/189236867-af7d8bc7-bd64-4d75-bc47-a6397aae991d.png)
![image](https://user-images.githubusercontent.com/90066319/189236960-6d72306c-08f6-450d-afd1-eea117ef1e35.png)
![image](https://user-images.githubusercontent.com/90066319/189237573-c74d6ff0-b617-4a96-aa4c-f75a96675867.png)

**Comment by BruceChenQAQ** [comment]
Magic is nerfed in https://github.com/MCCTeam/Minecraft-Console-Client/commit/223c13561c8fae96a374f0b0da0368ec88ed30e3.
After using -f, the robot will still skip a single block gap. This is not expected, although it can be done in vanilla clients.

<details>
  <summary>Gif</summary>

![4](https://user-images.githubusercontent.com/26017411/189304456-606d9164-978a-40e4-ad8a-4540bb55e9b7.gif)

</details>

---

Next I am going to rewrite the handling of moves, in order to allow MCC to handle more complex paths. After this it will be easier to implement commands such as follow. (#725 #2125)
There is a lot of work involved and it can take a long time to implement it.

**Comment by milutinke** [comment]
> Magic is nerfed in [223c135](https://github.com/MCCTeam/Minecraft-Console-Client/commit/223c13561c8fae96a374f0b0da0368ec88ed30e3). After using -f, the robot will still skip a single block gap. This is not expected, although it can be done in vanilla clients.
> Gif
> 
> Next I am going to rewrite the handling of moves, in order to allow MCC to handle more complex paths. After this it will be easier to implement commands such as follow. (#725 #2125) There is a lot of work involved and it can take a long time to implement it.

After it's done we should start porting Baritone as a ChatBot

**Comment by BruceChenQAQ** [comment]
> > Magic is nerfed in [223c135](https://github.com/MCCTeam/Minecraft-Console-Client/commit/223c13561c8fae96a374f0b0da0368ec88ed30e3). After using -f, the robot will still skip a single block gap. This is not expected, although it can be done in vanilla clients.
> > Gif
> > Next I am going to rewrite the handling of moves, in order to allow MCC to handle more complex paths. After this it will be easier to implement commands such as follow. (#725 #2125) There is a lot of work involved and it can take a long time to implement it.
> 
> After it's done we should start porting Baritone as a ChatBot

This work with more like our own implementation of the terrain processing that already exists in the vanilla client as well as improving the existing pathfinding algorithm.

After this work is done, we can encapsulate some pathfinding based features like Baritone, such as follow and farm.

Baritone is a mod, so it can easily call some code from minecraft, while we have to implement it ourselves.

**Comment by milutinke** [comment]
Making the Follow Player Chat Bot, currently testing it.
![image](https://user-images.githubusercontent.com/441903/189327852-e433078b-b1af-45ba-9b81-655dedf01ea7.png)

**Comment by Splarkszter** [comment]
you guys are awesome
