### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by miyatatakeshi** [MCCTeam/Minecraft-Console-Client#2175]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

20220909-54

### Expected Behavior

I don't know what happened so i can't really expect anything.

### Actual Behavior

Error while using client and it close itself.

### Steps to Reproduce the bug

1. Client running smoothly
2. This error appears after running for a while.
3. When I click yes clients close itself.

### Attach screenshot here (If applicable)

![mcc](https://user-images.githubusercontent.com/75170571/189371322-3211d5eb-5fed-4ef9-bb0b-6fa1b5922e92.png)

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Which .NET version are you running?
You need .NET core 6.0

**Comment by breadbyte** [comment]
Is there any error that appears on the console?

**Comment by miyatatakeshi** [comment]
> Which .NET version are you running? You need .NET core 6.0

I have .NET Core 6.0.7.

> Is there any error that appears on the console?

I forgot to look. I am running the client again to get this error again but it is not coming, I will reply when I get it.

**Comment by BruceChenQAQ** [comment]
This article may be of some help in solving this problem: [How to solve unknown software exception 0xe0434352](https://thegeekpage.com/how-to-solve-unknown-software-exception-0xe0434352/)

**Comment by breadbyte** [comment]
> This article may be of some help in solving this problem: [How to solve unknown software exception 0xe0434352](https://thegeekpage.com/how-to-solve-unknown-software-exception-0xe0434352/)

These are general troubleshooting steps for a windows machine, and may not help in our situation.

According to [MSDN](https://docs.microsoft.com/en-gb/shows/inside/e0434352), `0xe0434352` is simply the exception code that is given to windows when there is a CLR exception.

A CLR Exception is a generic .NET Exception, that is why I suggested checking the console for the actual error.

Since this is given to Windows, we may be able to see the exception itself using Event Viewer.

**Comment by breadbyte** [comment]
If you are willing to go through the trouble, here is a quick guide to opening the Event Viewer.

<details>
<summary>Guide</summary>

### 1. Open the Event Viewer from the Start Menu.
![Muted-Dobermanpinscher-c14473605404cac5](https://user-images.githubusercontent.com/14045257/189472276-88c7d47c-5ee2-404a-a6d2-b80070314590.png)

### 2. On the left side of the screen, click on `Windows Logs`, and then `Application`.
![Repentant-Antelope-d10f81b93dda560b](https://user-images.githubusercontent.com/14045257/189472292-7e1613db-e641-4310-90b8-f825121984fb.png)

### 3. On the right hand side of the screen, select `Filter Current Log.`
![Carefree-Dassie-bd961509a9a87de9](https://user-images.githubusercontent.com/14045257/189472303-ecbbb833-c878-46c5-8697-1762bb0d58b0.png)

### 4. Fill out the following information in the popup as shown.
![Darkgoldenrod-Azurevasesponge-0c1d566a418ef25d](https://user-images.githubusercontent.com/14045257/189472323-f09e4a92-ee43-4cfb-be7f-8674e8bf23f8.png)

### 5. You should now be able to see the exception information. Please find the correct time and date when the error happened.

The information that we require should be shown on the box below.

![Kaleidoscopic-Peafowl-88f7341007bf88f1](https://user-images.githubusercontent.com/14045257/189472345-f5434546-86fb-4fb3-a69f-4fc6b62eb97a.png)

</details>

**Comment by miyatatakeshi** [comment]
Application: MinecraftClient.exe
CoreCLR Version: 6.0.722.32202
.NET Version: 6.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: Console Reader thread is already running.
   at ConsoleInteractive.ConsoleReader.BeginReadThread(CancellationTokenSource cancellationTokenSource)
   at ConsoleInteractive.ConsoleReader.RequestImmediateInput()
   at MinecraftClient.Program.<>c__DisplayClass13_0.<HandleFailure>b__0()
   at System.Threading.Thread.StartCallback()

Event viewer log.

**Comment by breadbyte** [comment]
This issue is most likely triggered by reconnecting the client, therefore calling Init twice.
I'll be looking into a fix for this issue.

**Comment by milutinke** [comment]
> This issue is most likely triggered by reconnecting the client, therefore calling Init twice. I'll be looking into a fix for this issue.

I've experienced it when testing the WebSocket bot on 1.19.2, on 1.18 it never happens.

**Comment by milutinke** [comment]
Since I've ported the WebSocket chat bot on to the master with TOML settings, I have not experienced this issue anymore.
So I'll consider this as fixed and will close the issue.
If you still have it, reopen the issue.
