### ISSUE TITLE
[Idea] Fake Texurpack

### ISSUE THREAD

**Issue by Muharrem652** [MCCTeam/Minecraft-Console-Client#2179]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

v1.19

### Describe your problem

Hello,

Is it possible to put a "fake resource pack" for servers where this is required?
Can we do it as a script?

### Minecraft Version

1.12.2

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
That is already a feature
Check the code and the comment here: https://github.com/MCCTeam/Minecraft-Console-Client/blob/223c13561c8fae96a374f0b0da0368ec88ed30e3/MinecraftClient/Protocol/Handlers/Protocol18.cs#L1284

**Comment by milutinke** [comment]
![image](https://user-images.githubusercontent.com/441903/189522393-818943a5-7ea5-4223-a691-de3a7cab1850.png)
Yeah it works.
