### ISSUE TITLE
[Idea] Add physics/gravity

### ISSUE THREAD

**Issue by Vazgen005** [MCCTeam/Minecraft-Console-Client#2184]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Bot doesn't have any physics/gravity.
I know it's hard to add, but anyway ¯\_(ツ)_/¯

### Suggest a possible solution

Add physics/gravity 

### Attach screenshot here (If applicable)

Video: https://youtu.be/MUCOlbfoZRs

### Minecraft Version

All versions

**Comment by milutinke** [comment]
You can enable gravity with `/move gravity on`
As for physics, it's on the TODO.

**Comment by Vazgen005** [comment]
Ok, thanks for the answer. I hope you will add physics soon.
