### ISSUE TITLE
[BUG] Why I cannot open the exe

### ISSUE THREAD

**Issue by Picadoo** [MCCTeam/Minecraft-Console-Client#2185]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.12.2

### Console Client Version

Lastest

### Expected Behavior

I download but cannot open it. No answer.

### Actual Behavior

the exe file cannot build other file, with no answer.

### Steps to Reproduce the bug

1. download
2. open the file
3. no answer
4. 
5. 
6. 

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

none

**Comment by breadbyte** [comment]
You need to install the [.NET 6.0 Runtime](https://dotnet.microsoft.com/en-us/download).

**Comment by Picadoo** [comment]
> You need to install the [.NET 6.0 Runtime](https://dotnet.microsoft.com/en-us/download).

Thank you for your answer.
