### ISSUE TITLE
[BUG] kicking on server 1.16.5

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2187]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

latest

### Expected Behavior

not kicking

### Actual Behavior

kicking

### Steps to Reproduce the bug

1. change string in config
terrainandmovements=false          # Uses more ram, cpu, bandwidth but allows you to move around
inventoryhandling=false            # Toggle inventory handling (beta)
to true
2. join to server "mc.playrw.ru"
3. connect to the server with command "/grief-116-1"
4. wait a little time
5. and see kick with reason "Cheating"

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

mc.playrw.ru

**Comment by milutinke** [comment]
Some servers have anti cheats, unfortunately we can't do anything about it.
What you can do on your side is trying to disable terrain movement and change the [brandinfo](https://mccteam.github.io/guide/configuration.html#brandinfo) to `vanilla` or `forge`.

**Comment by BruceChenQAQ** [comment]
Try the [latest release](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest).
