### ISSUE TITLE
[BUG] Crash when processing explosion

### ISSUE THREAD

**Issue by Yejia995** [MCCTeam/Minecraft-Console-Client#2188]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

Latest

### Expected Behavior

Not crashing.

### Actual Behavior

When Creeper explodes beside the client player, there's a pretty high possibility to crash. 
A1 is the Player Name, **Error Message**:
````
A1 was blown up by Creeper
> Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type Explosion. (PacketID: 27, Protocol: 760, LoginPhase: False, InnerException: System.InvalidOperationException).
 ---> System.InvalidOperationException: Queue empty.
   at System.Collections.Generic.Queue`1.ThrowForEmptyQueue()
   at System.Collections.Generic.Queue`1.Dequeue()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   --- End of inner exception stack trace ---
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetID, Queue`1 packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o)
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)
````
(Client Crashes)

### Steps to Reproduce the bug

1. Place a creeper next to the player and explode. (try two to three times)
2. Client Crashes.

### Anythings that could help diagnosing the bug

I tried to run the client on my own windows computer but it also crashes, so it is not related to the Linux environment.

### Device

VPS

### Operating System

Linux

**Comment by milutinke** [comment]
Trying to figure out what is happening.
TNT does not cause a crash, but a creeper does, weird.

Rewrote the part of the code for handling explosions, it fully maps the [wiki.vg definition](https://wiki.vg/Protocol#Explosion):
```csharp
case PacketTypesIn.Explosion:
    Location explosionLocation;

    if (protocolVersion >= MC_1_19_Version)
        explosionLocation = new(dataTypes.ReadNextDouble(packetData), dataTypes.ReadNextDouble(packetData), dataTypes.ReadNextDouble(packetData));
    else
        explosionLocation = new(dataTypes.ReadNextFloat(packetData), dataTypes.ReadNextFloat(packetData), dataTypes.ReadNextFloat(packetData));

    float explosionStrength = dataTypes.ReadNextFloat(packetData);
    int explosionBlockCount = protocolVersion >= MC_1_17_Version
        ? dataTypes.ReadNextVarInt(packetData)
        : dataTypes.ReadNextInt(packetData);

    byte[] explosionOffsetX = dataTypes.ReadData(3, packetData);
    byte[] explosionOffsetY = dataTypes.ReadData(3, packetData);
    byte[] explosionOffsetZ = dataTypes.ReadData(3, packetData);

    float playerVelocityX = dataTypes.ReadNextFloat(packetData);
    float playerVelocityY = dataTypes.ReadNextFloat(packetData);
    float playerVelocityZ = dataTypes.ReadNextFloat(packetData);

    handler.OnExplosion(explosionLocation, explosionStrength, explosionBlockCount);
    break;
```

**Comment by milutinke** [comment]
Fixed, download the latest build, it will be available in 1-2 minutes.

**Comment by Yejia995** [comment]
Thank you so much for helping!
