### ISSUE TITLE
Error opening minecraft afk in vds?

### ISSUE THREAD

**Issue by Nivelll** [MCCTeam/Minecraft-Console-Client#2198]
I am constantly getting an error when trying to open console minecraft on my machine (VDS), for example the following figure;
The server I'm trying to connect to is currently an active server, but I can't connect in any way.

![1111](https://user-images.githubusercontent.com/114316692/192120994-761931ba-f65b-416b-8ec0-7628dac892ba.png)

**Comment by milutinke** [comment]
Seems like you're trying to play on a server that has non vanilla/notchian software, that could be cause of the issue.

**Comment by milutinke** [comment]
Closing due to being stale.
