### ISSUE TITLE
[BUG] My bot not moving

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2199]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

latest

### Expected Behavior

my bot moving and following

### Actual Behavior

my bot not moving and following

### Steps to Reproduce the bug

1. connect to server mc.hollyworld.ru
2. use command /useitem
3. use command /inventory 1 click 15
4. use command /inventory 2 click 10
5. you kicking and you dont moving and following player
6. to see use real minecraft

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

mc.hollyworld.ru

**Comment by milutinke** [comment]
Have you enabled terrain handling and entity handling, as well as the follow player chat bot?

**Comment by deosync** [comment]
ye his true

**Comment by milutinke** [comment]
The server has an anti bot system, could not even connect. That is the reason you probably was kicked. Nothing we could about it. You'll have to contact the server owner for an exemption in the plugin.

**Comment by milutinke** [comment]
Also, one more thing, in order for the bot to follow you, you need to start walking and be some distance from him, because he will not follow you if you're too close.
You can tweak `stop_at_distance` setting to your taste.
