### ISSUE TITLE
[Idea] Add an icon to an exe file.

### ISSUE THREAD

**Issue by ShaniZ-VK** [MCCTeam/Minecraft-Console-Client#2201]
### Prerequisites

- [x] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

v1.19.2

### Describe your problem

I tried to add an icon to the console using the Resource Hacker program, but the console closed immediately after opening. Please set the file icon.
![LLDhE](https://user-images.githubusercontent.com/66040895/192160356-acdde4e0-75b6-45ce-917a-ebd0a7303086.png)
I took the picture from the site icon

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
There already is an icon, it's when you log in the icon of the program becomes your Minecraft skin, tho this is only on Windows.

**Comment by breadbyte** [comment]
I think they meant adding an icon to the executable file itself.

**Comment by milutinke** [comment]
It has one.
![image](https://user-images.githubusercontent.com/441903/192528113-0cdfe4c0-fd22-463c-9426-8133a05d301a.png)
