### ISSUE TITLE
[Question]  Map Downloader

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2211]
Hi Guys! I knew that issue is duplicate, but are it possible now to download captcha Map after addind full Map DataPacket? 
I think it is possible with ChatBot, do u have something similar?
Thanks a lot!

**Comment by milutinke** [comment]
Being worked on, I updated the MapData packet and tested it on all versions 1.8+

![image](https://user-images.githubusercontent.com/441903/192515688-53bba4ca-2b62-4f87-875e-d1b9a0d3b678.png)

**Comment by Sergapr** [comment]
> Being worked on, I updated the MapData packet and tested it on all versions 1.8+, now working on the chat bot itself.
> 
> ![image](https://user-images.githubusercontent.com/441903/192515688-53bba4ca-2b62-4f87-875e-d1b9a0d3b678.png)

Thanks a lot, good luck bro)
we just have to wait)

**Comment by milutinke** [comment]
@Sergapr Implemented in #2215
