### ISSUE TITLE
[Question] Commands with coordinate argument?

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2212]
Hi dears, i just have a question.
It is possible to send commands with coordinate arguments?
For example, I send a command in console "/send I am at X Y Z" and it send to chat on server "I am at -120 65 2355" (for exaple)
Or if i want to change coordinates i send a command in console "/send //pos1 X+130 Y-120 Z+1" and if a am on coordinates 1 1 1
it type to chat "//pos1 130 -119 2"

**Comment by milutinke** [comment]
You can use the C# [`ChatBot API`](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Scripting/ChatBot.cs) to send text/commands with anything in them, currently ordinary commands to not have this option.
You can read [this](https://mccteam.github.io/guide/creating-bots.html) to get started with creating your own chat bots.

**Comment by milutinke** [comment]
The full script:
```csharp
//MCCScript 1.0

MCC.LoadBot(new SendPositionBot());

//MCCScript Extensions

public class SendPositionBot : ChatBot
    {
        public override void Initialize()
        {
            RegisterChatBotCommand("sendlocation", "Sends my location", "sendlocation", SendLocationCommand);
            RegisterChatBotCommand("sendpos", "Sends //pos command", "sendpos", SendPosCommand);
        }

        public string SendLocationCommand(string command, string[] args)
        {
            Location currentLocation = GetCurrentLocation();
            SendText("I am at " + currentLocation.X + " " + currentLocation.Y + " " + currentLocation.Z);
            return "Sent!";
        }

        public string SendPosCommand(string command, string[] args)
        {
            Location currentLocation = GetCurrentLocation();
            SendText("//pos1 X" + currentLocation.X + " Y" + currentLocation.Y + " Z" + currentLocation.Z);
            return "Sent!";
        }
    }
```

**Comment by Sergapr** [comment]
> The full script:
> 
> ```cs
> //MCCScript 1.0
> 
> MCC.LoadBot(new SendPositionBot());
> 
> //MCCScript Extensions
> 
> public class SendPositionBot : ChatBot
>     {
>         public override void Initialize()
>         {
>             RegisterChatBotCommand("sendlocation", "Sends my location", "sendlocation", SendLocationCommand);
>             RegisterChatBotCommand("sendpos", "Sends //pos command", "sendpos", SendPosCommand);
>         }
> 
>         public string SendLocationCommand(string command, string[] args)
>         {
>             Location currentLocation = GetCurrentLocation();
>             SendText("I am at " + currentLocation.X + " " + currentLocation.Y + " " + currentLocation.Z);
>             return "Sent!";
>         }
> 
>         public string SendPosCommand(string command, string[] args)
>         {
>             Location currentLocation = GetCurrentLocation();
>             SendText("//pos1 X" + currentLocation.X + " Y" + currentLocation.Y + " Z" + currentLocation.Z);
>             return "Sent!";
>         }
>     }
> ```

Thanks a lot, it is working. but plugin on server asks a coordinates without values after ","
This script send with it
![image](https://user-images.githubusercontent.com/106835861/192535676-20bfcb61-ff8f-442f-b1bb-74cec08666a8.png)
it will send 280, 63, 281

**Comment by Sergapr** [comment]
It is implemented in /move command and works cool!
I think it is good feauture to add a "~ ~ ~"  in console client for use without chatbots
For expample u can dig blocks with /dig ~ ~-1 ~   eth

**Comment by milutinke** [comment]
> It is implemented in /move command and works cool! I think it is good feauture to add a "~ ~ ~" in console client for use without chatbots For expample u can dig blocks with /dig ~ ~-1 ~ eth

That is supported by `/useblock` and `/move`, I'll see if I can add it to `/dig`

**Comment by milutinke** [comment]
> > The full script:
> > ```cs
> > //MCCScript 1.0
> > 
> > MCC.LoadBot(new SendPositionBot());
> > 
> > //MCCScript Extensions
> > 
> > public class SendPositionBot : ChatBot
> >     {
> >         public override void Initialize()
> >         {
> >             RegisterChatBotCommand("sendlocation", "Sends my location", "sendlocation", SendLocationCommand);
> >             RegisterChatBotCommand("sendpos", "Sends //pos command", "sendpos", SendPosCommand);
> >         }
> > 
> >         public string SendLocationCommand(string command, string[] args)
> >         {
> >             Location currentLocation = GetCurrentLocation();
> >             SendText("I am at " + currentLocation.X + " " + currentLocation.Y + " " + currentLocation.Z);
> >             return "Sent!";
> >         }
> > 
> >         public string SendPosCommand(string command, string[] args)
> >         {
> >             Location currentLocation = GetCurrentLocation();
> >             SendText("//pos1 X" + currentLocation.X + " Y" + currentLocation.Y + " Z" + currentLocation.Z);
> >             return "Sent!";
> >         }
> >     }
> > ```
> 
> Thanks a lot, it is working. but plugin on server asks a coordinates without values after "," This script send with it ![image](https://user-images.githubusercontent.com/106835861/192535676-20bfcb61-ff8f-442f-b1bb-74cec08666a8.png) it will send 280, 63, 281

Wrap all `currentLocation.<something>` with `Math.Round()`, example: `Math.Round(currentLocation.X)`

**Comment by milutinke** [comment]
> It is implemented in /move command and works cool! I think it is good feauture to add a "~ ~ ~" in console client for use without chatbots For expample u can dig blocks with /dig ~ ~-1 ~ eth

Added in #2219

**Comment by breadbyte** [comment]
It might be useful to add a helper class for coordinates in the future, so we don't need to manually add support for relative coordinates (we might even be able to expose it to the scripting system)

**Comment by milutinke** [comment]
> It might be useful to add a helper class for coordinates in the future, so we don't need to manually add support for relative coordinates for every bot that needs it (we might even be able to expose it to the scripting system)

Indeed.
I'll look into this tomorrow.
