### ISSUE TITLE
[BUG] AutoFish bug

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2213]
Hi guys! I have a problem with AutoFish on lastet version of MCC.
MCC dont use the ini file configuration and I have some logs about it in console.

[MCC] Failed to convert '0.4' into an integer. Please check your settings.
[MCC] Failed to convert '0.002' into an integer. Please check your settings.
[MCC] Failed to convert '0.2' into an integer. Please check your settings.
![image](https://user-images.githubusercontent.com/106835861/192502566-a24c2f7c-99b2-4383-a496-00e546384fea.png)

**Comment by ReinforceZwei** [comment]
An integer is a number without the dot (.)

Check your config file and correct the value.

**Comment by Sergapr** [comment]
> An integer is a number without the dot (.)
> 
> Check your config file and correct the value.

But it is a default value, will it work correctly if I change it?

**Comment by ReinforceZwei** [comment]
Can you show your config?

**Comment by Sergapr** [comment]
I changed default values and now there are no warnings in console, but i have new problem, 
fish biting, but bot dont catch it.
My ini file config
![image](https://user-images.githubusercontent.com/106835861/192527231-95a5d98a-1832-4642-8081-62be2f3140be.png)
Minecraft version 1.16.5

**Comment by Sergapr** [comment]
I can create a new issue 
if that's better.

**Comment by ReinforceZwei** [comment]
@milutinke

**Comment by Sergapr** [comment]
https://user-images.githubusercontent.com/106835861/192528389-d4b616da-28f2-4451-941f-f17ae69f90b8.mp4

**Comment by Sergapr** [comment]
I am testing it on my server now, if u want u can connect too

**Comment by milutinke** [comment]
> @milutinke

It was updated by @breadbyte , I'm not familiar with the code, but from what I see the values in @Sergapr config file are not double/float.

**Comment by Sergapr** [comment]
I have warning in console
![image](https://user-images.githubusercontent.com/106835861/192530307-99fb46ce-7161-47e0-9f4b-66203593c661.png)
(issue title)

**Comment by milutinke** [comment]
> I have warning in console ![image](https://user-images.githubusercontent.com/106835861/192530307-99fb46ce-7161-47e0-9f4b-66203593c661.png) (issue title)

Which build of the client are you using?

**Comment by Sergapr** [comment]
https://user-images.githubusercontent.com/106835861/192530576-77643074-9b5e-495f-a89d-4297c7ac451d.mp4

I have this, if ignore warning in console

**Comment by Sergapr** [comment]
[20220927-73](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220927-73)

**Comment by Sergapr** [comment]
> > I have warning in console ![image](https://user-images.githubusercontent.com/106835861/192530307-99fb46ce-7161-47e0-9f4b-66203593c661.png) (issue title)
> 
> Which build of the client are you using?

[20220927-73](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220927-73)

**Comment by breadbyte** [comment]
> It was updated by @breadbyte

Which one did I touch? I don't remember ever messing with any of the bots' code other than some minor changes for the console handler

**Comment by milutinke** [comment]
> > > I have warning in console ![image](https://user-images.githubusercontent.com/106835861/192530307-99fb46ce-7161-47e0-9f4b-66203593c661.png) (issue title)
> > 
> > 
> > Which build of the client are you using?
> 
> [20220927-73](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220927-73)

With default settings I do not get those warnings, however the bot does not catch the fish at all. 
No idea, we'll have to wait for @BruceChenQAQ

**Comment by Sergapr** [comment]
> > > > У меня есть предупреждение в консоли ![изображение](https://user-images.githubusercontent.com/106835861/192530307-99fb46ce-7161-47e0-9f4b-66203593c661.png)(название проблемы)
> > > 
> > > 
> > > Какую сборку клиента используете?
> > 
> > 
> > [20220927-73](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220927-73)
> 
> С настройками по умолчанию я не получаю этих предупреждений, однако бот вообще не ловит рыбу. Без понятия, будем ждать@BruceChenQAQ

In default ini settings autofishing
enabled = false
Change it to true and try again

**Comment by milutinke** [comment]
> > > > > У меня есть предупреждение в консоли ![изображение](https://user-images.githubusercontent.com/106835861/192530307-99fb46ce-7161-47e0-9f4b-66203593c661.png)(название проблемы)
> > > > 
> > > > 
> > > > Какую сборку клиента используете?
> > > 
> > > 
> > > [20220927-73](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220927-73)
> > 
> > 
> > С настройками по умолчанию я не получаю этих предупреждений, однако бот вообще не ловит рыбу. Без понятия, будем ждать@BruceChenQAQ
> 
> In default ini settings autofishing enabled = false Change it to true and try again

It is enabled, however it does not catch a fish at all.

**Comment by Sergapr** [comment]
He threw a fishing_rod and dont catch it simmilar on video?

**Comment by Sergapr** [comment]
@milutinke, I am sorry, but I think it take a lot of time to wait @BruceChenQAQ answer. Can we create a MCC version with all new features, but without auto fish upgrade?(create mcc with old autofish future)

**Comment by Sergapr** [comment]
> > > > > > У меня есть предупреждение в консоли ![изображение](https://user-images.githubusercontent.com/106835861/192530307-99fb46ce-7161-47e0-9f4b-66203593c661.png)(название проблемы)
> > > > > 
> > > > > 
> > > > > Какую сборку клиента используете?
> > > > 
> > > > 
> > > > [20220927-73](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220927-73)
> > > 
> > > 
> > > С настройками по умолчанию я не получаю этих предупреждений, однако бот вообще не ловит рыбу. Без понятия, будем ждать@BruceChenQAQ
> > 
> > 
> > In default ini settings autofishing enabled = false Change it to true and try again
> 
> It is enabled, however it does not catch a fish at all.

are entityhandling is enabled?

**Comment by BruceChenQAQ** [comment]
> > > > I have warning in console ![image](https://user-images.githubusercontent.com/106835861/192530307-99fb46ce-7161-47e0-9f4b-66203593c661.png) (issue title)
> > > 
> > > 
> > > Which build of the client are you using?
> > 
> > 
> > [20220927-73](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220927-73)
> 
> With default settings I do not get those warnings, however the bot does not catch the fish at all. No idea, we'll have to wait for @BruceChenQAQ

This error occurs when "double.TryParse" fails (I forgot to change the translation).
Can you provide the configuration file where the error occurred and the version of .NET?

About the problem of not catching fish, please change "A=B" in the settings and attach some logs.

**Comment by BruceChenQAQ** [comment]
> auto.fish.bug.mp4

The reason for not being able to catch fish in this video is that ``hook_threshold`` is set too high resulting in no fish bites being recognized (default value is 0.2, here 1.0) and ``stationary_threshold`` is also too high which may lead to a high false positive rate.

**Comment by Sergapr** [comment]
> > > > > У меня есть предупреждение в консоли ![изображение](https://user-images.githubusercontent.com/106835861/192530307-99fb46ce-7161-47e0-9f4b-66203593c661.png)(название проблемы)
> > > > 
> > > > 
> > > > Какую сборку клиента используете?
> > > 
> > > 
> > > [20220927-73](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20220927-73)
> > 
> > 
> > С настройками по умолчанию я не получаю этих предупреждений, однако бот вообще не ловит рыбу. Без понятия, будем ждать@BruceChenQAQ
> 
> Эта ошибка возникает при сбое "double.TryParse" (я забыл изменить перевод). Можете ли вы предоставить файл конфигурации, в котором произошла ошибка, и версию .NET?
> 
> По поводу проблемы с не ловлей рыбы, пожалуйста, измените `log_fishing_bobber=true`в настройках и прикрепите несколько логов.
> 
> Причина невозможности поймать рыбу в `auto.fish.bug.mp4`том, что `hook_threshold`установлено слишком высокое значение, в результате чего поклевки не обнаруживаются (значение по умолчанию 0,2, здесь 1,0).
> 
> Чрезмерно высокий уровень `stationary_threshold`может привести к высокому уровню ложных срабатываний. (как показано на `autofish.problem.2.mp4`)
> 
> Далее я обновлю документацию по авторыбалке. Извините, что не обновил вовремя, я был немного занят некоторое время назад.

Ok, thank u very much.
I guessed that problem related to configuration, but now I cant start a MCC with defauld ini settings.
Will wait a update. 
Thanks again

**Comment by BruceChenQAQ** [comment]
Fixed in #2234
