### ISSUE TITLE
[Bug] MCC send Bad Packets.

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2217]
Hi guys! I have a very big problem.
Up to this day i used a old MCC version(Minecraft Console Client v1.18.1) and it worked well and work well still now.
But today Was realesed a new version of MCC(Minecraft Console Client v1.19.2) which have a really cool tool(Map saving)
Minecraft version:1.16.5 but i testet also on new minecraft versions, zero results
Problem: When i just connect to server with new MCC version and connect minegame servers AntiChet kicks me with reason Bad Packets. after +-30seconds
But if i connect with old MCC version it works well!
I really need a new Map Saving feauture and your help.
And also AutoFishing dont working after upgrading by @BruceChenQAQ (I hope u read this and #2213 issue)
@milutinke read my issue 1 more time pls)
Waiting for your reply, thanks.  

Server: mc.holyworld.ru

minigame connect manual:
/useitem
/inventory 1 click 11
/inventory 2 click 10

[NEW.txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/9667018/NEW.txt)
[OLD.txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/9667031/OLD.txt)
There are also NEW mcc version config whith dont work correctly and OLD mcc version config which works well
Sorry for my bag English
Hope to your support. <3

**Comment by milutinke** [comment]
I can not re-create the problem, every version works well
1.16.5:
![image](https://user-images.githubusercontent.com/441903/192846261-ba2da9b7-2ed2-4863-bacb-a418b16bcd75.png)

**Comment by milutinke** [comment]
Also, do not ping people multiple times, this is an open source project, people work on it when they have some time and motivation, we here are not obliged to solve things in some time period or at all.
You should respect peoples time.

**Comment by Sergapr** [comment]
Oh, I am so sorry, my bad,
Thank u very much for your help. 
May be I will install another .NET version? Not 6.0?

**Comment by breadbyte** [comment]
We could compare the packets being sent from the previous version with the new one.
Bad Packets is a _very_ generic term that just simply means something is wrong with the packets the client is sending.

It could be that the client is sending way too many packets at a short amount of time, sending packets that the server did not expect, or some packets are malformed, very hard to tell with very little information.

We could create a simple replicable testbed with various configurations and anticheat providers so we can verify our movement and/or packet code.

**Comment by deosync** [comment]
just set this on autofish antidespawn=false

============================
 просто поменяй в авто рыбалке эту херню antidespawn=true на эту antidespawn=false 
я знаю что ты русский ведь ты играеш на холике)

**Comment by Sergapr** [comment]
> We could compare the packets being sent from the previous version with the new one.
> 
> Bad Packets is a _very_ generic term that just simply means something is wrong with the packets the client is sending.
> 
> 
> 
> It could be that the client is sending way too many packets at a short amount of time, sending packets that the server did not expect, or some packets are malformed, very hard to tell with very little information.
> 
> 
> 
> We could create a simple replicable testbed with various configurations and anticheat providers so we can verify our movement and/or packet code.

It will be cool,now I can't use new features because it.
Will it take a lot of time?

**Comment by BruceChenQAQ** [comment]
Link to https://github.com/MCCTeam/Minecraft-Console-Client/pull/2226
