### ISSUE TITLE
[BUG] Cant open MCC

### ISSUE THREAD

**Issue by truong0235** [MCCTeam/Minecraft-Console-Client#2220]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

Auto (i think cause i havent recieved config.ini file)

### Console Client Version

Latest

### Expected Behavior

open MCC normally

### Actual Behavior

It pop up and close right after i open it

### Steps to Reproduce the bug

1. download brand new MCC
2. extrac it
3. run the file

### Device

Laptop

### Operating System

Windows

**Comment by breadbyte** [comment]
You need to install .NET 6.0 [here](https://dotnet.microsoft.com/en-us/download).

**Comment by truong0235** [comment]
sorry for respond late
i installed .net 6.0 and it worked (my bad again, i tried it on a new lap, so i didnt notice that)
