### ISSUE TITLE
Downloading the source code as zip causes building Minecraft Console Client to fail

### ISSUE THREAD

**Issue by Skylandia** [MCCTeam/Minecraft-Console-Client#2230]
Using the readme's [Building from the source](https://github.com/MCCTeam/Minecraft-Console-Client#building-from-the-source-%EF%B8%8F) guide:
The [source code .zip file](https://mccteam.github.io/guide/installation.html#downloading-the-source-code-as-a-zip) doesn't include [breadbyte's ConsoleInteractive repository](https://github.com/breadbyte/ConsoleInteractive/tree/7acaa0ab31809f0f6512e6a76e53e15441de8e7c), and instead has an empty folder named ConsoleInteractive.

I was able to build the Minecraft Console Client after downloading [breadbyte's ConsoleInteractive repository as a .zip file](https://github.com/breadbyte/ConsoleInteractive/archive/7acaa0ab31809f0f6512e6a76e53e15441de8e7c.zip) and replacing my original empty folder (named ConsoleInteractive) with breadbyte's repo, but this may be troublesome for future developers looking to build MCC from the source.

**Comment by milutinke** [comment]
I'll remove a reference to downloading a Zip from the documentation, most of people use git anyway.

**Comment by milutinke** [comment]
Done.
