### ISSUE TITLE
Crash when open chest

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2245]
![image](https://user-images.githubusercontent.com/106835861/194324312-15495154-a9a7-4a79-980f-1ad386a2ece7.png)
MCC crash when open large chest (work on old version, but dont work on new)

**Comment by breadbyte** [comment]
Looks like it's happening here (given the equality operator in the stack trace references nullable, this is the only equality operator with nullable parameters): https://github.com/MCCTeam/Minecraft-Console-Client/blob/e92f4497496efdcce0f646e8ee766961005e8748/MinecraftClient/Mapping/Location.cs#L298-L305

It seems to be stuck in an infinite loop checking equality with itself and `null`.

**Comment by BruceChenQAQ** [comment]
> Looks like it's happening here (given the equality operator in the stack trace references nullable, this is the only equality operator with nullable parameters):
> 
> https://github.com/MCCTeam/Minecraft-Console-Client/blob/e92f4497496efdcce0f646e8ee766961005e8748/MinecraftClient/Mapping/Location.cs#L298-L305
> 
> It seems to be stuck in an infinite loop checking equality with itself and `null`.

Yes, try to fix it in https://github.com/MCCTeam/Minecraft-Console-Client/commit/a98438131fe6dd64ee87c78f1553db5e3d3b70f7

**Comment by BruceChenQAQ** [comment]
Try using the latest release

**Comment by Sergapr** [comment]
It is works, thank u very much.
btw, after player close a window, on the next opening he open second window, but the first window is closed.
Idk, may be it is not a bug.
Thanks a lot bro, you have helped me many times. Thank you for making MCC better. 
![image](https://user-images.githubusercontent.com/106835861/194366148-b4d91966-c16f-4a8f-94f4-23334b8d0132.png)


> Try using the latest release

**Comment by Sergapr** [comment]
I think it is not but, sorry
Tkanks again
