### ISSUE TITLE
[Idea]  Baritone like bots

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2247]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

use mining ores with baritone and use baritone for movement 

### Minecraft Version

1.16.5

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
We already have the idea on the table.
The thing is that baritone is written in Java and uses Minecraft code through mod api, while the  MCC is an implementation of Minecraft protocol in C#.
What we could do is learn from and replicate some parts of the code for features which are better than current MCC implementations.

**Comment by milutinke** [comment]
We already have the idea on the table.
The thing is that baritone is written in Java and uses Minecraft code through mod api, while the  MCC is an implementation of Minecraft protocol in C#.
What we could do is learn from and replicate some parts of the code for features which are better than current MCC implementations.

I'm working on a farm bot for the MCC similar to baritone one functionality wise, and then I'll look into Ore miner.
But the underlaying movement and obstacles overcoming code needs to be improved.
Currently the MCC can't jump, swim or climb up/down ladders and vines, or walk under half slabs by crouching.
For that we could replicate what Baritone or BotCraft are doing.

**Comment by breadbyte** [comment]
Using baritone is easier said than done.

We would have to translate the entirety of baritone from Java to C# _and then_ implement forge/fabric functions that baritone uses.

It would be like if you wanted to modify your regular car to have a race car engine. Sure, it's possible, but it would take a lot of work for it to be functional.

**Comment by deosync** [comment]
ok
