### ISSUE TITLE
[Feature] Auto-Captcha.

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2249]
Hi guys. I just have a question. It is possible to make an auto captcha bypass? 
MCC already can save an picture with map(captcha) in the folder(tkanks milutinke).
So, can it be added
in feature to type a number from map into console? 
It is not problem to write a captcha once a day, but when u have 10 or 20 AFK accounts it is so annoying.

My friend realised it, but he used mineflayer

**Comment by breadbyte** [comment]
This has been discussed as won't implement.
See ORelio's stance on the issue here:


![image](https://user-images.githubusercontent.com/14045257/194644895-cc3ac597-ada3-4666-b13a-43ad1a1d81d2.png)

**Comment by 678435021** [comment]
> It is not problem to write a captcha once a day, but when u have 10 or 20 AFK accounts it is so annoying.
> 
> My friend realised it, but he used mineflayer

@Sergapr  Maybe something like this could help?

![amogus](https://user-images.githubusercontent.com/110736028/194759693-43358751-fc3c-462b-b9ef-f62558a35619.svg)

**Comment by Sergapr** [comment]
> > It is not problem to write a captcha once a day, but when u have 10 or 20 AFK accounts it is so annoying.
> 
> > 
> 
> > My friend realised it, but he used mineflayer
> 
> 
> 
> @Sergapr  Maybe something like this could help?
> 
> 
> 
> from https://github.com/MC-Terminal/minecraft-terminal
> 
> 
> 
> ![amogus](https://user-images.githubusercontent.com/110736028/194759693-43358751-fc3c-462b-b9ef-f62558a35619.svg)
> 
> 

Look so good, thanks. But I am about automatic passing a captcha.

**Comment by milutinke** [comment]
Well, learn C# and find a good OCR library.

**Comment by Sergapr** [comment]
I didn't mean to offend you, if ORelio thinks this is a dangerous feature you shouldn't add it.
Sorry if offended

**Comment by milutinke** [comment]
> I didn't mean to offend you, if ORelio thinks this is a dangerous feature you shouldn't add it. Sorry if offended

No one was offended.
We have said multiple times that this won't be added, no need to open an issue over the feature after it has been said already.

**Comment by milutinke** [comment]
The MCC can now render maps inside the console.

**Comment by Sergapr** [comment]
> The MCC can now render maps inside the console.

Wow! It is really useful feature. Thanks! Good job 👍

**Comment by Sergapr** [comment]
> The MCC can now render maps inside the console.

What about make a rendered in console map smaller?

**Comment by milutinke** [comment]
> > The MCC can now render maps inside the console.
> 
> What about make a rendered in console map a bit smaller?

It auto scales to your terminal size.
