### ISSUE TITLE
Remote controle (Rus)

### ISSUE THREAD

**Issue by WakizashiPC** [MCCTeam/Minecraft-Console-Client#2252]
На сервере где я играю русские символы когда тебе пишут консоль поддерживает только английские (типо whisper to you)  как сделать что-бы работало и с русскими буквами?

On the server where I play Russian characters when they write to you, the console supports only English (like whisper to you) how to make something work with Russian letters?
![image](https://user-images.githubusercontent.com/115373399/194726683-1cc76e78-ac96-4dcd-8504-9c890abaaecf.png)

**Comment by milutinke** [comment]
https://mccteam.github.io/guide/configuration.html#chat-format

**Comment by stalsov** [comment]
Ок

**Comment by TheEndToCTPAX** [comment]
Вакашизаши нищий

**Comment by WakizashiPC** [comment]
> Ок

ок
