### ISSUE TITLE
[BUG] AutoFishing does not catch junk/treasure

### ISSUE THREAD

**Issue by br0gio** [MCCTeam/Minecraft-Console-Client#2256]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

Latest v1.19.2

### Expected Behavior

AutoFishing fishes junk/treasure

### Actual Behavior

AutoFishing does not check how deep the water is, so you only catch fish.

### Steps to Reproduce the bug

1. Start AutoFishing

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/93214699/194767856-fc5a73e9-5dc7-42de-bc80-dda89a5f0be3.png)
![image](https://user-images.githubusercontent.com/93214699/194767879-79b49de6-8461-4a25-af4e-eda4c0c44db8.png)

### Anythings that could help diagnosing the bug

```txt
I'm fishing with a maxed out fishing rod, and fished 100 times but got nothing but fish. I doubt this is very bad luck.
More info about how fishing works in the attached screenshot.
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

tqmc.org (I can fish junk/treasure with mcc btw) and the server has no anti cheat for fishing

**Comment by br0gio** [comment]
EDIT: it just doesn't show that it fishes other things inside of the console (this should be added though)

**Comment by not-Ambrose** [comment]
perhaps it's trying to fish in a 1 block deep water area? cause u cant get treasure in a 1 block area irrc only fish

**Comment by BruceChenQAQ** [comment]
Implemented in https://github.com/MCCTeam/Minecraft-Console-Client/pull/2280
