### ISSUE TITLE
[Bug] BadPackets

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2257]
Hi guys! Hi Bruce. I have a BadPackets problem again...
Today servers admin updated AntiCheat system and bot have been kicked after 3 seconds after join minigame. I have no idea how to fix it. 
How to reproduce?
1. Download any version of MCC
2. Enable inventory handling and Map in ini file.
3. Join server mc.holyworld.ru using Minecraft version 1.16.5 or newer 
4. Type a captcha code from folder Rendered Maps
Hope you help.
5. Register on server (/reg Lollol123 Lollol123)
6. Type /useitem
7. Type /inventory 1 click 11
8. Type /inventory 2 click 15
9. Now u are on minigame, and u will be kicked after 2-3 seconds.
Thanks.

**Comment by Werewolf6845** [comment]
Hello, I join the post above, I found out that freecam kicks

**Comment by Sergapr** [comment]
> Hello, I join the post above, I found out that freecam kicks

Are u playing HolyWorld too?

**Comment by Werewolf6845** [comment]
> > Hello, I join the post above, I found out that freecam kicks
> 
> Are u playing HolyWorld too?

yes

**Comment by Sergapr** [comment]
> > > Hello, I join the post above, I found out that freecam kicks
> 
> > 
> 
> > Are u playing HolyWorld too?
> 
> 
> 
> yes

Nick?

**Comment by Werewolf6845** [comment]
what does this have to do with the topic?

>

**Comment by Sergapr** [comment]
Nothing. I just want know who are u

**Comment by BruceChenQAQ** [comment]
> May be it is because TickTimeout?

Try using the last release, and check if this issue been fixed.

**Comment by Sergapr** [comment]
> > May be it is because TickTimeout?
> 
> Try using the last release, and check if this issue been fixed.

![image](https://user-images.githubusercontent.com/106835861/194843875-13d5f548-138a-4012-b403-9d80ee43ef59.png)
Not fixed(

**Comment by BruceChenQAQ** [comment]
> > > May be it is because TickTimeout?
> > 
> > 
> > Try using the last release, and check if this issue been fixed.
> 
> ![image](https://user-images.githubusercontent.com/106835861/194843875-13d5f548-138a-4012-b403-9d80ee43ef59.png) Not fixed(

I'll be a little busy for a few days, so I'll check back on this afterwards.

**Comment by Sergapr** [comment]
Yes, sure, thank u for answering

**Comment by Werewolf6845** [comment]
> > > > May be it is because TickTimeout?
> > > 
> > > 
> > > Try using the last release, and check if this issue been fixed.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/106835861/194843875-13d5f548-138a-4012-b403-9d80ee43ef59.png) Not fixed(
> 
> I'll be a little busy for a few days, so I'll check back on this afterwards.

I already wrote above, but I repeat, I contacted the server administrator why the kick from the server, he answered that it kicks because the anti-cheat was updated on the server and it kicks the bot because it is used by freecam

**Comment by not-Ambrose** [comment]
they fixed it u just gotta update it so yeah

**Comment by Werewolf6845** [comment]
I just updated to the latest version, they even asked me to reinstall MinecraftClient.ini, in general I went to the server and now it kicks not immediately, but only after a minute. But the reasons are now 2 (appear randomly) are BadPackets and TimeOut

**Comment by Sergapr** [comment]
> I just updated to the latest version, they even asked me to reinstall MinecraftClient.ini, in general I went to the server and now it kicks not immediately, but only after a minute. But the reasons are now 2 (appear randomly) are BadPackets and TimeOut

cant reproduce, I am using latest mcc version, but it kicks after 2-3 secconds after join. (Minegame - SpeedRun anarchy)

**Comment by Sergapr** [comment]
Ok, I am tested almost all releases and there are no one which don't kicks by server. All have one problem- BadPackets kick 😔

**Comment by milutinke** [comment]
It is the problem with anticheat itself.

**Comment by Werewolf6845** [comment]
> It is the problem with anticheat itself. No other people are reporting this problem on other servers to my knowledge.

Tested version 1.18.1-2 Kicks after 9-10 seconds due to BadPackets
On version 1.16.1-5 kicks after a minute due to Timed out

**Comment by BruceChenQAQ** [comment]
Now we are able to reproduce the issue locally and are trying to fix it.

**Comment by Sergapr** [comment]
> Now we are able to reproduce the issue locally and are trying to fix it.

I am glad to read this. Good luck

**Comment by BruceChenQAQ** [comment]
It is now possible to stay in that server for a long time without being kicked out.
However, local tests show that making a move will still be detected as cheating.
To do this without being detected as an abnormal move would require a very accurate simulation of the vanilla client's move behavior, and we don't have enough developers to do this yet.

**Comment by Sergapr** [comment]
> It is now possible to stay in that server for a long time without being kicked out.
> 
> However, local tests show that making a move will still be detected as cheating.(The administrator can set how many times abnormal behavior is detected before kicking the player out, so this will not be kicked out immediately.)
> 
> To do this without being detected as an abnormal move would require a very accurate simulation of the vanilla client's move behavior, and we don't have enough developers to do this yet.

Amazing job! Thank u very much.
I don't need moving, so being a long time in server and fishing is main task. 
When release will be ready?
Thanks again.

**Comment by BruceChenQAQ** [comment]
Try to use the latest release, all moves without Y-axis direction should be safe.

**Comment by Werewolf6845** [comment]
I tested it at night because there was no time before, 15 minutes without kicks, for clarity I started fishing. Thank you very much for the work done
![image](https://user-images.githubusercontent.com/75979792/196420132-03d394f2-90fe-41ae-81b6-b12b7af6ab20.png)
