### ISSUE TITLE
Automatic Reconnect

### ISSUE THREAD

**Issue by not-Ambrose** [MCCTeam/Minecraft-Console-Client#2260]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1.19.2

### Describe your problem

My internet is quite spotty, if you could add a toggleable auto reconnect, it would make this perfect for AFK-ing at afk farms.

### Suggest a possible solution

My internet is quite spotty, if you could add a toggleable auto reconnect, it would make this perfect for AFK-ing at afk farms.

### Minecraft Version

1.19.2

### Operating System

MacOS

**EDIT: IM A IDIOT I FORGOT TO READ THE FEATURES MENU**

**Comment by breadbyte** [comment]
Enable `AutoRelog` in the `MinecraftClient.ini` settings file.

**Comment by not-Ambrose** [comment]
thanks breadbyte

**Comment by BruceChenQAQ** [comment]
Remember to update to the latest release, which fixes AutoRelog's buggy delays.
