### ISSUE TITLE
need help running config file in mac

### ISSUE THREAD

**Issue by KILLERBOSS1475** [MCCTeam/Minecraft-Console-Client#2265]
how to run cosole clieent config file in mac os x

**Comment by not-Ambrose** [comment]
its in your users file. 
for me it was Macintosh>Users>MyUsername

**Comment by KILLERBOSS1475** [comment]
i still didnt find it
idk which one bc i downloaded sum console config but its for the windows one i think

**Comment by milutinke** [comment]
> i still didnt find it idk which one bc i downloaded sum console config but its for the windows one i think

I am not a mac user, but the config file should generate in the folder where the executable is when you run the program for the first time.

**Comment by KILLERBOSS1475** [comment]
> > i still didnt find it idk which one bc i downloaded sum console config but its for the windows one i think
> 
> I am not a mac user, but the config file should generate in the folder where the executable is when you run the program for the first time.

thats why i kinda confuse. when i download i got only the runner and it doesnt give me a zip file or when i run the console it doesnt generate any file

**Comment by ReinforceZwei** [comment]
Do you have .NET 6 installed?

**Comment by KILLERBOSS1475** [comment]
> Do you have .NET 6 installed?

what is that?

**Comment by milutinke** [comment]
> > Do you have .NET 6 installed?
> 
> what is that?

The Minecraft Console Client needs .NET Core 6 in order to work.
it is a runtime that executes applications made for it (in .NET).
To install .NET Core 6 on macOS, follow this guide: https://learn.microsoft.com/en-us/dotnet/core/install/macos

**Comment by zhaoyig** [comment]
> > > Do you have .NET 6 installed?
> > 
> > 
> > what is that?
> 
> The Minecraft Console Client needs .NET Core 6 in order to work. it is a runtime that executes applications made for it (in .NET). To install .NET Core 6 on macOS, follow this guide: https://learn.microsoft.com/en-us/dotnet/core/install/macos

Why is the .NET requirement not mentioned anywhere in the doc?

**Comment by breadbyte** [comment]
> Why is the .NET requirement not mentioned anywhere in the doc?

The latest builds no longer require downloading .NET separately.
If there are any other issues with the current build of MCC, please open a new issue instead of necroing resolved issues.
