### ISSUE TITLE
[BUG] Requires password even in offline mode

### ISSUE THREAD

**Issue by gamerrio** [MCCTeam/Minecraft-Console-Client#2266]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

Latest

### Expected Behavior

To start in offline mode

### Actual Behavior

The MCC is asking for Microsoft/ Minecraft account login even tho trying to use offline mode instead

### Steps to Reproduce the bug

1.  start MCC
2. 
3. 

### Anythings that could help diagnosing the bug

```txt
╰─λ ./MinecraftClient Gamerrio - localhost BasicIO
Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
§8[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: False
 triggerontime: True
 triggeroninterval: True
 timevalue: System.TimeSpan[]
 timeinterval: 75
 action: send /hello
§8[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: True
 triggerontime: False
 triggeroninterval: False
 timevalue: System.TimeSpan[]
 timeinterval: 56
 action: send /login pass
Color test: Your terminal should display [0123456789ABCDEF]: [§00§11§22§33§44§55§66§77§88§99§aA§bB§cC§dD§eE§fF§r]
§8[SessionCache] Initializing FileSystemWatcher for file: /home/rio/code/EZY-Console-Client/SessionCache.ini
§8No sessions could be loaded from disk
Please type the password for Gamerrio.

test
Connecting to Microsoft...
< 
< Host: login.live.com
< User-Agent: Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
< Accept: */*
< Connection: close
<
<
§aThe current setting is saved as MinecraftClient.ini```
```

### Device

Desktop

### Operating System

Linux

**Comment by milutinke** [comment]
Have you set the `Password` to `-`?

**Comment by gamerrio** [comment]
> Have you set the `Password` to `-`?
> Like this:  `Account = { Login = "milutinke2", Password = "-" } `

Well yep I have used - in command line when starting mcc you can even check it in the log I mentioned tho haven't edited anything in config except debug log.

**Comment by breadbyte** [comment]
The issue here seems to be that passing in the password through the command-line arguments doesn't work.

Putting dash as a password on the `Account` section in the `MinecraftClient.ini` file seems to work just fine.

**Comment by milutinke** [comment]
![image](https://user-images.githubusercontent.com/441903/195283003-4e8385aa-f99e-479d-add8-d6b43f3bd05d.png)
Try wrapping the `-` with `""`, for me it works.

**Comment by gamerrio** [comment]
> 

``` ╰─λ ./MinecraftClient Gamerrio "-" localhost BasicIO
Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
§8[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: False
 triggerontime: True
 triggeroninterval: True
 timevalue: System.TimeSpan[]
 timeinterval: 75
 action: send /hello
§8[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: True
 triggerontime: False
 triggeroninterval: False
 timevalue: System.TimeSpan[]
 timeinterval: 56
 action: send /login pass
Color test: Your terminal should display [0123456789ABCDEF]: [§00§11§22§33§44§55§66§77§88§99§aA§bB§cC§dD§eE§fF§r]
§8[SessionCache] Initializing FileSystemWatcher for file: /home/rio/code/EZY-Console-Client/SessionCache.ini
§8No sessions could be loaded from disk
Please type the password for Gamerrio.
```

Nope no luck maybe issue with linux binaries?

**Comment by BruceChenQAQ** [comment]
Should be fixed in the latest release.
