### ISSUE TITLE
[Question] Similar programs?

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2269]
Hi guys! Do u know any programs similar MCC
With a lot of features?

**Comment by deosync** [comment]
what exactly does not suit you in mcc

что именно тебя не устраивает в  mcc

**Comment by Sergapr** [comment]
> what exactly does not suit you in mcc
> 
> 
> 
> что именно тебя не устраивает в  mcc

An #2257 issue

**Comment by 678435021** [comment]
What about https://github.com/MC-Terminal/minecraft-terminal

**Comment by breadbyte** [comment]
You can find a list of alternative clients here on [wiki.vg's Client List](https://wiki.vg/Client_List).

**Comment by Sergapr** [comment]
> You can find a list of alternative clients here on [wiki.vg's Client List](https://wiki.vg/Client_List).

Thanks a lot. MCC was a a best one. Will wait a fix.

**Comment by Sergapr** [comment]
> What about https://github.com/MC-Terminal/minecraft-terminal

Very cool, but there are some issues in Mc-term

**Comment by milutinke** [comment]
Try [BotCraft](https://github.com/adepierre/Botcraft) and [Mineflyer](https://mineflayer.prismarine.js.org/#/)

**Comment by Sergapr** [comment]
> Try [BotCraft](https://github.com/adepierre/Botcraft) and [Mineflyer](https://mineflayer.prismarine.js.org/#/)

Thanks a lot. But there are no ready to use projects like MCC, if i use Mineflayer i will learn a library.
So, MCC is the best one for me and i will wait a fix of BadPackets kick.

**Comment by TheEndToCTPAX** [comment]
> Try [BotCraft](https://github.com/adepierre/Botcraft) and [Mineflyer](https://mineflayer.prismarine.js.org/#/)

Это проблема холика, типо новый ач, вся хуйня. В майнфлеере это фиксанули версией 1.18, здесь нет.
Problem in server. New Anti-Cheat. In MineFlayer this fixed version 1.18.x. It doesn't help here

**Comment by Sergapr** [comment]
> > Try [BotCraft](https://github.com/adepierre/Botcraft) and [Mineflyer](https://mineflayer.prismarine.js.org/#/)
> 
> 
> 
> Это проблема холика, типо новый ач, вся хуйня. В майнфлеере это фиксанули версией 1.18, здесь нет.
> 
> Problem in server. New Anti-Cheat. In MineFlayer this fixed version 1.18.x. It doesn't help here

Yeah, I know, but it is not not only server problem.
MCC sending some incorrect packets which trigger Anti-Cheat system.
So, now we will find and fix it

**Comment by deosync** [comment]
it's quite strange, everything works for me without kicks on Holik, maybe because of the tomla of configs, try downloading the old version

**Comment by Sergapr** [comment]
> it's
Hi, do u mean HolyWorld?
Can u upload ur mcc folder like zip archive?

**Comment by deosync** [comment]
мне лень переводить поэтому я протестил и именно на speed run анархии кикакт

**Comment by milutinke** [comment]
> мне лень переводить поэтому я протестил и именно на speed run анархии кикакт

Bruce was able to recreate the problem locally so it should be fixed soon.
I got kicked by the anti cheat for using a vanila minecraft, tell the admin to tweak it a bit.

**Comment by milutinke** [comment]
As the issue has been fixed, I'll close this one.
I'll discuss with others about linking similar projects in the README.md
