### ISSUE TITLE
[BUG] Getting kicked with MCC for not signing commands

### ISSUE THREAD

**Issue by JIBSIL** [MCCTeam/Minecraft-Console-Client#2270]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [x] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

Latest

### Expected Behavior

The chat to appear

### Actual Behavior

The bot receives `You were kicked from lobby-9: [multiplayer.disconnect.unsigned_chat]` when using /ad or chatting

### Steps to Reproduce the bug

1. Join minehut.com on 1.19.2
2. Try to chat
3. You're prevented from chatting

### Device

VPS

### Operating System

Windows

### Server Address (If applicable)

minehut.com

**Comment by JIBSIL** [comment]
Edit: confirmed that after enabling chat signing, the issue only occurs with the /ad command which requires signing.

**Comment by BruceChenQAQ** [comment]
You need to enable these settings to sign messages properly:
`[Main.General]`
`AccountType = "microsoft"`

`[Signature]`
`LoginWithSecureProfile = true`
`SignChat = true`
`SignMessageInCommand = true`

**Comment by JIBSIL** [comment]
> You need to enable these settings to sign messages properly: `[Main.General]` `AccountType = "microsoft"`
> 
> `[Signature]` `LoginWithSecureProfile = true` `SignChat = true` `SignMessageInCommand = true`

```# Chat signature related settings (affects minecraft 1.19+)
[Signature]
LoginWithSecureProfile = true               # Microsoft accounts only. If disabled, will not be able to sign chat and join servers configured with "enforce-secure-profile=true"
SignChat = true                             # Whether to sign the chat send from MCC
SignMessageInCommand = true                 # Whether to sign the messages contained in the commands sent by MCC. For example, the message in "/msg" and "/me"
MarkLegallySignedMsg = false                # Use green  color block to mark chat with legitimate signatures
MarkModifiedMsg = true                      # Use yellow color block to mark chat that have been modified by the server.
MarkIllegallySignedMsg = true               # Use red    color block to mark chat without legitimate signature
MarkSystemMessage = false                   # Use gray   color block to mark system message (always without signature)
ShowModifiedChat = true                     # Set to true to display messages modified by the server, false to display the original signed messages
ShowIllegalSignedChat = true                # Whether to display chat and messages in commands without legal signatures```

**Comment by JIBSIL** [comment]
Right now that is my [Signature] section of the config. Chat doesn't send anything and /ad disconnects the client

**Comment by BruceChenQAQ** [comment]
![image](https://user-images.githubusercontent.com/26017411/195749139-0ac98c01-aaea-4ddc-9f7e-2223052f61c8.png)

Chatting is now working properly in the latest version, but signing of messages contained in custom commands is not currently supported.

This feature will be supported later, which requires a lot of code.

**Comment by BruceChenQAQ** [comment]
Try using the latest release, which should fix this issue.

**Comment by JIBSIL** [comment]
> ![image](https://user-images.githubusercontent.com/26017411/195749139-0ac98c01-aaea-4ddc-9f7e-2223052f61c8.png)
> 
> Chatting is now working properly in the latest version, but signing of messages contained in custom commands is not currently supported.
> 
> This feature will be supported later, which requires a lot of code.

Hey, I managed to fix the issue in the old release

In the Protocol/Handlers/Protocol18.cs file, there's a section with command signing. I simply added "/ad" to that part, recompiled and it worked like a charm!

**Comment by JIBSIL** [comment]
Line 2258, File `Protocol18.cs`: `argStage1[0] == "ban" || argStage1[0] == "ban-ip" || argStage1[0] == "kick" || argStage1[0] == "ad")`. That was the code I used. I'll close this issue now as it's resolved
