### ISSUE TITLE
[BUG] remote control bug

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2281]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

latest

### Expected Behavior

Woriking

### Actual Behavior

Not working

### Steps to Reproduce the bug

1. on old versions this regex "^\[([A-Za-z0-9_]+) -> я] @(.+)$"
2. on latest version this not work
3. original message on chat "[UltraZXC -> я]"

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

mc.playrw.ru or mc.holyworld.ru

**Comment by breadbyte** [comment]
Your regex expression seems to be broken.
Can you try this one?

`^\[([A-Za-z0-9_]+) -> я] @(.+)$`

**Comment by BruceChenQAQ** [comment]
(remember to add quotes)
`xxx = '^\[([A-Za-z0-9_]+) -> я] @(.+)$'`

**Comment by Sergapr** [comment]
[conf.txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/9845083/conf.txt)
My ini file. 
It dont work for me.
![image](https://user-images.githubusercontent.com/106835861/197357612-89bc72ee-4be3-4d63-b71b-4d4a00315914.png)
Thanks

**Comment by breadbyte** [comment]
Use this pattern.
`Private = '^\[([A-Za-z0-9_]+) -> я] (.+)$'`

**Comment by Sergapr** [comment]
> Use this pattern. `Private = '^\[([A-Za-z0-9_]+) -> я] (.+)$'`

Thanks a lot, it is works. 
Can u help with this one pls? 
![image](https://user-images.githubusercontent.com/106835861/197375488-131f3dce-e447-4cb0-bb75-889b03d7b8ab.png)

**Comment by Sergapr** [comment]
> > Use this pattern. `Private = '^\[([A-Za-z0-9_]+) -> я] (.+)$'`
> 
> 
> 
> Thanks a lot, it is works. 
> 
> Can u help with this one pls? 
> 
> ![image](https://user-images.githubusercontent.com/106835861/197375488-131f3dce-e447-4cb0-bb75-889b03d7b8ab.png)
> 
> 

#Builtin chatformat don't work for me. I think it is because there are my donate group name before my nick and a title after nick.

**Comment by BruceChenQAQ** [comment]
> > > Use this pattern. `Private = '^\[([A-Za-z0-9_]+) -> я] (.+)$'`
> > 
> > 
> > Thanks a lot, it is works.
> > Can u help with this one pls?
> > ![image](https://user-images.githubusercontent.com/106835861/197375488-131f3dce-e447-4cb0-bb75-889b03d7b8ab.png)
> 
> #Builtin chatformat don't work for me. I think it is because there are my donate group name before my nick and a title after nick.

Please use text instead of images.

**Comment by Sergapr** [comment]
> > > > Use this pattern. `Private = '^\[([A-Za-z0-9_]+) -> я] (.+)$'`
> > > 
> > > 
> > > Thanks a lot, it is works.
> > > Can u help with this one pls?
> > > ![image](https://user-images.githubusercontent.com/106835861/197375488-131f3dce-e447-4cb0-bb75-889b03d7b8ab.png)
> > 
> > 
> > #Builtin chatformat don't work for me. I think it is because there are my donate group name before my nick and a title after nick.
> 
> Please use text instead of images. And point out the username and chat content section.

ʟ | «ᴋɪɴɢ» dpls Археолог: 123
ʟ - Local chat
 | 
 «ᴋɪɴɢ» - donate group 
 dpls - nick  
Археолог - titile
: - just before message

**Comment by BruceChenQAQ** [comment]
> > > > > Use this pattern. `Private = '^\[([A-Za-z0-9_]+) -> я] (.+)$'`
> > > > 
> > > > 
> > > > Thanks a lot, it is works.
> > > > Can u help with this one pls?
> > > > ![image](https://user-images.githubusercontent.com/106835861/197375488-131f3dce-e447-4cb0-bb75-889b03d7b8ab.png)
> > > 
> > > 
> > > #Builtin chatformat don't work for me. I think it is because there are my donate group name before my nick and a title after nick.
> > 
> > 
> > Please use text instead of images. And point out the username and chat content section.
> 
> ʟ | «ᴋɪɴɢ» dpls Археолог: 123 ʟ - Local chat | «ᴋɪɴɢ» - donate group dpls - nick Археолог - titile : - just before message

`xxx = '^ʟ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'`
Will match `dpls` as username and `123` as chat message.

**Comment by Sergapr** [comment]
Yes, L-local chat ɢ - global chat

**Comment by BruceChenQAQ** [comment]
> Yes, ʟ-local chat ɢ - global chat

Try 
`xxx = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'`

https://regex101.com/r/bqdEMj/1

**Comment by Sergapr** [comment]
> > Yes, ʟ-local chat ɢ - global chat
> 
> Try `xxx = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'`
> 
> https://regex101.com/r/bqdEMj/1

My ini file now:
# MCC does it best to detect chat messages, but some server have unusual chat formats
# When this happens, you'll need to configure chat format below, see https://mccteam.github.io/guide/configuration.html#chat-format
[ChatFormat]
Builtins = true                            # MCC support for common message formats. Set "false" to avoid conflicts with custom formats.
UserDefined = true                          # Whether to use the custom regular expressions below for detection.
Public = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'
Private = '^\[([A-Za-z0-9_]+) -> я] (.+)$'
TeleportRequest = '^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$' 
and private messages is work, but public is not. 
If i change ini file like this:

# MCC does it best to detect chat messages, but some server have unusual chat formats
# When this happens, you'll need to configure chat format below, see https://mccteam.github.io/guide/configuration.html#chat-format
[ChatFormat]
Builtins = true                             # MCC support for common message formats. Set "false" to avoid conflicts with custom formats.
UserDefined = true                          # Whether to use the custom regular expressions below for detection.
Public = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'
Private = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'
TeleportRequest = '^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$'

Local and global(public) messages work, but private is not(because i replaced a private line.)
How to fix it?

**Comment by breadbyte** [comment]
Set your builtins to false to avoid conflicts
`Builtins = false`
Set your public to
`Public = '^[^\s]+ | [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'`
and your private to
`Private = '^[([A-Za-z0-9_]+) -> я] (.+)$'`

**Comment by Sergapr** [comment]
i start mcc with this ini:
[ChatFormat]
Builtins = false                            # MCC support for common message formats. Set "false" to avoid conflicts with custom formats.
UserDefined = true                          # Whether to use the custom regular expressions below for detection.
Public = '^[^\s]+ | [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'
Private = '^[([A-Za-z0-9_]+) -> я] (.+)$'
TeleportRequest = '^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$'
nothing works. I close MCC and ini file changes to:
[ChatFormat]
Builtins = false                            # MCC support for common message formats. Set "false" to avoid conflicts with custom formats.
UserDefined = true                          # Whether to use the custom regular expressions below for detection.
Public = '^[^\s]+ | [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'
Private = "^[([A-Za-z0-9_]+) -> я] (.+)$"
TeleportRequest = '^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$'

**Comment by Sergapr** [comment]
I also cant reproduce this, lol

> > > Yes, ʟ-local chat ɢ - global chat
> > 
> > 
> > Try `xxx = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'`
> > https://regex101.com/r/bqdEMj/1
> 
> My ini file now:
> 
> # MCC does it best to detect chat messages, but some server have unusual chat formats
> # When this happens, you'll need to configure chat format below, see https://mccteam.github.io/guide/configuration.html#chat-format
> [ChatFormat] Builtins = true # MCC support for common message formats. Set "false" to avoid conflicts with custom formats. UserDefined = true # Whether to use the custom regular expressions below for detection. Public = '^[^\s]+ | [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$' Private = '^[([A-Za-z0-9_]+) -> я] (.+)$' TeleportRequest = '^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them).$' and private messages is work, but public is not. If i change ini file like this:
> 
> # MCC does it best to detect chat messages, but some server have unusual chat formats
> # When this happens, you'll need to configure chat format below, see https://mccteam.github.io/guide/configuration.html#chat-format
> [ChatFormat] Builtins = true # MCC support for common message formats. Set "false" to avoid conflicts with custom formats. UserDefined = true # Whether to use the custom regular expressions below for detection. Public = '^[^\s]+ | [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$' Private = '^[^\s]+ | [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$' TeleportRequest = '^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them).$'
> 
> Local and global(public) messages work, but private is not(because i replaced a private line.) How to fix it?

**Comment by BruceChenQAQ** [comment]
> > > Yes, ʟ-local chat ɢ - global chat
> > 
> > 
> > Try `xxx = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'`
> > https://regex101.com/r/bqdEMj/1
> 
> My ini file now:
> 
> ```toml
> # MCC does it best to detect chat messages, but some server have unusual chat formats
> # When this happens, you'll need to configure chat format below, see https://mccteam.github.io/guide/configuration.html#chat-format
> [ChatFormat]
> Builtins = true                            # MCC support for common message formats. Set "false" to avoid conflicts with custom formats.
> UserDefined = true                          # Whether to use the custom regular expressions below for detection.
> Public = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'
> Private = '^\[([A-Za-z0-9_]+) -> я] (.+)$'
> TeleportRequest = '^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$' 
> ```
> 
> and private messages is work, but public is not. If i change ini file like this:
> 
> ```toml
> # MCC does it best to detect chat messages, but some server have unusual chat formats
> # When this happens, you'll need to configure chat format below, see https://mccteam.github.io/guide/configuration.html#chat-format
> [ChatFormat]
> Builtins = true                             # MCC support for common message formats. Set "false" to avoid conflicts with custom formats.
> UserDefined = true                          # Whether to use the custom regular expressions below for detection.
> Public = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'
> Private = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'
> TeleportRequest = '^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$'
> ```
> 
> Local and global(public) messages work, but private is not(because i replaced a private line.) How to fix it?

Testing works fine with this setting.
Please close MCC first before changing the settings file.
```toml
Builtins = false
UserDefined = true
Public = '^[^\s]+ \| [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$'
Private = '^\[([A-Za-z0-9_]+) -> я] (.+)$'
```

![image](https://user-images.githubusercontent.com/26017411/197523701-cb8ca9da-e612-4396-9e22-f3681cf1fc04.png)

**Comment by BruceChenQAQ** [comment]
> I have no idea, if i use it - private messages is work, public dont work. if i change private to '^[^\s]+ | [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$' public messages is work. May be it is a mcc bug?

Are you using the latest build? I tested that both formats of chat are parsed correctly.

**Comment by Sergapr** [comment]
> > I have no idea, if i use it - private messages is work, public dont work. if i change private to '^[^\s]+ | [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$' public messages is work. May be it is a mcc bug?
> 
> 
> 
> Are you using the latest build? I tested that both formats of chat are parsed correctly.
> 
> 
> 
> 

Can it conflict with Autorespond?

**Comment by BruceChenQAQ** [comment]
> > > I have no idea, if i use it - private messages is work, public dont work. if i change private to '^[^\s]+ | [^\s]+ ([\w\d_]+) [^\s:]+: (.+)$' public messages is work. May be it is a mcc bug?
> > 
> > 
> > Are you using the latest build? I tested that both formats of chat are parsed correctly.
> 
> Can it conflict with Autorespond?

What rules do you have configured in Autorespond? Or in which part of the chat format matching is not working properly?
