### ISSUE TITLE
[Idea] Local Host WEB GUI for inventory & chest interactions

### ISSUE THREAD

**Issue by amigoexp** [MCCTeam/Minecraft-Console-Client#2297]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

handling inventory is pretty much difficult on commands. 

### Suggest a possible solution

Maybe you can build a local hosted GUI for inventory and chest interaction website on https:127.0.0.1 on Browser.

### Minecraft Version

1.19.2

### Device

Laptop

### Operating System

Windows

**Comment by amigoexp** [comment]
At least there can be a slow rate synced image of inventory could be beneficial. Because everytime typing /inventory p is a bit hard sometimes. There can be 2 images (1 player inv & 1 chest) and they can be updated like every 5 secs.

**Comment by milutinke** [comment]
There is already a plan for this, but as an option in a separate application (both for Desktop and Mobile) that would use the MCC.
First we need to do a major refactoring and restructuring of the code to enable embedding the MCC into GUI application, as proposed in #2197.
As a stop gap feature I am planing to make a web interface that will use the [MCC.js](https://github.com/milutinke/MCC.js) once the #2289 is merged after proper testing.
