### ISSUE TITLE
[BUG] dont work regex for tpa request

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2299]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

latest

### Expected Behavior

don`t work regex for tp request

### Actual Behavior

work regex for tp request

### Steps to Reproduce the bug

1. change tp request regex to "^([A-Za-z0-9_]+) просит телепортироваться к Вам. [✔] [✗]"
2. and tpa to you bot on server (mc.playrw.ru)
3. original tp request UltraZXC просит телепортироваться к Вам. [✔] [✗]

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

mc.playrw.ru

**Comment by milutinke** [comment]
For matching emojis in regex, you need to use unicode escape sequence.

**Comment by milutinke** [comment]
![image](https://user-images.githubusercontent.com/441903/197341880-fad4e7d8-60d1-4683-873e-a3c29818d5f1.png)

Regex
```
^([A-Za-z0-9_]+) просит телепортироваться к Вам. \[(\u2705)\] \[(\u2717)\]
```

Tested with:
```
UltraZXC просит телепортироваться к Вам. [✅] [✗]
```
