### ISSUE TITLE
Telegram bridge

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2301]
Are it possible to make a bridge between MCC and telegram bot?

**Comment by milutinke** [comment]
It is.
It's just the matter of coding it.
https://www.codeproject.com/Tips/5303407/How-to-Easily-Create-Telegram-Bot-using-Csharp

**Comment by Sergapr** [comment]
Thanks. 

don't u have any plans to add such a chatbot

**Comment by milutinke** [comment]
![image](https://user-images.githubusercontent.com/441903/197525902-9c13a390-a77a-49ef-b26b-1d2c22d668d9.png)
Almost done, now testing

**Comment by milutinke** [comment]
#2302
