### ISSUE TITLE
[Idea] Console integrated /swap account *Ingame-name* / *saved-profile* / #1 #2

### ISSUE THREAD

**Issue by amigoexp** [MCCTeam/Minecraft-Console-Client#2305]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Sometimes we need to swap account really quick.

### Suggest a possible solution

Maybe you can add a /swap account command. in minecraftclient.ini there can be multiple account string to save 2-3 accounts.

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/40539114/197826766-0d39b559-ef08-4842-a40b-4d9064bbe072.png)

### Minecraft Version

1.19.2

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
There is an option like this already:
https://mccteam.github.io/guide/configuration.html#account-list-section
Simply add accounts there and use the connect command: https://mccteam.github.io/guide/usage.html#connect and pass in the ip of the server and the account name/alias.

Refer to the documentation before posting suggestions/ideas.
