### ISSUE TITLE
How to solve it??

### ISSUE THREAD

**Issue by username902** [MCCTeam/Minecraft-Console-Client#2314]
Where to enter this, I entered minecraftclient.ini but nothing happened, I have an old console and this function is simply not there and nothing happens when I enter
[ChatBot.AutoDig]
enabled = true
Mode = "fixed position"
Places = [
{x=123.5, y=64.0, r=234.5},
{x=124.5, y=63.0, r=235.5},
{x=124.5, y=63.0, r=235.5},
{x=124.5, y=63.0, r=235.5},
{x=124.5, y=63.0, r=235.5},
]
List_Type = "black list"
blocks = [ ]
I wrote this in minecraftclient.ini and nothing happened, restarted many times but nothing happened

**Comment by BruceChenQAQ** [comment]
Please use the latest build, `AutoDig` is not supported in older versions.
