### ISSUE TITLE
[Idea] Allow [Main.General.Account] to take an alias from [Main.Advanced.AccountList] similar to [Main.General.Server]

### ISSUE THREAD

**Issue by Charzard4261** [MCCTeam/Minecraft-Console-Client#2327]
### Prerequisites

- [X] I have read and understood the [user manual](https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/config)
- [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/Minecraft-Console-Client/build/artifacts)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

GitHub build 154, built on 2022-11-05 from commit c026668

### Describe your problem

Having to fill in the username & password for the default account twice is a bit redundant, especially if you want to load up multiple clients at once quickly. (/reco does work, but serverside people see "Main account joined. Main account left. Alt account joned." many times which is a bit silly and opens up chances to be throttled.)

### Suggest a possible solution

Allow [Main.General.Account] to take Account = { Login="AccountAlias1" } similarly to [Main.General.Server] being able to take Server = { Host = "ServerAlias1" }. Alternatively, make a new [Main.General.Method] (or a more suitable setting) that prompts the user to pick an account from [Main.Advanced.AccountList] on startup.

### Device

Desktop

### Operating System

Windows

**Comment by BruceChenQAQ** [comment]
Implemented in 0b5a562f7f9062f83458d4a6d1a1c0b597757699
Try the latest build.
