### ISSUE TITLE
Leave server if there are other player online

### ISSUE THREAD

**Issue by henrydatei** [MCCTeam/Minecraft-Console-Client#2334]
I'm pretty sure it's possible but how can I leave the server if there are other player online? I would use something like `/execif <something that gets the current amout of players> > 1 ---> quit`. And then combine this with the script scheduler for regular checks.

**Comment by BruceChenQAQ** [comment]
Try this one
```
/execif MCC.GetOnlinePlayers().Length > 1 ---> quit
```

**Comment by henrydatei** [comment]
Thanks
