### ISSUE TITLE
[BUG] About Full-width characters and reborn

### ISSUE THREAD

**Issue by yhzcake** [MCCTeam/Minecraft-Console-Client#2336]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

build 158

### Expected Behavior

![image](https://user-images.githubusercontent.com/80627671/201372222-0efb0ef6-4c14-44b1-8060-5f7907ae69d1.png)
![image](https://user-images.githubusercontent.com/80627671/201372230-f99091f6-07a5-4e10-8cde-1198d7ac2ab2.png)

when I input Full-width characters it looks wrong

when server game rule  doImmediateRespawn is true , the auto reborn will output 1s later will respawn but not

change autorespawn false and writte /respawn is ok

### Actual Behavior

![image](https://user-images.githubusercontent.com/80627671/201372253-943e29c2-24d9-4c6a-ae3b-54c70356bf8e.png)

it's output is ok ,like this

when server gamerule doImmediateRespawn is true :
autorespawn is true : output '1s later respawn' (print every tick),use gui client login server will crash client
autorespawn is false: output 'input /respawn to reborn'(print every tick),input /respawn reborn success , (i didn't try that time if client can login in)

### Steps to Reproduce the bug

1. input Full-width characters
2. server gamerule doImmediateRespawn trun true
3. autoreborn
4. kill @s

### Device

Laptop

### Operating System

Windows

**Comment by BruceChenQAQ** [comment]
Try using https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/brigadier-dev-prerelease or an updated release, which should fix this issue.
