### ISSUE TITLE
[Idea] How about the plugin api for MCC ？

### ISSUE THREAD

**Issue by yyyytawa** [MCCTeam/Minecraft-Console-Client#2337]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

GitHub build 158, built on 2022-11-07 from commit 5a540f6

### Describe your problem

MCC can do more things by adding plugins（like Minecraft Mods)

**Comment by milutinke** [comment]
The MCC already has a "plugin" option, plugins here are called Chat Bots, you can check out the [ChatBotAPI](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/Scripting/ChatBot.cs).
Here is the documentation on how to make them: https://mccteam.github.io/guide/creating-bots.html
