### ISSUE TITLE
[BUG] I can't use /move on some server

### ISSUE THREAD

**Issue by GitH2b** [MCCTeam/Minecraft-Console-Client#2338]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

Latest

### Expected Behavior

Using correctly /move

### Actual Behavior

Bot can't moves on some server.

### Steps to Reproduce the bug

1. Login to for example mc.mineblaze.net (grief) use move function in the ender world
2. Login to mc.gamster.org and use same function

### Attach screenshot here (If applicable)

https://youtu.be/E7whPvNyQJM

### Server Address (If applicable)

mc.gamster.org + mc.mineblaze.net

**Comment by deosync** [comment]
ok

**Comment by GitH2b** [comment]
> Have you tried using coordinates instead of direction? The cause of this I think could be the custom server software that has a different way of handling movement packets, or there is a plugin which detects bot movement and disables it. Try setting the branding to vanilla and trying the move command again.

Yes, i tried but nothing happened

**Comment by kot9kas** [comment]
Привет, скорее всего проблема в анти чите сервера! Клиент отправляет пакеты для передвижения, стандартный майнкрафт делает это чуточку по другому.

**Comment by GitH2b** [comment]
> 

Есть ли возможность это как то обойти дабы иметь возможность пользоваться MCC на этом сервере?

**Comment by milutinke** [comment]
Use English

**Comment by kot9kas** [comment]
> > 
> 
> Есть ли возможность это как то это обойти дабы иметь возможность пользоваться MCC на этом сервере?

К сожалению нет.

**Comment by BruceChenQAQ** [comment]
This may be caused by anti-cheat plugins, try changing these in the settings file.
```toml
[Main.Advanced]
MinecraftVersion = "1.16.5"
BrandInfo = "vanilla"
TerrainAndMovements = true
MovementSpeed = 2
TemporaryFixBadpacket = true
```

**Comment by GitH2b** [comment]
> 

Thank you, fixed.
