### ISSUE TITLE
[Question] Docker Image

### ISSUE THREAD

**Issue by tangerine349** [MCCTeam/Minecraft-Console-Client#2339]
Hey, im trying to try MCC in Pterodactyl and cant find a docker image that works with it, i tried DotNet 6 and then got this error:

`Unhandled exception. System.DivideByZeroException: Attempted to divide by zero.
   at ConsoleInteractive.InternalWriter.Write(String value)
   at ConsoleInteractive.InternalWriter.WriteLine(String value)
   at ConsoleInteractive.ConsoleWriter.WriteLine(String value)
   at MinecraftClient.ConsoleIO.WriteLine(String line)
   at MinecraftClient.Program.Main(String[] args)
/entrypoint.sh: line 13:    13 Aborted                 (core dumped) ./MinecraftClient`

**Comment by milutinke** [comment]
Read the documentation: https://mccteam.github.io/guide/installation.html#using-docker

> There is a bug with the ConsoleInteractive which causes a crash when a container is started in a headless mode, so you need to use the interactive mode. Do not restart containers in a classic way, stop then and start them with interactive mode (this command), after that simply detach with CTRL + P and then CTRL + Q.
