### ISSUE TITLE
[Idea] Add pirate accounts support

### ISSUE THREAD

**Issue by kot9kas** [MCCTeam/Minecraft-Console-Client#2340]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Login

### Suggest a possible solution

Just add support xD

### Minecraft Version

1.19.2

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
If you want to use an offline account, set the password to `-`.

**Comment by deosync** [comment]
genuis
