### ISSUE TITLE
[Idea] Add the possiblity for the entity command to use/attack the nearest entity if using the entity type

### ISSUE THREAD

**Issue by ITHackerstein** [MCCTeam/Minecraft-Console-Client#2346]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

The entity command when called with an entity type it uses/attacks all entities with the type specified. 

### Suggest a possible solution

What I'd like is for the command to be able to choose the closest and use/attack that one.

### Minecraft Version

1.19

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
There is already an AutoAttack chat bot use him.

**Comment by ITHackerstein** [comment]
Yes, but won't that try to use/attack the entity periodically instead of one time only?
