### ISSUE TITLE
Question: Invalid profile keys 

### ISSUE THREAD

**Issue by DARKSRG** [MCCTeam/Minecraft-Console-Client#2351]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.16.5

### Console Client Version

last

### Expected Behavior

Вход на сервер

### Actual Behavior

Не входит на сервер

### Steps to Reproduce the bug

1. Запускаю мсс
2. Не подключается
3. Ошибка
Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
GitHub build 166, built on 2022-11-25 from commit 851ecf5
Разрешение mstnw.net...
Найден сервер line.mstnetwork.ru:25500 для домена mstnw.net
[MCC] [ScriptScheduler] Загруженная задача:
triggeronfirstlogin: False
 triggeronlogin: False
 triggerontime: True
 triggeroninterval: True
 timevalue: 14:00:00
 временной интервал: 53,4
 действие: send /hello
[MCC] [ScriptScheduler] Загруженная задача:
triggeronfirstlogin: False
 triggeronlogin: True
 triggerontime: False
 triggeroninterval: False
 timevalue:
 временной интервал: 56
 действие: send /login pass
Help us translate MCC: https://crwd.in/minecraft-console-client
Цветовой тест: В вашем терминале должно отображаться [0123456789ABCDEF]: (4bit)[0123456789ABCDEF]
Цветовой тест: В вашем терминале должно отображаться [0123456789]: (8bit)[0123456789]
Цветовой тест: В вашем терминале должно отображаться [0123456789]: (24bit)[0123456789]
[SessionCache] Инициализация FileSystemWatcher для файла: C:\Users\DARKSEh\Desktop\Ocholko10\SessionCache.ini
Загрузка профилей Minecraft: launcher_profiles.json
Ни одна сессия не могла быть загружена с диска
Вы выбрали запуск в автономном режиме.
Успех. (ID сессии: )
Получение информации о сервере...
{"version":{"protocol":760,"name":"MST Network 1.12.2-1.19.2"},"players":{"online":278,"max":1000,"sample":[]},"description":{"extra":[{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■ "},{"bold":true,"color":"white","text":"MST NETWORK "},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■"},{"color":"aqua","text":"■\n"},{"color":"aqua","text":"❄ "},{"color":"green","text":"Открытие новой "},{"color":"gold","text":"Анархии 1.16+"},{"color":"green","text":" уже "},{"color":"yellow","text":"СЕГОДНЯ! "},{"color":"aqua","text":"❄"}],"text":""},"favicon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAZtElEQVR4XuWbd3iUVfbHhwAqWGhSpUpIIKT3mcmUzKQQiqGFJkHpvRMSCBBKIKQCIYQmooCKIBawISq2dVFXXdhd10dddd1d3f3t6j4CqSR8f99z30kyDRLc/W/zPJ/nnXnLved877nn3jMz0QHQ/S/jcYLcQzLJV+Rv5K+3iDzzLSknQfBs/1Z5iFyAZz+3wvskHZ5tawK0iRzZCN+XFxx5FgOTJqBXlB336RObMBBjknfkGu/pFW1HP9toLMrfB2nLue1bhc/HX/ziG+jTl7LtBAdO9jSL9ozxoWX4/Vd/Fntsbu27CsDX9/7z3z/DJ8iKe1KWoPfMInR/sABdpxSgG4/dJvP1hO1e6TY5X93T4+EidErNROuQRHz82ZfSaYS7Yy2Fz56YsGoL7jBORM/0IvQQpha2GPXM1CLcbkhD2qrNYstJt/Y9BIgQo3X9AzEk5z2kMvAszwHGU0Dc84DpaR4fJY+5wXOm49o9iW8DAbkfQzcwDM+fl8jDaHfHWgqfPZs0YwnuTpyDhDNs+xXA/oInCae9k/QykHwW6DhqJeKnzhVb3nRr30MA25sf/hY6v2gE5PwKCS8ChsfroCeGI/WIfbQWkfsqEbm/yhWek2tyj53P+GWdVQIcefEN6XSau2Mthc++Z3xwPtpb0hFHGywyAOzDGeOROsQ6bPTgyHVYOHidx65D1JgHxZYP3dr3EGD8M+fehW6IEcF5l2Dn6Mc9fk1hko4O1yD8kSpEHKp2IfyRaugPa/ckvQT4r34JuvtDUHz0Wel0lbtjLYXPfjZkZDramabAeKgS5qcYjY9daySOGA7XIupQjXc4KKZnwOm5Hb7xI8WWL93a9xBg3r6TZ9AqxI7wkq9hO9XUoYxADBsN31+JiANVikgHEYwCPQ2Re5IYAb7Ln6MAwcgqPSyd5rs71hL4XOu6+np0t4zGHYYJMBy8DKtMM4fjgokDY6TwYpd3amGlD72ml6NLuBk1tdfEntuc+vAQIDv3wFG0jXoAUWX/gOWEpwCRByoRdbAKUc4CED3VjnusDomcqwOXnFACzM3dLR0ecHeuJfC5Tj/9fAVtQu24PXYMYvb+S00Bw2EZdQe0SyIv5pGaG2JlEPaddww+A4Px9x//LfZ0d+rDQ4BdS7btwu3MulF7r8B4FEphd1To0eGYgzUeSIf95h9TAkxbVyQdPu/gJJni7qib0/5kZ8Mzlysq0SoongMyCqE7/4bYY2gU3Rnn/qMOVLtcMzEC+i97njkpGJe4pPIv+GYCPD1h+Tq0j59B9Zj4HqMAj15zIU7murMAB1yRkOuZvgu6Ll3RVZ+M1AWrkDp/Fcav2ICnXn1bDPC6N+D5AT9frcDyov1IXZihnrOkz6OQQUzKEQgq+Ar6J+CZgIlz/1H7q9WUbLgWxyj2zXwdOv8ovP7Bp9J/ws0EeMsydR7uGbaEIU3nDwHmR+tgInKMO3RNYRIxHqlF9D526kItzE/Wo//842gXM5bL10JFx+GL0M7yEFqHJePb7/8hRvTzIkBB5s5DaBudiruSFuKu5EU8LkB7+2wyC8FF3yLm2HVON83BCK48EfvkWIXYg7UKPYnm9XCna0bmDf/1HzCx6zkA56XvyTcT4FLQiAnonLoW8U9yvj3CpY+qNiBOixiaAJx/B7j0HXRFL/cduq7tDw5rDOPKMDTrHMMwBG/95pIYYfUiwDPjlq1H+7hJdKQGBk6/2ENNRO1h3tldoVFeRfGrG4ktowhlXIp3VyKG1yQKGq4ZOG2G5n7GqWRF2fEXpO9FNxPguz7GZPSYlI+kUyLANYTtqUBEeSXCiUEJoEVBQySY5OiEnDfTecuRJlK4IRm84jR0A4Z6hKFT3yfHr8hhwhuH2PIKWGi48REHIsIuOld0WaO0Evr9FJtRJ8TsuHrDa/rHOemL/4o2kaOwce/j0neOVwF4vFuSTvuhUegz4wCSmcxkhMX5iL2cT1TWeJBOUpS4g7fGMO4nBiw8SQEC8fJ7H4kRw70IcHrUorVoSwEid/4bpsN0em+Nhji5qwIxxVcQU0IoRuxehn15M9cEihde9jMT+yQs3ib5FaU3EqDvn3/4P2XkwEUnMZzRIgpGlDECGGISgiY6YxYRHEczE6U6NkMKBfBbckq1/eybvxIjxnoR4HX7rBW4Q88I2PUjI4n976nREBF20MlCbZTltb68VrsmTpZcRTSvCS7XSMx+Tp+9dWhvm4kpGRul7yduJEDYp59/Bd2gMAxa9grs3HUZmNSMDCej42g6cE1hPlinxIlmVMTsrb4pMoKJTEQD58nSGISjL70pRqR7EeB9Q/oi3BbNPUjhD5xOFKCspondbKuU/e2qUq/jaEccbYrbzyP7MJZryGt1Tl2jzZxCFk7JDinLkDxzifT96o0E0OqAwdEYnPEurHwobu81WOms+YCGiQ0L8jqmnNm4tAKRTD43IoJElVXDxoTWe/oRJsEgPPHKeTFCNuY93PgwevJ8NVfD8/8Oiwiwu7aJMhlVJt4yLsF7arXoksFwDIiKRhWRYmvTNcsj15HIhH7vmPWIGutaD7gLkHby3DvQDTUiaN0lxB9mhUcBLNKQOO1w3Ly/DlYeY/dUMyNXIprTQ7HbCce5KBJDARIpwIBZx5QAWw4+hR/+9ZNX/Ljvvy16FKIpgOkAI7C01pNdjEYK0miTsO8m0N4kCtBjYgF8ba71gLsAqg7wCU1A2KY/wcrQMVFxizSyV8PE5CKYJcmUUoCdFIAhGV3qTLV25PkoEsP3SczovSYVQdfhdvgMCkJb/5Am/JrQ9R7AUtwfEZv/hHhGgDjrwU4KUCo2NNnl4bQLdRjGKdjnob3oHBHnUg+4C5Cde/AY2rAOiMxjCO6D6kyxi6FXwjmYfwWxBVdd4Tl9UaW6p/Fevlf3CoUVNKIeAas/QJ8pZeg346jG9KPoz+OA2cca6T/zMfSf9Tj0O35E/MH6pv5vgn4H5/pu14FyJ4U1xIA5T8DH17UecBdg15LtrAMME6EvvArLHq6/JbUaO+hcEUvevMvQb7/qSt4VGAoqYdzJzdEO7X59foU6r5DXxbWIp6BJnAqJjzngFEvisizGNXJCO1oZ/qbd0u9NcNhmYNtxjAiLOFvuHWlz0OLTqh64+MXXIkCINwFOjl+ejTstM2EquQ5zKZOgNC6UsC4ooABbL8OwjU6T2G1XNHJ5bnuFEsnIe4XYvKvqvKDP47USXiuisUXa9bhiZmm+Nu0Qw+tgKXeDYWvZU6eeaQ59Idvb6ZgSXpwXhnFFC8h4k/VAJM5d+EQESPQmwNvm9DnokLQUZlaxcTuvU90aB+yogNvN7RLyHFE6bChwwPdGXjMWa04qRxkRcl5dK2RBQgHiSkRIGTG2V6RhLOGStVtC2A1mfFOpdn9ziKAmEYD5ylzmBU6PJEZc0JqPWA/E4vjZt0SASd4E+F3giDR0HrkWcQzXWI5OTEmVB9EkdkcVLGw8nlg5UmYJ/wIaJKNBLDIned5SJlzT3jvu1e9gkiyubGqv2JMoElui9dEipH1viADMSfYybnLW/BG6IAv2PH1aBFjoTYC/9DYlo+vYPC53oHHcyNAQd6KLHMaxA6sgykv4b6fz+YRCWEq9G2YtcwjAJOnerksfjqOMnvTh3k6LcQgQz+kcueE7tA5PwcZ9TfVAowBw1AHtgqJYCO1WAoijYmgDMUVNAsiKoJwsFae4PErob6Xz20geBdjpMICdW0vFgDqFrYyZnc9GF3oXoKHPKEefZmlf+nFrp8XsdhxLOKAbf8RtLNEXby8VAVQ94CxAP6nTdQMD0e/hx5Ega3BxdSNGoudcjiUxnO+yIljppILGmWUecvStDH8DIyE09xpCKUbo1msIzq1FwKYalaziuY7r+WwMc4S05Y60a2JeCMqthn9ONUIoahgJZnuRbNeyo4bRVnvLxLMGMudfY6mdjimrN4kAqh5wFkCrA7hO+s9/ASMZJfESOrvqFDZiKKTh+ZUKeR3fIIBDBEGcHHUQWMM8k3VeO2Zy65/xBpC89zqCN1dw71DlFWk3jgkyrrgOi14Etlzg8+e15zewfprJ6jQ0l0WP2FBwa8QzByTsZT2QuBhJMxeLAGfdBXDUAVEIWvEuRjAC4jmvndEEoLEOAWxu14XYwjqMLv8JW0+ew6YTb2Lj0+ex4ak3kfPkyxi+6weEbKtRzsqK4o4IYKSAppJ6LD1yCfknXkLO8fPIYRuFp17BgsOfMKpY3eVXe4jXHNYd9UjhtO46aj0ix6h64CN3ARrrgIi1l5oEKGlCpoAIEKOWNhFA5pZ2TcSwMRJGHuYOI/MT6LoN5LY2CLq+EdDdFwpdp34ssd9DIqOjyelqbWl1IO2aud8YyS14W8sK6O7qoj0vdOiB1oZZzDnyPIXeXumJDI4X50VYK+0b+Si342mF8LU31QPOAswvP3EarVgHRK/7GskMmfhih3MOJw3bqhX6rVWc7zUuAlgLCedYSjnn0qqPoQvQs60k+IQP5zGZ72MQuOyCysb6rZWNGARHuwa2aymqwwiK1HPMFjUd5XlBPhTtmLSM0407xKJ6LrnVHjS24460S9uG7wf6Tt6HzpFN9YCzAOs3Hzii6gB91t9h3wrlkHJQhKDqlk1MQjlkA51lYlLXirTr1i1MNhtqkVwIBC/4NSMpVi05VJkOJKNViBlhSz6GPY8brA1XHVyGaUOF1q7AduO3awL0mcDCaVCwel7QDYlBR87fRAqYSBFszBPuWDY77Gtoz5mNtUjhSnD/g8fgM7ipHnAWYOfS/FLcoZ8I0/qrsOcyAkQAcV6c5GvVuBKgVhNArhVq10UAuTZMBJj/LgWIRuuI4Y0C6IKtCFnyWyRsdxbgiibARs1AaTc+r07N1V7ji10FCIhFB9tcJNCJhB3Q+nWjUYCG9twYzmf9Hn6B2+FgfP7NX0SAwc4CHJ26ZiPuMs2kIdcRv8lJAGE7O1inGWnJFgEc5x0CmKUTXh+WDwTO5p47IJICjHASwILQRZ8gYRsLrOwrDi4jbh2LrvW1Gmw3fmsdhjMCeqe5CTDUgLutM2Avvg67kwA2Thkb+7eJLRxpK22wygCJnQ3tCnw/vAAYOou2DYnAry/+UQTQOwvwcsrcpehoX4oEhr9tC6EANtUJG8/jKNNJBVWO3+a4VqBh3axdE5WHznqVq0k42jgEaBWWhNZhdkSu/APb4RzOqYBpY4U6mnMqXdulsKMYAf0n76YAQU0CBMbhTtM02NlXIvuQPmWArLL3EGT3ubmGjnKfsJFH0tjupmsqAtT0XMh6IDAWL77zgQgg2bBRgI8ixz2IriPWYTgLIXvhdQpQ50qBEze4JsYPnfcSk1bT6PmEJTIRJiI08wtYi7XcYi90a6+x3XqM5Hrdd2I5BQhsEiDIhDvjpsCWV4VERoC9oB5m7jhjN3PztKVaI1dDT4xE2rMLhfWwMIKtFC5k1R/UdDx46mURYLazAH/ua01Gz7H5GL5HOvAiQAsYxUw7ePbzrgKEJ0EXYkOfuZ8jYD2nyNp6hKzjpijbC2uBKE6TbmP2MIqcBTCjnWECp94VJDkEsFAAvbMADvSOoyRUJQDvtTKCzYyA8KxvVW7atP+ICLChQYC7rlRUsQ6IpPJ7MFIE2F4POx1qMdIZeYCj5zf9hIsAukAb2kamIPtMNfZcBHZxh7f7Q27GP/DOye+Y6DKfgq6HX1MbHLXbuY+3bP4Jw7gKJHCArJyG3gRowEZ7EmhbAgWQHGZmfore8C+0ZTuL8naJAPLVtRKgv6oDBgXAN/0oUrmW27fRIWZkdbwFUineoGlPuEZAyDDcxuV1XHYeZuQXIz23GNNytaM3Fu0oRsDEhfAZZGkSICRefVxuzvk/DJOVII9OsT4wbGK43wDJJwkiAv2wUSwzI8vAmqRd3DRMydTqgQYBtDrALwRDZp1B6l5JgtzkrGGiWdsMck/2NYdg9Ri1W9bawy4CtKXhrcWJXmHQdQ2Grjvp5jh6ozPxN6OtfmxjG7JBax05HNHLv4WdtpvXVsIkrKlQxK3harKGTq+pg5U2WXk0r+WGbS0TLa/L/bZ1FI5B39G2BEmztXqgQQCtDhgShRBuVx/gKNo2UYBVdG51M2SQLFcBBkze7yLAfwMfWUmYSyIXfwFbDvcSq6/ClClUKOL42ppZDXsmRzuTKxOP5swqGFdfUdfkXlvWdQzns12T1yMqTft+oEGACSdee5tz1YjIFb/DSFkFcthQhjTUDHLPGocA2ygAd2r9JjCB+TUtYf8NWsluMsyGqEV/RMJGRkBWhQumLAqQVdUogBwtfC/nG+6xZbHO4LO9RhbAN3kk5LcI/LtHBNDqgLAE6DO/wUjmB/s6NrKCZGjYVt8ARomNU0HlC0cE9Bm3o1GA9vrR6GAa7+FQS7idU6eTOU29VpupEAvC511EAlcSU8ZVDcfoxmVegSWzEvbVdcouOVr5Xs433GNbXYsHGAH9RrMeiImDfA/Kv74igKoD5HdBUgfIdtW8nhuKtSSbrKtBfGYt7OKsiOGMnBMhskUIKsxN1H0P5HMJ0wQoOnIK6nc+XhxsjrSMbZBPqXonp1OAYWovELH4t0ihffE5tImbHmtGA5z/PDrbJu/lvFyP59GypkbtVO+fpNUDDR+PiwCqDriddYBh7WWYmWSMG5hJc5qQ+W5f6UWABhEYLbaVLGSyWcmlbOVWOEQ5cexl9UWoh3MtYUHeHnn024GjZnDtTuEUNSBi2acqQhM43RJy69l/nerXvopHwcWupvMJvMfEgZRawvch7lP8Q3D+o4vSfrwIcHRq1ibcaZ7J4oRzhwLEra/W2KAdJdklUACJghuScV0J0H1YDgUIU04cek4SLerl+z53B5tjSYH6rfEXg8fMcQgQi7BFFzCKG6GEXDq1uU6bos3ZRRI4QGZGQALrgSEz31C1ivwekn/jtTpg/lK0syzB0AwgYEU9hiyr0liuHcNmX0P4zGsIm3VjwmcBMQuALva1DNdw5cTjZ16XTq7+kjzg+I3h74MnLFC7N11gFPxmvAMj65RwzvFwjn74HM2ucNX/jYmYUYegBdUIYf7onX5Bibn/mRel/bkiwMXglLHwn5yHLRywrNNA5nMaq5/n+2eBdU85cZw87UnOSWAbn+mfmg2db6hywvFV+D97JEzxcLA5Nu2XfQo+jpq6lEvgcPXL03F5n6LobSatlwjtzz5BaFP28Zsjdq95Bth8Dphz6DJ8Qu3YuEcJvFEE+L5n1AjETsvEi6++j+NnL+DJlz9w4YlX3HjVk6df+wAvvvERAsbPR6v7jcqJE1qYqXns7mBzOH5m+2vj9JWqtNYNMGDBtgN45bWP8ITYpOy64LCp4eidY6/K9Q9xhr7tfvI17kxTsThX2w6LAGdGrdyEVsGj0LbnBLTqaINPFztJaKRVS+hsR+tOSWgbyHVbr835F966IJ186T9mtoeDzbH7KfUNzlu2OVnqvY/+AbTpOww+HZLYl/TXZF9L0HWy4rYuqfAZMA66yGQ8duactD9dBJh++PRr8IkegW7RK9HV9yF0HDgenXwn3jJd7p+M9sFj0Cpa+zTojFZ3XwqdtMjDweY4flb9qPJc8oJ16n3rqJHo4J/GPiZ59NsS7umfil6By3BP7Fx0tKbix58vS/udRYDu8hmZLsKGTvp56BO0BJ19x+Je/8m3TPdBD+KuoHHuAsx/55PfISZ9OfxGz24WiZZJWdtxtbJKnj2TunwTnR+BNhEj0WXwJHTzm+LRb/NMwr0U4b7Ilawq0zAxa5u0zczV9HnArwzTl6J97FT0CV+FLr7jvDTSPCLAPYHjGU2aAGff/1g6SiYziPw+Tv4PqTm+JExviCfPjl+1FT4U4LbwB1QfXX+BAF380tBzyCx0j1mGVlHJOKnlpjQ4CZBReOQZtOZ63ZPToLv/ND400aOh5uhGAToGTFAGiwA3+lVoS+Gzx6esyVeC3hGWqpzv6qXf5pCI7hO8TEV4m+hEVFRVi13tnQUI+Ozr7zgN7OgSuxC9hy7gQ7ceBd38HkSnIRNV+Stz9v2Ln0lHBnfHWgqfPfLwhmI1pdqFjlYCu/fZErr4jkfv8JWM8Cmwz1stNr3haF8TwPHmL71TJuPu2IfQO3TFL8oDMkIyT9tGjFLz9jeffSGdRbo71lL47ME5uaVKgDtDxqop5t5nszCSe/g/jB7RyxiZw1F09JTYpP6LxV2AHcuL96Nt9FjcF7VSm2t+kzwbvAkNISrzVVaVS198I501/j7/VuGzZYvz9yoBJLn+EgEkknsHLsa9+oVc/uwNv1bv700As2RrXWQiusUuQ0//6ejQPwWd7k+9JboMGIs7QilAzIjGLyDcHWspfLZkZclBJebdQ0bj3v6jPfprjg79hqFP6HLcrZ+OoWmzxJ7fO7XvIoBPff113BmXgg6xMzAoJg99Qpajb1hGywnPRP/gDNwVkgYds+1X330vHfq6O9ZS+Gx+Vumj8IkYhm5BszAgbK1nnzehT+hKDAjPRl/9BualEawvDok9jf/D5CKA48Spcas2oW3kKPilHkPghJcwZNypFhOQ9gICx59GR8NctAqz4Pt//igd9nR3rKVIBKwoPqB+vNkvsQhBk85iyHjPfm9G6KQ30MO+AboQIy5c+lzsiXVq30OAhPc+/QO6xKfhHvNodDCPuSXUM5Zx6GSdiIR5ayH/9cW/1u6OtRSozysv4l7bJO7eJrB9zz6bo+EZyyyV/d91a79xGXRGtkny9ansFf8T5NMQtdn4D/lv2SO7nylwa9+9s/85/h9YiIegRTk8AwAAAABJRU5ErkJggg\u003d\u003d"}
Версия сервера: MST Network 1.12.2-1.19.2 (протокол v760)
Файл переводов загружен.
[MCC] Версия поддерживается.
Войти в игру...
[MCC] Войти не удалось:
[MCC] Открытый ключ профиля отсутствует.\nДля этого сервера требуются защищённые профили.

[ERROR] Не удалось войти на этот сервер.
Не подключен ни к одному серверу. Используйте '/help' для получения справки.
Нажмите Enter, чтобы выйти из консольного клиента Minecraft.
>

### Attach screenshot here (If applicable)

![2022-11-25_21-28-06](https://user-images.githubusercontent.com/103605226/204040087-1b1bfde1-efab-4e74-8b3e-f54d75f0a522.png)

### Anythings that could help diagnosing the bug

```txt
Разрешение mstnw.net...
Найден сервер line.mstnetwork.ru:25500 для домена mstnw.net
Help us translate MCC: https://crwd.in/minecraft-console-client
Вы выбрали запуск в автономном режиме.
Получение информации о сервере...
Версия сервера: MST Network 1.12.2-1.19.2 (протокол v760)
[MCC] Версия поддерживается.
Войти в игру...
[MCC] Войти не удалось:
[MCC] Открытый ключ профиля отсутствует.\nДля этого сервера требуются защищённые профили.

[ERROR] Не удалось войти на этот сервер.
Не подключен ни к одному серверу. Используйте '/help' для получения справки.
Нажмите Enter, чтобы выйти из консольного клиента Minecraft.
MCC: /reco [account]: перезапустить и заново подключиться к серверу.
MCC: /connect <server> [account]: подключиться к указанному серверу.
Перезапуск консольного клиента Minecraft...
Settings have been loaded from MinecraftClient.ini
Вы выбрали запуск в автономном режиме.
Получение информации о сервере...
Версия сервера: MST Network 1.12.2-1.19.2 (протокол v760)
[MCC] Версия поддерживается.
Войти в игру...
[MCC] Войти не удалось:
[MCC] Открытый ключ профиля отсутствует.\nДля этого сервера требуются защищённые профили.

[ERROR] Не удалось войти на этот сервер.
Не подключен ни к одному серверу. Используйте '/help' для получения справки.
Нажмите Enter, чтобы выйти из консольного клиента Minecraft.
>
```

### Operating System

Windows

### Server Address (If applicable)

mc.mstnw.net

**Comment by milutinke** [comment]
First of all, use English.
You need to use a premium account with that server.
If you are using a premium account, it must be migrated to Microsoft.
If you happen to use the premium and have migrated your account to Microsoft already, delete `SessionCache.ini` and `ProfileKeyCache.ini` (make sure the client is closed).
After you delete them, login to your account using the `browser` login method and try again.

**Comment by DARKSRG** [comment]
Я использую пиратский  сервер

**Comment by milutinke** [comment]
Use English

**Comment by DARKSRG** [comment]
Нет когда я захожу с пиратского лаунчера майнкрафт все прекрасно работает, а бот не подключается

**Comment by DARKSRG** [comment]
Okay, let's say if the built-in texture pack is installed on the server
and does not let the server?

**Comment by breadbyte** [comment]
mcc is programmed to fake the installed texture pack if the server requires a texture pack.

**Comment by DARKSRG** [comment]
Either I have a strange server or you have an error

**Comment by BruceChenQAQ** [comment]
I can't reproduce this. What minecraft version did you use to join the server?
![image](https://user-images.githubusercontent.com/26017411/204124144-98e72473-a0dc-4a97-abcd-facb703fea2d.png)

**Comment by DARKSRG** [comment]
1.16.5

**Comment by DARKSRG** [comment]
Thank all good
