### ISSUE TITLE
[BUG] An internal exception occured while parsing line 3 of the TOML document 

### ISSUE THREAD

**Issue by tolland** [MCCTeam/Minecraft-Console-Client#2355]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2

### Console Client Version

GitHub build 166, built on 2022-11-25

### Expected Behavior

should be able to edit config file. Any change to the config file, even trivial change causes the error.

### Actual Behavior

Any edits to the config file cause the following error:

```shell
Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam                                                
Failed to load settings:                                                                                                      
An internal exception occured while parsing line 3 of the TOML document                                                       
 --> Index was outside the bounds of the array.
                                                                                                                              
Failed to parse the settings file, enter "/new" to generate a new configuration.                                              
Or press Enter to exit Minecraft Console Client.                                                                              
New configuration file "MinecraftClient.ini" is generated. 
```

File is UTF-8 with LF linefeeds, which seems to be how it was generated.

also setting the following causes an error:

```
$ ./MinecraftClient --debugmessages=true

Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam                                              
GitHub build 166, built on 2022-11-25 from commit 851ecf5                                                                   
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at MinecraftClient.Settings.LoadArguments(String[] args)
   at MinecraftClient.Program.Main(String[] args)
Aborted (core dumped)
```

### Steps to Reproduce the bug

1. checkout master branch on fedora linux
2.  build executable with ` dotnet publish MinecraftClient -f net6.0 -r linux-x64 --no-self-contained -c Release -p:UseAppHost=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None`
3. run command from publish dir
4. config is generated
5. make any change to config.
6. Error is produced.

### Device

Desktop

### Operating System

Linux

**Comment by BruceChenQAQ** [comment]
> Any edits to the config file cause the following error

Can you upload the settings file where the problem occurred? So that we can reproduce the error.

> also setting the following causes an error:

Parsing the specified settings from command line parameters is not currently supported.

**Comment by tolland** [comment]
[MinecraftClient.ini.zip](https://github.com/MCCTeam/Minecraft-Console-Client/files/10119002/MinecraftClient.ini.zip)

**Comment by tolland** [comment]
Ah, so the problem happens when "trim trailing whitespace" is enabled.

**Comment by tolland** [comment]
`
[Minecraft-Console-Client] $ git diff MinecraftClient.ini
diff --git a/MinecraftClient.ini b/MinecraftClient.ini
index 893cfdd..e9e241f 100644
--- a/MinecraftClient.ini
+++ b/MinecraftClient.ini
@@ -1,6 +1,6 @@
 # Startup Config File
 # Please do not record extraneous data in this file as it will be overwritten by MCC.
-# 
+#
 # New to Minecraft Console Client? Check out this document: https://mccteam.github.io/g/conf.html
 # Want to upgrade to a newer version? See https://github.com/MCCTeam/Minecraft-Console-Client/#download
 [Head]
@@ -31,7 +31,7 @@ ShowSystemMessages = true                   # System messages for server ops.
 ShowXPBarMessages = true                    # Messages displayed above xp bar, set this to false in case of xp bar spam.
 ShowChatLinks = true                        # Decode links embedded in chat messages and show them in console.
 ShowInventoryLayout = true                  # Show inventory layout as ASCII art in inventory command.
-TerrainAndMovements = false                 # Uses more ram, cpu, bandwidth but allows you to move around.
+TerrainAndMovements = true                  # Uses more ram, cpu, bandwidth but allows you to move around.
 MoveHeadWhileWalking = true                 # Enable head movement while walking to avoid anti-cheat triggers.

`````

**Comment by BruceChenQAQ** [comment]
This issue should be fixed in https://github.com/SamboyCoding/Tomlet/pull/19.

**Comment by SamboyCoding** [comment]
Hey, thanks for the report, I've just pushed Tomlet 5.0.1 to nuget which contains the mentioned PR, should be available within about 5-10 minutes of this comment.
