### ISSUE TITLE
Server version not reported

### ISSUE THREAD

**Issue by razzeking** [MCCTeam/Minecraft-Console-Client#2356]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

1.4.6

### Expected Behavior

connect to my 1.19.2 server

### Actual Behavior

it doesnt connect and says what can be seen in screenshot Attached

### Steps to Reproduce the bug

1. connect mcc 1.19.2 server

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/47952472/204747960-230d2dba-df48-4005-80b2-1aa6e182f05a.png)

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

178.32.123.15:25599

**Comment by breadbyte** [comment]
You can specify the minecraft version to be used when prompted, or you can force the version in the `MinecraftClient.ini` file under `MinecraftVersion` in `[Main.Advanced]`
