### ISSUE TITLE
[QUESTION] I can have the Discord Console with colors?

### ISSUE THREAD

**Issue by PJ289** [MCCTeam/Minecraft-Console-Client#2376]
I would like to know if it is possible to see the Discord Bridge console with the same colors and formats as the client console. If possible, could you tell me how I can do it?

**Comment by milutinke** [comment]
Discord does not have support for colored text, so it's not possible.

**Comment by ReinforceZwei** [comment]
Discord "partially" supported using `ANSI` code-block: https://gist.github.com/kkrypt0nn/a02506f3712ff2d1c8ca7c9e0aed7c06

**Comment by milutinke** [comment]
> Discord "partially" support color text by using `ANSI` code-block: https://gist.github.com/kkrypt0nn/a02506f3712ff2d1c8ca7c9e0aed7c06

That is cool, didn't know about that, I'll look into this in a month or two

**Comment by milutinke** [comment]
> Discord "partially" support color text by using `ANSI` code-block: https://gist.github.com/kkrypt0nn/a02506f3712ff2d1c8ca7c9e0aed7c06

Doesn't appear to be working. Tested it out, it would not work both in the web browser or in the electron app.

**Comment by ReinforceZwei** [comment]
> Doesn't appear to be working. Tested it out, it would not work both in the web browser or in the electron app.

![image](https://user-images.githubusercontent.com/39955851/207819219-cd17fa35-9bdf-44f7-bce6-95cc4626d8c2.png)
https://rebane2001.com/discord-colored-text-generator/
It works when using the generator.

**Comment by breadbyte** [comment]
Take note, from the gist itself:

> The \u001b is the unicode for ESCAPE/ESC, see http://www.unicode-symbol.com/u/001B.html. **_If you want to use it yourself without bots, then you need to copy paste the character from the website._**

The wording is a little bit confusing, but basically, copying `\u001b[{format};{color}m` as-is into discord does not work.
It will only work when applying it through bots and/or automated systems, since `\u001b` automatically gets converted into the corresponding unicode letter using the programming language (as it is escaped through the string).

You have to replace the `\u001b` character manually using the link provided, in order for it to work when pasting directly into discord.

Rebane's tool does this automatically and has a user-friendly interface for changing the colors.

**Comment by milutinke** [comment]
> Take note, from the gist itself:
> 
> > The \u001b is the unicode for ESCAPE/ESC, see http://www.unicode-symbol.com/u/001B.html. **_If you want to use it yourself without bots, then you need to copy paste the character from the website._**
> 
> The wording is a little bit confusing, but basically, copying `\u001b[{format};{color}m` as-is into discord does not work. It will only work when applying it through bots and/or automated systems, since `\u001b` automatically gets converted into the corresponding unicode letter using the programming language (as it is escaped through the string).
> 
> You have to replace the `\u001b` character manually using the link provided, in order for it to work when pasting directly into discord.
> 
> Rebane's tool does this automatically and has a user-friendly interface for changing the colors.

Plus it only renders on the pc
