### ISSUE TITLE
[Idea] use %variable% on name

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2379]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

use %variable% on nickname

### Minecraft Version

1.16.5

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Discussed in #2380
