### ISSUE TITLE
[BUG] Packet processing error when using inventory command

### ISSUE THREAD

**Issue by Pledix** [MCCTeam/Minecraft-Console-Client#2382]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.17.1

### Console Client Version

GitHub build 176, built on 2022-12-02 from commit 597af24

### Expected Behavior

Should click slot on the current open inventory

### Actual Behavior

Getting [MCC] Packet processing error

### Steps to Reproduce the bug

1. I open a double chest inventory (gui)
2. I try these commands `/inventory 1 shiftclick 10 right` and `/inventory container shiftclick 10 right
3. And i get packet processing error

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/22866860/208241867-ef39a9c2-8e5f-4383-90e9-24fba45b11ca.png)
![image](https://user-images.githubusercontent.com/22866860/208241890-d5e03e16-d43a-408c-9417-688b38d44da1.png)

### Anythings that could help diagnosing the bug

```txt
My changes in MinecraftClient.ini file

[Main.Advanced]
TemporaryFixBadpacket = true
InventoryHandling = true
```

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Can you attack the exact error log?

**Comment by milutinke** [comment]
Closing as a stale issue.
