### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by truong0235** [MCCTeam/Minecraft-Console-Client#2386]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

auto

### Console Client Version

Latest

### Expected Behavior

Work normally (with color)

### Actual Behavior

Color error come back when change (any) setting in MinecraftClient.ini

### Steps to Reproduce the bug

1. Download latest one
2. Extract, run (in windows 7), work with color
3. Close console, open MinecraftClient.ini that it generated
4. Change any setting (debugmessages=true for example), save change
5. Run it again, see error

### Anythings that could help diagnosing the bug

```txt
Also, if set debugmessages=true and run it, it may freeze my laptop for no reason
```

### Device

Laptop

### Operating System

Windows

**Comment by BruceChenQAQ** [comment]
Did you change the setting after the window was completely closed and save it before the next time you run MCC?
(Slow window closing is a bug and will be fixed in #2385)

I tested it inside a Windows 7 SP1 x64 virtual machine and it worked fine.

**Comment by BruceChenQAQ** [comment]
It is more recommended to use more modern terminals for better color support.
You can refer to this discussion: https://github.com/MCCTeam/Minecraft-Console-Client/discussions/2366

**Comment by truong0235** [comment]
> Did you change the setting after the window was completely closed and save it before the next time you run MCC? (Slow window closing is a bug and will be fixed in #2385)
yes, completely closed before changing setting

**Comment by truong0235** [comment]
> It is more recommended to use more modern terminals for better color support. You can refer to this discussion: #2366

it freeze the os completely, tried opening task manager with keyboard shortcut but no respond, so i have to press power button to force shutdown and reboot again

**Comment by kvr25565** [comment]
Windows 7 x64 here, no freeze

**Comment by milutinke** [comment]
Try using Alacritty on Windows 7

**Comment by truong0235** [comment]
ok
maybe it has some problem with default windows 7 cmd (in my case)
i tried install some c runtime update, nothing works
so i will use cmder and left the default cmd problem behind
