### ISSUE TITLE
how i can automaticly sand a messeg every moment i coined server

### ISSUE THREAD

**Issue by mattxn3** [MCCTeam/Minecraft-Console-Client#2387]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

latest

### Expected Behavior

how i can automaticly sand a messeg every moment i coined server

### Actual Behavior

how i can automaticly sand a messeg every moment i coined server

### Steps to Reproduce the bug

1. 
2. 
3. 

### Attach screenshot here (If applicable)

how i can automaticly sand a messeg every moment i coined server

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Use Script Scheduler
https://mccteam.github.io/guide/chat-bots.html#script-scheduler
