### ISSUE TITLE
0x8007000E when running in Ubuntu termux

### ISSUE THREAD

**Issue by Dominik159E0** [MCCTeam/Minecraft-Console-Client#2389]
![Screenshot_2022-12-24-20-40-50-94_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/90928810/209449205-09b5c419-35bc-471d-a2ff-08c25ea89363.jpg)

**Comment by milutinke** [comment]
You ran out of memory.
Try executing `ulimit -v unlimited`

**Comment by Dominik159E0** [comment]
Tried that command but it did nothing.

**Comment by milutinke** [comment]
> Tried that command but it did nothing.



> Tried that command but it did nothing.

Then you don't have enough of memory to run the app.
Try stopping all other apps and just running termux and mcc.

**Comment by Dominik159E0** [comment]
Tried, with 2.8GB free ram it still didn't work

**Comment by milutinke** [comment]
> Tried, with 2.8GB free ram it still didn't work

Try setting other ulimits to unlimited, search it up.

**Comment by Dominik159E0** [comment]
Thank you, after setting everything i could in ulimit -a fixed it.

**Comment by XIAYM-gh** [comment]
This is my solution
Hope to help people who also encounter this problem

You can write a script called `start.sh`

Then, Write the following contents to this file:
```shell
#!/bin/bash
ulimit -c unlimited
ulimit -s unlimited
./MinecraftClient
```

to run, type `chmod +x start.sh` and `./start.sh`
