### ISSUE TITLE
[BUG]  cannot execute binary file

### ISSUE THREAD

**Issue by CatNiangFeitu** [MCCTeam/Minecraft-Console-Client#2391]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2

### Console Client Version

Laste

### Expected Behavior

Fix this bug

### Actual Behavior

.

### Steps to Reproduce the bug

1. Download from https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/brigadier-dev-prerelease (I tried [MinecraftClient-linux.zip](https://github.com/MCCTeam/Minecraft-Console-Client/releases/download/brigadier-dev-prerelease/MinecraftClient-linux.zip) and [MinecraftClient-osx.zip](https://github.com/MCCTeam/Minecraft-Console-Client/releases/download/brigadier-dev-prerelease/MinecraftClient-osx.zip) they all can not run.)
2. Open new shell
3. Run command   **bash /root/MinecraftClient**

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/108512490/209515686-41a5469d-e059-4e3b-805e-df05980098b6.png)

### Anythings that could help diagnosing the bug

```txt
root@catniang:~# uname -a
Linux catniang 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:32:55 UTC 2022 s390x s390x s390x GNU/Linux

root@catniang:~# lscpu
Architecture:                    s390x
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Big Endian
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s) per book:              1
Book(s) per drawer:              1
Drawer(s):                       2
NUMA node(s):                    1
Vendor ID:                       IBM/S390
Machine type:                    8561
CPU dynamic MHz:                 5200
CPU static MHz:                  5200
BogoMIPS:                        3241.00
Hypervisor:                      z/VM 7.1.0
Hypervisor vendor:               IBM
Virtualization type:             full
Dispatching mode:                horizontal
L1d cache:                       256 KiB
L1i cache:                       256 KiB
L2d cache:                       8 MiB
L2i cache:                       8 MiB
L3 cache:                        256 MiB
L4 cache:                        960 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; etokens
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx vxd vxe gs
                                  vxe2 vxp sort dflt sie
```

### Device

VPS

### Operating System

Linux

**Comment by ReinforceZwei** [comment]
`sudo chmod a+x /root/MinecraftClient` to give it permission to run.

**Comment by CatNiangFeitu** [comment]
I tried, but it didn't work.
![image](https://user-images.githubusercontent.com/108512490/209539130-6f8b0647-8ad5-453b-aca5-a557ced46332.png)


> `sudo chmod a+x /root/MinecraftClient` to give it permission to run.

**Comment by ReinforceZwei** [comment]
Delete old one and download Linux version [MinecraftClient-linux.zip](https://github.com/MCCTeam/Minecraft-Console-Client/releases/download/brigadier-dev-prerelease/MinecraftClient-linux.zip)
Then `sudo chmod a+x /root/MinecraftClient` and try again.

**Comment by CatNiangFeitu** [comment]
I tried, but it didn't also work.
![image](https://user-images.githubusercontent.com/108512490/209540173-d85bb14c-15f4-45cb-8b23-0275d3979bde.png)
I have replaced the file and run **sudo chmod a+x /root/MinecraftClient**     (GTM +8)
![image](https://user-images.githubusercontent.com/108512490/209540304-73b3a521-ce3d-4154-ae83-da6adef84bd8.png)



> Delete old one and download Linux version [MinecraftClient-linux.zip](https://github.com/MCCTeam/Minecraft-Console-Client/releases/download/brigadier-dev-prerelease/MinecraftClient-linux.zip) Then `sudo chmod a+x /root/MinecraftClient` and try again.

**Comment by ReinforceZwei** [comment]
Don't use `bash` to run program on Linux. Simply use `./MinecraftClient`.

**Comment by CatNiangFeitu** [comment]
> ./MinecraftClient

![image](https://user-images.githubusercontent.com/108512490/209540977-5b872c53-bea0-40de-a14e-c346dbb31ce9.png)

**Comment by breadbyte** [comment]
The underlying issue here is that the poster is running under the `s390x` architecture.

.NET supports `s390x`, but the support is provided by the open-source community, so there are no binaries provided by Microsoft that supports this architecture.

The only downloadable binaries that support s390x compilation out of the box come from RedHat, and Github Actions currently does not have native support for running an `s390x` build.

I'll look into this a bit further, but `s390x` is a bit of a _niche_ architecture, so your options currently are

1. download source and build it yourself with the rid `linux-s390x`
2. (preferably), get an x86 machine and run it there

**Comment by CatNiangFeitu** [comment]
> The underlying issue here is that the poster is running under the `s390x` architecture.
> 
> .NET supports `s390x`, but the support is provided by the open-source community, so there are no binaries provided by Microsoft that supports this architecture.
> 
> The only downloadable binaries that support s390x compilation out of the box come from RedHat, and Github Actions currently does not have native support for running an `s390x` build.
> 
> I'll look into this a bit further, but `s390x` is a bit of a _niche_ architecture, so your options currently are
> 
> 1. download source and build it yourself with the rid `linux-s390x`
> 2. (preferably), get an x86 machine and run it there

OK.Thanks.
