### ISSUE TITLE
Accounts log in but instant log back to hub [BUG] 

### ISSUE THREAD

**Issue by Rusty1410** [MCCTeam/Minecraft-Console-Client#2392]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

auto

### Console Client Version

latest just downloaded

### Expected Behavior

Alts to log in saico as normal and afk things 

### Actual Behavior

Logs onto server
one first command from hub goes through it goes onto server
then instant goes back to hub
when i turn on DebugMessages it works the first time then doesn't unless I change the true or false

### Steps to Reproduce the bug

1. drag alt file onto mincraftclient,exe
2. allow to load up
3. alt logs into server
4. trys once to log onto realm 
5. then crashes and keeps doing the same thing
6. 
7. 

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/121429634/209536982-d4530d48-fd06-4d88-9937-4310bb9f5bd3.png)

### Anythings that could help diagnosing the bug

```txt
no clue
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

play.saicopvp.com

**Comment by deosync** [comment]
use auto respond bot

**Comment by Rusty1410** [comment]
> use auto respond bot

Might i ask what that is?

**Comment by Rusty1410** [comment]
Thanks to Deosync i got the issue resolved

**Comment by milutinke** [comment]
Use ScriptScheduler and use the on login event to send a command to switch to a sub server.

**Comment by Rusty1410** [comment]
idk what that means

**Comment by milutinke** [comment]
> idk what that means

You can use Script Scheduler chat bot to define a task that will trigger once you login to the serer, then it can send a command to switch you to a sub server automatically.

More on it:
https://mccteam.github.io/guide/chat-bots.html#script-scheduler
