### ISSUE TITLE
[BUG] Bot doesn't work in screen 

### ISSUE THREAD

**Issue by Vazgen005** [MCCTeam/Minecraft-Console-Client#2396]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [x] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

Latest

### Expected Behavior

Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
GithubPreRelease build 177, built on 2022-12-14 from commit 7ee0809
Login :
>

### Actual Behavior

Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
GithubPreRelease build 177, built on 2022-12-14 from commit 7ee0809
[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: False
 triggerontime: True
 triggeroninterval: True
 timevalue: 14:00:00
 timeinterval: 53.4
 action: send /hello
[MCC] [ScriptScheduler] Loaded task:
triggeronfirstlogin: False
 triggeronlogin: True
 triggerontime: False
 triggeroninterval: False
 timevalue:
 timeinterval: 56
 action: send /login pass

### Steps to Reproduce the bug

1. screen -S bot
2. cd bots/
3. ./MinecraftClient

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/70487205/209888939-7d95d9bc-537f-4c05-85fd-84b0a64e25c1.png)

### Anythings that could help diagnosing the bug

```txt
Default config with debugmessages=true

When i trying to open MCC in screen console output stops on:
Minecraft Console Client v1.19.2 - for MC 1.4.6 to 1.19.2 - Github.com/MCCTeam
GithubPreRelease build 177, built on 2022-12-14 from commit 7ee0809

I can't even enter login or server ip address
```

### Device

Raspberry Pi

### Operating System

Linux

### Server Address (If applicable)

I can't even enter ip address

**Comment by Sanceilaks** [comment]
I have same problem

**Comment by BruceChenQAQ** [comment]
Should be fixed in the latest release. Testing found it was stuck when setting the console title.

Since https://github.com/breadbyte/ConsoleInteractive/pull/20 and https://github.com/MCCTeam/Minecraft-Console-Client/pull/2358 have not yet been merged, only the released files are updated and no new releases are published.
