### ISSUE TITLE
[BUG] MCC eat up too much ram

### ISSUE THREAD

**Issue by truong0235** [MCCTeam/Minecraft-Console-Client#2397]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

auto-1.19.2

### Console Client Version

Latest

### Expected Behavior

run normal like older version

### Actual Behavior

ram usage can up to 3gb when run MCC

### Steps to Reproduce the bug

1. download lastest one
2. extract file
3. open task manager (or any thing else to track resource usage)
4. run MCC, notice resource eat up every thing

### Attach screenshot here (If applicable)

on low-end device, 4gb ram, intel core i3 chipset, windows 7 pro
https://user-images.githubusercontent.com/53035575/210087601-955f9617-e02c-4cf2-b189-38cd021fc44d.mp4

mid-end device, 8gb ram, intel core i5 chipset, windows 7 pro

[8ec3bfa8-cf79-44f3-a194-e3022fe44642.webm](https://user-images.githubusercontent.com/53035575/210087720-ac423178-3386-48e1-8bd9-cf3ef9270604.webm)

### Device

Laptop

### Operating System

Windows

**Comment by BruceChenQAQ** [comment]
Will it also use so much memory if opened with system cmd?

The memory usage seen from the "Processes" page is normal. Try clicking "View", selecting "Select Columns", and checking all memory-related indicators.

**Comment by BruceChenQAQ** [comment]
![image](https://user-images.githubusercontent.com/26017411/210128602-942a527e-a52d-42c7-a524-bc9db2f36ea9.png)
![image](https://user-images.githubusercontent.com/26017411/210128608-1df91cf7-eb99-419e-b088-c1f003e5fecf.png)

The problem was successfully reproduced and after initial testing it was found that the problem occurred before the MCC started executing.

This could be a .NET related issue (needs further testing).

**Comment by BruceChenQAQ** [comment]
Related issue: https://github.com/dotnet/runtime/issues/80078

**Comment by truong0235** [comment]
so there is nothing i can do with it but use older version?

**Comment by breadbyte** [comment]
@BruceChenQAQ Can you do a bisect and see if it's an issue that we can fix on our side while we wait for a response in the dotnet runtime repo?

**Comment by BruceChenQAQ** [comment]
@truong0235 @breadbyte 

Simply put, the solution is to run this command first:
`setx DOTNET_EnableWriteXorExecute 0`

---

> It might be caused by the double allocator introduced by W^X. If you run your app on Linux you may see the virtual address space mapped is 2TB. 
> Can you try setting the environment variable `DOTNET_EnableWriteXorExecute=0`?

https://github.com/dotnet/runtime/issues/79469#issuecomment-1345148117
