### ISSUE TITLE
[Idea] Is it possible to claim a quest (ftb-quests) programmatically?

### ISSUE THREAD

**Issue by LaserKaspar** [MCCTeam/Minecraft-Console-Client#2399]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

v1.19.2

### Describe your problem

It would be great to interact with the ftb-quest book to claim some quests automatically.

### Suggest a possible solution

Something similar to the chest interaction.

### Minecraft Version

1.16.5

### Device

None

### Operating System

None

**Comment by milutinke** [comment]
This is a vanilla first client and this is a mod feature.
