### ISSUE TITLE
[Idea] support unicode characters in AutoRespond

### ISSUE THREAD

**Issue by truong0235** [MCCTeam/Minecraft-Console-Client#2400]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Auto respond cant detect unicode character (it can detect Cau ca, but not Câu cá)

### Attach screenshot here (If applicable)

Skip this idea if you guys are too busy, anyway

### Minecraft Version

Auto

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
It can, but you have to use Unicode escape sequences for regex.
Read this; https://github.com/MCCTeam/Minecraft-Console-Client/issues/2299#issuecomment-1287794555
