### ISSUE TITLE
[BUG] Telegram bot execute command it executed (.quit)

### ISSUE THREAD

**Issue by HundSimon** [MCCTeam/Minecraft-Console-Client#2402]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

20221214-177

### Expected Behavior

(i am not a native speaker, so please forgive my errors in words)
quit console after using .quit in telegram bot
should be normal next time

### Actual Behavior

execute command(.quit) next time I start MCC

### Steps to Reproduce the bug

1. use .quit in telegram bot
2. MCC quits
3. next time it runs, still execute command .quit which it executed

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/77706174/210952605-b13cdb12-eb25-4f90-bb19-04b19122bcea.png)
![image](https://user-images.githubusercontent.com/77706174/210952938-4bd9aa2e-c06b-4b5d-9c5b-65759c4d2262.png)
first image means: command executed, result: Done

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
That is the bug with Telegram caching, nothing we can do about it.
