### ISSUE TITLE
[BUG] 生成的dll被火绒当做病毒 | The resulting DLL is treated as a virus by Velvet

### ISSUE THREAD

**Issue by NingLiu1998** [MCCTeam/Minecraft-Console-Client#2412]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

最新

### Expected Behavior

如何解决这个问题

### Actual Behavior

生成项目后的MinecraftClient.dll被火绒直接当做病毒删除
English： After generating the project, the MinecraftClient .dll removed as a virus by Velvet
![image](https://user-images.githubusercontent.com/109678937/213908800-4170bece-3546-4441-9efd-dcde8c97bfb4.png)

### Steps to Reproduce the bug

1. 安装火绒
2. 下载本项目最新源码
3. 编译MinecraftClient

### Attach screenshot here (If applicable)

![V(G{WM9MR9NI2Y1XO)2}OS0](https://user-images.githubusercontent.com/109678937/213908838-52e4e644-ef80-4ad5-9372-e347ef80256d.png)

### Device

Desktop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
Anti-virus software false positive. You've got the source code, you can check the code if you don't trust my word.

**Comment by BruceChenQAQ** [comment]
已经提交反馈，等待官方跟进。
https://bbs.huorong.cn/thread-119062-1-1.html

Have submitted the issue to HuoRong and waiting for their further feedback.
