### ISSUE TITLE
[Idea] 

### ISSUE THREAD

**Issue by NOAHBENJ** [MCCTeam/Minecraft-Console-Client#2421]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

GitHub build 189, built on 2023-01-29 from commit 3735cab

### Describe your problem

Add a Timer for scripting, because the SendText method is not static, and the Timer stuff is all meant to be static, meaning that I cannot stop the timer, meaning that the script keeps going with the timer, and the rest of it kinda dies.

### Minecraft Version

1.8.9

### Device

Laptop

### Operating System

MacOS

**Comment by milutinke** [comment]
Use Update method or create a separate thread where you can have a while loop to infinity and Thread.Sleep
