### ISSUE TITLE
[BUG] When sending text via a function, the text will repeatedly send, in increments of one every time the function is run

### ISSUE THREAD

**Issue by NOAHBENJ** [MCCTeam/Minecraft-Console-Client#2422]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

Latest

### Expected Behavior

public void SendFinal(string option) {
		SendText("Text1");
		SendText("Text2");
		SendText("Text3");
		party = false;
	}

Output:
Text1
Text2
Text3

### Actual Behavior

(assume 3rd time run, and same function as above)
Text1
Text1
Text1
Text2
Text2
Text2
Text3
Text3
Text3

### Steps to Reproduce the bug

1. 
2. 
3. 

### Device

Laptop

### Operating System

MacOS

**Comment by milutinke** [comment]
Can't reproduce.
Only thing that comes to my head is that you ran the script multiple times.
