### ISSUE TITLE
Translation correction

### ISSUE THREAD

**Issue by CatNiangFeitu** [MCCTeam/Minecraft-Console-Client#2428]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Laste

### Describe your problem

There is a translation error when sending `/help` (with Chinese language)

> [MCC] 帮助 <cmdname>。可用命令：
> /help [animation|bed|blockinfo|bots|changeslot|chunk|connect|debug|dig|dropitem|enchant|entity|execif|execmulti|exit|health|inventory|list|log|look|move|reco|reload|respawn|script|send|set|setrnd|sneak|tps|upgrade|useblock|useitem]
> /animation [mainhand|offhand|_help]
> /bed (leave|sleep|_help)
> /blockinfo [-s|<Location>|_help]
> /bots [list|unload|_help]
> /changeslot (<Slot>|_help)
> /chunk (status|_setloading|_setloaded|_delete|_help)
> /connect (<ServerNick>|_help)
> /debug [on|off|_help]
> /dig [<Duration>|<Location>|_help]
> /dropitem (<ItemType>|_help)
> /enchant (top|middle|bottom|_help)
> /entity [near|<EntityID>|<EntityType>|_help]
> /execif <Condition> <Command>
> /execmulti <Commands>
> /exit [<ExitCode>|_help]
> /quit -> exit
> /health [_help]
> /inventory [creativegive|creativedelete|inventories|search|<InventoryId>|player|container|_help]
> /list [_help]
> /log (<String>|_help)
> /look [up|down|east|west|north|south|<Yaw>|<Location>|_help]
> /move (on|off|gravity|up|down|east|west|north|south|center|get|<location>|_help)
> /reco [<AccountNick>|_help]
> /reload [_help]
> /respawn [_help]
> /script (<Script>|_help)
> /send <any>
> /set (<Expression>|_help)
> /setrnd <VarName> (<Min>|<Expression>)
> /sneak [_help]
> /tps [_help]
> /upgrade [-f|download|check|cancel|_help]
> /useblock (<Location>|_help)
> /useitem [_help]
> 服务器帮助，请使用 '/发送 /help' 代替。

`/发送 /help` cannot obtain any information during use.
![image](https://user-images.githubusercontent.com/108512490/218267969-e8399b5c-d08b-440b-b704-5c3d1956e624.png)

### Suggest a possible solution

I think `/发送 /help` should replace `/send /help` In language file.

### Minecraft Version

1.18.2

### Device

Desktop

### Operating System

Windows

**Comment by BruceChenQAQ** [comment]
Fixed, the translation will be updated in the next build.
https://crowdin.com/translate/minecraft-console-client/85/en-zhcn#28349
