### ISSUE TITLE
[BUG] The level and experience value are exchange.

### ISSUE THREAD

**Issue by coffeekevin-joingithub** [MCCTeam/Minecraft-Console-Client#2429]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.3

### Console Client Version

Latest

### Expected Behavior

![image](https://user-images.githubusercontent.com/64188466/218505580-851a9b9f-37c8-45ba-858d-113fd3f5bd08.png)

### Actual Behavior

Just exchange.

### Steps to Reproduce the bug

1. Close MCC
2. Open MCC
3. 

### Device

None

### Operating System

None

**Comment by ReinforceZwei** [comment]
Hi coffee :)
The `Total Experience` and `Level` fields were swapped in 1.19.3 accroding to the protocol document ([1.19.3](https://minecraft-data.prismarine.js.org/?v=1.19.3&d=protocol#toClient_experience), [1.19.2](https://minecraft-data.prismarine.js.org/?v=1.19.2&d=protocol#toClient_experience)). However, it seems like not the case when testing in vallina/paper server.

I will revert the change for now.

**Comment by milutinke** [comment]
> Hi coffee :) The `Total Experience` and `Level` fields were swapped in 1.19.3 accroding to the protocol document ([1.19.3](https://minecraft-data.prismarine.js.org/?v=1.19.3&d=protocol#toClient_experience), [1.19.2](https://minecraft-data.prismarine.js.org/?v=1.19.2&d=protocol#toClient_experience)). However, it seems like not the case when testing in 1.19.3 vanilla/paper server.
> 
> I will revert the change for now.

Wiki is not always correct, I forgot to test that out.
This is like the second time there is a major mistake.
