### ISSUE TITLE
Bot Flying

### ISSUE THREAD

**Issue by ClemenzDerEchte** [MCCTeam/Minecraft-Console-Client#2431]
Hello there,
i build an cactus farm and now i want to build an afk bot.
But the bot is always kicked from the server after a few minutes because the bot is flying
How can i disable flying for minecraft console client?
Thank you

**Comment by milutinke** [comment]
`move gravity on`

**Comment by ClemenzDerEchte** [comment]
i have tried it and the bot fly althrough
![image](https://user-images.githubusercontent.com/115500434/219490802-8aa175e1-5750-445b-96f7-2adb7205a7f9.png)

**Comment by milutinke** [comment]
> i have tried it and the bot fly althrough ![image](https://user-images.githubusercontent.com/115500434/219490802-8aa175e1-5750-445b-96f7-2adb7205a7f9.png)

You need to enable `TerrainAndMovement` first.

**Comment by ClemenzDerEchte** [comment]
i have enabled TerrainAndMovement and it will also not work like the image above
but here my ini file
[minecraftclient.txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/10774044/minecraftclient.txt)

**Comment by milutinke** [comment]
Put some blocks bellow it and try to enable the gravity

**Comment by ClemenzDerEchte** [comment]
I tried it if I spawn the bot on my island and the blocks are not placed he will fall down. But if the blocks are placed and i remove them the bot will not fall down. And the bot will in both cases not affected by water

**Comment by milutinke** [comment]
> I tried it if I spawn the bot on my island and the blocks are not placed he will fall down. But if the blocks are placed and i remove them the bot will not fall down. And the bot will in both cases not affected by water

Try reconnecting the bot after you remove the blocks.
Water physics are not implemented.
