### ISSUE TITLE
[Idea] AutoAttack LookAt mode

### ISSUE THREAD

**Issue by deosync** [MCCTeam/Minecraft-Console-Client#2435]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

add LookAt mod to auto-attack using raycast

### Suggest a possible solution

use raycast

### Minecraft Version

1.16.5

### Device

Laptop

### Operating System

Linux

**Comment by milutinke** [comment]
Got a code that is working partially, it does not attack entities if they're behind blocks, but it can attack entities outside of the eyes range, eg. behind. I need to figure out how to limit that.

```csharp
if (attackOnlySeen && GetCurrentLocation().Distance(entity.Location) <= attackRange)
{
  var camera = GetCurrentLocation().EyesLocation();
  var rotation = MathHelper.GetRotationVector(GetYaw(), GetPitch());

  // Legs
  (bool hasBlock, _, Block block) = RaycastHelper.Raycast(
    world: Handler.GetWorld(),
    start: camera + rotation, // Player eyes location and rotation
    end: entity.Location, // Entity position
    includeFluids: false);

  // Torso and head
  (bool hasBlock2, _, Block block2) = RaycastHelper.Raycast(
    world: Handler.GetWorld(),
    start: camera + rotation, // Player eyes location and rotation
    end: entity.Location + new Location(0, 1, 0), // Entity position
    includeFluids: false);

  if (!hasBlock || !hasBlock2)
    canAttackSeen = true;
}
  ```

**Comment by deosync** [comment]
I don't understand how I can embed this code into the standard MCC
