### ISSUE TITLE
How to run MinecraftClient.exe on linux ubuntu 22.04

### ISSUE THREAD

**Issue by Mcstudio-technik** [MCCTeam/Minecraft-Console-Client#2437]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Hello can you help me?

How to run mcc on linux.
I try with "MONO" but this not working.

Can you give me any of suggestion how to run this?

### Device

None

### Operating System

None

**Comment by deosync** [comment]
use chmod +x MinecraftClient in mcc folder

**Comment by Mcstudio-technik** [comment]
-bash: ./MinecraftClient: cannot execute binary file: Exec format error

**Comment by deosync** [comment]
use chmod +x MinecraftClient

**Comment by deosync** [comment]
after this use ./MinecraftClient

**Comment by breadbyte** [comment]
1. you need to download the linux zip from [here](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20230129-189)
![image](https://user-images.githubusercontent.com/14045257/221997765-78c36f52-782b-48a7-a16f-ac22f4a26fd9.png)

2. extract the zip file

3. run `./MinecraftClient`

**Comment by Mcstudio-technik** [comment]
![image](https://user-images.githubusercontent.com/57962598/222061813-49871714-b4fa-4e1a-96f6-fd7493730556.png)

idk why but when i join on server, i have this error everytime how to fix this?

**Comment by breadbyte** [comment]
What minecraft version are you running on?

**Comment by Mcstudio-technik** [comment]
i try on 1.12.2 1.16.5 and 1.17.1

**Comment by milutinke** [comment]
Closing as a stale issue.
Follow the instructions on the documentation Website: https://mccteam.github.io/guide/installation.html
