### ISSUE TITLE
MCC on android not working 

### ISSUE THREAD

**Issue by M2242460** [MCCTeam/Minecraft-Console-Client#2440]
I followed instructions to run minecraft on android 
But received this message after the last step

Failed to create CoreCLR, HRESULT: 0x8007000E

**Comment by milutinke** [comment]
From FAQ section on the discord server:

Q: I get 0x8007000E error on Termux.
A: Execute the following commands, in order:  ulimit -v unlimited, sudo ulimit -u unlimited, sudo ulimit -s unlimited, sudo ulimit -n unlimited. sudo ulimit -l unlimited

**Comment by lauris0910** [comment]
i tried the method mentioned above, however i was unable to execute any of the sudo commands for unknown reasons on my end

**Comment by milutinke** [comment]
> i tried the method mentioned above, however i was unable to execute any of the sudo commands for unknown reasons on my end

Make sure you have sudo installed.
If you have, try without sudo

**Comment by lauris0910** [comment]
fortunately, after trying some of them without sudo, there were enough of them to make it working
