### ISSUE TITLE
[Feature Request] New Captcha

### ISSUE THREAD

**Issue by Sergapr** [MCCTeam/Minecraft-Console-Client#2444]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Lastet 

### Describe your problem

There are new captcha on the biggest CIS server (HolyWorld 1.16.5 mc.holyworld.ru)
![image](https://user-images.githubusercontent.com/106835861/225931785-b92858cb-e9f4-402f-8f16-6f3ec2cd8100.png)
Are it possible to pass new captcha using MCC? If it possible, help me please. 

### Device

None

### Operating System

None

**Comment by Sergapr** [comment]
@milutinke

**Comment by milutinke** [comment]
Use the map chat bot.
We already said that we will not make captcha solving chat bots.

**Comment by Sergapr** [comment]
> Use the map chat bot.
> 
> We already said that we will not make captcha solving chat bots.

U don't understand me. 
The problem is that a new captcha has appeared on the server. Now these are not 1 map that appears in the player's hand, it is several cards that appear in front of the player. You can check it by going to the server
mc.HolyWorld.ru 1.16.5
Thank you. Sorry for my English.

**Comment by breadbyte** [comment]
You need to use the map chat bot to download the images and arrange the maps manually.

**Comment by Sergapr** [comment]
> You need to use the map chat bot to download the images and arrange the maps manually.
> 
> 
> 
> I don't think there is a way to arrange these images automatically without checking the world as we don't know the order in which the server sends the map files (i could be wrong though, i haven't checked)

Maps are really downloaded, but each time in a new sequence, and it is not possible to guess the order of the numbers to pass the captcha. In addition, the maps seem to be downloaded incorrectly, and one card contains part of the other.

**Comment by kotav1322** [comment]
Привет, как ты решил эту проблему, и решил ли? Мне бы очень помог твой ответ
Hi, how did you solve this problem, and did you solve it? Your answer would help me a lot

**Comment by kotav1322** [comment]
@Sergapr

**Comment by Sergapr** [comment]
> @Sergapr 
> 
> 

Хай, для какого проекта тебе нужно? Холиворлд?

**Comment by kotav1322** [comment]
@Sergapr естественно, я кстати нашел решение, костыльное, но работает, нужно написать короткий скрипт на питоне для собирания из 9 картинок готовую каптчу, бот загружает карты всегда в одном порядке
https://www.tutorialspoint.com/python_pillow/Python_pillow_merging_images.htm

**Comment by Sergapr** [comment]
> @Sergapr естественно, я кстати нашел решение, костыльное, но работает, нужно написать короткий скрипт на питоне для собирания из 9 картинок готовую каптчу, бот загружает карты всегда в одном порядке
> 
> https://www.tutorialspoint.com/python_pillow/Python_pillow_merging_images.htm

Да, я решил эту проблему так же. Питон скрипт отслеживает папку в которую сохраняются фото капчи, и как только обновляется 9 фото(последнее) он в нужной последовательности собирает их в 1 фото и открывает его. Других решений пока нет, увы. Если нужен скрипт - могу скинуть чуть позднее

**Comment by kotav1322** [comment]
Точь в точь

**Comment by kotav1322** [comment]
@Sergapr А как ты решил проблему с тем что все карты сохраняются в папку с ботом, и изменить ее расположение никак нельзя? И если ты ее решил при помощи своего скрипта, можешь пожалуйста его прислать?

**Comment by kotav1322** [comment]
@Sergapr ???

**Comment by kotav1322** [comment]
@Sergapr у меня несколько ботов, под каждого бота нужны разные прокси, т.е нужны несколько конфигов под каждого бота и несколько папок с клиентами

**Comment by kotav1322** [comment]
Rendered maps всегда находится в папке с клиентом, т.е у меня будет столько же этих папок сколько и ботов.

**Comment by pipi337** [comment]
@Sergapr Send me this script and tell me how to use it pls

**Comment by Hum6d** [comment]
> > @Sergapr естественно, я кстати нашел решение, костыльное, но работает, нужно написать короткий скрипт на питоне для собирания из 9 картинок готовую каптчу, бот загружает карты всегда в одном порядке
> > https://www.tutorialspoint.com/python_pillow/Python_pillow_merging_images.htm
> 
> Да, я решил эту проблему так же. Питон скрипт отслеживает папку в которую сохраняются фото капчи, и как только обновляется 9 фото(последнее) он в нужной последовательности собирает их в 1 фото и открывает его. Других решений пока нет, увы. Если нужен скрипт - могу скинуть чуть позднее

@Sergapr , брат, скинь пожалуйста скрипт
