### ISSUE TITLE
[Idea] Support for 1.19.4

### ISSUE THREAD

**Issue by kqfflo** [MCCTeam/Minecraft-Console-Client#2446]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Support for 1.19.4 would be highly appreciated. 

### Suggest a possible solution

Implement MC 1.19.4 

### Minecraft Version

1.19.4

### Device

VPS

### Operating System

Windows

**Comment by milutinke** [comment]
Working on it, some packets have been added but no info on them.

**Comment by milutinke** [comment]
More info, just need to find what are the IDs of packets.

Added packets:
- Bundle
- Damage Event
- Hurt Animation

Budle Packet:
- Empty body

Damage Event:
- Entity Id: Varint
- Source Type: Varint
- Source Cause Id: Varint (Optional)
- Source Direct Id: Varint (Optional)
- Source Position: Location (Optional)

Hurt Animation:
- Id: Varint
- Yaw: Float

**Comment by milutinke** [comment]
Made good progress #2447

**Comment by milutinke** [comment]
Closing, since we're releasing #2447 as a pre-release for testing.
