### ISSUE TITLE
Make commands auto run upon death

### ISSUE THREAD

**Issue by Luke7352** [MCCTeam/Minecraft-Console-Client#2456]
Can i make it auto respawn and also issue a command every time i die?

**Comment by milutinke** [comment]
There is already an option for auto respawning in the settings, it's called`AutoRespawn`, set it to `true`.
As for sending a command when you Respawn, you need a C# script (chat bot) for that.

```csharp
//MCCScript 1.0

MCC.LoadBot(new SendCommandOnRespawn());

//MCCScript Extensions

class SendCommandOnRespawn : ChatBot
{
    public override void OnRespawn()
    {
        SendText("/yourcommandhere");
    }
}
```

[More on C# scripts (chat bots)](https://mccteam.github.io/guide/creating-bots.html)

**Comment by Luke7352** [comment]
That did not work, the script, running it returned
![B704AA2A-33A4-41C8-83C5-6A6B22F1D6B9](https://user-images.githubusercontent.com/87235341/227804382-67d25b43-5c15-408e-a9cf-c55a745f1800.png)

**Comment by milutinke** [comment]
> That did not work, the script, running it returned ![B704AA2A-33A4-41C8-83C5-6A6B22F1D6B9](https://user-images.githubusercontent.com/87235341/227804382-67d25b43-5c15-408e-a9cf-c55a745f1800.png)

You're doing something wrong, or you're using an oudated version where the Scripting API was broken, there was one such version. Use the latest version of the client.
![image](https://user-images.githubusercontent.com/441903/227810515-a2940e6b-8c5e-46a4-93e8-3d4d6965cfdf.png)

**Comment by Luke7352** [comment]
I’m using the latest version. ARM64 https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20230326-203

**Comment by ReinforceZwei** [comment]
Can confirm the issue happens on _transition build_ (not sure what they call)
![image](https://user-images.githubusercontent.com/39955851/227878778-75699469-bf9d-426c-b329-79cf94123081.png)

Tested on Linux x64, Linux ARM, Windows x64, all shows the same error when running _transition build_. Zipped executable (file name without date) have no problem.

**Comment by ReinforceZwei** [comment]
Sorry, maybe I should start a new issue.
