### ISSUE TITLE
[BUG] Armor stand

### ISSUE THREAD

**Issue by MousePak** [MCCTeam/Minecraft-Console-Client#2463]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

GitHub build 206, built on 2023-03-29 from commit e8b3e6b

### Expected Behavior

Armor stands seem to be unusable, this could either be bug or feature request
\entity nnn use 
\entity nnn attack

### Actual Behavior

Nothing changes

### Steps to Reproduce the bug

1. Place armor stand 
2. Ensure bot holding correct item
3. \entity near (ensure stand is within range)
4. \entity ### use

### Anythings that could help diagnosing the bug

```txt
Server version : Requires MC 1.8 - 1.19.4 (protocol v762)
Server reports a different version than manually set. Login may not work.
[KeysCache] Initializing FileSystemWatcher for file: xxxxxx
Loading profile key cache from disk: ProfileKeyCache.ini
Loaded profile key, it will be refresh at 3/31/2023 4:55:38 PM
Loaded profile key, it will be refresh at 3/30/2023 5:28:55 AM
Loaded profile key, it will be refresh at 3/31/2023 1:58:14 PM
Profile keys has been successfully loaded from disk.
Cached profile key needs to be refreshed.
Fetching profile key from Microsoft.
< POST /player/certificates HTTP/1.1
< Host: api.minecraftservices.com
< User-Agent: MCC/1.0
< Accept: application/json
< Connection: close
< Authorization: Bearer xxxxxxxx
< Content-Type: application/json
< Content-Length: 0
<
<
> POST /session/minecraft/join HTTP/1.1
> Host: sessionserver.mojang.com
> User-Agent: MCC/1.19.4
> Content-Type: application/json
> Content-Length: 560
> Connection: close


Log file has nothing related to action to help debug so dropped all signon details. The following is almost as is without further details to assist.


\entity near 

[MCC] Entity: 1691498
 [MCC] Type: Armor Stand
 [MCC] Pose: Standing
 [MCC] Health: 20
 [MCC] Distance: 1.41
 [MCC] Location: X:1.5, Y:60, Z:0.5

\inventory 0 list 
(usable item in hand)
[MCC] Inventory #0 - Player Inventory
>5 | #40: x1  Diamond Leggings - Player's Hero Leggings | Protection I | Unbreaking I
Your selected hotbar is 5


\entity 
\entity ArmorStand use
[MCC] 9 Entity used

\entity 1691498 use
[MCC] Entity used

View player to see nothing changed 
[MCC] Inventory #0 - Player Inventory
>5 | #40: x1  Diamond Leggings - ZeroWork's Hero Leggings | Protection I | Unbreaking I
Your selected hotbar is 5
```

### Device

Other

### Operating System

Linux

**Comment by milutinke** [comment]
Try using a build from #2465 
Link: https://github.com/milutinke/Minecraft-Console-Client/releases/tag/20230330-45

**Comment by MousePak** [comment]
Spot on boss just tested and works
I created this bug to assist a discussion > https://github.com/MCCTeam/Minecraft-Console-Client/discussions/1903

So expect requesting them to wait until your patch goes to main would be our easiest route.

**Comment by milutinke** [comment]
> Spot on boss just tested and works I created this bug to assist a discussion > #1903
> 
> So expect requesting them to wait until your patch goes to main would be our easiest route.

There is an active thread on Discord about this, already notified them, they will try it out too.
Hope it works.
Thanks for the help.

**Comment by milutinke** [comment]
Since their problem is solved, I am closing this as resolved.
