### ISSUE TITLE
Disconnected by Server

### ISSUE THREAD

**Issue by jcodyparker** [MCCTeam/Minecraft-Console-Client#2469]
Why do my alts keep getting disconnected? I turned debugging on and this is all it shows in the log

Disconnected by Server :
ReadTimeoutException : null

Happens daily if not a few times a day

**Comment by jcodyparker** [comment]
It also does it without crashing too, and doesn't auto reconnect

![image](https://user-images.githubusercontent.com/90956620/230224951-b5b1032f-fe13-4291-85d9-89c23d1e7b33.png)

**Comment by milutinke** [comment]
Increase the timeout in the settings to something like 60 or 90 seconds

**Comment by jcodyparker** [comment]
> Your connection is not that stable or the server does not have good bandwith. Increase the timeout in the settings to something like 60 or 90 seconds

Where is the timeout setting? I don't see it in the config

**Comment by milutinke** [comment]
> > Your connection is not that stable or the server does not have good bandwith. Increase the timeout in the settings to something like 60 or 90 seconds
> 
> Where is the timeout setting? I don't see it in the config

`TcpTimeout`

**Comment by jcodyparker** [comment]
Still happening after changing that setting, why isn't it at least auto reconnecting some of the accounts? 

![image](https://user-images.githubusercontent.com/90956620/231671014-d762b166-cc6a-4018-adc5-733111a28152.png)

**Comment by milutinke** [comment]
> Still happening after changing that setting, why isn't it at least auto reconnecting some of the accounts?
> 
> ![image](https://user-images.githubusercontent.com/90956620/231671014-d762b166-cc6a-4018-adc5-733111a28152.png)

Make sure to configure the Auto Reconnect to have Ignore Kick Messages setting enabled

**Comment by jcodyparker** [comment]
> > Still happening after changing that setting, why isn't it at least auto reconnecting some of the accounts?
> > ![image](https://user-images.githubusercontent.com/90956620/231671014-d762b166-cc6a-4018-adc5-733111a28152.png)
> 
> Make sure to configure the Auto Reconnect to have Ignore Kick Messages setting enabled

have that enabled already too

**Comment by milutinke** [comment]
I'll investigate the AutoReconnect bot, a lot of people are complaining about it.

**Comment by jcodyparker** [comment]
> I'll investigate the AutoReconnect bot, a lot of people are complaining about it.

even if that did work, it's still disconnecting random alts as I log more on. Seems like after opening like 5, when I open the 6th itll kick a random alt I have already open. I contacted my VPS provider and they said there are no bandwidth or connection issues

**Comment by milutinke** [comment]
> > I'll investigate the AutoReconnect bot, a lot of people are complaining about it.
> 
> even if that did work, it's still disconnecting random alts as I log more on. Seems like after opening like 5, when I open the 6th itll kick a random alt I have already open. I contacted my VPS provider and they said there are no bandwidth or connection issues. Sometimes it'll be fine for hours before kicking any, and sometimes it takes 30 seconds

If you're playing on the same server with all of them, it could be the server making a problem.
Maybe try using a proxy with some accounts.

**Comment by jcodyparker** [comment]
> > > I'll investigate the AutoReconnect bot, a lot of people are complaining about it.
> > 
> > 
> > even if that did work, it's still disconnecting random alts as I log more on. Seems like after opening like 5, when I open the 6th itll kick a random alt I have already open. I contacted my VPS provider and they said there are no bandwidth or connection issues. Sometimes it'll be fine for hours before kicking any, and sometimes it takes 30 seconds
> 
> If you're playing on the same server with all of them, it could be the server making a problem. Maybe try using a proxy with some accounts.

been using the same server and vps for the past few years now and only recently its been giving me issues tbh

**Comment by jcodyparker** [comment]
it gave me this today
![image](https://user-images.githubusercontent.com/90956620/234748595-bf2cf764-7ceb-4862-9d9a-261c54e8d027.png)

**Comment by milutinke** [comment]
> it gave me this today
> ![image](https://user-images.githubusercontent.com/90956620/234748595-bf2cf764-7ceb-4862-9d9a-261c54e8d027.png)
> 

This is an error with the minecraft server proxy itself, nothing we can do about it
