### ISSUE TITLE
[BUG] Empty line shown as {"text":""}

### ISSUE THREAD

**Issue by KevGOtt** [MCCTeam/Minecraft-Console-Client#2470]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.4

### Console Client Version

GitHub build 209, built on 2023-04-01 from commit 78f5d24

### Expected Behavior

Im on Win11

When a line is empty it should just stay empty.
https://prnt.sc/UKjdarcGDRvL

### Actual Behavior

Spamming {"text":""} instead of an empty line.

### Steps to Reproduce the bug

im normally starting MCC.

### Attach screenshot here (If applicable)

https://prnt.sc/UKjdarcGDRvL

### Anythings that could help diagnosing the bug

```txt
i think some win11 issue
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

skyblock.enchantedmc.net

**Comment by milutinke** [comment]
That is not a bug, that is just new chat fromat  that is in JSON, we still don't have a parser made for that.
