### ISSUE TITLE
[BUG] Czech symbols in the ini file (Autorelog problem)

### ISSUE THREAD

**Issue by teodortomas** [MCCTeam/Minecraft-Console-Client#2476]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.3

### Console Client Version

213

### Expected Behavior

I am trying to set a string: "Pravidelný restart" (letter "ý" in czech language) into Kick_Messages (ini file), i would expect it to work so that when i get kicked with this reason (which i confirmed is the reason), it Autorelogs for me.

### Actual Behavior

When I put the "Pravidelný restart" string in the list of Kick_messages and save it, after running the client and opening the ini file after, there is a string "pravidelnďż˝ restart" which does not trigger the Autorelog when it should.

### Steps to Reproduce the bug

1. put "pravidelný restart" in the Kick_messages list under AutoRelog section (ini file)
2. save and close the ini file
3. run the client
4. open the ini file again
5. there should be a "pravidelnďż˝ restart" instead of "pravidelný restart"

### Attach screenshot here (If applicable)

![image](https://user-images.githubusercontent.com/91433717/230766043-d065e458-60ce-41d5-a589-96d0004ebd8d.png)

### Device

Desktop

### Operating System

Linux

**Comment by breadbyte** [comment]
Since you are using Linux, I do not know what editor you are using, but make sure that you are saving the file as `UTF-8`.
If you are using FTP, setting your transfer mode to `Binary` may help, as the file encoding may get mangled in transit.

**Comment by teodortomas** [comment]
> Since you are using Linux, I do not know what editor you are using, but make sure that you are saving the file as `UTF-8`. If you are using FTP, setting your transfer mode to `Binary` may help, as the file encoding may get mangled in transit.

I'm using WINSCP to connect from a Windows computer (using its built-in editor). I previously attempted to switch to UTF-8, but it failed, so I downloaded the ini file and, using a different editor, was able to alter it successfully. Thank you, it's working now.
