### ISSUE TITLE
[Question] Invalid credentials.

### ISSUE THREAD

**Issue by StevisCodes** [MCCTeam/Minecraft-Console-Client#2480]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.4

### Console Client Version

Latest

### Expected Behavior

To be able to login

### Actual Behavior

Microsoft authenticate failed: Invalid credentials. Check your credentials

### Steps to Reproduce the bug

1. i dont know
2. i dont know 
3. i dont know

### Anythings that could help diagnosing the bug

```txt
I have 2 factor auth on for that account. I tried logging in normally and it asked for a verification code like normal, but when I try the console client i get no code and it just says failed login. I dont see anywhere about not being able to accept 2 factor
```

### Device

Laptop

### Operating System

Windows

**Comment by breadbyte** [comment]
Change the login method in the ini to `browser` instead of `mcc`, it will prompt you to login through the browser.
