### ISSUE TITLE
help me not working consle client

### ISSUE THREAD

**Issue by ginowhis** [MCCTeam/Minecraft-Console-Client#2482]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

new

### Describe your problem

it works on my own computer but not on my virtual server please help

### Attach screenshot here (If applicable)

![1Ekran Alıntısı](https://user-images.githubusercontent.com/96331732/233153703-962a1938-cfcf-43b7-afc3-3e53e3155ffa.PNG)

### Minecraft Version

1.16.5

### Device

VPS

### Operating System

Windows

**Comment by breadbyte** [comment]
Check your Microsoft email if you have been sent an email to confirm the login.

**Comment by milutinke** [comment]
> > 
> 
> unfortunately, it works on my own computer, not on the virtual server, how strange

Your server ip is probably blacklisted by Microsoft, try using a proxy

**Comment by ginowhis** [comment]
Thank You
