### ISSUE TITLE
Moving detected by AntiCheat plugin

### ISSUE THREAD

**Issue by Kkordics** [MCCTeam/Minecraft-Console-Client#2485]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.3

### Console Client Version

v1.19.4

### Expected Behavior

On "/move north"command the player starts moving.

### Actual Behavior

When i try to move with "/move north" than the server kicks the client with a message. And when i try the farm command happens the same. And I set the BrandInfo to Vanilla.

### Steps to Reproduce the bug

1. Login to the server
2. /move nort or any direction

### Device

None

### Operating System

None

**Comment by milutinke** [comment]
We can't help you, Anti Cheats have easy time detecting any bot movement due to the way they move.
Play on a different server.
