### ISSUE TITLE
What is the wait command [ScriptScheduler]

### ISSUE THREAD

**Issue by sayit135** [MCCTeam/Minecraft-Console-Client#2488]

**Comment by sayit135** [comment]
![image](https://user-images.githubusercontent.com/35692406/234994011-33042480-b9c4-4273-b09f-a0a3fd60f4f6.png)
I want to write once

**Comment by breadbyte** [comment]
Set `Enable = false` on `Trigger_On_Times` and `Trigger_On_Interval`.
Set only `Trigger_On_Login = true` for it to trigger on login.

**Comment by sayit135** [comment]
![image](https://user-images.githubusercontent.com/35692406/234995269-33a9599b-5f14-46c2-b1e3-76ef41643a44.png)

**Comment by sayit135** [comment]
> ve `Enable = false`üzerine ayarlayın . Yalnızca oturum açıldığında tetiklenecek şekilde ayarlayın.`Trigger_On_Times``Trigger_On_Interval``Trigger_On_Login = true`

It isn't happening

**Comment by breadbyte** [comment]
Make this your task config. You can only have one task with the same name.
```
[[ChatBot.ScriptScheduler.TaskList]]
Task_Name = "Login"
Trigger_On_First_Login = false
Trigger_On_Login = true
Trigger_On_Times = { Enable = false, Times = [ ] }
Trigger_On_Interval = { Enable = false, MinTime = 60.0, MaxTime = 180.0 }
Action = "script login.txt"
```

Create a file beside your MinecraftClient.exe called login.txt with the following contents.
```
send /login password
wait 10
send /server vadi
```

It will run the login.txt script whenever you log in.

**Comment by sayit135** [comment]
![image](https://user-images.githubusercontent.com/35692406/235000445-3d299a13-283f-4e14-85d2-c424220540f1.png)

**Comment by sayit135** [comment]
It isn't happening

**Comment by sayit135** [comment]
It isn't happening

**Comment by sayit135** [comment]
> Make this your task config. You can only have one task with the same name.
> 
> ```
> [[ChatBot.ScriptScheduler.TaskList]]
> Task_Name = "Login"
> Trigger_On_First_Login = false
> Trigger_On_Login = true
> Trigger_On_Times = { Enable = false, Times = [ ] }
> Trigger_On_Interval = { Enable = false, MinTime = 60.0, MaxTime = 180.0 }
> Action = "script login.txt"
> ```
> 
> Create a file beside your MinecraftClient.exe called login.txt with the following contents.
> 
> ```
> send /login password
> wait 10
> send /server vadi
> ```
> 
> It will run the login.txt script whenever you log in.
It isn't happening

**Comment by sayit135** [comment]
> Make this your task config. You can only have one task with the same name.
> 
> ```
> [[ChatBot.ScriptScheduler.TaskList]]
> Task_Name = "Login"
> Trigger_On_First_Login = false
> Trigger_On_Login = true
> Trigger_On_Times = { Enable = false, Times = [ ] }
> Trigger_On_Interval = { Enable = false, MinTime = 60.0, MaxTime = 180.0 }
> Action = "script login.txt"
> ```
> 
> Create a file beside your MinecraftClient.exe called login.txt with the following contents.
> 
> ```
> send /login password
> wait 10
> send /server vadi
> ```
> 
> It will run the login.txt script whenever you log in.


It isn't happening

**Comment by sayit135** [comment]
![image](https://user-images.githubusercontent.com/35692406/235005384-93791d79-f696-4f08-8054-057626fed6d8.png)

**Comment by sayit135** [comment]
> Make this your task config. You can only have one task with the same name.
> 
> ```
> [[ChatBot.ScriptScheduler.TaskList]]
> Task_Name = "Login"
> Trigger_On_First_Login = false
> Trigger_On_Login = true
> Trigger_On_Times = { Enable = false, Times = [ ] }
> Trigger_On_Interval = { Enable = false, MinTime = 60.0, MaxTime = 180.0 }
> Action = "script login.txt"
> ```
> 
> Create a file beside your MinecraftClient.exe called login.txt with the following contents.
> 
> ```
> send /login password
> wait 10
> send /server vadi
> ```
> 
> It will run the login.txt script whenever you log in.


help pls.

**Comment by sayit135** [comment]
![image](https://user-images.githubusercontent.com/35692406/235173800-73f8b5c2-d826-4844-8106-ed4dd2a1e921.png)
![image](https://user-images.githubusercontent.com/35692406/235173897-04c04d4f-db4a-4ac5-9125-0dad0481fc98.png)
don't wait

**Comment by milutinke** [comment]
> ![image](https://user-images.githubusercontent.com/35692406/235173800-73f8b5c2-d826-4844-8106-ed4dd2a1e921.png)
> ![image](https://user-images.githubusercontent.com/35692406/235173897-04c04d4f-db4a-4ac5-9125-0dad0481fc98.png)
> don't wait

Remove seconds, it just needs to be `wait 20`
