### ISSUE TITLE
[Idea] 

### ISSUE THREAD

**Issue by Lerkista** [MCCTeam/Minecraft-Console-Client#2489]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Can you implement a option to inspect an item?

### Suggest a possible solution

Maybe something like /inventory 1 look 10
To see the info/lore/description of the item in slot 10 in the inventory 1

### Minecraft Version

1.19.4

### Device

Raspberry Pi

### Operating System

Linux

**Comment by milutinke** [comment]
![image](https://user-images.githubusercontent.com/441903/235354667-7a9d0fcf-0ddf-4f88-b3dd-45c6e7a11ee2.png)
Added.
