### ISSUE TITLE
[Idea] Add functionality to load bot via file path

### ISSUE THREAD

**Issue by drithh** [MCCTeam/Minecraft-Console-Client#2495]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

I want to load another bot from another file with cs script,
currently what you can do is put all bot classes in 1 file then load it with LoadBot method, but i wanna seperate the bot on each file and then load it with file path like [script ](https://github.com/MCCTeam/Minecraft-Console-Client/blob/f94c1ed60d4143b9b06ba69da06d60943c7af965/MinecraftClient/ChatBots/Script.cs#L9) command 

### Suggest a possible solution

add another method to overload LoadBot in [here ](https://github.com/MCCTeam/Minecraft-Console-Client/blob/f94c1ed60d4143b9b06ba69da06d60943c7af965/MinecraftClient/Scripting/ChatBot.cs#L39) so when the args is string, so it will load it from file instead

### Minecraft Version

1.19.2

### Device

Desktop

### Operating System

Linux

**Comment by breadbyte** [comment]
You only have two options in mcc to load your own code

1. Use scripts, and run a startup script that will load all your scripts with `/script`.
2. Compile MCC with your bot already included, and add it [here](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/McClient.cs#L289-L290).

**Comment by drithh** [comment]
> You only have two options in mcc to load your own code
> 
> 1. Use scripts, and run a startup script that will load all your scripts with `/script`.
> 2. Compile MCC with your bot already included, and add it [here](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/McClient.cs#L289-L290).

yeah probably i would use CallScript method, 1 more question tho, is it  still not possible to import class from another file?

**Comment by drithh** [comment]
Hey, I'm experiencing a problem with building from source code too. I'm using Visual Studio 2022 with Dotnet 7. When I do a release build, my changes are updated successfully. However, when I publish it, the published version doesn't reflect my changes. Can you help me understand what might be causing this issue? i dont really know how Visual Studio works

> You only have two options in mcc to load your own code
> 
> 1. Use scripts, and run a startup script that will load all your scripts with `/script`.
> 2. Compile MCC with your bot already included, and add it [here](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/McClient.cs#L289-L290).

**Comment by milutinke** [comment]
> Hey, I'm experiencing a problem with building from source code too. I'm using Visual Studio 2022 with Dotnet 7. When I do a release build, my changes are updated successfully. However, when I publish it, the published version doesn't reflect my changes. Can you help me understand what might be causing this issue? i dont really know how Visual Studio works
> 
> > You only have two options in mcc to load your own code
> > 
> > 1. Use scripts, and run a startup script that will load all your scripts with `/script`.
> > 2. Compile MCC with your bot already included, and add it [here](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/McClient.cs#L289-L290).

Try running Clean, then Rebuild.
Visual Studio is weird sometimes.

**Comment by drithh** [comment]
> > Hey, I'm experiencing a problem with building from source code too. I'm using Visual Studio 2022 with Dotnet 7. When I do a release build, my changes are updated successfully. However, when I publish it, the published version doesn't reflect my changes. Can you help me understand what might be causing this issue? i dont really know how Visual Studio works
> > > You only have two options in mcc to load your own code
> > > 
> > > 1. Use scripts, and run a startup script that will load all your scripts with `/script`.
> > > 2. Compile MCC with your bot already included, and add it [here](https://github.com/MCCTeam/Minecraft-Console-Client/blob/master/MinecraftClient/McClient.cs#L289-L290).
> 
> Try running Clean, then Rebuild. Visual Studio is weird sometimes.

Although it may seem unrelated from this issue, I cant get it to work. the changes I made are not reflected in the published app, but they are in the release build. I'm unsure of what I'm doing wrong. take a look https://youtu.be/QfClocGbhxs

**Comment by breadbyte** [comment]
> is it still not possible to import class from another file? because i have some util classess that uses in so many files

Unfortunately for scripts no, one way you could do this is to compile MCC with your helper scripts in, and expose them through the CSharpAPI class, which makes them available to the scripting system.

----

> the changes I made are not reflected in the published app, but they are in the release build.

Looking around, I found an issue in the `dotnet` repository that says `dotnet clean` does not include `publish` folders, only `build` folders.

This should be fixed by deleting the `/bin` and `/obj` folders which will force a complete rebuild.

To automate this with the (right-click -> `clean`) menu in VS, add the code in from [here](https://github.com/dotnet/docs/issues/12304#issuecomment-755672578) to the MinecraftClient csproj
