### ISSUE TITLE
I want to open 4 5 accounts without extra files

### ISSUE THREAD

**Issue by sayit135** [MCCTeam/Minecraft-Console-Client#2502]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

.

### Expected Behavior

s

### Actual Behavior

s

### Steps to Reproduce the bug

1. 
2. 
3. 
s

### Attach screenshot here (If applicable)

s

### Anythings that could help diagnosing the bug

```txt
s
```

### Device

None

### Operating System

None

**Comment by milutinke** [comment]
Can't be implemented yet.
