### ISSUE TITLE
[Idea] Automatically accept resource pack downloads

### ISSUE THREAD

**Issue by aabssmc** [MCCTeam/Minecraft-Console-Client#2515]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

When trying to connect to a server with a custom texture pack it disconnects you 
`[MCC] Disconnected by Server :
[MCC] The ResourcePack download failed. Please try rejoining.`
This could get really annoying when you download the client for that one server but since that one server has a texture pack you cant even join it

### Attach screenshot here (If applicable)

https://i.imgur.com/bbku2Ct.png

### Minecraft Version

1.19.3

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
This feature already exists
