### ISSUE TITLE
[Question] Connecting to Microsoft Stuck

### ISSUE THREAD

**Issue by Veyzn** [MCCTeam/Minecraft-Console-Client#2516]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.4

### Console Client Version

Latest

### Expected Behavior

It should connect

### Actual Behavior

I'm trying to connect to Microsoft but it got stuck in "Connecting to Microsoft"

### Steps to Reproduce the bug

1. Start Client
2. Login
3. See

### Attach screenshot here (If applicable)

![BugReport](https://github.com/MCCTeam/Minecraft-Console-Client/assets/46071523/d8f3c51f-1393-4437-8602-eb3420811bf5)

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Use a proxy
