### ISSUE TITLE
[Idea] 能不能宣传中文玩家？

### ISSUE THREAD

**Issue by nannanthis** [MCCTeam/Minecraft-Console-Client#2517]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

最新版本

### Describe your problem

不能宣传中文玩家使宣传变得繁琐

### Suggest a possible solution

希望可以宣传中文玩家

### Minecraft Version

1.12.2

### Device

Laptop

### Operating System

Windows

**Comment by ReinforceZwei** [comment]
What do you mean by Promote Chinese Players? Also please use **English** when posting issue.

**Comment by nannanthis** [comment]
While using MCC, I want Chinese players to see my promotion, but he can only send it to English players.
![`EU VUZ9I(T WRRF88{2)@X](https://github.com/MCCTeam/Minecraft-Console-Client/assets/134784117/3381ed42-d594-4011-8cf9-52de6b5a3434)

**Comment by ReinforceZwei** [comment]
I think vanilla Minecraft doesn't support Chinese player name. MCC will ensure player name only contains `a-z A-Z 0-9 _` and filter out invalid player name.
https://github.com/MCCTeam/Minecraft-Console-Client/blob/9855e2e0f19942006bb62ec230bc6a935b5da270/MinecraftClient/Scripting/ChatBot.cs#L556-L569

**Comment by nannanthis** [comment]
If it's not the original Minecraft, is there a way to promote Chinese players?

**Comment by nannanthis** [comment]
Why ChatBot function getOnlinePlayers() can’t get players  which name includes Chinese words

**Comment by nannanthis** [comment]
There are also many Minecraft Servers supports Chinese name players.
Can you tell me where filter code is?

**Comment by nannanthis** [comment]
There are also many Minecraft Servers supports Chinese name players.
Can you tell me where filter code is?

**Comment by ReinforceZwei** [comment]
https://github.com/MCCTeam/Minecraft-Console-Client/blob/9855e2e0f19942006bb62ec230bc6a935b5da270/MinecraftClient/McClient.cs#L2953-L2955

**Comment by XIAYM-gh** [comment]
Players' names should follow Minecraft's official naming rules
Using invalid characters (like CJK characters) can cause a lot of problems. For example, unable to join most of the offline servers or single player worlds in modern minecraft versions.

***

*If you can't understand Chinese, then u can ignore the messages below.*

***

玩家名应该遵循正版命名法，使用非法字符会导致很多问题
现在很多离线服务器 **不支持** 中文用户名
在高版本mc你压根无法进入游戏
MCC在这做个过滤很正常吧

>还有，
你这宣传的什么玩意，MCC不是让你干这个的
还有你这中文表达能力也是逆天 我看了半天没看懂 一看你在这发骚扰广告 绷不住了
