### ISSUE TITLE
AutoCraft not working

### ISSUE THREAD

**Issue by CatNiangFeitu** [MCCTeam/Minecraft-Console-Client#2518]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.4

### Console Client Version

Laste

### Expected Behavior

I want see my bot can craft sucessful.

### Actual Behavior

MCC told me "缺失材料：PrismarineShard"，but I checked bot's inventory.

### Steps to Reproduce the bug

1. Launcher MCC in GitHub build 219, built on 2023-05-21 from commit 1bba41c.
2. Join Server.
3. run  /autocraft start SeaLantern

### Attach screenshot here (If applicable)

/inventory search PrismarineShard
![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/108512490/0944d9e1-2471-4edd-b726-8c6501159e18)
/inventory search PrismarineCrystals
![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/108512490/7debe0e7-00b3-4911-824f-b4b3bda7b5cf)
/autocraft start SeaLantern
![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/108512490/a23b3f0a-7355-49d8-88f0-8b3f324c1cf4)

### Anythings that could help diagnosing the bug

```txt
`
[ChatBot.AutoCraft]
Enabled = true
CraftingTable = { X = 6365.0, Y = -63.0, Z = 2129.0 } # 如果你打算使用工作台，请填写它所在的位置。（需要启用地形处理）
OnFailure = "abort"                         # 合成失败时应该怎么处理，"abort"（中止）或 "wait"（等待）。

[[ChatBot.AutoCraft.Recipes]]
Name = "SeaLantern"
Type = "table"
Result = "SeaLantern"
Slots = [ "PrismarineShard", "PrismarineCrystals", "PrismarineShard", "PrismarineCrystals", "PrismarineCrystals", "PrismarineCrystals", "PrismarineShard", "PrismarineCrystals", "PrismarineShard", ]
````
```


### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

_No response_

**Comment by ReinforceZwei** [comment]
AutoCraft doesn't split a stack of item for you. So you either have to split the item stack into 9 stacks manaully or have 9 stacks of x64 shards in the inventory.

**Comment by CatNiangFeitu** [comment]
OK.Thanks.
