### ISSUE TITLE
我有个小问题，怎样才算Minecraft的非法字符，我该如何去除非法字符？

### ISSUE THREAD

**Issue by NingLiu1998** [MCCTeam/Minecraft-Console-Client#2532]
![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/109678937/bb6d028a-2b82-49be-b133-c78d2fd69a46)

我接入了ChatGPT3.5，但是它有时候回复的发言会导致“非法字符”的问题出现，我想我该怎么删除掉回复的内容当中的非法字符？

**Comment by ReinforceZwei** [comment]
Please use **English** when posting issue.

Seems like your message contains new line character (`\n`) which is not allowed. You have to remove any special characters before sending message.

For your information, Minecraft server uses the following function to check message.
```java
public static boolean isAllowedChatCharacter(char c0) {
    return c0 != 167 && c0 >= ' ' && c0 != 127;
}
```

**Comment by NingLiu1998** [comment]
oh,thanks, i'am sorry next time i will use english, thanks you answer, this answer help me very much
