### ISSUE TITLE
[ERROR]  The chunk where the target location resides has not yet been loaded.

### ISSUE THREAD

**Issue by Sapiens12** [MCCTeam/Minecraft-Console-Client#2538]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.18.2

### Console Client Version

Latest

### Expected Behavior

moving

### Actual Behavior

not moving

### Steps to Reproduce the bug

1. 
2. 
3. 

### Anythings that could help diagnosing the bug

```txt
[MCC] The chunk where the target location resides has not yet been loaded.
You can use "/chunk status -4,5 65,0 0,5" to check the chunk loading status.
```

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
This is expected behavior, the server did not send the chunks.
