### ISSUE TITLE
InsufficientPrivilegesException

### ISSUE THREAD

**Issue by jungwuk-ryu** [MCCTeam/Minecraft-Console-Client#2539]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1

### Console Client Version

225 (latest)

### Expected Behavior

Successfully logged into this server.

### Actual Behavior

Failed to check session.

### Steps to Reproduce the bug

1. Input ID and PW
2. Input Server IP

### Anythings that could help diagnosing the bug

```txt
I tried it on my laptop and VPS.

==========

[MCC] Version is supported.
Logging in...
[DEBUG] Crypto keys & hash generated.
[MCC] Checking Session...
Performing request to sessionserver.mojang.com
> POST /session/minecraft/join HTTP/1.1
> Host: sessionserver.mojang.com
> User-Agent: MCC/1.20.1
> Content-Type: application/json
> Content-Length: 613
> Connection: close
>
> {"accessToken":"...","selectedProfile":"...","serverId":"..."}

< HTTP/1.1 403 Forbidden
< Cache-Control: no-store
< Content-Length: 87
< Content-Type: application/json
< x-minecraft-request-id: ...
< X-Cache: CONFIG_NOCACHE
< X-Azure-Ref: ...
< Date: Sat, 24 Jun 2023 11:05:56 GMT
< Connection: close
<
< {
<   "error" : "InsufficientPrivilegesException",
<   "path" : "/session/minecraft/join"
< }
[MCC] Login failed :
[MCC] Failed to check session.
[ERROR] Failed to login to this server.
Initialization failed.
```

### Device

Laptop

### Operating System

Windows

**Comment by breadbyte** [comment]
Are you trying to login an account with any of these possible causes?
1. Account is using Xbox Game Pass
2. Account only has Bedrock Edition and not Java Edition

**Comment by jungwuk-ryu** [comment]
Thank you for your response.
This issue has been resolved after changing everything to 'Allow' at https://account.xbox.com/Settings
