### ISSUE TITLE
chat message bug

### ISSUE THREAD

**Issue by byiit** [MCCTeam/Minecraft-Console-Client#2540]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.3

### Console Client Version

Latest

### Expected Behavior

This is how the messages appear when I run it for the 2nd time 
( [90m, [92m )

### Actual Behavior

This is how the messages appear when I run it for the 2nd time 
( [90m, [92m )

### Steps to Reproduce the bug

1. run the client
2. run the client again
3. 

### Attach screenshot here (If applicable)

https://www.hizliresim.com/h3jghpc

### Anythings that could help diagnosing the bug

```txt
.
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

play.provanas.com

**Comment by breadbyte** [comment]
Change the following settings in your config file.
![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/14045257/c4fdfe59-34f9-44e6-adb1-73b2249d294c)
