### ISSUE TITLE
anti afk 

### ISSUE THREAD

**Issue by R333L** [MCCTeam/Minecraft-Console-Client#2541]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

anti afk for serverr auto text /ping to anti afk

### Suggest a possible solution

anti afk for serverr auto text /ping to anti afk

### Minecraft Version

1.8.9

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
https://mccteam.github.io/guide/chat-bots.html#anti-afk
