### ISSUE TITLE
[MCC] Please enable inventory handling in the config file first.

### ISSUE THREAD

**Issue by RutekGutek** [MCCTeam/Minecraft-Console-Client#2542]
I was trying to make my bot clicks the compass to open gui and then choose server to join, but I have no idea why the /useitem command is not working. (note that I changed the value in minecraftclient.ini to true for inventoryhandling). Any suggestions?

**Comment by breadbyte** [comment]
Make sure that MCC is closed before making changes to the configuration, or it will be reverted after closing MCC.
