### ISSUE TITLE
Run external script? 

### ISSUE THREAD

**Issue by Norntek** [MCCTeam/Minecraft-Console-Client#2543]
Can scripts only be scheduled in the main config file now or is it possible to link to an external tasks file like in previous versions?

I saw dexters video and his configuration compared to obviously the newer version is extremely different. I'd like to use the newest version but I liked that in older versions scripts were separated into individual files so they were easier to read.

Sorry for not following any particular format but this isn't a bug or a feature request just a general question.

**Comment by breadbyte** [comment]
I'm assuming you're referring to the `ScriptScheduler` feature.

Unfortunately the configuration for the `ScriptScheduler` has been moved to the configuration file completely,
(so setting up when the scripts run is fixed into the configuration file),

but you are still able to separate different scripts into different files, as the `/script` command takes in a filename relative to the MCC executable location.

**Comment by Norntek** [comment]
> I'm assuming you're referring to the `ScriptScheduler` feature.
> 
> Unfortunately the configuration for the `ScriptScheduler` has been moved to the configuration file completely, (so setting up when the scripts run is fixed into the configuration file),
> 
> but you are still able to separate different scripts into different files, as the `/script` command takes in a filename relative to the MCC executable location.

Thank you!
