### ISSUE TITLE
[BUG] InvalidOperationException: Queue empty

### ISSUE THREAD

**Issue by tanyaofei** [MCCTeam/Minecraft-Console-Client#2546]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1

### Console Client Version

20230623-225

### Expected Behavior

Can not login server

```
正在解析xxxx.xx...
正在获取服务器信息...
服务器的Minecraft版本：My custom version name! (协议v763)
正在从微软获取聊天签名密钥。
[MCC] 该版本受到支持
正在登录...
[MCC] 检查会话... 
[ERROR] InvalidOperationException: Queue empty.
[ERROR] 加入服务器时发生错误。
Initialization failed.

未连接至任何服务器。输入 '/help' 获得帮助。
或者敲击回车退出Minecraft Console Client。
   at MinecraftClient.McClient..ctor(SessionToken session, PlayerKeyPair playerKeyPair, String server_ip, UInt16 port, Int32 protocolversion, ForgeInfo forgeInfo)
   at MinecraftClient.Program.InitializeClient()
```

This is a purpur 1.20.1 server,but in another 1.20.1 it's ok. I guess this server initialize failed cause it require client to apply server resource pack maybe?

### Actual Behavior

Failed to connect to server

### Steps to Reproduce the bug

1. 
2. 
3. 

### Device

Laptop

### Operating System

MacOS

### Server Address (If applicable)

mcfree.top

**Comment by milutinke** [comment]
The MCC should automatically fake the resource pack check.
I can't re-create this because I can't even get to that step, something hangs the session checking.
I think that this server is running a modified version of Purpur, because I am able to connect all servers that run purpur without issues.

**Comment by tanyaofei** [comment]
> The MCC should automatically fake the resource pack check.
> I can't re-create this because I can't even get to that step, something hangs the session checking.
> I think that this server is running a modified version of Purpur, because I am able to connect all servers that run purpur without issues.

As I know, `mcfree.top` using  an unmodified `purpur-2014` version. I'am trying to rebuild the server in my local machine and try to find the reason. Any progress I will continue to reply here.

**Comment by milutinke** [comment]
This server does not follow a proper normal login process, I am forever stuck in the "login" phase.
