### ISSUE TITLE
how can i add this code to a script

### ISSUE THREAD

**Issue by alfaPHO3NIX** [MCCTeam/Minecraft-Console-Client#2547]
//Detect Essentials Pay message
                //${amount} has been received from {user}.
                else if (text.StartsWith("$"))
                {
                    sender = tmp[4].ToString().Remove(tmp[4].ToString().Length - 1);
                    message = tmp[0].ToString();
                    return isValidName(sender);
                }

how can i add this code to any script?

**Comment by milutinke** [comment]
What exactly you want to do?
