### ISSUE TITLE
Can you have multiple actions for one match?

### ISSUE THREAD

**Issue by periskil** [MCCTeam/Minecraft-Console-Client#2548]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.8.9

### Console Client Version

Latest

### Expected Behavior

Reading sample-matches I don't quite know but for example, if i were to have something like

[Match]
regex=.......
action=set Var1=$1
action=set Var2=$2

Is this able to happen or is there a different method of doing so?

### Actual Behavior

.

### Steps to Reproduce the bug

.

### Device

None

### Operating System

None

**Comment by milutinke** [comment]
`Action="script yourscriptname.txt"`

**Comment by periskil** [comment]
@milutinke when I do that I get "[MCC] [AutoRespond] Unknown command '"execmulti'. Use 'help' for command list."

**Comment by periskil** [comment]
Ah, my console client is out of date for that and I cant get dotnet 7 to work on my raspberry pi so I guess im just gonna be out of luck for that

**Comment by periskil** [comment]
hm seems I need to update my console client. Are there no longer ready to go .exe that you can download? Having issues setting it up following the installation page currently

**Comment by periskil** [comment]
So I had to update my console client (old vers doesnt have execmulti) and when trying to ./MinecraftClient, I get 
"bash: ./MinecraftClient: cannot execute binary file: Exec format error"
and I don't know how to fix this, can't find a solution in any issue posts.
@milutinke

**Comment by milutinke** [comment]
> So I had to update my console client (old vers doesnt have execmulti) and when trying to ./MinecraftClient, I get 
> "bash: ./MinecraftClient: cannot execute binary file: Exec format error"
> and I don't know how to fix this, can't find a solution in any issue posts.
> @milutinke 

Download the lastest version for your os from the Releases section here. Just make sure to select the proper version.

**Comment by periskil** [comment]
So I have everything working, just now after I have it do execmulti it returns

[MCC] [AutoRespond] NotRun

**Comment by periskil** [comment]
So i have that done and now I have one last weird issue (sorry)

server commands stop working entirely after about 1 minute, never had this issue before on the old release I was on

**Comment by milutinke** [comment]
No idea, I can't re-create the problem.

**Comment by periskil** [comment]
@milutinke sorry for late reply, busy with school.

Server IP: play.minecadia.com
Server Version: 1.8.9

**Comment by periskil** [comment]
@milutinke 

Did some testing, using the script scheduler on anything that isnt triggered on first loging (i.e on interval), the server seems to not allow the bot to send commands. Disabling a script that is on interval leads the client to still be able to send commands.

I am going to guess this means the server has something that is meant to prevent some scripts/macros and it detects the newer client but doesn't detect the older client.
