### ISSUE TITLE
[Idea] Random wait times

### ISSUE THREAD

**Issue by Norntek** [MCCTeam/Minecraft-Console-Client#2549]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Randomising wait times in scripts. 

### Suggest a possible solution

If there's a "," in wait it will randomise between those two integers.

So "wait 1, 47" would be a random number between 1 and 47

I think this would be useful when executing AutoResponder on multiple accounts to the same response and executing the same script. So the timing is always slightly different. 

### Device

VPS

### Operating System

Windows

**Comment by milutinke** [comment]
You can use `setrnd random_wait_time 5to100` command, and then use `wait %random_wait_time%

**Comment by milutinke** [comment]
@Norntek Added, the build will be available in 5-10 minutes.

**Comment by Norntek** [comment]
Awesome thanks
