### ISSUE TITLE
[Idea] easymc compatiblilty

### ISSUE THREAD

**Issue by kittenvr** [MCCTeam/Minecraft-Console-Client#2550]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

latest

### Describe your problem

i would like to be able to login using easymc Alt Tokens

### Minecraft Version

1.20

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
If added this will be used in a malicious way, thus giving the MCC a bad name.
Won't be implemented.

**Comment by kittenvr** [comment]
> If added this will be used in a malicious way to raid servers with a lot of bots, thus giving the MCC a bad name. Won't be implemented.
i just want to make a bridge between discord and minecraft but dont have the money for 2 accounts

**Comment by Leo-Aqua** [comment]
actually raiding minecraft servers is difficult because the accounts expire within 5h and there already is a offline account option and on top of that most servers have anti raid plugins

**Comment by kittenvr** [comment]
> actually raiding minecraft servers is difficult because the accounts expire within 5h and there already is a offline account option and on top of that most servers have anti raid plugins

the server i am making a bridge for is not offline

**Comment by kittenvr** [comment]
> actually raiding minecraft servers is difficult because the accounts expire within 5h and there already is a offline account option and on top of that most servers have anti raid plugins

Yeah and you need to wait 1 min per alt

**Comment by milutinke** [comment]
> > actually raiding minecraft servers is difficult because the accounts expire within 5h and there already is a offline account option and on top of that most servers have anti raid plugins
> 
> Yeah and you need to wait 1 min per alt



> actually raiding minecraft servers is difficult because the accounts expire within 5h and there already is a offline account option and on top of that most servers have anti raid plugins

You can use proxies to obtain a lot of accounts.
And anti raid plugins mostly use the IP which you can change by using a proxy.

**Comment by kittenvr** [comment]
> > > actually raiding minecraft servers is difficult because the accounts expire within 5h and there already is a offline account option and on top of that most servers have anti raid plugins
> > 
> > 
> > Yeah and you need to wait 1 min per alt
> 
> > actually raiding minecraft servers is difficult because the accounts expire within 5h and there already is a offline account option and on top of that most servers have anti raid plugins
> 
> You can use proxies to obtain a lot of accounts. And anti raid plugins mostly use the IP which you can change by using a proxy.

proxies like vpns?

**Comment by Leo-Aqua** [comment]
but it would be a cool feature.
