### ISSUE TITLE
a idea?

### ISSUE THREAD

**Issue by FIZxingchen** [MCCTeam/Minecraft-Console-Client#2563]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

new

### Describe your problem

Can you put the script into the source code,scripts are automatically started after MCC is run

### Minecraft Version

1.12.2

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Use English please.
If I have understood your question, the answer is no.

**Comment by FIZxingchen** [comment]
Well, I hope it translates correctly

**Comment by FIZxingchen** [comment]
Can you put the script into the source code,scripts are automatically started after MCC is run

**Comment by milutinke** [comment]
> Can you put the script into the source code,scripts are automatically started after MCC is run

Yes, you can make chat bots in the source code, there are built-in/integrated chat bots (scripts), you can see examples of them in the source code of the client.

**Comment by FIZxingchen** [comment]
Which folder in the source code, I can not find

**Comment by milutinke** [comment]
> Which folder in the source code, I can not find

https://github.com/MCCTeam/Minecraft-Console-Client/tree/master/MinecraftClient/ChatBots
