### ISSUE TITLE
[Question] cant join a sever

### ISSUE THREAD

**Issue by Sypex88** [MCCTeam/Minecraft-Console-Client#2564]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1

### Console Client Version

Lastest

### Expected Behavior

cant connect to a server 

### Actual Behavior

cant connect to a server 

### Steps to Reproduce the bug

1. login
2. join a server  

### Attach screenshot here (If applicable)

![Mcc 14 08 2023 16_42_29](https://github.com/MCCTeam/Minecraft-Console-Client/assets/141229690/33c5ba32-2687-4401-b411-0f2c98b7cadb)

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

cloud.griefergames.net

**Comment by milutinke** [comment]
Old Mojang accounts have been discontinued, migrate your Mojang account to Microsoft.
Then set the login method to "browser" in the configuration file.
Make sure the mcc is closed while you're editing the configuration file.
Also, delete `SessionKeysCache.ini` and `SessionCache.ini` if you have them by any chance.
