### ISSUE TITLE
[Idea] If the server uses BC to reverse proxy to the mod server, it will not be able to read the internal mod and therefore cannot access it

### ISSUE THREAD

**Issue by Xnidada** [MCCTeam/Minecraft-Console-Client#2573]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

20230802-227

### Describe your problem

If the server uses BC to reverse proxy to the mod server, it will not be able to read the internal mod and therefore cannot access it

### Suggest a possible solution

I hope to solve this problem or manually add mods myself

### Minecraft Version

1.12.2

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
In this case you will have to modify the source code and hard code the modes manually.
