### ISSUE TITLE
Help for code(old name: much more details for shift click[Idea]) 

### ISSUE THREAD

**Issue by ozi2285** [MCCTeam/Minecraft-Console-Client#2576]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

While in guide it says you can do things like this "/inventory container shiftclick 14 rightclick" in console client it self you can't do that at max can do this "/inventory container click 14 shiftclick" which is just left click that no use for me. there is a farmer plugin(a plugin that collects the item that listed in it self in your island without showing them even for a second) that quite useful and it has ability to sell items directly from it(instead pulling them to inventory and sell) but for sell you need to shift + right click but it's not aviable on console client. there is auto sell function in plugin but it requires you to buy it from server's site + it sells everything which is not good for me because i don't wanna sell some of items that's helps me about progessing island's growth. I am sure this gonna usefull for other users too.

### Suggest a possible solution

make it like in guide we should able to shift + right click atleast.

### Minecraft Version

1.16.5-1.20.1

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/441903/602f5abe-b7ff-49d0-a758-7a26e6bfe049)

`Shift + Left Click` is the same as the `Shift + Right Click` in the game, and in the game protocol definition.
It should work with `Shift + Left Click`

**Comment by ozi2285** [comment]
> ![image](https://user-images.githubusercontent.com/441903/263699410-602f5abe-b7ff-49d0-a758-7a26e6bfe049.png)
> 
> `Shift + Left Click` is the same as the `Shift + Right Click` in the game, and in the game protocol definition. It should work with `Shift + Left Click`

no in game or console client tried shift + left click one but it just shut's farmer menu but not sell the thing.

https://drive.google.com/file/d/1KD0XztPBpNpxb6DAnr0JP2YgFBFeFbxA/view?usp=drive_link

**Comment by ozi2285** [comment]
i just pulled package and trying to doing it my self but even after maket it work as action server still understands as shift + left click, action name needs different it looks like but if ShiftRightClick doesn't work then what would work?

**Comment by ozi2285** [comment]
i found it in the end. i needed to add action in protocol(just added on protocol18.cs) i am not sure my work is good on it but how can i just add changes to here? i am sure seniors can fix my mistakes when they have time.

**Comment by ReinforceZwei** [comment]
You can fork our repository and make change on your forked one. Once you finished your work, send us a pull request on Github and we will review your code.

**Comment by ozi2285** [comment]
well from my point of view it's done state but well i do that thanks

**Comment by ozi2285** [comment]
i just made pull request

**Comment by ozi2285** [comment]
gonna wait for review of pull request
