### ISSUE TITLE
[Idea] Tablist header and footer

### ISSUE THREAD

**Issue by ttryy** [MCCTeam/Minecraft-Console-Client#2606]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

Accessing tab header and footer

### Suggest a possible solution

- ChatBot function that returns the current header and footer.
- ChatBot function that is called when the header or footer change.

### Device

None

### Operating System

None

**Comment by milutinke** [comment]
@ttryy Implemented in #2619
