### ISSUE TITLE
[Idea] 

### ISSUE THREAD

**Issue by minecraft-fff** [MCCTeam/Minecraft-Console-Client#2608]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

20231011-230

### Describe your problem

I can't join the Minecraft 1.20.2 server because the unsupported protocol versions(v764)

### Suggest a possible solution

Add a new version of the agreement

### Minecraft Version

1.20.2

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
I started working on it, but I will not be able to do so for the next week, so I can continue the week after.

**Comment by agitationswapping** [comment]
Any update on this? Any estimate on the time involved?

I'm also now locked out of my server on MCC because there's no support for 1.20.2.

**Comment by milutinke** [comment]
> Any update on this? Any estimate on the time involved?
> 
> I'm also now locked out of my server on MCC because there's no support for 1.20.2.

#2614

It's being tested.
Preview version download: https://github.com/milutinke/Minecraft-Console-Client/releases/tag/20231117-76

**Comment by minecraft-fff** [comment]
Does it have Chinese? It seems to only be in English.

**Comment by milutinke** [comment]
> Does it have Chinese? It seems to only be in English.

Translation pipeline doesn't work in my repository.

**Comment by milutinke** [comment]
Implemented in the latest PR.
