### ISSUE TITLE
[Idea]  FML3 Support

### ISSUE THREAD

**Issue by PolyAnthi** [MCCTeam/Minecraft-Console-Client#2621]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1.20.1

### Describe your problem

The ability to connect to FML3, I noticed it is not widely documented so I took a look at node minecraft protocol forge's github repo and found this, https://github.com/PrismarineJS/node-minecraft-protocol-forge/commit/ec62693bb73af99845cc20f8e5dd164e2cc0ac2a
Hoping this can help some of the developers to implement FML3

### Suggest a possible solution

FML3 implementation by referencing https://github.com/PrismarineJS/node-minecraft-protocol-forge/commit/ec62693bb73af99845cc20f8e5dd164e2cc0ac2a would be a huge step

### Minecraft Version

1.20.1

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Implemented in #2644, will be merged soon.
