### ISSUE TITLE
[Idea] About Discord Information

### ISSUE THREAD

**Issue by yyhhkya** [MCCTeam/Minecraft-Console-Client#2625]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

MinecraftClient-20231120-234-linux-x64

### Describe your problem

![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/87574541/987ed181-1713-46c8-824f-7ce7e6c39bb5)
How to close this information? I don't want it to be displayed in the console

### Minecraft Version

1.20.1

### Device

VPS

### Operating System

Linux

**Comment by milutinke** [comment]
You can only disable it by editing the source code of the Chat Bot.
