### ISSUE TITLE
Howto

### ISSUE THREAD

**Issue by advocaite** [MCCTeam/Minecraft-Console-Client#2626]
I want to detect chat msg and auto reply with some text 
the text in console shows this
eg:
▌Chat Race >> Type YouTube

i want it to type that word for me 

how to do this

**Comment by milutinke** [comment]
There is a Chat Bot for that
https://mccteam.github.io/guide/chat-bots.html#auto-respond

**Comment by advocaite** [comment]
that did not help  can you give me a example for this exact line of text using last word
