### ISSUE TITLE
[BUG] Can't join my 1.20 Waterfall (Bungeecord) server

### ISSUE THREAD

**Issue by bobbyl140** [MCCTeam/Minecraft-Console-Client#2627]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.4 (the proxy supports 1.20.4 down to 1.8)

### Console Client Version

Latest

### Expected Behavior

The client connects to the server

### Actual Behavior

The client reports the (correct) server version, then says the version is incorrect and refuses to connect.

### Steps to Reproduce the bug

1. Try to connect to the server

### Anythings that could help diagnosing the bug

```txt
Minecraft Console Client v1.20.1 - for MC 1.4.6 to 1.20.1 - Github.com/MCCTeam
GitHub build 237, built on 2023-12-02 from commit f2e1c57
Login :
Password(invisible):
Connecting to Microsoft...
Server IP :
Resolving [redacted]...
Retrieving Server Info...
Server is running Forge without mods.
Server version : Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.19.x, 1.20.x (protocol v765)
Fetching profile key from Microsoft.
Cannot connect to the server : This version is not supported !
Server version :
>
(The second "Server version :" line is actually blank in the console, that wasn't a typo.)
```

### Device

Laptop

### Operating System

MacOS

### Server Address (If applicable)

I don't feel comfortable publicly listing this, but if it's needed to diagnose I can provide it privately.

**Comment by milutinke** [comment]
Set the `MinecraftVersion` in the settings to a specific version instead of `auto`

**Comment by Zorua162** [comment]
I had the same issue, however setting `MinecraftVersion` to the correct version for the server in my `MinecraftClient.ini`, as recommended above, worked like a charm. Ty!

**Comment by bobbyl140** [comment]
Same here, that fixed it. Sorry, I swear I responded to this issue but never did.
