### ISSUE TITLE
[BUG] type /useblock command and then crash

### ISSUE THREAD

**Issue by KATu2011** [MCCTeam/Minecraft-Console-Client#2635]
### Prerequisites

- [x] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [x] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [x] I have set `debugmessages=true` in config to diagnose my issue
- [x] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.10

### Console Client Version

Latest

### Expected Behavior

/useblock command will place a block

### Actual Behavior

It's crashed

### Steps to Reproduce the bug

1. Open Minecraft Console Client
2. Join a server
3. Use /useblock to place the block where you stand at

### Attach screenshot here (If applicable)

![Capture](https://github.com/MCCTeam/Minecraft-Console-Client/assets/135348369/36c1b973-d7e2-434c-956a-6baa9206ecba)

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Inventories are not fully supported bellow 1.13, due to missing mappings.
This will work once we create the mappings (which will take some time).
