### ISSUE TITLE
[Idea]  1.20.4 Support

### ISSUE THREAD

**Issue by hseermc** [MCCTeam/Minecraft-Console-Client#2638]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

20231215-238

### Describe your problem

Added version 1.20.4 server

### Suggest a possible solution

Added version 1.20.4 server

### Minecraft Version

1.20.4

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
I'll start working on support for 1.20.3 and 1.20.4 soon.

**Comment by TheoMarque** [comment]
When new update arrive? 1.201 released half year ago.... There is large difference between 1.20.2 and 1.20.4 in protocol?

**Comment by FuriousStryker** [comment]
Are there any updates on this?

**Comment by milutinke** [comment]
> Are there any updates on this?
> 

Implemented everything except new NBT chat system, having some issues with it

**Comment by hseermc** [comment]
Today I installed the Grim AC anti-cheat plugin on my server, but MCC kept alerting "BadPacketsN" after entering the server, and after I sent an issue to Grim, I learned that it was most likely not following vanilla rules.I don't know if this issue can be fixed. If it can't or is difficult, I think it can be left unfixed

**Comment by hseermc** [comment]
When I use mcc to enter an anti-cheat plugin server with grimac, although I have turned on "Fix bad resource pack", although there is no anti-cheat alert when I hang up, but when I attack a mob the anti-cheat alert "badpacketB".

**Comment by milutinke** [comment]
> When I use mcc to enter an anti-cheat plugin server with grimac, although I have turned on "Fix bad resource pack", although there is no anti-cheat alert when I hang up, but when I attack a mob the anti-cheat alert "badpacketB".

That is because the bot does not have physics and line of sight intersection.

**Comment by TheoMarque** [comment]
> > Are there any updates on this?
> 
> Implemented everything except new NBT chat system, having some issues with it

And how situation is? More and more servers migrate to 1.204. and 1.20.5 incoming in few days...

**Comment by FuriousStryker** [comment]
Any luck with the new NBT chat system you previously mentioned? Or possible timeline for a 1.20.4 release.

**Comment by milutinke** [comment]
Released as a Pre-Release
https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20240218-246

**Comment by ReinforceZwei** [comment]
> Still occur a problem. Even removed ViaVersion - same behavior.
> 
> <img alt="image" width="563" src="https://private-user-images.githubusercontent.com/19385639/308941607-20618906-22b2-462f-9e64-ee28cf95bc71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTQzMzksIm5iZiI6MTcwOTIxNDAzOSwicGF0aCI6Ii8xOTM4NTYzOS8zMDg5NDE2MDctMjA2MTg5MDYtMjJiMi00NjJmLTllNjQtZWUyOGNmOTViYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDEzNDAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1NTM4YWRmN2I3YjVmYzIyZDg2OTJkY2FjZGY4YzdhN2JlNjBkZTM3MDIyYjlmZjU3MGM1ODgzZTYzMTNhMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qIIqxmlwoE0w6gTUTUrlCZHnFRwS-Ae0iGhg7QvudiQ">

set minecraft version to 1.20.4
https://mccteam.github.io/guide/configuration.html#minecraftversion

**Comment by TheoMarque** [comment]
Set 
MinecraftVersion = "1.20.4"
in MinecraftClient.ini - same as above error, nothing change even I set 1.20, 1.20.2, 1.20.4, auto...

**Comment by hseermc** [comment]
It could be a paper issue. I don't have this problem with my leaves server (paper branch).

**Comment by TheoMarque** [comment]
Problem solved. ViaVersion behavior was weird. If I set blocked protocol version by number - MCC can't log. If set '<1.20' - works okay but not allow connect any client older than 1.20.4 (even block 1.20.2) Second issue was disabled proxy connections.
