### ISSUE TITLE
[BUG] 使用Yggdrasil登录服务器无法发送消息

### ISSUE THREAD

**Issue by Dino-doge** [MCCTeam/Minecraft-Console-Client#2642]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1

### Console Client Version

GitHub build 238, built on 2023-12-15

### Expected Behavior

可以在Yggdrasil认证的服务器正常发送消息

### Actual Behavior

发送消息提示：
由于个人信息公钥丢失，聊天已被禁用。请尝试重新连接。
（发送指令不受影响）

### Steps to Reproduce the bug

1.登录服务器（Yggdrasil）验证
2.发送消息，提示
由于个人信息公钥丢失，聊天已被禁用。请尝试重新连接。
已经重复尝试，仍复现
[MinecraftClient.ini.txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/13917964/MinecraftClient.ini.txt)
（github无法上传ini）

### Attach screenshot here (If applicable)

![2024-01-12_18-42-05](https://github.com/MCCTeam/Minecraft-Console-Client/assets/137175007/694d93ca-d6e6-4efb-bec6-e445a0523c45)

### Device

Other

### Operating System

Linux

### Server Address (If applicable)

v6.akashic.cc

**Comment by oldkingOK** [comment]
@Dino-doge 你好！
我的分支 https://github.com/oldkingOK/Minecraft-Console-Client/tree/dev 已经修复了这个问题（至少在我的测试过程中没有发现问题），你可以Clone并编译测试。
因为我正在目前正在编写QQ机器人脚本，请记得将配置文件最底部的 Enabled 设置为false（如下），我会在提交pr之前把代码修改回去。
```
[ChatBot.OkWsBot]
Enabled = true
pythonSendWsApi = "ws://127.0.0.1:12345" # Python Websocket接口
serverName = "1.20" # 在群内显示的服务器名称
groupCard = "QQbot" # 在群内昵称
```

**Comment by milutinke** [comment]
> @Dino-doge 你好！ 我的分支 https://github.com/oldkingOK/Minecraft-Console-Client/tree/dev 已经修复了这个问题（至少在我的测试过程中没有发现问题），你可以Clone并编译测试。 因为我正在目前正在编写QQ机器人脚本，请记得将配置文件最底部的 Enabled 设置为false（如下），我会在提交pr之前把代码修改回去。
> 
> ```
> [ChatBot.OkWsBot]
> Enabled = true
> pythonSendWsApi = "ws://127.0.0.1:12345" # Python Websocket接口
> serverName = "1.20" # 在群内显示的服务器名称
> groupCard = "QQbot" # 在群内昵称
> ```

I see that you're working on FML3 support.
Can you make a Pull Request when you are finished?

**Comment by Dino-doge** [comment]
> @Dino-doge 你好！ 我的分支 https://github.com/oldkingOK/Minecraft-Console-Client/tree/dev 已经修复了这个问题（至少在我的测试过程中没有发现问题），你可以Clone并编译测试。 因为我正在目前正在编写QQ机器人脚本，请记得将配置文件最底部的 Enabled 设置为false（如下），我会在提交pr之前把代码修改回去。
> 
> ```
> [ChatBot.OkWsBot]
> Enabled = true
> pythonSendWsApi = "ws://127.0.0.1:12345" # Python Websocket接口
> serverName = "1.20" # 在群内显示的服务器名称
> groupCard = "QQbot" # 在群内昵称
> ```

感谢！成功了

**Comment by oldkingOK** [comment]
@milutinke, Hi
> I see that you're working on FML3 support too. Can you make a Pull Request when you are finished?

Yep I will submit a pull request when I'm done.
