### ISSUE TITLE
[BUG] Receive unformatted message

### ISSUE THREAD

**Issue by oldkingOK** [MCCTeam/Minecraft-Console-Client#2649]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1

### Console Client Version

20240114-240

### Expected Behavior

After entering `/kill`, `oldkingOK was killed` will be logged

### Actual Behavior

After entering `/kill`, `[death.attack.genericKill] oldkingOK` is logged

### Steps to Reproduce the bug

1. Start a Vanilla minecraft server
2. Set the mcc client as an operator using `/op` in server console.
3. Connect to the server with mcc client
4. Enter `/kill`

### Anythings that could help diagnosing the bug

```txt
[MCC] You are dead. Type '/respawn' to respawn.
[MCC] You have respawned.
[DEBUG] Receive DeclareCommands
[DEBUG] CanSendMessage = True
[DEBUG] chat command = kill
▌[death.attack.genericKill] oldkingOK
▌Killed oldkingOK
[MCC] You are dead. Type '/respawn' to respawn.
```

### Device

Desktop

### Operating System

Linux

**Comment by milutinke** [comment]
Can you try it on the latest 1.20.4 release?
I've included the latest translations, so it should work.

**Comment by oldkingOK** [comment]
> Can you try it on the latest 1.20.4 release? I've included the latest translations, so it should work.

It works, thanks.
