### ISSUE TITLE
NotRun

### ISSUE THREAD

**Issue by WERKuPL** [MCCTeam/Minecraft-Console-Client#2659]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1

### Console Client Version

Github 245

### Expected Behavior

script run

### Actual Behavior

[MCC] [ScriptScheduler] NotRun

script run if run it manualy

### Steps to Reproduce the bug

i dont know
[MinecraftClient (2).txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/14126169/MinecraftClient.2.txt)
i change ini to txt 

### Anythings that could help diagnosing the bug

[logg.txt](https://github.com/MCCTeam/Minecraft-Console-Client/files/14126210/logg.txt)
my  script 
### Device
Desktop

### Operating System

Windows

### Server Address (If applicable)

craftmc.pl

**Comment by milutinke** [comment]
Remove the `/` from `Action = "/script logg.txt"`
It needs to look like this:
`Action = "script logg.txt"`

**Comment by WERKuPL** [comment]
it work thanks
