### ISSUE TITLE
[BUG] Moving between servers using reconfiguring 

### ISSUE THREAD

**Issue by Epicguy05** [MCCTeam/Minecraft-Console-Client#2664]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.2

### Console Client Version

Latest

### Expected Behavior

Alt can move between bungee servers fine 

### Actual Behavior

the alt will crash during the reconfiguring screen which u get on you're minecraft. 

### Steps to Reproduce the bug

1. Launch console onto any server that has a reconfiguring phase while moving between servers
2. the bot will than just have no repsonse and crash

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

play.midnight.net

**Comment by milutinke** [comment]
Can you provide an ip of the server?

**Comment by Epicguy05** [comment]
> Can you provide an ip of the server?
Mentioned above
Play.midnightsky.net

**Comment by milutinke** [comment]
> > Can you provide an ip of the server?
> > Mentioned above
> > Play.midnightsky.net

![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/441903/3d4a022f-3f43-4320-8cc1-e5356f36a252)

I cannot re-produce this, it works on the latest version, I've set the `MinecraftVersion = "1.20.2"` in the settings.
For some reason I can not join using an ordinary vanilla client.

**Comment by Epicguy05** [comment]
> > > Can you provide an ip of the server?
> 
> > > Mentioned above
> 
> > > Play.midnightsky.net
> 
> 
> 
> ![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/441903/3d4a022f-3f43-4320-8cc1-e5356f36a252)
> 
> 
> 
> I cannot re-produce this, it works on the latest version, I've set the `MinecraftVersion = "1.20.2"` in the settings.
> 
> For some reason I can not join using an ordinary vanilla client.

Connecting isn't an issue it's moving to island so if you try run "/is go" it will get stuck and than crash, also idk why vanilla won't work it works for me

**Comment by Epicguy05** [comment]
@milutinke  you had any chance to try use mmc to move onto your island

**Comment by DjKingFury1** [comment]
i have this same issue on the same server XD but what epic says seems right on the vanilla client you get a screen that looks like this: https://i.imgur.com/wA7TuWw.png and then you tp to the island but when doing this on console client it seems that it doesn't recognise this and crashes

**Comment by milutinke** [comment]
> @milutinke you had any chance to try use mmc to move onto your island

I'll try it when I catch some time.

**Comment by milutinke** [comment]
@Epicguy05 Found the issue, I'll push the fix.
