### ISSUE TITLE
Question: Critical damage

### ISSUE THREAD

**Issue by thankhoi98** [MCCTeam/Minecraft-Console-Client#2672]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.2

### Console Client Version

Lastest

### Expected Behavior

Why I can hit a critical dame (like you jump and attack) in minecraft console client

### Actual Behavior

.

### Steps to Reproduce the bug

1. 
2. .
3. 

### Device

None

### Operating System

None

**Comment by milutinke** [comment]
Not a bug.
