### ISSUE TITLE
[Idea] Can i implement right click (like place block or use an button) ?

### ISSUE THREAD

**Issue by thankhoi98** [MCCTeam/Minecraft-Console-Client#2673]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Lastest

### Describe your problem

Can i implement right click (like place block or use an button) ?

### Minecraft Version

1.19.2

### Device

None

### Operating System

None

**Comment by milutinke** [comment]
Use the `/useblock` command and read the documentation.
https://mccteam.github.io/guide/usage.html#useblock
