### ISSUE TITLE
[BUG]  Not Supported FlameCord

### ISSUE THREAD

**Issue by MrRubby** [MCCTeam/Minecraft-Console-Client#2674]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.4

### Console Client Version

latest

### Expected Behavior

The client connects to the server

### Actual Behavior

Bu sürüm desteklenmiyor! desteklenmiyor demekte

### Steps to Reproduce the bug

1.  Tekrar bağlanmayı deneme
2.  MinecraftVersion auto olarak kullanma
3. 

### Anythings that could help diagnosing the bug

```txt
Minecraft Console Client v1.20.2 - for MC 1.4.6 to 1.20.2 - Github.com/MCCTeam
GitHub build 245, built on 2024-01-30 from commit 1e60b61
play.reborncraft.pw çözümleniyor...
Çevrimdışı modda giriş yaptınız.
Bilinmeyen veya desteklenmeyen MC sürümü 1.20.4. Otomatik algılama moduna geçiş.
Sunucu Bilgileri Alınıyor...
Sunucuya Forge kullanılmadan giriş yapılıyor.
Sunucu sürümü : FlameCord 1.7.x-1.20.x (protokol v765)
Sunucuya bağlanılamıyor: Bu sürüm desteklenmiyor!
Sunucu sürümü:
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

play.reborncraft.pw

**Comment by breadbyte** [comment]
Please set a version in the configuration file lower than 1.20.4 (we only support up to 1.20.2 at the moment, and the server is trying to use 1.20.4 protocol).
