### ISSUE TITLE
[BUG] Pre-Rlease bug

### ISSUE THREAD

**Issue by hseermc** [MCCTeam/Minecraft-Console-Client#2679]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.4

### Console Client Version

20240218-246

### Expected Behavior

After joining the 1.20.4 server, it can be operated normally

### Actual Behavior

There is an ERROR.After this, MCC shutdown. This is the screenshots
![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/143265074/19b747a8-e43f-41c0-88ed-f0888037daa1)

### Steps to Reproduce the bug

1. join the 1.20.4 server

### Attach screenshot here (If applicable)

![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/143265074/0b7ae133-eead-4b1e-8a25-4ec8f0488492)

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Can you attach the IP?
I can not re-create this on Paper MC or Vanilla.

**Comment by hseermc** [comment]
The server is 1.20.4 and it  have viaversion, so i use MCC 1.20.2 join the server,it don't have any error. 
My server ip is top1.9666.fun:10354 I don't know if it can be connected outside of China

**Comment by milutinke** [comment]
Managed to get the error, with the following command:
```
/summon zombie ~ ~ ~ {CustomName:'[{"text":"Boban","bold":true,"color":"green"}]',CustomNameVisible:1b,Health:2000,CanPickUpLoot:1b,Glowing:1b,HandItems:[{id:diamond_sword,Count:1}],HandDropChances:[0f],Attributes:[{Name:"generic.max_health",Base:2000f}]}
```
Now the problem is why this happens, because Entity Metadata IDs go up to 27, there are no mentioned changes to Entity Metadata format since 1.19.4 and the code was not changed since then too.
For now you can disable Entity Handling, until we determine where is the issue.

**Comment by milutinke** [comment]
Fixed
Use Pre-Release 6: https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20240225-251
