### ISSUE TITLE
[BUG] When trying to launch the program built from the source code on ubuntu 20.04 it gives me an error: "-bash: ./MinecraftClient: cannot execute binary file: Exec format error"

### ISSUE THREAD

**Issue by obvGamer** [MCCTeam/Minecraft-Console-Client#2689]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.3

### Console Client Version

latest

### Expected Behavior

I expect the console client to run perfectly

### Actual Behavior

it gives me the error  "-bash: ./MinecraftClient: cannot execute binary file: Exec format error". I've tried chmod + MinecraftClient but it still doesnt work

### Steps to Reproduce the bug

1. build from src code using git on ubuntu 20.04

### Device

VPS

### Operating System

Linux

**Comment by ReinforceZwei** [comment]
what is your build arguments and your cpu architecture?

**Comment by Tienkut** [comment]
obvgamer lamf cah nao de tui nhan tin cho ban tui can bangiup
