### ISSUE TITLE
[BUG] Reconnect Bug

### ISSUE THREAD

**Issue by Nekiplay** [MCCTeam/Minecraft-Console-Client#2691]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.2

### Console Client Version

https://github.com/MCCTeam/Minecraft-Console-Client/commit/9a147b57e5cab19ce7fe60d4510435220c1c5cee

### Expected Behavior

Auto Recoonect

### Actual Behavior

Failed to connect to the server when the connection was lost

Tests on local server: https://youtu.be/kkIDtEnwb-c

### Steps to Reproduce the bug

1.  Server restart
2.  Reconecting
3.  Loss of connection
4.  Work stoppage

### Attach screenshot here (If applicable)

![7kAwfBFq8k](https://github.com/MCCTeam/Minecraft-Console-Client/assets/35975332/1a70cc73-3d3c-4ddb-b750-626c42f6f99f)

### Anythings that could help diagnosing the bug

```txt
[ChatBot.AutoRelog]
Enabled = true
Delay = { min = 10.0, max = 16.0 }          # The delay time before joining the server. (in seconds)
Retries = 2147483647                        # Retries when failing to relog to the server. use -1 for unlimited retries.
Ignore_Kick_Message = true                  # When set to true, autorelog will reconnect regardless of kick messages.
# If the kickout message matches any of the strings, then autorelog will be triggered.
Kick_Messages = [ "connection has been lost", "server is restarting", "server is full", "too many people", ]
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

play.oldfrog.org

**Comment by Nekiplay** [comment]
It was fine before, who broke autoreconect?

**Comment by Nekiplay** [comment]
Also DigBlock doesn't work correctly because you can't specify Direction
Since Direction.Down works fine if the player looks at the block from below

**Comment by Nekiplay** [comment]
For my bot to work I only changed the DigBlock method to specify the Dicrection of digging, since Direction.Down does not work and is blocked by anti-chit, on the server allowed cheats

**Comment by Nekiplay** [comment]
Bring back the ability to control the direction of block breaking as I intended until you make a better solution.

**Comment by Nekiplay** [comment]
I add Tests on local server: https://youtu.be/kkIDtEnwb-c media

**Comment by milutinke** [comment]
@BruceChenQAQ If you have some time, could you look at this, since you were the last one to change this part of the code?

**Comment by breadbyte** [comment]
@Nekiplay can you try with this version?

https://github.com/breadbyte/Minecraft-Console-Client/releases/tag/20240307-106

**Comment by Nekiplay** [comment]
> @Nekiplay can you try with this version?
> 
> https://github.com/breadbyte/Minecraft-Console-Client/releases/tag/20240307-106
![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/35975332/b01bebc4-6bdf-448c-b6f8-fcec1caa32c7)

**Comment by Nekiplay** [comment]
> @Nekiplay can you try with this version?
> 
> https://github.com/breadbyte/Minecraft-Console-Client/releases/tag/20240307-106

So far so good.

**Comment by breadbyte** [comment]
If everything looks fine until now, I will merge the pull request later in the day.
