### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Tienkut** [MCCTeam/Minecraft-Console-Client#2694]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.12

### Console Client Version

moi nhat

### Expected Behavior

Em xin cách nhắn với anh tên Quân đội ạ 

### Actual Behavior

Em xin cách nhắn với anh tên Quân đội ạ 

### Steps to Reproduce the bug

1. 
2. 
3. 

### Attach screenshot here (If applicable)

a

### Anythings that could help diagnosing the bug

```txt
a
```

### Device

Other

### Operating System

Other

### Server Address (If applicable)

a

**Comment by milutinke** [comment]
Please use English.
