### ISSUE TITLE
Issue regarding chat signature

### ISSUE THREAD

**Issue by TheRealMonkey** [MCCTeam/Minecraft-Console-Client#2701]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [x] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.4

### Console Client Version

20240305-253

### Expected Behavior

I expect to see player messages in chat

### Actual Behavior

I am unable to see any player messages(including mine) in chat. The messages get converted to "7" as can be seen in the screenshot. 

### Steps to Reproduce the bug

Im not sure how to reproduce it as i connected to a random server and the message could be seen.

The server is running paper 1.20.4 with the following plugins:
Paper Plugins:
▌ - MarriageMaster
▌Bukkit Plugins:
▌ - ChatColor2, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, EssentialsXMPP, LuckPerms, mcMMO
▌ Sleeper, SpawnerSilk, SpentTime, Vault, Zenchantments

im not sure if it could be the plugins that are causing the issue

### Attach screenshot here (If applicable)

![image](https://github.com/MCCTeam/Minecraft-Console-Client/assets/71186391/74cc1410-096b-43a7-ab82-ee034bf61a06)

### Anythings that could help diagnosing the bug

```txt
From my understanding, The rectangle on the left is orange when MarkModifiedMsg is true

There was a time where i was able to see 1 message in the chat on MCC that was sent from myself from another account i was playing on.

When the message is sent from MCC, the other players are able to see what was sent
```

### Device

Laptop

### Operating System

Windows

**Comment by milutinke** [comment]
Send us the IP address, this needs to be manually debugged

**Comment by TheRealMonkey** [comment]
would it be possible for me to privately message you to send the IP as i dont want to publicly share the IP of the server.
If this would be okay with you, my discord name is monkey_face311

Thank you

**Comment by milutinke** [comment]
Solved.

**Comment by SeparateDuck517** [comment]
> Solved.

![IMG_20240310_223923.JPG](https://github.com/MCCTeam/Minecraft-Console-Client/assets/96333616/b2ec52bd-0bcd-4cfd-9df4-01dd68b80829)

Same issue. It worked perfectly in 20240218-247，but later version chat message only shows "7"
