### ISSUE TITLE
[Idea] Automatic synthesis of items and recipes, allowing customization of items and synthesized products.

### ISSUE THREAD

**Issue by VIRTUALXN** [MCCTeam/Minecraft-Console-Client#2708]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

20240312-257

### Describe your problem

I'm playing on a server that offers additional items and crafted items. I hope to be able to craft them as well.

### Suggest a possible solution

Allowing direct inclusion of the item's name in the configuration file.

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
We won't support such an option because item names are hard-coded as an enum in C#, that would require us to keep custom items for any server that implements them.
If you want to add any items, fork the repository, clone the project and then add them yourself.
