### ISSUE TITLE
[Idea] Gravity

### ISSUE THREAD

**Issue by onure9e** [MCCTeam/Minecraft-Console-Client#2727]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

2024 04 15 Latest

### Describe your problem

I cannot pass XCord's drop test in minecraft console client.

### Minecraft Version

1.19.4

### Device

VPS

### Operating System

Windows

**Comment by milutinke** [comment]
Gravity is implemented in the client, use `/move gravity on` to enable it.
If you fall but still get kicked that is because the client does not implement fall damage (for that we need to implement physics).
