### ISSUE TITLE
[BUG] Unknown Exception when starting

### ISSUE THREAD

**Issue by m1919810** [MCCTeam/Minecraft-Console-Client#2735]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1

### Console Client Version

Latest

### Expected Behavior

I use ./MinecraftClient to start minecraftClient-linux-x64 on one of my remote linux machines console
I expect it to start running

### Actual Behavior

It throws out unhandled exception as follows on my console
![4A203872-2D7E-47C9-AA84-4E353CE44379](https://github.com/MCCTeam/Minecraft-Console-Client/assets/151806404/a20be294-07f9-457f-8b5b-88293209e474)
I DONT KNOW WHAT‘S GOING ON

### Steps to Reproduce the bug

1. write ./MinecraftClient in start.sh
2. run start.sh
3. 

### Attach screenshot here (If applicable)

![24E2EA27-5D55-4897-8B00-0E7A49AB5E19](https://github.com/MCCTeam/Minecraft-Console-Client/assets/151806404/32cf302a-3bc7-4f5c-8bd6-f23a299d0f8e)

### Anythings that could help diagnosing the bug

```txt
none
actually it doesn‘t generate anything like config
```

### Device

Other

### Operating System

Linux

### Server Address (If applicable)

0

**Comment by milutinke** [comment]
Are you running in a container, eg. Docker?
Because .NET does not support console in containerized environments.

**Comment by m1919810** [comment]
> Are you running in a container, eg. Docker? Because .NET does not support console in containerized environments.

thanks for your help, that's the problem.
so is there any way to get it working?

**Comment by milutinke** [comment]
> > Are you running in a container, eg. Docker? Because .NET does not support console in containerized environments.
> 
> thanks for your help, that's the problem. so is there any way to get it working?

Nope, it's the problem in the .NET Environment itself, so yeah.

**Comment by breadbyte** [comment]
Seems to be fixed now- if you are still having the same issue, please make a new report or report it to the Discord.
