### ISSUE TITLE
[Idea] Add 1.21 Support

### ISSUE THREAD

**Issue by Rickieh1** [MCCTeam/Minecraft-Console-Client#2747]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

It would be nice for this console client to have the new 1.21 version support.

### Minecraft Version

1.21

### Device

Desktop

### Operating System

Windows

**Comment by Sebastien-Moraz** [comment]
already exist: https://github.com/MCCTeam/Minecraft-Console-Client/issues/2738

**Comment by milutinke** [comment]
As Sebastien mentioned, it's a duplicate. 
Closing this issue, and I will post an update there.
