### ISSUE TITLE
[BUG] in tasks "Trigger_On_Login" doesn't working

### ISSUE THREAD

**Issue by ozi2285** [MCCTeam/Minecraft-Console-Client#2752]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.19.4

### Console Client Version

Latest

### Expected Behavior

when entered the server activating script login.txt or send hello commands

### Actual Behavior

nothing happens and i wait at login screen until timeout kick

### Steps to Reproduce the bug

1. Open MCC
2. wait for login
3. doesn't happens

### Anythings that could help diagnosing the bug

```txt
i make sure activated it in config
```

### Device

Laptop

### Operating System

Windows

### Server Address (If applicable)

play.ruinnetwork.com

**Comment by milutinke** [comment]
Can you post your config?

**Comment by ozi2285** [comment]
[MinecraftClient.txt](https://github.com/user-attachments/files/16096536/MinecraftClient.txt)
there you go

**Comment by ozi2285** [comment]
i found my problem sorry about that
