### ISSUE TITLE
[Idea] Suggestion: /Follow [NamePlayer]

### ISSUE THREAD

**Issue by 1337kat** [MCCTeam/Minecraft-Console-Client#2770]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

1.8.9

### Describe your problem

**/move command**

### Suggest a possible solution

As the title suggests, this idea proposes the implementation of a /Follow command for tracking specific players. Automating the process with a **/follow** command can significantly enhance the user experience by providing seamless tracking capabilities, eliminating the need for manual adjustments.

NOTE: This should not replace the /move command, rather it enhances tracking capabilities for smoother navigation.

Command usage: **/follow zack123**

### Minecraft Version

1.8.9

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Already exists
https://mccteam.github.io/guide/chat-bots.html#follow-player
