### ISSUE TITLE
[HELP] Getting started on Docker

### ISSUE THREAD

**Issue by harrisonratcliffe** [MCCTeam/Minecraft-Console-Client#2783]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

N/A

### Console Client Version

Latest

### Expected Behavior

Docker container to run

### Actual Behavior

❯ docker run -it minecraft-console-client:latest

platform is
Donwloading MinecraftClient for 20240713-273
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0     20      0 --:--:-- --:--:-- --:--:--    21
Archive:  MinecraftClient-linux.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of MinecraftClient-linux.zip or
        MinecraftClient-linux.zip.zip, and cannot find MinecraftClient-linux.zip.ZIP, period.
chmod: cannot access './MinecraftClient': No such file or directory
/opt/start-latest.sh: 33: ./MinecraftClient: not found

I have tried running the command in both the Minecraft-Console-Client repo directory as well as /Docker which returns the same error. Using the -v flag to specify a volume also returns the same.

### Steps to Reproduce the bug

1. Clone the repo
2. Build the image in the /Docker folder
3. Run docker run -it minecraft-console-client:latest

### Device

None

### Operating System

None

**Comment by breadbyte** [comment]
Should be fixed in [8bdb20a](https://github.com/MCCTeam/Minecraft-Console-Client/commit/8bdb20a22c7abf6c409141753d8d5d0d9998ed00). Can you please try again?

**Comment by harrisonratcliffe** [comment]
That appears to be working now, thanks for sorting so quickly.
