### ISSUE TITLE
How can i do that ?

### ISSUE THREAD

**Issue by xDarkLife55** [MCCTeam/Minecraft-Console-Client#2789]
I playing a minecraft server. Server has got a bot guard. Bot guard active via chat. I want to if chat message "Lütfen sohbete /doğrula ... yaz!" afk client automatic send "/doğrula ..."
I write this code : 
[Match]
regex=/doğrula ([a-zA-Z0-9_]+).*
action=send /doğrula $1
cooldown=1

But I have got a problem. Code is work but only when /is chat activated. To explain better if "/doğrula ..." written a island chat, code is work but written a orginal chat or island team chat code isn't work. I can't solve this problem. Please help me.
![Ekran görüntüsü_20240901_015655](https://github.com/user-attachments/assets/dea18966-6db6-4c27-995d-90b7f8b882dd)
As seen in the photo, the code only works if written in the island chat. I couldn't understand why.

I want to autorespond bot read a this text : 
![Ekran görüntüsü_20240901_015713](https://github.com/user-attachments/assets/a09ad87f-109a-4e6d-8b91-8012a1386a34)

**Comment by milutinke** [comment]
Try adding:
`actionother=send /doğrula $1` under the `action=send /doğrula $1`.

**Comment by xDarkLife55** [comment]
thank u so much it's correct.
