### ISSUE TITLE
[Idea] Should support snapshot version

### ISSUE THREAD

**Issue by hnrie** [MCCTeam/Minecraft-Console-Client#2812]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [x] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Snapshot

### Describe your problem

I want it to support snapshots version

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Too much work for no one to use the feature.
Won't be supported.
