### ISSUE TITLE
[Idea] Offline accounts?

### ISSUE THREAD

**Issue by hnrie** [MCCTeam/Minecraft-Console-Client#2813]
### Prerequisites

- [X] I have read and understood the [user manual](https://mccteam.github.io/guide/)
- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar feature requests](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

### Console Client Version

Latest

### Describe your problem

No offline account option

### Suggest a possible solution

Make an option for offline accounts

### Device

Desktop

### Operating System

Windows

**Comment by milutinke** [comment]
Use "-" as password if you want to use an offline account.
