### ISSUE TITLE
[BUG] The given key 'overworld' was not present in the dictionary

### ISSUE THREAD

**Issue by Coderzzz01** [MCCTeam/Minecraft-Console-Client#2815]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [x] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.1\1.19.1

### Console Client Version

1

### Expected Behavior

Join the game normally

### Actual Behavior

When I join the game, I get an error message and crash

### Steps to Reproduce the bug

1. Let TerrainAndMovements = true
2. Join game
Join a 1.21 server which also runs the latest version of ViaVersion should work with an older client like this.

### Attach screenshot here (If applicable)

> Type '/quit' to leave the server.
> > Unhandled exception. System.IO.InvalidDataException: Failed to process incoming packet of type JoinGame. (PacketID: 40, Protocol: 763, LoginPhase: False, InnerException: System.Collections.Generic.KeyNotFoundException).
>  ---> System.Collections.Generic.KeyNotFoundException: The given key 'overworld' was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at MinecraftClient.Mapping.World.SetDimension(String name) in C:\Users\Administrator\Desktop\Minecraft-Console-Client-20240906-276\MinecraftClient\Mapping\World.cs:line 92
>    at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePlayPackets(Int32 packetId, Queue`1 packetData) in C:\Users\Administrator\Desktop\Minecraft-Console-Client-20240906-276\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 666
>    at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData) in C:\Users\Administrator\Desktop\Minecraft-Console-Client-20240906-276\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 457
>    --- End of inner exception stack trace ---
>    at MinecraftClient.Protocol.Handlers.Protocol18Handler.HandlePacket(Int32 packetId, Queue`1 packetData) in C:\Users\Administrator\Desktop\Minecraft-Console-Client-20240906-276\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 491
>    at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater(Object o) in C:\Users\Administrator\Desktop\Minecraft-Console-Client-20240906-276\MinecraftClient\Protocol\Handlers\Protocol18.cs:line 259
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> 

### Anythings that could help diagnosing the bug

```txt
I join successfuly, but Only change TerrainAndMovements = true，I just join fail.

Server is 1.21.1 but have Viaversion,I try join the server by 1.20.1 and 1.19.1,but fail.
```

### Device

Desktop

### Operating System

Windows

### Server Address (If applicable)

by2.jingmc.top

**Comment by Now722** [comment]
Is there any news about this bug?
