### ISSUE TITLE
[BUG] Minecraft Console Client exe x86 compile only

### ISSUE THREAD

**Issue by myxxmikeyxx** [MCCTeam/Minecraft-Console-Client#2831]
### Prerequisites

- [X] I made sure I am running the latest [development build](https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest)
- [X] I tried to [look for similar issues](https://github.com/MCCTeam/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
- [X] I have set `debugmessages=true` in config to diagnose my issue
- [X] I have redacted session tokens and passwords before attaching screenshots

### Minecraft Version

1.20.4

### Console Client Version

20241225-281

### Expected Behavior

I don't see a x64 bit version, only x86.
I was looking at the latest release (20241225-281) [here](https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20241225-281)
I normally see a x64 bit version and use this version.

### Actual Behavior

I don't see a x64 bit version, only x86

### Steps to Reproduce the bug

Go to https://github.com/MCCTeam/Minecraft-Console-Client/releases/tag/20241225-281
This is the latest release but no exe for x64

### Device

None

### Operating System

None

**Comment by breadbyte** [comment]
Thank you for bringing this to our attention. We have fixed the builds and have restored the missing builds.
