### ISSUE TITLE
Multiple Accounts on 1 Email

### ISSUE THREAD

**Issue by Monclerr** [MCCTeam/Minecraft-Console-Client#470]
Hi, just wondering if there's a way I can use console client on both of my accounts even though they're both linked to 1 email

**Comment by Pokechu22** [comment]
That's an interesting situation, and I didn't think the Mojang API allowed that.  How do you select the account in the normal launcher?

**Comment by Monclerr** [comment]
whenever I log into the account it gives me a choice between the two accounts

**Comment by Pokechu22** [comment]
Ah, right, the [authentication API](http://wiki.vg/Authentication#Response) does support multiple profiles (`availableProfiles` is an array).  Not one that's easy to test for (I don't think it's possible to register multiple accounts to the same email anymore?) though.  I do see some stuff in [authlib itself](https://libraries.minecraft.net/com/mojang/authlib/1.5.25/authlib-1.5.25-sources.jar) (`com.mojang.authlib.UserAuthentication`; yes, authlib's source is public) that talks about it, but it's not _super_ detailed.  But this should be fixable with some experimentation...

**Comment by Monclerr** [comment]
Would be cool if this could be implemented into the future console client
