### ISSUE TITLE
Weird character-sequence (343;3R) on mono after being kicked

### ISSUE THREAD

**Issue by TheSnoozer** [MCCTeam/Minecraft-Console-Client#543]
Hi,
thanks for the awesome client ;-)

I'm currently working on 1.13 and noticed a weird character-sequence popping up on mono after the client gets kicked. I can reproduce this issue with the latest (unmodified) Minecraft-Console-Client on 1.12.2 (protocol v340).

In my local development-build I could trace it down to [this Console.ReadLine()](https://github.com/ORelio/Minecraft-Console-Client/blob/4a4beb86d05a059c4ed2779aa4f632a559d91087/MinecraftClient/Program.cs#L373) and when removed this statement the weird sequence won't be printed.
However for me this seems to be a system call, so I'm not even sure if its a mono problem or an issue within the client.

How it looks like:
![selection_2018-08-10_20-08-49](https://user-images.githubusercontent.com/6849390/43986046-dfca6ee4-9cda-11e8-97bd-43342fafbaae.png)

# Steps to reproduce
Client-Side
```
$ cd /tmp
$ git clone git@github.com:ORelio/Minecraft-Console-Client.git
$ git rev-parse HEAD
871a7522d954f0d7156a9d723a35e883826d2bce
$ msbuild MinecraftClient.sln /t:build /p:Configuration=Debug /p:Platform="x86" /p:TargetFrameworkVersion="v4.0" /verbosity:minimal
$ mono ./MinecraftClient/bin/Debug/MinecraftClient.exe
```

Server-Side
```
$ wget https://launcher.mojang.com/mc/game/1.12.2/server/886945bfb2b978778c3a0288fd7fab09d315b25f/server.jar
$ echo "eula=true" > eula.txt
$ java -Xmx1024M -Xms1024M -jar server.jar nogui
# wait until client joins

[Server thread/INFO]: snooozer[/127.0.0.1:44132] logged in with entity id 2412 at (-138.5, 68.0, 238.5)
[Server thread/INFO]: snooozer joined the game
[Server thread/INFO]: <snooozer> hello
/kick player
[Server thread/INFO]: Kicked snooozer from the game
[Server thread/INFO]: snooozer lost connection: Kicked by an operator.
[Server thread/INFO]: snooozer left the game
```

# Environment
```
$ mono --version
Mono JIT compiler version 5.14.0.177 (tarball Mon Aug  6 09:13:43 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-/)
	GC:            sgen (concurrent by default)

$ msbuild -version
Microsoft (R) Build Engine version 15.6.0.0 ( Thu May 10 14:00:26 UTC 2018) for Mono
Copyright (C) Microsoft Corporation. All rights reserved.

15.6.0.0

$ cat /etc/*release* | grep -i version=
VERSION="16.04.5 LTS (Xenial Xerus)"
```

**Comment by ORelio** [comment]
Thanks for the detailed report. I think I encountered this issue previously, and I think this is propably due to the way Mono is handling input. If the thread performing the ReadLine() in Mono gets killed, it will send a bad escape sequence to the terminal.

The only workaround I can see for this would be having the same input prompt when logged in _and_ not logged in instead of restarting one (and thus killing a thread), but that would require some important changes in MCC's code.

**Comment by milutinke** [comment]
Since Mono is not used any more, I think this issue could be closed.
