### ISSUE TITLE
Add support for %datetime%

### ISSUE THREAD

**Issue by superhero578** [MCCTeam/Minecraft-Console-Client#688]
I want something like %username% and %serverip% but for the date and time. How would i do this?

**Comment by TheSnoozer** [comment]
Date and time is currently not supported (see https://github.com/ORelio/Minecraft-Console-Client/blob/950fc42118c3e877668f79b9b30fc7aacb5c3c2e/MinecraftClient/Settings.cs#L779). Also this wouldn#t make much sense without https://github.com/ORelio/Minecraft-Console-Client/issues/560

**Comment by milutinke** [comment]
Implemented in #2200
