### ISSUE TITLE
Support for use of relative coordinates in /move?

### ISSUE THREAD

**Issue by EchoesNetwork** [MCCTeam/Minecraft-Console-Client#724]
Hi,

What changes would need to happen to support the use of relative coordinates in the /move command, similar to this syntax in Minecraft's /teleport?
`/tp @s ~100 ~2.5 ~-10` where the player is teleported 100 blocks east of his current position, 2.5 block up, and 15 blocks north.

I'm sure something similar can be done with `/move getpos` and subtracting from the output of that, but relative coordinates would allow for easier scripting to have the bot move in a certain direction on a loop, and potentially a lot easier to handle for MCC-users with minimal knowledge of C#.

**Comment by ORelio** [comment]
Since `/move` already knows the current coordinates, seems pretty easy to implement.
