### ISSUE TITLE
Support for following players via /move?

### ISSUE THREAD

**Issue by EchoesNetwork** [MCCTeam/Minecraft-Console-Client#725]
Hi, 

I looked through older issues on this GitHub and came across #484, where it was concluded that in order for MCC bots to follow another player, support for entities would need to be added, and that seems pretty daunting. However, I noticed that if you force your Minecraft client to crash by holding F3+C, it outputs a list of all the entities within your render distance and their positions; am I misinterpreting this, or does this mean there's potentially another way to get the position of a nearby user and relay those coordinates to /move?

**Comment by ORelio** [comment]
This would require implementing entity handling. Currently, MCC has no idea where is the other player.

**Comment by Pedro9700** [comment]
Hey, I know this is a old thread but now that entity handling is a thing in the latest build, this could be a feature :)
Btw i cant do it myself because i know absolutly nothing about coding

**Comment by ORelio** [comment]
Yes, it is easier to add now that entity handling is implemented. Only thing that still needs to be taken care of: parhfinding algorithm is pretty slow so following a player may significantly slow down the client.

**Comment by milutinke** [comment]
Implemented in #2174
