### ISSUE TITLE
Feature: PlayerListLogger

### ISSUE THREAD

**Issue by Chtholly** [MCCTeam/Minecraft-Console-Client#847]
Ive worked for some time on the PlayerListLogger to write it into config to toggle, but without success.
Is it possibble to add toggle PlayerListLogger into settings.cs ? 

[PlayerListLogger]
enabled=true
delay=600
logfile=Playerlog.txt

ps. If runs and look for playerlist, there is no logfile which should generated and write in, allways written in chatlogs like all other stuff

**Comment by milutinke** [comment]
Fixed in #2200
