### ISSUE TITLE
Bug after close Inventory

### ISSUE THREAD

**Issue by Chtholly** [MCCTeam/Minecraft-Console-Client#928]
After clicks in some Inventorys and close it like:
/inventory 2 click 4
/inventory 3 close

its not poibble to click in any other inventory or if you close alle and try to click after open again, only /reco can fix this

**Comment by ORelio** [comment]
Thanks for reporting. Indeed, the click counter was not reset back to zero when closing the inventory from MCC. Could you try with the newer development build?

**Comment by Chtholly** [comment]
Havent resolved with the latest dev build.
After try to click Slot, theres only the message in which slot from inventory it clicks, but nothing happens

**Comment by ORelio** [comment]
OK, putting this back to the TODO list.

**Comment by nirikikry** [comment]
> OK, putting this back to the TODO list.

Now I also faced this problem. Not fixed yet ?

**Comment by ORelio** [comment]
We're lacking contributors and I have very limited time myself.

**Comment by milutinke** [comment]
Could not recreate, seems to be fixed. 
If it happens again, re-open the issue.
